return {
    descriptions = {
        Joker = {
            j_kranlaxs_tagger = {name = "Markierer", text = {"Erhält {C:red}+#1#{} Mult für jedes", "erhaltene {C:attention}Tag{}", "{C:inactive}(Aktuell {C:red}+#2#{C:inactive} Mult){}"}, unlock = {"Kaufe {C:attention}2{} Leere", "Gutscheine in einem Durchlauf"}},
            j_kranlaxs_Cashback = {name = "Cashback", text = {"{C:green}#1# zu #2#{} Chance, {X:money,C:white} $3 {} zu erhalten,", "wenn du eine Karte kaufst"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Rotem Einsatz{}", "mit dem {C:attention}Weltraum-Deck{}"}},
            j_kranlaxs_underratedjoker = {name = "Unterschätzter Joker", text = {"Dieser Joker erhält {X:chips,C:white} X0.2 {} Chips", "wenn die gespielte Hand {C:attention}nicht{}", "deine meistgespielte Pokerhand ist", "{C:inactive}(Wird zurückgesetzt, wenn sie es ist){}", "{C:inactive}(Aktuell {X:chips,C:white} X#1# {C:inactive} Chips){}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Blauem Einsatz{}", "mit dem {C:attention}Weltraum-Deck{}"}},
            j_kranlaxs_facelessaccountant = {name = "Gesichtsloser Buchhalter", text = {"Dieser Joker erhält {X:blue,C:white} X0.1 {} Chips für", "jede gewertete {C:attention}#2#{}", "{C:inactive}(Aktuell {X:blue,C:white} X#1# {C:inactive} Chips){}"}, unlock = {"Gewinne einen Durchlauf ohne Bildkarten zu spielen,", "während du mindestens {C:attention}1{} in deinem Deck hast"}},
            j_kranlaxs_thefixer = {name = "Der Ausputzer", text = {"Der Verkauf eines {C:attention}Jokers{} während eines", "{C:purple}Blinds{} verringert die erforderliche Punktzahl", "{C:inactive}(Gewöhnlich: -10%, Ungewöhnlich: -30%){}", "{C:inactive}(Selten: -60%, Legendär: -95%){}"}, unlock = {"Verkaufe mindestens {C:attention}2{} Joker", "jeder Seltenheit"}},
            j_kranlaxs_mysteriousgeode = {name = "Mysteriöse Geode", text = {"Jede gewertete {C:attention}Jokerkarte{} (Wild Card)", "gibt einen {C:attention}zufälligen{} Effekt"}, unlock = {"Spiele eine Hand", "mit {C:attention}5{} Jokerkarten"}},
            j_kranlaxs_benchwarmer = {name = "Bankdrücker", text = {"Gibt das {C:attention}4-fache{} des {C:blue}Chip{}-Wertes", "der ranghöchsten Karte auf der Hand"}},
            j_kranlaxs_entropy2 = {name = "Wirbel", text = {"Erhält {X:dark_edition,C:white} ^1 {} Mult und {X:dark_edition,C:white} ^1 {} Chips", "für jede Karte {C:attention}unter 52{} in deinem Deck", "{C:inactive}(Aktuell {X:dark_edition,C:white} ^#1# {C:inactive} Mult und {X:dark_edition,C:white} ^#1# {C:inactive} Chips){}"}},
            j_kranlaxs_greedyleprachaun = {name = "Gieriger Kobold", text = {"Ziehe {C:attention}3 zusätzliche Karten{}", "beim ersten {C:red}Abwurf{} der Runde"}, unlock = {"Wirf genau {C:attention}1{} Karte ab", "{C:attention}3{} mal hintereinander"}},
            j_kranlaxs_charismaticbard = {name = "Charismatischer Barde", text = {"{C:attention}-1{} Handgröße", "Reduziert die {C:purple}Blind{}-Anforderung um {C:attention}2%{} jedes Mal,", "wenn du deine {C:attention}meistgespielte Hand{} spielst", "{C:inactive}(Maximal 90%){}", "Wird zurückgesetzt, wenn du eine andere Hand spielst", "{C:inactive}(Aktuell {C:attention}-#1#%{C:inactive} Blindgröße){}"}},
            j_kranlaxs_russianroulette = {name = "Russisches Roulette", text = {"{C:green}#1# zu #2#{} Chance, {C:red}den Durchlauf zu verlieren{}", "beim Auswählen eines Blinds", "Wenn du überlebst, erhältst du", "{X:mult,C:white} X3 {} Mult und {X:chips,C:white} X3 {} Chips", "{C:inactive}(Aktuell {X:mult,C:white} X#3# {C:inactive} Mult und {X:chips,C:white} X#3# {C:inactive} Chips){}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Schwarzem Einsatz{}", "mit dem {C:attention}Weltraum-Deck{}"}},
            j_kranlaxs_fidelitycard = {name = "Battle Pass", text = {"Nach dem Kauf von {C:attention}6{} Karten gibt die {C:attention}siebte{}", "gekaufte Karte {X:money,C:white} Geld {} in Höhe des", "{C:attention}Verkaufswertes{} aller deiner Joker", "{C:inactive}(Aktuell {C:attention}#1#/6{C:inactive} Karten){}", "{C:inactive}(Gesamter Verkaufswert: {X:money,C:white} $#2# {C:inactive}){}"}},
            j_kranlaxs_devioussheep = {name = "Gefräßiges Schaf", text = {"{C:red}Verschlingt{} einen zufälligen Joker beim", "Auswählen eines {C:attention}Blinds{} und erhält {X:mult,C:white} X0.4 {} Mult", "{C:hearts}Game Over{} wenn es keine anderen Joker gibt", "{C:inactive}(Priorisiere bestimmte Ziele für mehr Mult!){}", "{C:inactive}(Aktuell {X:mult,C:white} X#1# {C:inactive} Mult){}"}},
            j_kranlaxs_lifeassurance = {name = "Lebensretter", text = {"Verhindert ein Game Over, wenn", "du mindestens {X:money,C:white} $#1# {} hast", "{C:inactive}(Preis verdoppelt sich nach jeder Nutzung){}"}, unlock = {"Verliere einen Durchlauf mit", "{X:money,C:white} $100 {} oder mehr", "vor {C:attention}Ante 8{}"}},
            j_kranlaxs_sundaycheckpoint = {name = "Checkpoint", text = {"{C:red}Game Over{} wenn du einen Blind", "an einem {C:attention}Wochentag{} auswählst", "Ansonsten wird am Ende der Runde ein {C:attention}Wöchentliche Herausforderung{}-Joker erstellt", "und {C:red}zerstört sich selbst{}", "{C:inactive}(Aktueller Tag: #1#){}"}},
            j_kranlaxs_weeklychallenge = {name = "Wöchentliche Herausforderung", text = {"Setzt eine zufällige Herausforderung für diesen Durchlauf fest", "{C:clubs}Aktuelle Herausforderung:{} {C:attention}#1#{}", "{C:inactive}1:{} Du hast {X:money,C:white} -$100 {}, zahle es vor Ante 8", "{C:inactive}2:{} Eingeschränkter Shop", "{C:inactive}3:{} 1 Hand, 20 Abwürfe (Keine extra Gutscheine)", "{C:inactive}4:{} Limit von {C:blue}#2#{} Händen und {C:red}#3#{} Abwürfen im Durchlauf", "{C:inactive}5:{} Spielgeschwindigkeit auf 0,5x gesperrt", "{C:inactive}6:{} 3 Ewige Triboulets (Max 3 Joker, Schnelles Ante)", "{C:inactive}7:{} 1 zu 6 Chance zu GEWINNEN (Verlieren bei Ante 8)"}},
            j_kranlaxs_panda = {name = "Flauschiger Panda", text = {"Gibt {C:chips}+#1#{} Chips", "{C:attention}-1{} Joker-Platz"}},
            j_kranlaxs_miner = {name = "Bergmann", text = {"Erhält {C:red}+5{} Mult für jede", "gewertete {C:attention}Steinkarte{}", "{C:green}#2# zu #3#{} Chance auf", "{X:money,C:white} $#4# {} bis {X:money,C:white} $#5# {} beim Spielen einer Hand", "{C:inactive}(Aktuell {C:red}+#1#{C:inactive} Mult){}"}, unlock = {"Spiele eine Hand", "mit {C:attention}5{} Steinkarten"}},
            j_kranlaxs_birthdaycake = {name = "Geburtstagskuchen", text = {"Gibt {X:dark_edition,C:white} ^#1# {} Mult", "Verliert {X:dark_edition,C:white} ^0.25 {} nach", "jeder gespielten Hand", "Wenn aufgebraucht, wird ein {C:attention}Weitergeschenkter Joker{} erstellt"}, unlock = {"Gewinne einen Durchlauf auf", "{C:attention}Blauem Einsatz{} mit", "dem {C:attention}Wöchentliche Herausforderung{}-Deck"}},
            j_kranlaxs_vipsuscription = {name = "V.I.P. Abonnement", text = {"Gibt {C:attention}+#2#{} Shop-Plätze,", "{C:attention}+1{} extra Gutschein und Paket", "Zieht {X:money,C:white} $#1# {} beim Öffnen des Shops ab.", "Preis und Shopgröße", "{C:attention}steigen{}, wenn ein {C:attention}Boss-Blind{} besiegt wird"}, unlock = {"Gewinne einen Durchlauf auf", "{C:attention}Orangefarbenem Einsatz{} mit", "dem {C:attention}Wöchentliche Herausforderung{}-Deck"}},
            j_kranlaxs_painterjoker = {name = "Maler-Joker", text = {"Wenn eine Hand gewertet wird, entsteht ein", "{C:attention}Jongleur-Tag{} für jede", "{C:attention}Jokerkarte{} in deiner Hand", "{C:inactive}(Kostet {X:money,C:white} $#1# {C:inactive} pro Tag){}"}, unlock = {"Gewinne einen Durchlauf auf", "{C:attention}Orangefarbenem Einsatz{} mit", "dem {C:attention}Wöchentliche Herausforderung{}-Deck"}},
            j_kranlaxs_coronation = {name = "Krönung", text = {"Wenn die gespielte Hand gewertete Karten", "im Rang {C:attention}10 oder niedriger{} enthält, wird", "die niedrigste in einen {C:attention}König{} verwandelt.", "Wenn keine niedrigen Karten auf der Hand sind,", "wird dem ersten gewerteten {C:attention}König{} ein {C:red}Rotes Siegel{} hinzugefügt."}, unlock = {"Spiele eine Hand mit genau", "{C:attention}5 Königen{}. Alle müssen", "ein {C:red}Rotes Siegel{} haben und {C:attention}Stahl{}-Karten sein"}},
            j_kranlaxs_speedrunner = {name = "Speedrunner", text = {"{X:mult,C:white} X#1# {} Mult.", "Du hast {C:attention}#2# Sekunden{} um", "eine Hand zu spielen oder abzuwerfen.", "Wenn die Zeit abläuft, {C:red}GAME OVER{}."}, unlock = {"Gewinne einen Durchlauf auf", "{C:attention}Grünem Einsatz{} mit", "dem {C:attention}Wöchentliche Herausforderung{}-Deck"}},
            j_kranlaxs_passcode = {name = "Passwort", text = {"Wenn die gespielte Hand einem", "der folgenden Codes entspricht, zählt die Hand", "als ein {C:attention}Flush Five{}", "{C:inactive}1. {C:attention}#1#{}", "{C:inactive}2. {C:attention}#2#{}", "{C:inactive}3. {C:attention}#3#{}"}, unlock = {"Gewinne einen Durchlauf auf", "{C:attention}Schwarzem Einsatz{} mit", "dem {C:attention}Wöchentliche Herausforderung{}-Deck"}},
            j_kranlaxs_chronometer = {name = "Chronometer", text = {"Beim Spielen einer Hand: ", "Gibt {C:chips}Chips{} gleich den aktuellen {C:attention}Sekunden{}", "Gibt {C:mult}Mult{} gleich den aktuellen {C:attention}Minuten{}", "Verdient {C:money}Geld{} gleich den aktuellen {C:attention}Stunden{}", "{C:inactive}(Aktuell: {C:chips}+#1#{C:inactive} Chips, {C:mult}+#2#{C:inactive} Mult, {C:money}+$#3#{C:inactive}){}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Gold-Einsatz{}", "mit dem {C:attention}Weltraum-Deck{}"}},
            j_kranlaxs_zombiejoker = {name = "Zombi Joka", text = {"{C:attention}zstöört{} die {C:attention}este{} katr", "de kine punkte gibt n grigt {C:red}+15{} mult", "abr du varlisrt {C:red}-10{} mult", "xjede gepiilte hnd in dr rude", "wen es uf {C:red}0{} mult fllt", "{C:attention}stibrt er {}", "{C:inactive}(du hasd {C:red}+#1#{C:inactive} mult odr soo){}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Lila Einsatz{}", "mit dem {C:attention}Weltraum-Deck{}"}},
            j_kranlaxs_thecousin = {name = "Der Cousin", text = {"Erhält {C:chips}+13{} Chips für jede", "gewertete {C:attention}Primzahl{}", "{C:inactive}(Aktuell {C:chips}+#1#{C:inactive} Chips){}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Türkisfarbenem Einsatz{}", "mit dem {C:attention}Weltraum-Deck{}"}},
            j_kranlaxs_colasoda = {name = "Cola-Limonade", text = {"Gibt {X:dark_edition,C:white} ^#1# {} Mult", "Verliert {X:dark_edition,C:white} ^#2# {} für", "fast {C:attention}jede Aktion{}, die du ausführst"}, unlock = {"Gewinne einen Durchlauf auf", "{C:attention}Blauem Einsatz{} mit", "dem {C:attention}Wöchentliche Herausforderung{}-Deck"}},
            j_kranlaxs_icecreamsandwich = {name = "Eiscreme-Sandwich", text = {"Verdiene {X:money,C:white} $#1# {} am Ende", "der Runde", "Belohnung sinkt um {X:money,C:white} $#2# {}", "nach jeder Runde"}, unlock = {"Verdiene {X:money,C:white} $50 {} oder mehr", "als Auszahlung in", "einer einzigen Runde"}},
            j_kranlaxs_dispensermachine = {name = "Verkaufsautomat", text = {"Wenn dieser Joker beim Verlassen des Shops {C:attention}ausgewählt{} ist", "gibst du {X:money,C:white} $#1# {} aus", "und erstellst einen {C:attention}Nahrungs-Joker{}"}, unlock = {"Besitze {C:attention}4{} Nahrungs-", "Joker gleichzeitig"}},
            j_kranlaxs_bottledwater = {name = "Wasser in Flaschen", text = {"{X:chips,C:white} X#1# {} Chips", "Verliert {X:chips,C:white} X#2# {} für", "jede gewertete Karte"}, unlock = {"Gewinne einen Durchlauf auf", "{C:attention}Blauem Einsatz{} mit", "dem {C:attention}Wöchentliche Herausforderung{}-Deck"}},
            j_kranlaxs_burrow = {name = "Kaninchenbau", text = {"Erhält {C:attention}+1{} Häschen für", "jeden besiegten {C:attention}Blind{}", "Wenn {C:gold}verkauft{}, werden {C:attention}#1#{} Häschen erstellt"}},
            j_kranlaxs_bunny = {name = "Häschen", text = {"Erhält {X:mult,C:white} X#1# {} Mult für jeden", "{C:attention}Häschen{}-Joker, den du hast", "{C:inactive}(Aktuell {X:mult,C:white} X#2# {C:inactive} Mult){}"}},
            j_kranlaxs_sushi = {name = "Sushi", text = {"Reduziert die Blind-Anforderung", "um {C:attention}#1#%{}", "Reduzierung sinkt um {C:attention}#2#%{}", "nach dem Besiegen eines {C:attention}Blinds{}"}, unlock = {"Gewinne einen Durchlauf auf", "{C:attention}Lila Einsatz{} mit", "dem {C:attention}Wöchentliche Herausforderung{}-Deck"}},
            j_kranlaxs_gigachad = {name = "Gigachad", text = {"Erhält {C:chips}+#2#{} Chips für fast", "{C:attention}jede Aktion{}, die du ausführst", "{C:inactive}(Aktuell {C:chips}+#1#{C:inactive} Chips){}"}, unlock = {"Gewinne einen Durchlauf auf", "{C:attention}Weißem Einsatz{} mit", "dem {C:attention}Wöchentliche Herausforderung{}-Deck"}},
            j_kranlaxs_nft = {name = "Krypto-Betrug", text = {"Reduziert den {C:attention}Rang{} aller", "Karten in deiner Hand um {C:attention}1{}", "beim Werten einer Hand", "{C:inactive}(Kann nicht unter 2 sinken){}"}},
            j_kranlaxs_beanstalk = {name = "Bohnenranke", text = {"Nutzlose Bohnen"}, unlock = {"Gewinne einen Durchlauf auf", "{C:attention}Weißem Einsatz{} mit", "dem {C:attention}Wöchentliche Herausforderung{}-Deck"}},
            j_kranlaxs_suspiciousbeanstalk = {name = "Verdächtige Bohnenranke", text = {"Nutzlose Bohnen?..."}},
            j_kranlaxs_epicbeanstalk = {name = "Epische Bohnenranke", text = {"Vielleicht sind es doch keine nutzlosen Bohnen..."}},
            j_kranlaxs_zenithbeanstalk = {name = "Zenit-Bohnenranke", text = {"Bohnen"}},
            j_kranlaxs_commonseed = {name = "Gewöhnlicher Samen", text = {"{C:attention}Erstellt{} einen zufälligen", "{C:common}Gewöhnlichen{} Joker"}},
            j_kranlaxs_weirdlookingseed = {name = "Seltsamer Samen", text = {"{C:attention}Erstellt{} einen zufälligen", "{C:uncommon}Ungewöhnlichen{} Joker"}},
            j_kranlaxs_magnificentseed = {name = "Prächtiger Samen", text = {"{C:attention}Erstellt{} einen zufälligen", "{C:rare}Seltenen{} Joker"}},
            j_kranlaxs_godseed = {name = "Göttlicher Samen", text = {"{C:attention}Erstellt{} einen zufälligen", "{C:legendary}Legendären{} Joker"}},
            j_kranlaxs_anonymousjoker = {name = "Anonymer Joker", text = {"Beim Werten dreht er sich um und gibt zwischen", "{X:mult,C:white} X1.5 {} und {X:mult,C:white} X4.0 {} Mult"}, unlock = {"Besiege den {C:attention}Bernstein-Eichel{}", "Boss-Blind 1 Mal"}},
            j_kranlaxs_littlebro = {name = "Kleiner Bruder", text = {"Wenn die gespielte Hand {C:attention}High Card{} ist und", "die gewertete Karte eine {C:attention}#2#{} ist,", "erhält dieser Joker {X:red,C:white} X#3# {} Mult", "Der Rang ändert sich jede Runde", "{C:inactive}(Aktuell {X:red,C:white} X#1# {C:inactive} Mult){}"}, unlock = {"Spiele {C:attention}High Card{}", "{C:attention}30{} Mal in", "einem einzigen Durchlauf"}},
            j_kranlaxs_medusa = {name = "Medusa", text = {"{C:attention}Alle gespielten Karten{}", "werden dauerhaft zu {C:attention}Steinkarten{}", "nach dem Spielen einer Hand", "{C:inactive}(Auch nicht gewertete){}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Braunem Einsatz{}", "mit dem {C:attention}Weltraum-Deck{}"}},
            j_kranlaxs_depression = {name = "Wirtschaftskrise", text = {"Gibt {X:dark_edition,C:white}^#2#{} Mult", "Erhöht sich um {X:dark_edition,C:white}^#1#{} für jeden {X:money,C:white} $1 {}", "unter {X:money,C:white} $0 {}"}, unlock = {"Betritt einen Shop", "mit {X:money,C:white} -$25 {} oder weniger"}},
            j_kranlaxs_grannyjoker = {name = "Oma", text = {"Gibt {X:dark_edition,C:white} ^3 {} Chips und {X:dark_edition,C:white} ^3 {} Mult", "Die Spielgeschwindigkeit ist auf {C:attention}0.25x{} gesperrt", "{C:inactive}(Zerstört, wenn du eine {C:attention}Straße{}", "{C:inactive}oder {C:attention}Straight Flush{C:inactive} spielst){}"}, unlock = {"Besiege {C:attention}12{} Blinds mit", "Spielgeschwindigkeit auf {C:attention}0.5{}"}},
            j_kranlaxs_lateshippment = {name = "Verspätete Lieferung", text = {"Triggert {C:attention}alle gespielten Karten{} erneut", "für jede {C:attention}1 gespielte Hand{}", "in der {C:attention}vorherigen Runde{}", "{C:inactive}(Aktuell {C:attention}#1#{C:inactive} Retrigger){}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Orangefarbenem Einsatz{}", "mit dem {C:attention}Weltraum-Deck{}"}},
            j_kranlaxs_unkownfactor = {name = "Variable X", text = {"Alle gespielten Karten", "gelten als {C:attention}#1#{}", "{C:inactive}(Rang ändert sich am Ende der Runde){}"}, unlock = {"Gewinne einen Durchlauf auf", "{C:attention}Gold-Einsatz{} mit", "dem {C:attention}Wöchentliche Herausforderung{}-Deck"}},
            j_kranlaxs_thethreers = {name = "Die 3 R's", text = {"Erstellt eine {C:attention}Kopie{} von jeder gespielten Karte", "und fügt sie deinem {C:attention}Deck{} hinzu", "{C:attention}Zerstört{} alle gewerteten Karten"}, unlock = {"Gewinne einen Durchlauf auf", "{C:attention}Gold-Einsatz{} mit", "dem {C:attention}Wöchentliche Herausforderung{}-Deck"}},
            j_kranlaxs_the = {name = "Jok", text = {"Gibt {X:chips,C:white} X2 {} Chips und {X:mult,C:white} X2 {} Mult", "nur bei der {C:attention}ersten Hand{} der Runde"}, unlock = {"Besiege {C:attention}5{} Blinds mit", "jeweils nur {C:attention}1{} gespielten Hand"}},
            j_kranlaxs_chainreaction = {name = "Kettenreaktion", text = {"Wenn die gespielte Hand {C:attention}#2#{} ist,", "erhält er {X:chips,C:white} X0.5 {} Chips und die Hand ändert sich", "Wird zurückgesetzt, wenn die Hand {C:attention}nicht übereinstimmt{}", "{C:inactive}(Aktuell {X:chips,C:white} X#1# {C:inactive} Chips){}"}, unlock = {"Spiele jede Pokerhand", "mindestens {C:attention}1{} Mal in einem Durchlauf"}},
            j_kranlaxs_anubis = {name = "Anubis", text = {"Gleicht die {C:blue}Chips{} und den {C:red}Mult{} aus", "wenn eine Hand gewertet wird"}, unlock = {"Gewinne einen Durchlauf mit dem {C:attention}Plasma-Deck{}", "auf jedem Einsatz-Schwierigkeitsgrad"}},
            j_kranlaxs_erraticjoker = {name = "Sprunghafter Joker", text = {"Wenn die gewertete Karte eine", "{C:attention}Jokerkarte{} (Wild) ist, werden", "{C:blue}Chips{} und {C:red}Mult{} getauscht"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Weißem Einsatz{}", "mit dem {C:attention}Weltraum-Deck{}"}},
            j_kranlaxs_luckyseven = {name = "Glückliche Siebenen", text = {"Wenn die gespielte Hand genau", "ein {C:attention}Drilling{} nur aus {C:attention}7ern{} ist, erhält dieser Joker", "{C:blue}+7{} Chips, {C:red}+7{} Mult und gibt {X:money,C:white} $7 {}", "{C:inactive}(Aktuell {C:blue}+#1#{} Chips, {C:red}+#2#{} Mult)"}, unlock = {"Habe mindestens {C:attention}10{} Karten", "mit dem Rang {C:attention}7{} in deinem Deck"}},
            j_kranlaxs_certificateddocument = {name = "Zertifiziertes Dokument", text = {"Triggert {C:attention}alle{} Siegel erneut"}, unlock = {"Gewinne einen Durchlauf auf", "{C:attention}Lila Einsatz{} mit", "dem {C:attention}Wöchentliche Herausforderung{}-Deck"}},
            j_kranlaxs_platanito = {name = "Kleine Banane", text = {"Wann immer ein anderer Joker triggert,", "gibt es {X:mult,C:white} X#3# {} extra Mult", "{C:green}#1# zu #2#{} Chance,", "am Ende der Runde zerstört zu werden"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Platin-Einsatz{}", "mit dem {C:attention}Weltraum-Deck{}"}},
            j_kranlaxs_cubicaljoker = {name = "Kubischer Joker", text = {"Gibt {C:mult}+#1#{} Mult", "Wert wird mit der", "{C:attention}Kubikzahl (^3){} für jeden", "besiegten {C:attention}Boss-Blind{} berechnet"}},
            j_kranlaxs_grapesoda = {name = "Traubenlimonade", text = {"Wenn {C:gold}verkauft{}, wird eine", "zufällige {C:spectral}Spektralkarte{} mit der", "{C:dark_edition}Negativ{}-Edition erstellt"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Magenta Einsatz{}", "mit dem {C:attention}Weltraum-Deck{}"}},
            j_kranlaxs_telescope = {name = "Teleskop", text = {"Wenn {C:attention}#1#{} aufsteigt, wird", "diese Hand {C:attention}1{} weiteres Mal hochgestuft", "{C:inactive}(Hand ändert sich am Ende der Runde){}"}, unlock = {"Gewinne einen Durchlauf auf", "{C:attention}Rotem Einsatz{} mit", "dem {C:attention}Wöchentliche Herausforderung{}-Deck"}},
            j_kranlaxs_pandorabox = {name = "Büchse der Pandora", text = {"Beim Besiegen eines {C:attention}Boss-Blinds{},", "wird ein {C:attention}nützlicher{} Joker basierend", "auf deinem aktuellen Deck erstellt", "{C:inactive}(Muss Platz haben){}"}},
            j_kranlaxs_doppelganger = {name = "Doppelgänger", text = {"Kopiert die Fähigkeit eines zufälligen", "{C:attention}Jokers{} aus dem gesamten Spiel.", "Kopierter Joker ändert sich nach", "Besiegen eines {C:attention}Blinds{}.", "{C:inactive}(Aktuell: {C:attention}#1#{C:inactive})"}, unlock = {"Gewinne einen Durchlauf auf", "{C:attention}Gold-Einsatz{} mit", "dem {C:attention}Wöchentliche Herausforderung{}-Deck"}},
            j_kranlaxs_thechampion = {name = "Der Champion", text = {"Blind-Anforderung {C:attention}X#1#{}", "Verdiene {X:money,C:white} $#2# {} am Ende der Runde"}, unlock = {"Erreiche {C:attention}Ante 16{}"}},
            j_kranlaxs_clerigo = {name = "Kleriker", text = {"Gibt {C:mult}+#1#{} Mult für jede", "Karte in deinem vollständigen Deck", "Verliert {C:mult}-#2#{} Mult für jede Karte", "mit einer Verbesserung oder einem Siegel", "{C:inactive}(Aktuell {C:mult}+#3#{C:inactive} Mult){}"}, unlock = {"Schließe die Herausforderung ab:", "{C:attention}Familienrezept{}"}},
            j_kranlaxs_entrenador = {name = "Trainer", text = {"Gibt {X:mult,C:white} X#1# {} Mult, wenn du", "unter Ante {C:attention}#3#{} bist", "Andernfalls gibt es {X:mult,C:white} X#2# {} Mult", "{C:inactive}(Aktuell {X:mult,C:white} X#4# {C:inactive} Mult){}"}, unlock = {"Schließe die Herausforderung ab:", "{C:attention}Wirtschaftskrise{}"}},
            j_kranlaxs_medium = {name = "Medium", text = {"Gibt {C:mult}+#1#{} Mult für jeden", "{C:red}verlorenen{} Durchlauf in deinem Profil", "{C:inactive}(Aktuell {C:mult}+#2#{C:inactive} Mult){}"}, unlock = {"Verliere {C:attention}1{} Durchlauf", "{C:inactive}(Fortschritt: {C:attention}#1#{C:inactive} / 1){}"}},
            j_kranlaxs_monk = {name = "Mönch", text = {"Erhält {X:chips,C:white} X#1# {} Chips, wenn du", "den Shop verlässt, ohne {X:money,C:white} Geld {} auszugeben", "{C:red}Wird zurückgesetzt{}, wenn du etwas kaufst", "{C:inactive}(Aktuell {X:chips,C:white} X#2# {C:inactive} Chips){}"}, unlock = {"Schließe die Herausforderung ab:", "{C:attention}Armutsgelübde{}"}},
            j_kranlaxs_knight = {name = "Ritter", text = {"Nach Wertung von {C:attention}#1#{} {C:attention}Stahl{}-Karten,", "wird der nächste {C:attention}Boss-Blind{} {C:attention}deaktiviert{}", "{C:inactive}(Gewertete Karten: #2#/#1#){}"}, unlock = {"Schließe die Herausforderung ab:", "{C:attention}Boss-Syndikat{}"}},
            j_kranlaxs_overpopulation = {name = "Überbevölkerung", text = {"Gibt {C:mult}+#1#{} Mult für jede", "{C:attention}Bildkarte{} über dem", "Limit von {C:attention}#2#{}", "in deinem Deck", "{C:inactive}(Aktuell {C:mult}+#3#{C:inactive} Mult){}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Grünem Einsatz{}", "mit dem {C:attention}Weltraum-Deck{}"}},
            j_kranlaxs_antisocial = {name = "Antisozial", text = {"Dieser Joker erhält {C:mult}+#1#{} Mult", "wenn du genau {C:attention}1{} Karte spielst", "{C:red}Wird zurückgesetzt{}, wenn du mehr als 1 spielst", "{C:inactive}(Aktuell {C:mult}+#2#{C:inactive} Mult){}"}, unlock = {"Schließe die Herausforderung ab:", "{C:attention}Totale Fixierung{}"}},
            j_kranlaxs_famous = {name = "Berühmt", text = {"Gibt {C:chips}+#1#{} Chips, wenn die gespielte", "Hand ein {C:attention}Five of a Kind{},", "{C:attention}Flush Five{} oder {C:attention}Flush House{} ist"}},
            j_kranlaxs_influencer = {name = "Influencer", text = {"Gibt {C:mult}+#1#{} Mult, wenn die gespielte", "Hand ein {C:attention}Five of a Kind{},", "{C:attention}Flush Five{} oder {C:attention}Flush House{} ist"}},
            j_kranlaxs_potatobag = {name = "Kartoffelsack", text = {"Sammelt gewertete Chips", "Bei Erreichen von {C:attention}#1#{} wird", "{X:mult,C:white} X#2# {} Mult auf die", "nächste Hand angewendet und entleert sich", "{C:inactive}(Gesammelt: #3#/#1#){}"}},
            j_kranlaxs_simonsays = {name = "Simon sagt", text = {"Dieser Joker erhält {X:mult,C:white} X#2# {} Mult", "wenn seine Anforderung erfüllt wird", "Simon sagt... {C:attention}#3#{}", "{C:inactive}(Aktuell {X:mult,C:white} X#1# {C:inactive} Mult){}"}, unlock = {"Schließe die Herausforderung ab:", "{C:attention}Die Große Bohnenranke{}"}},
            j_kranlaxs_cheater = {name = "Betrüger", text = {"Joker im Shop", "haben eine {C:green}35%{} Chance", "durch {C:attention}Gutscheine{} oder", "{C:attention}Booster-Packs{} ersetzt zu werden"}, unlock = {"Schließe die Herausforderung ab:", "{C:attention}Gachapon{}"}},
            j_kranlaxs_philosopher = {name = "Philosoph", text = {"Enthüllt die nächsten {C:attention}5 Karten{}", "aus deinem Deck", "{C:inactive}(Jede Karte hat eine 20%{}", "{C:inactive}Chance, verdeckt zu bleiben){}", "{C:attention}#1#{}"}, unlock = {"Schließe die Herausforderung ab:", "{C:attention}Vorahnungen{}"}},
            j_kranlaxs_mandalajoker = {name = "Mandala-Joker", text = {"Dieser Joker erhält {X:mult,C:white} X0.5 {} Mult", "für jede benutzte {C:spectral}Spektral{}-Karte", "{C:inactive}(Aktuell {X:mult,C:white} X#1# {C:inactive} Mult){}"}, unlock = {"Benutze {C:attention}20{} {C:spectral}Spektral{}-Karten", "{C:inactive}(Fortschritt: {C:attention}#1#{C:inactive} / 20){}"}},
            j_kranlaxs_regift = {name = "Weitergeschenkter Joker", text = {"Wenn {C:gold}verkauft{}, wird ein", "zufälliger {C:attention}Joker{} erstellt", "Seltenheit hängt vom aktuellen {C:attention}Blind{} ab"}, unlock = {"Verkaufe insgesamt {C:attention}50{} Joker", "{C:inactive}(Fortschritt: {C:attention}#1#{C:inactive} / 50){}"}},
            j_kranlaxs_pyromaniac = {name = "Pyromane", text = {"Nach Wertung einer Hand werden", "alle {C:attention}Zahlenkarten{} in deiner Hand {C:red}zerstört{}", "{C:inactive}(Gold-, Glas- und Stahlkarten sind sicher){}"}, unlock = {"Zerstöre {C:attention}100{} Karten", "die keine Bildkarten sind", "{C:inactive}(Fortschritt: {C:attention}#1#{C:inactive} / 100){}"}},
            j_kranlaxs_neverendinggambling = {name = "Endloses Glücksspiel", text = {"Verliere {X:money,C:white} $1 {} für jede deiner Aktionen", "{C:inactive}(Nur wenn du {X:money,C:white} $5 {} oder mehr hast){}", "Drehe 3 Zahlen. Bei Übereinstimmung, gewinne einen Preis!", "Wenn 2 übereinstimmen, erhalte {X:money,C:white} $1 {} als Trost", "{C:inactive}(Aktueller Dreh: #1# - #2# - #3#){}"}, unlock = {"Verfehle {C:attention}30{} Joker- oder", "Verbrauchsartikel-Wahrscheinlichkeiten", "{C:inactive}(Fortschritt: {C:attention}#1#{C:inactive} / 30){}"}},
            j_kranlaxs_solarsystem = {name = "Sonnensystem", text = {"Erstellt am {C:attention}Ende der Runde{} eine", "{C:planet}Planeten{}-Karte in einer festen Reihenfolge", "{C:inactive}(Nächster Planet: {C:planet}#1#{C:inactive}){}"}, unlock = {"Benutze alle {C:attention}12{} Standard", "{C:planet}Planeten{}-Karten mindestens einmal", "in einem Durchlauf", "{C:inactive}(Fortschritt: {C:attention}#1#{C:inactive} / 12){}"}},
            j_kranlaxs_deranged = {name = "Geistesgestört", text = {"Gibt {C:mult}+#1#{} Mult oder {C:chips}+#2#{} Chips", "Effekt wechselt jedes Mal", "wenn du eine Hand spielst"}, unlock = {"Schließe die Herausforderung ab:", "{C:attention}Identitätskrise{}"}},
            j_kranlaxs_deranged_mult = {name = "Geistesgestört", text = {"Gibt {C:mult}+#1#{} Mult", "Effekt wechselt jedes Mal", "wenn du eine Hand spielst"}},
            j_kranlaxs_deranged_chips = {name = "Geistesgestört", text = {"Gibt {C:chips}+#2#{} Chips", "Effekt wechselt jedes Mal", "wenn du eine Hand spielst"}},
            j_kranlaxs_tmtrainer = {
                name = "TMTRAINER", 
                text = {
                    "{C:dark_edition}#1#{}",
                    "{C:attention}#2#{}",
                    "{C:red}#3#{}",
                    "{C:chips}#4#{}"
                },
                unlock = {
                    "Schließe die Herausforderung ab:",
                    "{C:attention}Identitätskrise{}"
                }
            },
            j_kranlaxs_bingocard = {name = "Bingokarte", text = {"Erhält {X:mult,C:white} X0.25 {} Mult", "für jede vervollständigte Linie", "{C:inactive}(Gesamt: {X:mult,C:white} X#2# {C:inactive} Mult){}", "{C:attention}#3#{}", "{C:attention}#4#{}", "{C:attention}#5#{}", "{C:attention}#6#{}", "{C:attention}#7#{}"}, unlock = {"Schließe die Herausforderung ab:", "{C:attention}Totale Anonymität{}"}}
        },

        Back = {
            b_kranlaxs_week_challenge = {name = "Wöchentliche Herausforderung", text = {"Starte mit einem {C:attention}Wöchentliche Herausforderung{}-Joker", "{C:red}Schaffbar{} jedes {C:attention}Wochenende{}"}, unlock = {"Öffne das Spiel an einem", "{C:attention}Samstag{} oder {C:attention}Sonntag{}"}},
            b_kranlaxs_chaos_deck = {name = "Chaos-Deck", text = {"Genieße das Chaos"}, unlock = {"Schalte {C:legendary,E:1}ALLES{} in", "deiner Sammlung frei"}},
            b_kranlaxs_dungeon_deck = {name = "Dungeon-Deck", text = {"Nachdem du einen {C:attention}Boss-Blind{} besiegt hast,", "wähle zwischen 3 {C:attention}Optionen{}", "mit {C:green}Vor-{} und {C:red}Nachteilen{}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Grünem Einsatz{}", "oder höher mit dem", "{C:attention}Wöchentliche Herausforderung{}-Deck"}},
            b_kranlaxs_space_deck = {name = "Weltraum-Deck", text = {"{C:attention}0{} Joker-Plätze, {C:attention}5{} Verbrauchsartikel-Plätze", "Shop verkauft nur {C:attention}Quarze{}", "{C:attention}+1{} zur Shopgröße, Blinds sind {C:attention}7.5%{} kleiner", "Sieges-Ante: {C:attention}10{}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Grünem Einsatz{}", "mit dem {C:attention}Magie-Deck{}, dem", "{C:attention}Nebel-Deck{} und dem {C:attention}Tierkreis-Deck{}"}},
            b_kranlaxs_bugged_deck = {name = "Verbuggtes Deck", text = {"!?"}, unlock = {"Erwirb zum ersten Mal", "einen {C:attention}TMTRAINER{}"}}
        },

        Stake = {
            stake_kranlaxs_magenta = {name = "Magenta Einsatz", text = {"Shop-Karten können den", "{C:attention}Angeheftet{}-Aufkleber haben"}},
            stake_kranlaxs_brown = {name = "Brauner Einsatz", colour = "Braun", text = {"{C:attention}-1{} {C:attention}Booster-Pack{}-Platz", "im Shop"}},
            stake_kranlaxs_turquoise = {name = "Türkisfarbener Einsatz", colour = "Türkis", text = {"Blinds haben eine {C:attention}50%{} Chance,", "{C:red}nicht überspringbar zu sein{}"}},
            stake_kranlaxs_deviled = {name = "Teuflischer Einsatz", colour = "Teuflischer", text = {"{C:attention}-1{} {C:attention}Joker{}-Platz"}},
            stake_kranlaxs_glass = {name = "Glaseinsatz", colour = "Glas", text = {"Erforderliche Punktzahl skaliert", "noch schneller für jedes {C:attention}Ante{}"}},
            stake_kranlaxs_platinum = {name = "Platin-Einsatz", colour = "Platin", text = {"Muss {C:attention}Ante 10{} schlagen", "um den Durchlauf zu gewinnen"}}
        },

        UNOCards = {
            c_kranlaxs_skip = {name = "Aussetzen", text = {"Erhalte {C:attention}sofort{} die Blind-Anforderung", "Funktioniert nicht bei {C:attention}Boss-Blinds{}"}},
            c_kranlaxs_stacking = {name = "Stapeln", text = {"Fügt einer {C:attention}1{} ausgewählten Karte auf", "der Hand ein {C:attention}Rosa Siegel{} hinzu"}},
            c_kranlaxs_draw2 = {name = "Ziehe 2", text = {"Bei Verwendung {C:attention}ziehe 2 zusätzliche Karten{}", "auf deine Hand, verliere {C:blue}1{} Hand"}},
            c_kranlaxs_draw4 = {name = "Ziehe 4", text = {"Bei Verwendung {C:attention}ziehe 4 zusätzliche Karten{}", "auf deine Hand, verliere {C:blue}1{} Hand"}},
            c_kranlaxs_reverse = {name = "Retour", text = {"Gibt {C:attention}alle Karten{} aus deiner", "Hand ins Deck zurück und {C:attention}mischt{} sie neu"}},
            c_kranlaxs_wildcard = {name = "Farbenwahl", text = {"{C:attention}Verwandelt{} jede Karte in", "deiner Hand {C:attention}unabhängig{}", "in eine {C:attention}zufällige Farbe{}"}},
            c_kranlaxs_replay = {name = "Wiederholen", text = {"Gibt die Karten der", "zuletzt gespielten Hand auf deine Hand zurück", "{C:inactive}(Wird nach Gebrauch oder", "{C:inactive}am Ende der Runde zurückgesetzt)"}},
            c_kranlaxs_discardall = {name = "Alles abwerfen", text = {"Benötigt {C:attention}1{} ausgewählte Karte.", "Wirft {C:red}alle{} Karten", "aus deiner {C:attention}Hand{} und {C:attention}Deck{} ab, die", "die gleiche Farbe teilen"}},
            c_kranlaxs_shield = {name = "Schild", text = {"Schützt dich passiv vor dem Tod oder", "kann verkauft werden, um den {C:attention}Boss-Blind{} zu deaktivieren"}},
            c_kranlaxs_misery = {name = "Elend", text = {"Wähle eine {C:attention}Farbe{}.", "Zieht ununterbrochen Karten aus deinem Deck", "bis du", "eine dieser Farbe erhältst"}},
            c_kranlaxs_gift = {name = "Geschenk", text = {"Gewährt {C:attention}1{} der folgenden", "zufälligen Preise:", "• Ein {C:attention}Joker{} mit Edition", "• Ein negativer {C:attention}Verbrauchsartikel{}", "• Eine {C:attention}Karte{} mit Verbesserung, Siegel und Edition"}},
            c_kranlaxs_customdraw = {name = "Angepasstes Ziehen", text = {"Zieht die gleiche Anzahl von Karten", "wie die Anzahl deiner Abwürfe", "{C:inactive}(Aktuell: {C:attention}#1#{C:inactive} Karten){}"}}
        },

        InverseTarot = {
            c_kranlaxs_thefool = {name = "Der Narr?", text = {"Erstellt eine zufällige {C:spectral}Spektralkarte{}", "{C:attention}Stuft{} eine zufällige Pokerhand ab"}},
            c_kranlaxs_themagician = {name = "Der Magier?", text = {"Erstellt {C:attention}2{} zufällige {C:attention}Glücks{}-Karten"}},
            c_kranlaxs_thehighpriestess = {name = "Die Hohepriesterin?", text = {"Erstellt ein {C:spectral}Schwarzes Loch{}", "Dein {X:money,C:white} Geld {} {C:attention}sinkt{} um 20%"}},
            c_kranlaxs_theempress = {name = "Die Herrscherin?", text = {"Fügt permanent {C:red}+8{} Mult hinzu", "zu bis zu {C:attention}2{} ausgewählten Karten"}},
            c_kranlaxs_theemperor = {name = "Der Herrscher?", text = {"Erstellt {C:attention}2{} zufällige {C:attention}Tags{}"}},
            c_kranlaxs_thehierophant = {name = "Der Hierophant?", text = {"Fügt permanent {C:blue}+40{} Chips hinzu", "zu bis zu {C:attention}2{} ausgewählten Karten"}},
            c_kranlaxs_thelovers = {name = "Die Liebenden?", text = {"Erhalte {C:attention}+1{} Handgröße, wenn", "du eine {C:attention}Jokerkarte{} in deinem Deck hast"}},
            c_kranlaxs_thechariot = {name = "Der Wagen?", text = {"Erstellt {C:attention}1{} zufällige {C:attention}Stahl{}-Karte", "mit einem {C:attention}Roten{} Siegel"}},
            c_kranlaxs_justice = {name = "Gerechtigkeit?", text = {"Fügt permanent {X:red,C:white} X2 {} Mult hinzu", "zu {C:attention}1{} ausgewählten Karte", "{C:green}#1# zu #2#{} Chance, diese Karte zu {C:attention}zerstören{}"}},
            c_kranlaxs_thehermit = {name = "Der Eremit?", text = {"{C:attention}Setzt{} dein {X:money,C:white} Geld {} auf {X:money,C:white} $25 {} wenn", "du {C:attention}weniger als{} {X:money,C:white} $25 {} hast"}},
            c_kranlaxs_thewheeloffortune = {name = "Das Rad des Schicksals?", text = {"{C:green}#1# zu #2#{} Chance eine {C:attention}Kopie{} eines", "zufälligen Jokers mit {C:dark_edition}Negativer{}-Edition zu erstellen"}},
            c_kranlaxs_strenght = {name = "Kraft?", text = {"{C:attention}Reduziert{} den {C:attention}Rang{} von bis zu", "{C:attention}2{} ausgewählten Karten um {C:attention}1{}"}},
            c_kranlaxs_thehangedman = {name = "Der Gehängte?", text = {"Gänzliche {C:attention}Zufallsgenerierung{} von bis zu", "{C:attention}2{} ausgewählten Karten auf der Hand"}},
            c_kranlaxs_death = {name = "Der Tod?", text = {"Erstellt eine {C:attention}Negative Kopie{} eines zufälligen Jokers", "Ein zufälliger Joker erhält einen {C:attention}Verderblich{}-Aufkleber"}},
            c_kranlaxs_temperance = {name = "Mäßigkeit?", text = {"Verkauft {C:attention}ALLE{} Joker (sogar Ewige)", "für den {C:money}dreifachen{} Verkaufswert", "{C:inactive}(Verkauft keine Angehefteten Joker){}"}},
            c_kranlaxs_thedevil = {name = "Der Teufel?", text = {"Fügt permanent {X:money,C:white} $2 {} hinzu", "zu bis zu {C:attention}2{} ausgewählten Karten"}},
            c_kranlaxs_thetower = {name = "Der Turm?", text = {"{C:attention}Entfernt{} alle Verbesserungen, Siegel,", "Editionen und Boni von Karten in der Hand", "Erhalte {X:money,C:white} $1 {} für jede entfernte Modifikation"}},
            c_kranlaxs_thestars = {name = "Die Sterne?", text = {"Fügt ein {C:attention}Weißes Siegel{} hinzu", "zu bis zu {C:attention}2{} ausgewählten Karten"}},
            c_kranlaxs_themoon = {name = "Der Mond?", text = {"Fügt ein {C:attention}Graues Siegel{} hinzu", "zu bis zu {C:attention}2{} ausgewählten Karten"}},
            c_kranlaxs_thesun = {name = "Die Sonne?", text = {"Fügt ein {C:attention}Oranges Siegel{} hinzu", "zu bis zu {C:attention}2{} ausgewählten Karten"}},
            c_kranlaxs_judgement = {name = "Das Gericht?", text = {"{C:attention}Löst{} einen zufälligen {C:attention}Gutschein{} ein", "{C:red}-1{} Handgröße"}},
            c_kranlaxs_theworld = {name = "Die Welt?", text = {"Fügt ein {C:attention}Braunes Siegel{} hinzu", "zu bis zu {C:attention}2{} ausgewählten Karten"}}
        },

        Voucher = {
            v_kranlaxs_more_stock = {name = "Mehr Bestand", text = {"Shop hat {C:attention}1{} extra", "{C:attention}Booster-Pack{}-Platz"}},
            v_kranlaxs_even_more_stock = {name = "Noch Mehr Bestand", text = {"Shop hat {C:attention}1{} extra", "{C:attention}Gutschein{}-Platz"}},
            v_kranlaxs_shiny_appearance = {name = "Glänzender Auftritt", text = {"Legendäre Karten und seltene Verbrauchsartikel", "können nun im Shop erscheinen"}},
            v_kranlaxs_stickerfever = {name = "Aufkleber-Fieber", text = {"Wann immer du ein", "{C:attention}Tag{} erhältst, bekommst du", "{C:attention}1{} zusätzliche Kopie"}},
            v_kranlaxs_stickeralbum = {name = "Aufkleber-Album", text = {"Wann immer du ein", "{C:attention}Tag{} erhältst, bekommst du", "{C:attention}1{} weitere Kopie zusätzlich"}},
            v_kranlaxs_hotfix = {name = "Hotfix", text = {"Das {C:attention}Neurollen{} des Shops", "aktualisiert auch {C:attention}Gutscheine{}", "und {C:attention}Booster-Packs{}"}},
            v_kranlaxs_version2 = {name = "Version 2.0", text = {"Überspringen von Blinds gewährt dir die {X:money,C:white} Geld {}", "Belohnung dieses Blinds.", "Blind-Anforderung {C:attention}-15%{}"}},
            v_kranlaxs_common_shinys = {name = "Legendäre Sichtung", text = {"Legendäre Karten und seltene Verbrauchsartikel", "werden häufiger erscheinen"}},
            v_kranlaxs_blessing = {name = "Segen", text = {"Du beginnst mit {C:attention}10%{}", "der Chip-Anforderung", "erfüllt bei jedem Blind"}},
            v_kranlaxs_protection = {name = "Göttlicher Schutz", text = {"Schützt dich vor einem {C:attention}Game Over{}.", "Bei Verwendung wird dieser Gutschein zerstört", "und kann wieder im Shop erscheinen,", "aber zum {X:money,C:white} doppelten {} seines ursprünglichen Preises"}}
        },

        Quartz = {
            c_kranlaxs_blackquartz = {name = "Obsidian", text = {"Modifiziert einige Regeln", "deiner Wahl"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Braunem Einsatz{}", "mit dem {C:attention}Magie-Deck{}"}},
            c_kranlaxs_whitequartz = {name = "Perle", text = {"Erstellt den zuletzt", "verwendeten Verbrauchsartikel", "{C:inactive}(Letzte Karte: {C:attention}#1#{C:inactive}){}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Braunem Einsatz{}", "mit dem {C:attention}Geister-Deck{}"}},
            c_kranlaxs_pinkquartz = {name = "Rosenquarz", text = {"Fügt einem ausgewählten {C:attention}Joker{}", "oder einer {C:attention}Karte{} {C:dark_edition}Polychrom{} hinzu"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Magenta Einsatz{}", "oder höher mit dem {C:attention}Dungeon-Deck{}"}},
            c_kranlaxs_bluequartz = {name = "Saphir", text = {"Fügt einem ausgewählten {C:attention}Joker{}", "oder einer {C:attention}Karte{} {C:chips}Foil{} hinzu"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Platin-Einsatz{}", "mit dem {C:attention}Plasma-Deck{}"}},
            c_kranlaxs_lilacquartz = {name = "Kunzite", text = {"Fügt einem ausgewählten {C:attention}Joker{}", "oder einer {C:attention}Karte{} {C:mult}Holografisch{} hinzu"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Braunem Einsatz{}", "mit dem {C:attention}Nebel-Deck{}"}},
            c_kranlaxs_grayquartz = {name = "Hämatit", text = {"Fügt einem ausgewählten {C:attention}Joker{}", "oder {C:attention}Verbrauchsartikel{} {C:dark_edition}Negativ{} hinzu"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Türkisfarbenem Einsatz{}", "mit dem {C:attention}Bemalten Deck{}"}},
            c_kranlaxs_transparentquartz = {name = "Diamant", text = {"{C:attention}Entfernt{} alle Aufkleber oder Editionen", "von einem {C:attention}Joker{} oder Siegel oder", "Editionen von einer ausgewählten {C:attention}Karte{}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Platin-Einsatz{}", "mit dem {C:attention}Dungeon-Deck{}"}},
            c_kranlaxs_redquartz = {name = "Rubin", text = {"Während {C:attention}gehalten{},", "gibt {X:mult,C:white} X2 {} Mult", "{C:inactive}(Passiv){}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Magenta Einsatz{}", "oder höher mit dem {C:attention}Roten Deck{}"}},
            c_kranlaxs_celestequartz = {name = "Larimar", text = {"Während {C:attention}gehalten{},", "gibt {X:chips,C:white} X1.5 {} Chips", "{C:inactive}(Passiv){}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Türkisfarbenem Einsatz{}", "mit dem {C:attention}Karierten Deck{}"}},
            c_kranlaxs_yellowquartz = {name = "Topas", text = {"Erstellt den angegebenen {C:attention}Joker{}.", "Joker ändert sich zufällig", "nach jeder {C:attention}Runde{}", "{C:inactive}(Ziel: {C:attention}#1#{C:inactive}){}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Blauem Einsatz{}", "mit dem {C:attention}Dungeon-Deck{}"}},
            c_kranlaxs_greenquartz = {name = "Smaragd", text = {"Während {C:attention}gehalten{}, erstellt ein", "{C:attention}Tag{} nach dem Besiegen eines {C:attention}Blinds{}", "Zerstört nach Erstellen von {C:attention}#2#{} Tags", "{C:inactive}(Aktuell: {C:attention}#1#{C:inactive}){}", "{C:inactive}(Passiv){}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Magenta Einsatz{}", "oder höher mit dem {C:attention}Grünen Deck{}"}},
            c_kranlaxs_brownquartz = {name = "Tigerauge", text = {"Erstellt die angegebene {C:attention}Karte{}.", "Karte ändert sich zufällig nach", "{C:green}Neurollen{} des Shops", "{C:inactive}(Ziel: {C:attention}#1#{C:inactive}){}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Türkisfarbenem Einsatz{}", "mit dem {C:attention}Anaglyph-Deck{}"}},
            c_kranlaxs_turquoisequartz = {name = "Türkis", text = {"Während {C:attention}gehalten{}, {C:attention}deaktiviert{}", "alle Joker außer dem ersten", "Triggert diesen Joker {C:attention}2{} Mal erneut", "{C:inactive}(Passiv){}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Türkisfarbenem Einsatz{}", "mit dem {C:attention}Tierkreis-Deck{}"}},
            c_kranlaxs_orangequartz = {name = "Citrin", text = {"Fügt einer {C:attention}Karte{} ein {C:green}Minzsiegel{}", "oder einem ausgewählten {C:attention}Joker{}", "einen {C:green}Kleeblatt-Aufkleber{} hinzu"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Magenta Einsatz{}", "oder höher mit dem {C:attention}Gelben Deck{}"}},
            c_kranlaxs_lapislazuli = {name = "Lapislazuli", text = {"Während {C:attention}gehalten{}, fügt", "{C:chips}+#1#{} Chips zur ersten gewerteten Karte hinzu", "Effekt verringert sich um {C:chips}-#2#{} bei jeder Nutzung.", "{C:inactive}(Inaktiv, wenn es 0 erreicht){}", "{C:inactive}(Passiv){}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Magenta Einsatz{}", "oder höher mit dem {C:attention}Blauen Deck{}"}},
            c_kranlaxs_cinnabar = {name = "Zinnober", text = {"Während {C:attention}gehalten{}, fügt", "{C:mult}+#1#{} Mult zur ersten gewerteten Karte hinzu", "Effekt verringert sich um {C:mult}-#2#{} bei jeder Nutzung.", "{C:inactive}(Inaktiv, wenn es 0 erreicht){}", "{C:inactive}(Passiv){}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Braunem Einsatz{}", "mit dem {C:attention}Verlassenen Deck{}"}},
            c_kranlaxs_graphite = {name = "Graphit", text = {"Während {C:attention}gehalten{}, {C:green}#1# zu #2#{}", "Chance, eine Kopie aller gespielten Karten in deiner", "Hand zu erstellen.", "Chance sinkt beim Auslösen.", "{C:inactive}(Inaktiv, wenn es 0 erreicht){}", "{C:inactive}(Passiv){}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Magenta Einsatz{}", "oder höher mit dem {C:attention}Schwarzen Deck{}"}},
            c_kranlaxs_uranium = {name = "Uran", text = {"Während {C:attention}gehalten{}, wendet 1 zufälligen", "Effekt pro Runde an. Er kann", "sehr gut oder sehr zerstörerisch sein.", "{C:dark_edition}Aktueller Status:{}", "{C:red,E:2}#1#{}", "{C:inactive}(Traust du dich, es zu tragen?){}", "{C:inactive}(Passiv){}"}, unlock = {"Gewinne einen Durchlauf auf {C:attention}Platin-Einsatz{}", "mit dem {C:attention}Errant-Deck{}"}}
        },

        Tag = {
            tag_kranlaxs_mega_invtarot = {name = "Mega Inverses Tag", text = {"Gewährt sofort ein", "kostenloses {C:attention}Mega Inverses Tarot-Paket{}"}},
            tag_kranlaxs_mega_uno = {name = "Jumbo UNO Tag", text = {"Gewährt sofort ein", "kostenloses {C:attention}Jumbo UNO-Paket{}"}},
            tag_kranlaxs_mega_invtarot_store = {name = "Gespeichertes Mega Inverses Tag", text = {"Gewährt sofort ein", "kostenloses {C:attention}Gespeichertes Mega Inverses Tarot{}"}},
            tag_kranlaxs_quartz_tag = {name = "Quarz Tag", text = {"Erstellt einen zufälligen {C:attention}Quarz{}", "{C:inactive}(Muss Platz haben){}"}},
            tag_kranlaxs_sticker_remover = {name = "Reiniger Tag", text = {"Entfernt einen {C:attention}Ewigen{},", "{C:attention}Verderblichen{} oder {C:attention}Leih{}-Aufkleber von", "einem zufälligen {C:attention}Joker{}", "{C:inactive}(Gibt {X:money,C:white} $5 {C:inactive} wenn keine Aufkleber vorhanden sind){}"}},
            tag_kranlaxs_legendary = {name = "Legendäres Tag", text = {"Shop hat einen kostenlosen", "{C:legendary}Legendären Joker{}"}},
            tag_kranlaxs_cosmic_tag = {name = "Kosmischer Tag", text = {"Fügt einer zufälligen Karte", "in deinem {C:attention}Deck{}", "die {C:dark_edition}Kosmisch{}-Edition hinzu"}},
            tag_kranlaxs_yellowish_tag = {name = "Gelblicher Tag", text = {"Fügt einer zufälligen Karte", "in deinem {C:attention}Deck{}", "die {C:attention}Sepia{}-Edition hinzu"}},
            tag_kranlaxs_boring_tag = {name = "Langweiliger Tag", text = {"Der nächste Joker im Shop", "ist {C:dark_edition}Monochrom{}"}},
            tag_kranlaxs_demonic_tag = {name = "Dämonischer Tag", text = {"Der nächste Joker im Shop", "ist {C:red}Verflucht{}"}},
            tag_kranlaxs_wet_tag = {name = "Nasser Tag", text = {"Fügt einer zufälligen Karte", "in deinem {C:attention}Deck{}", "die {C:blue}Unterwasser{}-Edition hinzu"}},
            tag_kranlaxs_zen_tag = {name = "Zen Tag", text = {"Reduziert das aktuelle", "{C:attention}Basis-Ante{} um {C:blue}-1{}"}}
        },

        Edition = {
            e_kranlaxs_cosmic = {name = "Kosmisch", text = {"Wertet die {C:attention}ausgewählte Pokerhand{} auf,", "wenn sie {C:red}abgeworfen{} wird"}},
            e_kranlaxs_sepia = {name = "Sepia", text = {"{C:green}#1# zu #2#{} Chance,", "einen {C:attention}Tag{} zu erstellen,", "wenn bei der Wertung auf der Hand"}},
            e_kranlaxs_cursed = {name = "Verflucht", text = {"{C:attention}Gleicht{} Chips und Mult", "bei der Wertung aus.", "{C:green}#1# zu #2#{} Chance,", "sich danach zu {C:red}zerstören{}. "}},
            e_kranlaxs_monochrome = {name = "Monochrom", text = {"{X:dark_edition,C:white} ^#1# {} Mult", "{C:red}Zerstört{} sich bei Wertung"}},
            e_kranlaxs_underwater = {name = "Unterwasser", text = {"{X:chips,C:white} X#1# {} Chips"}}
        },

        Other = {
            kranlaxs_magenta_sticker = {name = "Magenta Aufkleber", text = {"Verwendete diesen Joker,", "um auf {C:attention}Magenta Einsatz{} zu gewinnen"}},
            kranlaxs_brown_sticker = {name = "Brauner Aufkleber", text = {"Verwendete diesen Joker,", "um auf {C:attention}Braunem Einsatz{} zu gewinnen"}},
            kranlaxs_turquoise_sticker = {name = "Türkiser Aufkleber", text = {"Verwendete diesen Joker,", "um auf {C:attention}Türkisfarbenem Einsatz{} zu gewinnen"}},
            kranlaxs_platinum_sticker = {name = "Platin-Aufkleber", text = {"Verwendete diesen Joker,", "um auf {C:attention}Platin-Einsatz{} zu gewinnen"}},
            kranlaxs_orangeseal_seal = {name = "Oranges Siegel", text = {"Wenn in Hand gewertet: {C:attention}#1#{},", "erstellt 1 {C:attention}#2#{}", "{C:inactive}Ändert sich nach Gebrauch.{}", "{C:inactive}(Muss Platz haben){}"}},
            kranlaxs_pinkseal_seal = {name = "Rosa Siegel", text = {"Wendet {X:dark_edition,C:white}^1.75{} Mult an", "wenn {C:attention}gewertet{}"}},
            kranlaxs_whiteseal_seal = {name = "Weißes Siegel", text = {"{C:attention}Wird immer gewertet{}, immun gegen", "{C:red}Schwächung{}, {C:red}Zerstörung{}", "oder {C:attention}Umdrehen{}"}},
            kranlaxs_brownseal_seal = {name = "Braunes Siegel", text = {"{C:green}#1# zu #2#{} Chance,", "diese Karte zu {C:attention}duplizieren{}", "während sie auf der Hand ist"}},
            kranlaxs_grayseal_seal = {name = "Graues Siegel", text = {"Wenn {C:attention}gewertet{}, ändert sich", "die {C:enhanced}Verbesserung{} dieser Karte {C:attention}zufällig{}"}},
            kranlaxs_mintseal_seal = {name = "Minzsiegel", text = {"Verdoppelt alle {C:attention}angegebenen Wahrscheinlichkeiten{}", "auf dieser Karte"}},
            kranlaxs_deviled_sticker = {name = "Teuflischer Aufkleber", text = {"Verwendete diesen Joker,", "um auf {C:attention}Teuflischem Einsatz{} zu gewinnen"}},
            kranlaxs_glass_sticker = {name = "Glasaufkleber", text = {"Verwendete diesen Joker,", "um auf {C:attention}Glaseinsatz{} zu gewinnen"}},
            p_kranlaxs_uno_store_3 = {name = "UNO-Paket", text = {"Wähle {C:attention}1{} von bis zu", "{C:attention}3{} {C:blue}UNO{}-Karten"}},
            p_kranlaxs_uno_store_5 = {name = "Jumbo UNO-Paket", text = {"Wähle {C:attention}1{} von bis zu", "{C:attention}5{} {C:blue}UNO{}-Karten"}},
            p_kranlaxs_invtarot_instant_3_1 = {name = "Inverses Tarot-Paket", text = {"Wähle {C:attention}1{} von bis zu", "{C:attention}3{} {C:purple}Inversen Tarot{}-Karten"}},
            p_kranlaxs_invtarot_instant_5_1 = {name = "Jumbo Inverses Tarot-Paket", text = {"Wähle {C:attention}1{} von bis zu", "{C:attention}5{} {C:purple}Inversen Tarot{}-Karten"}},
            p_kranlaxs_invtarot_instant_5_2 = {name = "Mega Inverses Tarot-Paket", text = {"Wähle {C:attention}2{} von bis zu", "{C:attention}5{} {C:purple}Inversen Tarot{}-Karten"}},
            p_kranlaxs_invtarot_store_3_1 = {name = "Gespeichertes Inverses Tarot", text = {"Wähle {C:attention}1{} von bis zu", "{C:attention}3{} {C:purple}Inversen Tarot{}-Karten"}},
            p_kranlaxs_invtarot_store_5_1 = {name = "Gespeichertes Jumbo Inverses Tarot", text = {"Wähle {C:attention}1{} von bis zu", "{C:attention}5{} {C:purple}Inversen Tarot{}-Karten"}},
            p_kranlaxs_invtarot_store_5_2 = {name = "Gespeichertes Mega Inverses Tarot", text = {"Wähle {C:attention}2{} von bis zu", "{C:attention}5{} {C:purple}Inversen Tarot{}-Karten"}}
        },

        Booster = {
            p_kranlaxs_uno_store_3 = {name = "UNO-Paket", text = {"Wähle {C:attention}1{} von bis zu", "{C:attention}3{} {C:blue}UNO{}-Karten"}},
            p_kranlaxs_uno_store_5 = {name = "Jumbo UNO-Paket", text = {"Wähle {C:attention}1{} von bis zu", "{C:attention}5{} {C:blue}UNO{}-Karten"}},
            p_kranlaxs_invtarot_instant_3_1 = {name = "Inverses Tarot-Paket", text = {"Wähle {C:attention}1{} von bis zu", "{C:attention}3{} {C:purple}Inversen Tarot{}-Karten"}},
            p_kranlaxs_invtarot_instant_5_1 = {name = "Jumbo Inverses Tarot-Paket", text = {"Wähle {C:attention}1{} von bis zu", "{C:attention}5{} {C:purple}Inversen Tarot{}-Karten"}},
            p_kranlaxs_invtarot_instant_5_2 = {name = "Mega Inverses Tarot-Paket", text = {"Wähle {C:attention}2{} von bis zu", "{C:attention}5{} {C:purple}Inversen Tarot{}-Karten"}},
            p_kranlaxs_invtarot_store_3_1 = {name = "Gespeichertes Inverses Tarot", text = {"Wähle {C:attention}1{} von bis zu", "{C:attention}3{} {C:purple}Inversen Tarot{}-Karten"}},
            p_kranlaxs_invtarot_store_5_1 = {name = "Gespeichertes Jumbo Inverses Tarot", text = {"Wähle {C:attention}1{} von bis zu", "{C:attention}5{} {C:purple}Inversen Tarot{}-Karten"}},
            p_kranlaxs_invtarot_store_5_2 = {name = "Gespeichertes Mega Inverses Tarot", text = {"Wähle {C:attention}2{} von bis zu", "{C:attention}5{} {C:purple}Inversen Tarot{}-Karten"}}
        }
    },
    
    misc = {
        dictionary = {
            ["k_uno-paket_pack"] = "UNO-Paket",
            ["k_jumbo uno-paket_pack"] = "Jumbo UNO-Paket",
            ["k_inverses tarot-paket_pack"] = "Inverses Tarot-Paket",
            ["k_jumbo inverses tarot-paket_pack"] = "Jumbo Inverses Tarot-Paket",
            ["k_mega inverses tarot-paket_pack"] = "Mega Inverses Tarot-Paket",
            ["k_gespeichertes inverses tarot_pack"] = "Gespeichertes Inverses Tarot",
            ["k_gespeichertes jumbo inverses tarot_pack"] = "Gespeichertes Jumbo Inverses Tarot",
            ["k_gespeichertes mega inverses tarot_pack"] = "Gespeichertes Mega Inverses Tarot",
            
            k_uno_pack = "UNO-Paket",
            k_inversetarot_pack = "Inverses Tarot-Paket"
        },

        labels = {
            kranlaxs_magenta_sticker = "Magenta Aufkleber",
            kranlaxs_brown_sticker = "Brauner Aufkleber",
            kranlaxs_turquoise_sticker = "Türkiser Aufkleber",
            kranlaxs_platinum_sticker = "Platin-Aufkleber",
            kranlaxs_orangeseal_seal = "Oranges Siegel", 
            kranlaxs_pinkseal_seal = "Rosa Siegel", 
            kranlaxs_deviled_sticker = "Teuflischer Aufkleber",
            kranlaxs_glass_sticker = "Glasaufkleber",
            kranlaxs_whiteseal_seal = "Weißes Siegel", 
            kranlaxs_brownseal_seal = "Braunes Siegel", 
            kranlaxs_grayseal_seal = "Graues Siegel", 
            kranlaxs_mintseal_seal = "Minzsiegel", 
            clover = "Kleeblatt-Aufkleber",
            p_kranlaxs_uno_store_3 = "UNO-Paket",
            p_kranlaxs_uno_store_5 = "Jumbo UNO-Paket",
            p_kranlaxs_invtarot_instant_3_1 = "Inverses Tarot-Paket",
            p_kranlaxs_invtarot_instant_5_1 = "Jumbo Inverses Tarot-Paket",
            p_kranlaxs_invtarot_instant_5_2 = "Mega Inverses Tarot-Paket",
            p_kranlaxs_invtarot_store_3_1 = "Gespeichertes Inverses Tarot",
            p_kranlaxs_invtarot_store_5_1 = "Gespeichertes Jumbo Inverses Tarot",
            p_kranlaxs_invtarot_store_5_2 = "Gespeichertes Mega Inverses Tarot",
            kranlaxs_wave = "Aquatisch",
            e_kranlaxs_cosmic = "Kosmisch",
            e_kranlaxs_sepia = "Sepia",
            e_kranlaxs_cursed = "Verflucht",
            e_kranlaxs_monochrome = "Monochrom",
            e_kranlaxs_underwater = "Unterwasser"
        },

        v_text = {
            ch_c_kran_fijado_1 = {"Alle Joker haben den {C:attention}Angeheftet{}-Aufkleber"},
            ch_c_kran_abuela_1 = {"{C:attention}Wertende{} Joker sind {C:red}verboten{}"},
            ch_c_kran_crisis_1 = {"Der Shop ist {C:attention}20% teurer{}"},
            ch_c_kran_crisis_2 = {"Die Basis-Blind-Belohnung wird um {X:money,C:white} $2 {} {C:red}reduziert{}"},
            ch_c_kran_crisis_3 = {"Das Deck besteht nur aus {C:attention}52 Assen{}"},
            ch_c_kran_doppel_1 = {"Alle Joker sind im Shop {C:red}verboten{}"},
            ch_c_kran_anonimo_1 = {"Karten auf der Hand und Joker sind {C:attention}verdeckt{}"},
            ch_c_kran_jefes_1 = {"Kleine und Große Blinds sind {C:attention}Boss-Blinds{}"},
            ch_c_kran_premon_1 = {"Alle Karten auf deiner Hand sind {C:attention}verdeckt{}"},
            ch_c_kran_tallo_1 = {"Andere {C:attention}Joker{} und {C:attention}Pakete{} sind {C:red}verboten{}"},
            ch_c_gacha_rule_1 = {"Keine {C:attention}einzelnen Karten{} erscheinen im Shop"},
            ch_c_kran_pobreza_1 = {"{C:attention}50%{} Chance, dass ein {C:common}Gewöhnlicher{} Joker {C:legendary}Legendär{} ist"},
            ch_c_kran_pobreza_2 = {"Wenn dein {C:attention}Mönch{}-Joker enttäuscht wird, {C:red}verlierst du den Durchlauf{}"}
        }
    }
}