return {
    descriptions = {
        Joker = {
            j_kranlaxs_tagger = {name = "Tagger", text = {"Gains {C:red}+#1#{} Mult for each", "{C:attention}Tag{} obtained", "{C:inactive}(Currently {C:red}+#2#{C:inactive} Mult){}"}, unlock = {"Buy {C:attention}2{} Blank", "Vouchers in a single run"}},
            j_kranlaxs_Cashback = {name = "Cashback", text = {"{C:green}#1# in #2#{} chance to get {X:money,C:white} $3 {},", "when buying a card"}, unlock = {"Win a run on {C:attention}Red Stake{}", "using the {C:attention}Space Deck{}"}},
            j_kranlaxs_underratedjoker = {name = "Underrated Joker", text = {"This Joker gains {X:chips,C:white} X0.2 {} Chips", "if the played hand {C:attention}is not{}", "your most played poker hand", "{C:inactive}(Resets if it is){}", "{C:inactive}(Currently {X:chips,C:white} X#1# {C:inactive} Chips){}"}, unlock = {"Win a run on {C:attention}Blue Stake{}", "using the {C:attention}Space Deck{}"}},
            j_kranlaxs_facelessaccountant = {name = "Faceless Accountant", text = {"This Joker gains {X:blue,C:white} X0.1 {} Chips for", "each scored {C:attention}#2#{}", "{C:inactive}(Currently {X:blue,C:white} X#1# {C:inactive} Chips){}"}, unlock = {"Win a run without playing face cards,", "while having at least {C:attention}1{} in your deck"}},
            j_kranlaxs_thefixer = {name = "The Fixer", text = {"Selling a {C:attention}Joker{} during a", "{C:purple}Blind{} reduces the required score", "{C:inactive}(Common: -10%, Uncommon: -30%){}", "{C:inactive}(Rare: -60%, Legendary: -95%){}"}, unlock = {"Sell at least {C:attention}2{} Jokers", "of each rarity"}},
            j_kranlaxs_mysteriousgeode = {name = "Mysterious Geode", text = {"Each scored {C:attention}Wild Card{} gives", "a {C:attention}random{} effect"}, unlock = {"Play a hand", "with {C:attention}5{} Wild Cards"}},
            j_kranlaxs_benchwarmer = {name = "Benchwarmer", text = {"Gives {C:attention}4 times{} the {C:blue}Chip{} value", "of the highest ranked card held in hand"}},
            j_kranlaxs_entropy2 = {name = "Vortex", text = {"Gains {X:dark_edition,C:white} ^1 {} Mult and {X:dark_edition,C:white} ^1 {} Chips", "for each card {C:attention}below 52{} in your deck", "{C:inactive}(Currently {X:dark_edition,C:white} ^#1# {C:inactive} Mult and {X:dark_edition,C:white} ^#1# {C:inactive} Chips){}"}},
            j_kranlaxs_greedyleprachaun = {name = "Greedy Leprechaun", text = {"Draw {C:attention}3 extra cards{}", "on the first {C:red}discard{} of the round"}, unlock = {"Discard exactly {C:attention}1{} card", "{C:attention}3{} times in a row"}},
            j_kranlaxs_charismaticbard = {name = "Charismatic Bard", text = {"{C:attention}-1{} hand size", "Reduces {C:purple}Blind{} requirement by {C:attention}2%{} every time", "you play your {C:attention}most played hand{}", "{C:inactive}(Maximum 90%){}", "Resets if you play another hand", "{C:inactive}(Currently {C:attention}-#1#%{C:inactive} Blind size){}"}},
            j_kranlaxs_russianroulette = {name = "Russian Roulette", text = {"{C:green}#1# in #2#{} chance to {C:red}Lose the run{}", "when selecting a blind", "If you survive, gains", "{X:mult,C:white} X3 {} Mult and {X:chips,C:white} X3 {} Chips", "{C:inactive}(Currently {X:mult,C:white} X#3# {C:inactive} Mult and {X:chips,C:white} X#3# {C:inactive} Chips){}"}, unlock = {"Win a run on {C:attention}Black Stake{}", "using the {C:attention}Space Deck{}"}},
            j_kranlaxs_fidelitycard = {name = "Battle Pass", text = {"After buying {C:attention}6{} cards, the {C:attention}seventh{}", "bought card gives {X:money,C:white} money {} equal to", "the {C:attention}sell value{} of all your Jokers", "{C:inactive}(Currently {C:attention}#1#/6{C:inactive} cards){}", "{C:inactive}(Total sell value: {X:money,C:white} $#2# {C:inactive}){}"}},
            j_kranlaxs_devioussheep = {name = "Gluttonous Sheep", text = {"{C:red}Devours{} a random Joker when", "selecting a {C:attention}Blind{} and gains {X:mult,C:white} X0.4 {} Mult", "{C:hearts}Game Over{} if there are no other Jokers", "{C:inactive}(Prioritize certain targets for more Mult!){}", "{C:inactive}(Currently {X:mult,C:white} X#1# {C:inactive} Mult){}"}},
            j_kranlaxs_lifeassurance = {name = "Death Avoider", text = {"Prevents a Game Over if", "you have at least {X:money,C:white} $#1# {}", "{C:inactive}(Price doubles after each use){}"}, unlock = {"Lose a run with", "{X:money,C:white} $100 {} or more", "before {C:attention}Ante 8{}"}},
            j_kranlaxs_sundaycheckpoint = {name = "Checkpoint", text = {"{C:red}Game Over{} if you select", "a blind on a {C:attention}weekday{}", "Otherwise, creates a {C:attention}Weekly Challenge{} Joker", "at end of round and {C:red}self-destructs{}", "{C:inactive}(Current day: #1#){}"}},
            j_kranlaxs_weeklychallenge = {name = "Weekly Challenge", text = {"Sets a random challenge for this run", "{C:clubs}Current challenge:{} {C:attention}#1#{}", "{C:inactive}1:{} You have {X:money,C:white} -$100 {}, pay it before Ante 8", "{C:inactive}2:{} Restricted shop", "{C:inactive}3:{} 1 Hand, 20 Discards (No extra Vouchers)", "{C:inactive}4:{} Limit of {C:blue}#2#{} hands and {C:red}#3#{} discards in the run", "{C:inactive}5:{} Game speed locked at 0.5x", "{C:inactive}6:{} 3 Eternal Triboulets (Max 3 Jokers, Fast Ante)", "{C:inactive}7:{} 1 in 6 chance to WIN when defeating blind (Lose on Ante 8)"}},
            j_kranlaxs_panda = {name = "Fluffy Panda", text = {"Gives {C:chips}+#1#{} Chips", "{C:attention}-1{} Joker slot"}},
            j_kranlaxs_miner = {name = "Miner", text = {"Gains {C:red}+5{} Mult for each", "scored {C:attention}Stone Card{}", "{C:green}#2# in #3#{} chance to gain", "from {X:money,C:white} $#4# {} to {X:money,C:white} $#5# {} when playing a hand", "{C:inactive}(Currently {C:red}+#1#{C:inactive} Mult){}"}, unlock = {"Play a hand", "with {C:attention}5{} Stone Cards"}},
            j_kranlaxs_birthdaycake = {name = "Birthday Cake", text = {"Gives {X:dark_edition,C:white} ^#1# {} Mult", "Loses {X:dark_edition,C:white} ^0.25 {} after", "each played hand", "When depleted, creates a {C:attention}Regifted Joker{}"}, unlock = {"Win a run on", "{C:attention}Blue Stake{} using", "the {C:attention}Weekly Challenge{} deck"}},
            j_kranlaxs_vipsuscription = {name = "V.I.P. Subscription", text = {"Gives {C:attention}+#2#{} Shop slots,", "{C:attention}+1{} extra Voucher and Pack", "Subtracts {X:money,C:white} $#1# {} when opening the shop.", "Price and shop size", "{C:attention}increase{} when defeating a {C:attention}Boss Blind{}"}, unlock = {"Win a run on", "{C:attention}Orange Stake{} using", "the {C:attention}Weekly Challenge{} deck"}},
            j_kranlaxs_painterjoker = {name = "Painter Joker", text = {"When a hand scores, creates a", "{C:attention}Juggler Tag{} for each", "{C:attention}Wild Card{} in your hand", "{C:inactive}(Costs {X:money,C:white} $#1# {C:inactive} per tag){}"}, unlock = {"Win a run on", "{C:attention}Orange Stake{} using", "the {C:attention}Weekly Challenge{} deck"}},
            j_kranlaxs_coronation = {name = "Coronation", text = {"If played hand contains scored cards", "ranked {C:attention}10 or lower{}, transforms", "the lowest one into a {C:attention}King{}.", "If there are no low cards in hand,", "adds a {C:red}Red Seal{} to the first scored {C:attention}King{}."}, unlock = {"Play a hand of exactly", "{C:attention}5 Kings{}. All must have", "a {C:red}Red Seal{} and be {C:attention}Steel{} cards"}},
            j_kranlaxs_speedrunner = {name = "Speedrunner", text = {"{X:mult,C:white} X#1# {} Mult.", "You have {C:attention}#2# seconds{} to", "play a hand or discard.", "If time runs out, {C:red}GAME OVER{}."}, unlock = {"Win a run on", "{C:attention}Green Stake{} using", "the {C:attention}Weekly Challenge{} deck"}},
            j_kranlaxs_passcode = {name = "Passcode", text = {"If played hand matches any", "of the following codes, hand", "counts as a {C:attention}Flush Five{}", "{C:inactive}1. {C:attention}#1#{}", "{C:inactive}2. {C:attention}#2#{}", "{C:inactive}3. {C:attention}#3#{}"}, unlock = {"Win a run on", "{C:attention}Black Stake{} using", "the {C:attention}Weekly Challenge{} deck"}},
            j_kranlaxs_chronometer = {name = "Chronometer", text = {"When playing a hand: ", "Gives {C:chips}Chips{} equal to current {C:attention}Seconds{}", "Gives {C:mult}Mult{} equal to current {C:attention}Minutes{}", "Earns {C:money}money{} equal to current {C:attention}Hours{}", "{C:inactive}(Currently: {C:chips}+#1#{C:inactive} Chips, {C:mult}+#2#{C:inactive} Mult, {C:money}+$#3#{C:inactive}){}"}, unlock = {"Win a run on {C:attention}Gold Stake{}", "using the {C:attention}Space Deck{}"}},
            j_kranlaxs_zombiejoker = {name = "Sombi Yoker", text = {"{C:attention}destrois{} the {C:attention}fist{} card", "tht doesnt giv pionts n gains {C:red}+15{} mult", "bt u lose {C:red}-10{} mult", "xech hand playd in rond", "if it rches {C:red}0{} mult", "{C:attention}it dies {}", "{C:inactive}(u hv {C:red}+#1#{C:inactive} mult or smth){}"}, unlock = {"Win a run on {C:attention}Purple Stake{}", "using the {C:attention}Space Deck{}"}},
            j_kranlaxs_thecousin = {name = "The Cousin", text = {"Gains {C:chips}+13{} Chips for each", "scored {C:attention}prime number{}", "{C:inactive}(Currently {C:chips}+#1#{C:inactive} Chips){}"}, unlock = {"Win a run on {C:attention}Turquoise Stake{}", "using the {C:attention}Space Deck{}"}},
            j_kranlaxs_colasoda = {name = "Cola Soda", text = {"Gives {X:dark_edition,C:white} ^#1# {} Mult", "Loses {X:dark_edition,C:white} ^#2# {} for", "almost {C:attention}any action{} you take"}, unlock = {"Win a run on", "{C:attention}Blue Stake{} using", "the {C:attention}Weekly Challenge{} deck"}},
            j_kranlaxs_icecreamsandwich = {name = "Ice Cream Sandwich", text = {"Earn {X:money,C:white} $#1# {} at the end", "of the round", "Reward decreases by {X:money,C:white} $#2# {}", "after each round"}, unlock = {"Earn {X:money,C:white} $50 {} or more", "from payout in", "a single round"}},
            j_kranlaxs_dispensermachine = {name = "Vending Machine", text = {"If this Joker is {C:attention}selected{}", "when leaving the shop, spend {X:money,C:white} $#1# {}", "and create a {C:attention}Food Joker{}"}, unlock = {"Have {C:attention}4{} food", "Jokers at the same time"}},
            j_kranlaxs_bottledwater = {name = "Bottled Water", text = {"{X:chips,C:white} X#1# {} Chips", "Loses {X:chips,C:white} X#2# {} for", "each scored card"}, unlock = {"Win a run on", "{C:attention}Blue Stake{} using", "the {C:attention}Weekly Challenge{} deck"}},
            j_kranlaxs_burrow = {name = "Burrow", text = {"Gains {C:attention}+1{} Bunny for", "each {C:attention}Blind defeated{}", "When {C:gold}sold{}, creates {C:attention}#1#{} Bunnies"}},
            j_kranlaxs_bunny = {name = "Bunny", text = {"Gains {X:mult,C:white} X#1# {} Mult for each", "{C:attention}Bunny{} Joker you have", "{C:inactive}(Currently {X:mult,C:white} X#2# {C:inactive} Mult){}"}},
            j_kranlaxs_sushi = {name = "Sushi", text = {"Reduces Blind requirement", "by {C:attention}#1#%{}", "Reduction decreases by {C:attention}#2#%{}", "after defeating a {C:attention}Blind{}"}, unlock = {"Win a run on", "{C:attention}Purple Stake{} using", "the {C:attention}Weekly Challenge{} deck"}},
            j_kranlaxs_gigachad = {name = "Gigachad", text = {"Gains {C:chips}+#2#{} Chips for almost", "{C:attention}any action{} you take", "{C:inactive}(Currently {C:chips}+#1#{C:inactive} Chips){}"}, unlock = {"Win a run on", "{C:attention}White Stake{} using", "the {C:attention}Weekly Challenge{} deck"}},
            j_kranlaxs_nft = {name = "Crypto Scam", text = {"Reduces the {C:attention}rank{} of all", "cards in your hand by {C:attention}1{}", "when scoring a hand", "{C:inactive}(Cannot be reduced below 2){}"}},
            j_kranlaxs_beanstalk = {name = "Beanstalk", text = {"Useless beans"}, unlock = {"Win a run on", "{C:attention}White Stake{} using", "the {C:attention}Weekly Challenge{} deck"}},
            j_kranlaxs_suspiciousbeanstalk = {name = "Suspicious Beanstalk", text = {"Useless beans?..."}},
            j_kranlaxs_epicbeanstalk = {name = "Epic Beanstalk", text = {"Maybe they aren't useless beans..."}},
            j_kranlaxs_zenithbeanstalk = {name = "Zenith Beanstalk", text = {"Beans"}},
            j_kranlaxs_commonseed = {name = "Common Seed", text = {"{C:attention}Creates{} a random", "{C:common}Common{} Joker"}},
            j_kranlaxs_weirdlookingseed = {name = "Weird Seed", text = {"{C:attention}Creates{} a random", "{C:uncommon}Uncommon{} Joker"}},
            j_kranlaxs_magnificentseed = {name = "Magnificent Seed", text = {"{C:attention}Creates{} a random", "{C:rare}Rare{} Joker"}},
            j_kranlaxs_godseed = {name = "God Seed", text = {"{C:attention}Creates{} a random", "{C:legendary}Legendary{} Joker"}},
            j_kranlaxs_anonymousjoker = {name = "Anonymous Joker", text = {"When scoring, flips and gives between", "{X:mult,C:white} X1.5 {} and {X:mult,C:white} X4.0 {} Mult"}, unlock = {"Defeat the {C:attention}Amber Acorn{}", "Boss Blind 1 time"}},
            j_kranlaxs_littlebro = {name = "Little Bro", text = {"If played hand is {C:attention}High Card{} and", "scoring card is a {C:attention}#2#{},", "this Joker gains {X:red,C:white} X#3# {} Mult", "Rank changes every round", "{C:inactive}(Currently {X:red,C:white} X#1# {C:inactive} Mult){}"}, unlock = {"Play {C:attention}High Card{}", "{C:attention}30{} times in", "a single run"}},
            j_kranlaxs_medusa = {name = "Medusa", text = {"{C:attention}All played cards{}", "permanently become {C:attention}Stone Cards{}", "after playing a hand", "{C:inactive}(Even unscored ones){}"}, unlock = {"Win a run on {C:attention}Brown Stake{}", "using the {C:attention}Space Deck{}"}},
            j_kranlaxs_depression = {name = "Economic Recession", text = {"Gives {X:dark_edition,C:white}^#2#{} Mult", "Increases by {X:dark_edition,C:white}^#1#{} for each {X:money,C:white} $1 {}", "below {X:money,C:white} $0 {}"}, unlock = {"Enter a shop", "with {X:money,C:white} -$25 {} or less"}},
            j_kranlaxs_grannyjoker = {name = "Granny", text = {"Gives {X:dark_edition,C:white} ^3 {} Chips and {X:dark_edition,C:white} ^3 {} Mult", "Game speed is locked at {C:attention}0.25x{}", "{C:inactive}(Destroyed if you play a {C:attention}Straight{}", "{C:inactive}or {C:attention}Straight Flush{C:inactive}){}"}, unlock = {"Defeat {C:attention}12{} Blinds with", "game speed at {C:attention}0.5{}"}},
            j_kranlaxs_lateshippment = {name = "Late Shipment", text = {"Retrigger {C:attention}all played cards{}", "{C:attention}1 time{} for each hand played", "in the {C:attention}previous round{}", "{C:inactive}(Currently {C:attention}#1#{C:inactive} retriggers){}"}, unlock = {"Win a run on {C:attention}Orange Stake{}", "using the {C:attention}Space Deck{}"}},
            j_kranlaxs_unkownfactor = {name = "Variable X", text = {"All played cards are", "considered {C:attention}#1#{}", "{C:inactive}(Rank changes at end of round){}"}, unlock = {"Win a run on", "{C:attention}Gold Stake{} using", "the {C:attention}Weekly Challenge{} deck"}},
            j_kranlaxs_thethreers = {name = "The 3 Rs", text = {"Creates a {C:attention}copy{} of each played card", "and adds it to your {C:attention}deck{}", "{C:attention}Destroys{} all scored cards"}, unlock = {"Win a run on", "{C:attention}Gold Stake{} using", "the {C:attention}Weekly Challenge{} deck"}},
            j_kranlaxs_the = {name = "Jok", text = {"Gives {X:chips,C:white} X2 {} Chips and {X:mult,C:white} X2 {} Mult", "only on the {C:attention}first hand{} of the round"}, unlock = {"Defeat {C:attention}5{} Blinds using", "only {C:attention}1{} hand each"}},
            j_kranlaxs_chainreaction = {name = "Chain Reaction", text = {"If played hand is {C:attention}#2#{},", "gains {X:chips,C:white} X0.5 {} Chips and hand changes", "Resets if hand {C:attention}does not match{}", "{C:inactive}(Currently {X:chips,C:white} X#1# {C:inactive} Chips){}"}, unlock = {"Play every poker hand", "at least {C:attention}1{} time in a run"}},
            j_kranlaxs_anubis = {name = "Anubis", text = {"Balances {C:blue}Chips{} and {C:red}Mult{}", "when a hand is scored"}, unlock = {"Win a run with {C:attention}Plasma Deck{}", "on every stake difficulty"}},
            j_kranlaxs_erraticjoker = {name = "Erratic Joker", text = {"If scoring card is a", "{C:attention}Wild Card{}, swaps", "{C:blue}Chips{} and {C:red}Mult{}"}, unlock = {"Win a run on {C:attention}White Stake{}", "using the {C:attention}Space Deck{}"}},
            j_kranlaxs_luckyseven = {name = "Lucky Sevens", text = {"If played hand is exactly", "a {C:attention}Three of a Kind{} of only {C:attention}7s{}, this Joker", "gains {C:blue}+7{} Chips, {C:red}+7{} Mult and gives {X:money,C:white} $7 {}", "{C:inactive}(Currently {C:blue}+#1#{} Chips, {C:red}+#2#{} Mult)"}, unlock = {"Have at least {C:attention}10{} cards", "with rank {C:attention}7{} in your deck"}},
            j_kranlaxs_certificateddocument = {name = "Certified Document", text = {"Retriggers {C:attention}all{} seals"}, unlock = {"Win a run on", "{C:attention}Purple Stake{} using", "the {C:attention}Weekly Challenge{} deck"}},
            j_kranlaxs_platanito = {name = "Little Banana", text = {"Whenever another Joker triggers,", "gives {X:mult,C:white} X#3# {} extra Mult", "{C:green}#1# in #2#{} chance to", "be destroyed at end of round"}, unlock = {"Win a run on {C:attention}Platinum Stake{}", "using the {C:attention}Space Deck{}"}},
            j_kranlaxs_cubicaljoker = {name = "Cubical Joker", text = {"Gives {C:mult}+#1#{} Mult", "Value is raised to the", "{C:attention}Cube (^3){} for each", "{C:attention}Boss Blind{} defeated"}},
            j_kranlaxs_grapesoda = {name = "Grape Soda", text = {"When {C:gold}sold{}, creates a", "random {C:spectral}Spectral{} card", "with {C:dark_edition}Negative{} edition"}, unlock = {"Win a run on {C:attention}Magenta Stake{}", "using the {C:attention}Space Deck{}"}},
            j_kranlaxs_telescope = {name = "Telescope", text = {"If {C:attention}#1#{} levels up, level up", "that hand {C:attention}1{} extra time", "{C:inactive}(Hand changes at end of round){}"}, unlock = {"Win a run on", "{C:attention}Red Stake{} using", "the {C:attention}Weekly Challenge{} deck"}},
            j_kranlaxs_pandorabox = {name = "Pandora's Box", text = {"When defeating a {C:attention}Boss Blind{},", "creates a {C:attention}useful{} Joker based", "on your current deck", "{C:inactive}(Must have room){}"}},
            j_kranlaxs_doppelganger = {name = "Doppelgänger", text = {"Copies the ability of a random", "{C:attention}Joker{} from the entire game.", "Copied Joker changes after", "defeating a {C:attention}Blind{}.", "{C:inactive}(Currently: {C:attention}#1#{C:inactive})"}, unlock = {"Win a run on", "{C:attention}Gold Stake{} using", "the {C:attention}Weekly Challenge{} deck"}},
            j_kranlaxs_thechampion = {name = "The Champion", text = {"Blind requirement {C:attention}X#1#{}", "Earn {X:money,C:white} $#2# {} at end of round"}, unlock = {"Reach {C:attention}Ante 16{}"}},
            j_kranlaxs_clerigo = {name = "Cleric", text = {"Gives {C:mult}+#1#{} Mult for each", "card in your full deck", "Loses {C:mult}-#2#{} Mult for each card", "with an enhancement or seal", "{C:inactive}(Currently {C:mult}+#3#{C:inactive} Mult){}"}, unlock = {"Complete challenge:", "{C:attention}Family Recipe{}"}},
            j_kranlaxs_entrenador = {name = "Coach", text = {"Gives {X:mult,C:white} X#1# {} Mult if you are", "below Ante {C:attention}#3#{}", "Otherwise, gives {X:mult,C:white} X#2# {} Mult", "{C:inactive}(Currently {X:mult,C:white} X#4# {C:inactive} Mult){}"}, unlock = {"Complete challenge:", "{C:attention}Economic Crisis{}"}},
            j_kranlaxs_medium = {name = "Medium", text = {"Gives {C:mult}+#1#{} Mult for each", "{C:red}lost{} run in your profile", "{C:inactive}(Currently {C:mult}+#2#{C:inactive} Mult){}"}, unlock = {"Lose {C:attention}1{} run", "{C:inactive}(Progress: {C:attention}#1#{C:inactive} / 1){}"}},
            j_kranlaxs_monk = {name = "Monk", text = {"Gains {X:chips,C:white} X#1# {} Chips if you leave", "the shop without spending {X:money,C:white} money {}", "{C:red}Resets{} if you buy something", "{C:inactive}(Currently {X:chips,C:white} X#2# {C:inactive} Chips){}"}, unlock = {"Complete challenge:", "{C:attention}Vow of Poverty{}"}},
            j_kranlaxs_knight = {name = "Knight", text = {"After scoring {C:attention}#1#{} {C:attention}Steel{} cards,", "{C:attention}Disables{} the next {C:attention}Boss Blind{}", "{C:inactive}(Scored cards: #2#/#1#){}"}, unlock = {"Complete challenge:", "{C:attention}Boss Syndicate{}"}},
            j_kranlaxs_overpopulation = {name = "Overpopulation", text = {"Gives {C:mult}+#1#{} Mult for each", "{C:attention}face card{} above", "the limit of {C:attention}#2#{}", "in your deck", "{C:inactive}(Currently {C:mult}+#3#{C:inactive} Mult){}"}, unlock = {"Win a run on {C:attention}Green Stake{}", "using the {C:attention}Space Deck{}"}},
            j_kranlaxs_antisocial = {name = "Antisocial", text = {"This Joker gains {C:mult}+#1#{} Mult", "if you play exactly {C:attention}1{} card", "{C:red}Resets{} if you play more than 1", "{C:inactive}(Currently {C:mult}+#2#{C:inactive} Mult){}"}, unlock = {"Complete challenge:", "{C:attention}Total Fixation{}"}},
            j_kranlaxs_famous = {name = "Famous", text = {"Gives {C:chips}+#1#{} Chips if played", "hand is a {C:attention}Five of a Kind{},", "{C:attention}Flush Five{} or {C:attention}Flush House{}"}},
            j_kranlaxs_influencer = {name = "Influencer", text = {"Gives {C:mult}+#1#{} Mult if played", "hand is a {C:attention}Five of a Kind{},", "{C:attention}Flush Five{} or {C:attention}Flush House{}"}},
            j_kranlaxs_potatobag = {name = "Potato Bag", text = {"Accumulates scored Chips", "When reaching {C:attention}#1#{}, applies", "{X:mult,C:white} X#2# {} Mult to the", "next hand and empties", "{C:inactive}(Accumulated: #3#/#1#){}"}},
            j_kranlaxs_simonsays = {name = "Simon Says", text = {"This Joker gains {X:mult,C:white} X#2# {} Mult", "when completing its request", "Simon says... {C:attention}#3#{}", "{C:inactive}(Currently {X:mult,C:white} X#1# {C:inactive} Mult){}"}, unlock = {"Complete challenge:", "{C:attention}The Great Beanstalk{}"}},
            j_kranlaxs_cheater = {name = "Cheater", text = {"Jokers in the shop", "have a {C:green}35%{} chance", "to be replaced by", "{C:attention}Vouchers{} or {C:attention}Booster Packs{}"}, unlock = {"Complete challenge:", "{C:attention}Gachapon{}"}},
            j_kranlaxs_philosopher = {name = "Philosopher", text = {"Reveals the next {C:attention}5 cards{}", "from your deck", "{C:inactive}(Each card has a 20%{}", "{C:inactive}chance of being hidden){}", "{C:attention}#1#{}"}, unlock = {"Complete challenge:", "{C:attention}Premonitions{}"}},
            j_kranlaxs_mandalajoker = {name = "Mandala Joker", text = {"This Joker gains {X:mult,C:white} X0.5 {} Mult", "for each {C:spectral}Spectral{} card used", "{C:inactive}(Currently {X:mult,C:white} X#1# {C:inactive} Mult){}"}, unlock = {"Use {C:attention}20{} {C:spectral}Spectral{} cards", "{C:inactive}(Progress: {C:attention}#1#{C:inactive} / 20){}"}},
            j_kranlaxs_regift = {name = "Regifted Joker", text = {"When {C:gold}sold{}, creates a", "random {C:attention}Joker{}", "Rarity depends on current {C:attention}Blind{}"}, unlock = {"Sell {C:attention}50{} Jokers", "in total", "{C:inactive}(Progress: {C:attention}#1#{C:inactive} / 50){}"}},
            j_kranlaxs_pyromaniac = {name = "Pyromaniac", text = {"After scoring a hand, {C:red}destroys{}", "all {C:attention}number{} cards in your hand", "{C:inactive}(Gold, Glass and Steel cards are safe){}"}, unlock = {"Destroy {C:attention}100{} cards", "that are not face cards", "{C:inactive}(Progress: {C:attention}#1#{C:inactive} / 100){}"}},
            j_kranlaxs_neverendinggambling = {name = "Neverending Gambling", text = {"Lose {X:money,C:white} $1 {} for each action you take", "{C:inactive}(Only if you have {X:money,C:white} $5 {} or more){}", "Spin 3 numbers. If they match, win a prize!", "If 2 match, recover {X:money,C:white} $1 {} as consolation", "{C:inactive}(Current spin: #1# - #2# - #3#){}"}, unlock = {"Fail {C:attention}30{} Joker or", "consumable probabilities", "{C:inactive}(Progress: {C:attention}#1#{C:inactive} / 30){}"}},
            j_kranlaxs_solarsystem = {name = "Solar System", text = {"At {C:attention}end of round{}, creates a", "{C:planet}Planet{} card in a fixed sequence", "{C:inactive}(Next planet: {C:planet}#1#{C:inactive}){}"}, unlock = {"Use all {C:attention}12{} standard", "{C:planet}Planet{} cards at least once", "in a single run", "{C:inactive}(Progress: {C:attention}#1#{C:inactive} / 12){}"}},
            j_kranlaxs_deranged = {name = "Deranged", text = {"Gives {C:mult}+#1#{} Mult or {C:chips}+#2#{} Chips", "Effect swaps every time", "you play a hand"}, unlock = {"Complete challenge:", "{C:attention}Identity Crisis{}"}},
            j_kranlaxs_deranged_mult = {name = "Deranged", text = {"Gives {C:mult}+#1#{} Mult", "Effect swaps every time", "you play a hand"}},
            j_kranlaxs_deranged_chips = {name = "Deranged", text = {"Gives {C:chips}+#2#{} Chips", "Effect swaps every time", "you play a hand"}},
            j_kranlaxs_tmtrainer = {
                name = "TMTRAINER", 
                text = {
                    "{C:dark_edition}#1#{}",
                    "{C:attention}#2#{}",
                    "{C:red}#3#{}",
                    "{C:chips}#4#{}"
                },
                unlock = {
                    "Complete challenge:",
                    "{C:attention}Identity Crisis{}"
                }
            },
            j_kranlaxs_bingocard = {name = "Bingo Card", text = {"Gains {X:mult,C:white} X0.25 {} Mult", "for each completed line", "{C:inactive}(Total: {X:mult,C:white} X#2# {C:inactive} Mult){}", "{C:attention}#3#{}", "{C:attention}#4#{}", "{C:attention}#5#{}", "{C:attention}#6#{}", "{C:attention}#7#{}"}, unlock = {"Complete challenge:", "{C:attention}Total Anonymity{}"}}
        },

        Back = {
            b_kranlaxs_week_challenge = {name = "Weekly Challenge", text = {"Start with a {C:attention}Weekly Challenge{} Joker", "{C:red}Beatable{} every {C:attention}weekend{}"}, unlock = {"Open the game on a", "{C:attention}Saturday{} or {C:attention}Sunday{}"}},
            b_kranlaxs_chaos_deck = {name = "Chaos Deck", text = {"Enjoy the chaos"}, unlock = {"Unlock {C:legendary,E:1}EVERYTHING{} in", "your collection"}},
            b_kranlaxs_dungeon_deck = {name = "Dungeon Deck", text = {"After defeating a {C:attention}Boss Blind{},", "choose between 3 {C:attention}options{}", "with {C:green}pros{} and {C:red}cons{}"}, unlock = {"Win a run on {C:attention}Green Stake{}", "or higher using the", "{C:attention}Weekly Challenge{} deck"}},
            b_kranlaxs_space_deck = {name = "Space Deck", text = {"{C:attention}0{} Joker slots, {C:attention}5{} consumable slots", "Shop only sells {C:attention}Quartzes{}", "{C:attention}+1{} to shop size, Blinds are {C:attention}7.5%{} smaller", "Winning Ante: {C:attention}10{}"}, unlock = {"Win a run on {C:attention}Green Stake{}", "with the {C:attention}Magic Deck{}, the", "{C:attention}Nebula Deck{} and the {C:attention}Zodiac Deck{}"}},
            b_kranlaxs_bugged_deck = {name = "Bugged Deck", text = {"!?"}, unlock = {"Acquire a {C:attention}TMTRAINER{}", "for the first time"}}
        },

        Stake = {
            stake_kranlaxs_magenta = {name = "Magenta Stake", text = {"Shop cards can have", "the {C:attention}Pinned{} sticker"}},
            stake_kranlaxs_brown = {name = "Brown Stake", colour = "Brown", text = {"{C:attention}-1{} {C:attention}Booster Pack{} slot", "in the shop"}},
            stake_kranlaxs_turquoise = {name = "Turquoise Stake", colour = "Turquoise", text = {"Blinds have a {C:attention}50%{} chance", "of {C:red}not being skippable{}"}},
            stake_kranlaxs_deviled = {name = "Deviled Stake", colour = "Deviled", text = {"{C:attention}-1{} {C:attention}Joker{} slot"}},
            stake_kranlaxs_glass = {name = "Glass Stake", colour = "Glass", text = {"Required score scales", "even faster for each {C:attention}Ante{}"}},
            stake_kranlaxs_platinum = {name = "Platinum Stake", colour = "Platinum", text = {"Must beat {C:attention}Ante 10{}", "to win the run"}}
        },

        UNOCards = {
            c_kranlaxs_skip = {name = "Skip", text = {"Instantly get the Blind requirement", "Does not work on {C:attention}Boss Blinds{}"}},
            c_kranlaxs_stacking = {name = "Stacking", text = {"Adds a {C:attention}Pink Seal{} to", "{C:attention}1{} selected card in hand"}},
            c_kranlaxs_draw2 = {name = "Draw 2", text = {"When used, {C:attention}draw 2 extra cards{}", "to your hand, lose {C:blue}1{} hand"}},
            c_kranlaxs_draw4 = {name = "Draw 4", text = {"When used, {C:attention}draw 4 extra cards{}", "to your hand, lose {C:blue}1{} hand"}},
            c_kranlaxs_reverse = {name = "Reverse", text = {"Returns {C:attention}all cards{} from your", "hand to the deck and {C:attention}reshuffles{} them"}},
            c_kranlaxs_wildcard = {name = "Wild Card", text = {"{C:attention}Converts{} each card in", "your hand to a {C:attention}random suit{}", "{C:attention}independently{}"}},
            c_kranlaxs_replay = {name = "Replay", text = {"Returns the cards from the", "last played hand to your hand", "{C:inactive}(Resets after use or", "{C:inactive}at end of round)"}},
            c_kranlaxs_discardall = {name = "Discard All", text = {"Requires {C:attention}1{} selected card.", "Discards {C:red}all{} cards", "from your {C:attention}hand{} and {C:attention}deck{} that", "share the same suit"}},
            c_kranlaxs_shield = {name = "Shield", text = {"Passively protects you from death or", "can be sold to disable the {C:attention}Boss Blind{}"}},
            c_kranlaxs_misery = {name = "Misery", text = {"Choose a {C:attention}Suit{}.", "Draws cards from your deck", "non-stop until you", "get one of that suit"}},
            c_kranlaxs_gift = {name = "Gift", text = {"Grants {C:attention}1{} of the following", "random prizes:", "• A {C:attention}Joker{} with Edition", "• A Negative {C:attention}Consumable{}", "• A {C:attention}Card{} with Enhancement, Seal and Edition"}},
            c_kranlaxs_customdraw = {name = "Custom Draw", text = {"Draws the same amount of cards", "as discards you have made", "{C:inactive}(Currently: {C:attention}#1#{C:inactive} cards){}"}}
        },

        InverseTarot = {
            c_kranlaxs_thefool = {name = "The Fool?", text = {"Creates a random {C:spectral}Spectral{} card", "{C:attention}Downgrades{} a random poker hand"}},
            c_kranlaxs_themagician = {name = "The Magician?", text = {"Creates {C:attention}2{} random {C:attention}Lucky{} cards"}},
            c_kranlaxs_thehighpriestess = {name = "The High Priestess?", text = {"Creates a {C:spectral}Black Hole{}", "Your {X:money,C:white} money {} {C:attention}decreases{} by 20%"}},
            c_kranlaxs_theempress = {name = "The Empress?", text = {"Adds permanent {C:red}+8{} Mult", "to up to {C:attention}2{} selected cards"}},
            c_kranlaxs_theemperor = {name = "The Emperor?", text = {"Creates {C:attention}2{} random {C:attention}Tags{}"}},
            c_kranlaxs_thehierophant = {name = "The Hierophant?", text = {"Adds permanent {C:blue}+40{} Chips", "to up to {C:attention}2{} selected cards"}},
            c_kranlaxs_thelovers = {name = "The Lovers?", text = {"Gain {C:attention}+1{} hand size if", "you have a {C:attention}Wild Card{} in your deck"}},
            c_kranlaxs_thechariot = {name = "The Chariot?", text = {"Creates {C:attention}1{} random {C:attention}Steel{} card", "with a {C:attention}Red{} Seal"}},
            c_kranlaxs_justice = {name = "Justice?", text = {"Adds permanent {X:red,C:white} X2 {} Mult", "to {C:attention}1{} selected card", "{C:green}#1# in #2#{} chance to {C:attention}destroy{} this card"}},
            c_kranlaxs_thehermit = {name = "The Hermit?", text = {"{C:attention}Sets{} your {X:money,C:white} money {} to {X:money,C:white} $25 {} if", "you have {C:attention}less than{} {X:money,C:white} $25 {}"}},
            c_kranlaxs_thewheeloffortune = {name = "The Wheel of Fortune?", text = {"{C:green}#1# in #2#{} chance to create a {C:attention}copy{}", "of a random Joker with {C:dark_edition}Negative{} edition"}},
            c_kranlaxs_strenght = {name = "Strength?", text = {"{C:attention}Reduces{} the {C:attention}rank{} of up to", "{C:attention}2{} selected cards by {C:attention}1{}"}},
            c_kranlaxs_thehangedman = {name = "The Hanged Man?", text = {"Completely {C:attention}randomizes{} up to", "{C:attention}2{} selected cards in hand"}},
            c_kranlaxs_death = {name = "Death?", text = {"Creates a {C:attention}Negative copy{} of a random Joker", "A random Joker receives a {C:attention}Perishable{} Sticker"}},
            c_kranlaxs_temperance = {name = "Temperance?", text = {"Sells {C:attention}ALL{} Jokers (even Eternals)", "for {C:money}triple{} their sell value", "{C:inactive}(Does not sell Pinned Jokers){}"}},
            c_kranlaxs_thedevil = {name = "The Devil?", text = {"Adds permanent {X:money,C:white} $2 {}", "to up to {C:attention}2{} selected cards"}},
            c_kranlaxs_thetower = {name = "The Tower?", text = {"{C:attention}Removes{} all enhancements, seals,", "editions and bonuses from cards in hand", "Gains {X:money,C:white} $1 {} for each modification removed"}},
            c_kranlaxs_thestars = {name = "The Stars?", text = {"Adds a {C:attention}White Seal{} to up to", "{C:attention}2{} selected cards"}},
            c_kranlaxs_themoon = {name = "The Moon?", text = {"Adds a {C:attention}Gray Seal{} to up to", "{C:attention}2{} selected cards"}},
            c_kranlaxs_thesun = {name = "The Sun?", text = {"Adds an {C:attention}Orange Seal{} to up to", "{C:attention}2{} selected cards"}},
            c_kranlaxs_judgement = {name = "Judgement?", text = {"{C:attention}Redeems{} a random {C:attention}Voucher{}", "{C:red}-1{} hand size"}},
            c_kranlaxs_theworld = {name = "The World?", text = {"Adds a {C:attention}Brown Seal{} to up to", "{C:attention}2{} selected cards"}}
        },

        Voucher = {
            v_kranlaxs_more_stock = {name = "More Stock", text = {"Shop has {C:attention}1{} extra", "{C:attention}Booster Pack{} slot"}},
            v_kranlaxs_even_more_stock = {name = "Even More Stock", text = {"Shop has {C:attention}1{} extra", "{C:attention}Voucher{} slot"}},
            v_kranlaxs_shiny_appearance = {name = "Shiny Appearance", text = {"Legendary cards and rare consumables", "can now appear in the shop"}},
            v_kranlaxs_stickerfever = {name = "Sticker Fever", text = {"Whenever you obtain", "a {C:attention}Tag{}, gain", "{C:attention}1{} extra copy"}},
            v_kranlaxs_stickeralbum = {name = "Sticker Album", text = {"Whenever you obtain", "a {C:attention}Tag{}, gain", "{C:attention}1{} more extra copy"}},
            v_kranlaxs_hotfix = {name = "Hotfix", text = {"{C:attention}Rerolling{} the shop", "also refreshes {C:attention}Vouchers{}", "and {C:attention}Booster Packs{}"}},
            v_kranlaxs_version2 = {name = "Version 2.0", text = {"Skipping blinds grants you the {X:money,C:white} money {}", "reward of that blind.", "Blind requirement {C:attention}-15%{}"}},
            v_kranlaxs_common_shinys = {name = "Legendary Sighting", text = {"Legendary cards and rare consumables", "will appear more frequently"}},
            v_kranlaxs_blessing = {name = "Blessing", text = {"You start with {C:attention}10%{}", "of the chip requirement", "completed on every blind"}},
            v_kranlaxs_protection = {name = "Divine Protection", text = {"Protects you from a {C:attention}Game Over{}.", "Upon use, this voucher is destroyed", "and can reappear in the shop,", "but at {X:money,C:white} double {} its original price"}}
        },

        Quartz = {
            c_kranlaxs_blackquartz = {name = "Obsidian", text = {"Modifies some rules", "of your choice"}, unlock = {"Win a run on {C:attention}Brown Stake{}", "using the {C:attention}Magic Deck{}"}},
            c_kranlaxs_whitequartz = {name = "Pearl", text = {"Creates the last", "used consumable", "{C:inactive}(Last card: {C:attention}#1#{C:inactive}){}"}, unlock = {"Win a run on {C:attention}Brown Stake{}", "using the {C:attention}Ghost Deck{}"}},
            c_kranlaxs_pinkquartz = {name = "Rose Quartz", text = {"Adds {C:dark_edition}Polychrome{} to a {C:attention}Joker{}", "or selected {C:attention}card{}"}, unlock = {"Win a run on {C:attention}Magenta Stake{}", "or higher using the {C:attention}Dungeon Deck{}"}},
            c_kranlaxs_bluequartz = {name = "Sapphire", text = {"Adds {C:chips}Foil{} to a", "selected {C:attention}Joker{} or {C:attention}card{}"}, unlock = {"Win a run on {C:attention}Platinum Stake{}", "using the {C:attention}Plasma Deck{}"}},
            c_kranlaxs_lilacquartz = {name = "Kunzite", text = {"Adds {C:mult}Holographic{} to a", "selected {C:attention}Joker{} or {C:attention}card{}"}, unlock = {"Win a run on {C:attention}Brown Stake{}", "using the {C:attention}Nebula Deck{}"}},
            c_kranlaxs_grayquartz = {name = "Hematite", text = {"Adds {C:dark_edition}Negative{} to a", "selected {C:attention}Joker{} or {C:attention}consumable{}"}, unlock = {"Win a run on {C:attention}Turquoise Stake{}", "using the {C:attention}Painted Deck{}"}},
            c_kranlaxs_transparentquartz = {name = "Diamond", text = {"{C:attention}Removes{} all stickers or editions", "from a {C:attention}Joker{}, or seals or", "editions from a selected {C:attention}card{}"}, unlock = {"Win a run on {C:attention}Platinum Stake{}", "using the {C:attention}Dungeon Deck{}"}},
            c_kranlaxs_redquartz = {name = "Ruby", text = {"While {C:attention}held{},", "gives {X:mult,C:white} X2 {} Mult", "{C:inactive}(Passive){}"}, unlock = {"Win a run on {C:attention}Magenta Stake{}", "or higher using the {C:attention}Red Deck{}"}},
            c_kranlaxs_celestequartz = {name = "Larimar", text = {"While {C:attention}held{},", "gives {X:chips,C:white} X1.5 {} Chips", "{C:inactive}(Passive){}"}, unlock = {"Win a run on {C:attention}Turquoise Stake{}", "using the {C:attention}Checkered Deck{}"}},
            c_kranlaxs_yellowquartz = {name = "Topaz", text = {"Creates the indicated {C:attention}Joker{}.", "Joker changes randomly", "after each {C:attention}round{}", "{C:inactive}(Target: {C:attention}#1#{C:inactive}){}"}, unlock = {"Win a run on {C:attention}Blue Stake{}", "using the {C:attention}Dungeon Deck{}"}},
            c_kranlaxs_greenquartz = {name = "Emerald", text = {"While {C:attention}held{}, creates a", "{C:attention}Tag{} after defeating a {C:attention}Blind{}", "Destroyed after creating {C:attention}#2#{} tags", "{C:inactive}(Current: {C:attention}#1#{C:inactive}){}", "{C:inactive}(Passive){}"}, unlock = {"Win a run on {C:attention}Magenta Stake{}", "or higher using the {C:attention}Green Deck{}"}},
            c_kranlaxs_brownquartz = {name = "Tiger's Eye", text = {"Creates the indicated {C:attention}Card{}.", "Card changes randomly after", "{C:green}Rerolling{} the shop", "{C:inactive}(Target: {C:attention}#1#{C:inactive}){}"}, unlock = {"Win a run on {C:attention}Turquoise Stake{}", "using the {C:attention}Anaglyph Deck{}"}},
            c_kranlaxs_turquoisequartz = {name = "Turquoise", text = {"While {C:attention}held{}, {C:attention}disables{}", "all Jokers except the first one", "Retriggers that Joker {C:attention}2{} times", "{C:inactive}(Passive){}"}, unlock = {"Win a run on {C:attention}Turquoise Stake{}", "using the {C:attention}Zodiac Deck{}"}},
            c_kranlaxs_orangequartz = {name = "Citrine", text = {"Adds {C:green}Mint Seal{} to a {C:attention}card{}", "or {C:green}Clover Sticker{} to a", "selected {C:attention}Joker{}"}, unlock = {"Win a run on {C:attention}Magenta Stake{}", "or higher using the {C:attention}Yellow Deck{}"}},
            c_kranlaxs_lapislazuli = {name = "Lapis Lazuli", text = {"While {C:attention}held{}, adds", "{C:chips}+#1#{} Chips to the first scored card", "Effect decreases by {C:chips}-#2#{} each use.", "{C:inactive}(Inactive when it reaches 0){}", "{C:inactive}(Passive){}"}, unlock = {"Win a run on {C:attention}Magenta Stake{}", "or higher using the {C:attention}Blue Deck{}"}},
            c_kranlaxs_cinnabar = {name = "Cinnabar", text = {"While {C:attention}held{}, adds", "{C:mult}+#1#{} Mult to the first scored card", "Effect decreases by {C:mult}-#2#{} each use.", "{C:inactive}(Inactive when it reaches 0){}", "{C:inactive}(Passive){}"}, unlock = {"Win a run on {C:attention}Brown Stake{}", "using the {C:attention}Abandoned Deck{}"}},
            c_kranlaxs_graphite = {name = "Graphite", text = {"While {C:attention}held{}, {C:green}#1# in #2#{}", "chance to create a copy in your", "hand of all played cards.", "Chance drops on trigger.", "{C:inactive}(Inactive when it reaches 0){}", "{C:inactive}(Passive){}"}, unlock = {"Win a run on {C:attention}Magenta Stake{}", "or higher using the {C:attention}Black Deck{}"}},
            c_kranlaxs_uranium = {name = "Uranium", text = {"While {C:attention}held{}, applies 1 random", "effect per round. It can be", "very good or very destructive.", "{C:dark_edition}Current status:{}", "{C:red,E:2}#1#{}", "{C:inactive}(Dare to carry it?){}", "{C:inactive}(Passive){}"}, unlock = {"Win a run on {C:attention}Platinum Stake{}", "using the {C:attention}Erratic Deck{}"}}
        },

        Tag = {
            tag_kranlaxs_mega_invtarot = {name = "Mega Inverse Tag", text = {"Grants a free {C:attention}Mega Inverse Tarot Pack{}", "instantly"}},
            tag_kranlaxs_mega_uno = {name = "Jumbo UNO Tag", text = {"Grants a free {C:attention}Jumbo UNO Pack{}", "instantly"}},
            tag_kranlaxs_mega_invtarot_store = {name = "Stored Mega Inverse Tag", text = {"Grants a free {C:attention}Stored Mega Inverse Tarot{}", "instantly"}},
            tag_kranlaxs_quartz_tag = {name = "Quartz Tag", text = {"Creates a random {C:attention}Quartz{}", "{C:inactive}(Must have room){}"}},
            tag_kranlaxs_sticker_remover = {name = "Cleanser Tag", text = {"Removes an {C:attention}Eternal{},", "{C:attention}Perishable{} or {C:attention}Rental{} sticker from", "a random {C:attention}Joker{}", "{C:inactive}(Gives {X:money,C:white} $5 {C:inactive} if no stickers){}"}},
            tag_kranlaxs_legendary = {name = "Legendary Tag", text = {"Shop has a free", "{C:legendary}Legendary Joker{}"}}
        },

        Edition = {
            e_kranlaxs_wave = {name = "Aquatic", text = {"{X:chips,C:white} X#1# {} Chips"}}
        },

        Other = {
            kranlaxs_magenta_sticker = {name = "Magenta Sticker", text = {"Used this Joker", "to win on {C:attention}Magenta Stake{}"}},
            kranlaxs_brown_sticker = {name = "Brown Sticker", text = {"Used this Joker", "to win on {C:attention}Brown Stake{}"}},
            kranlaxs_turquoise_sticker = {name = "Turquoise Sticker", text = {"Used this Joker", "to win on {C:attention}Turquoise Stake{}"}},
            kranlaxs_platinum_sticker = {name = "Platinum Sticker", text = {"Used this Joker", "to win on {C:attention}Platinum Stake{}"}},
            kranlaxs_orangeseal_seal = {name = "Orange Seal", text = {"If scored in hand: {C:attention}#1#{},", "creates 1 {C:attention}#2#{}", "{C:inactive}Changes after use.{}", "{C:inactive}(Must have room){}"}},
            kranlaxs_pinkseal_seal = {name = "Pink Seal", text = {"Applies {X:dark_edition,C:white}^1.75{} Mult", "when {C:attention}scored{}"}},
            kranlaxs_whiteseal_seal = {name = "White Seal", text = {"{C:attention}Always scores{}, immune to", "being {C:red}debuffed{}, {C:red}destroyed{}", "or {C:attention}flipped{}"}},
            kranlaxs_brownseal_seal = {name = "Brown Seal", text = {"{C:green}#1# in #2#{} chance to", "{C:attention}duplicate{} this card", "while held in hand"}},
            kranlaxs_grayseal_seal = {name = "Gray Seal", text = {"When {C:attention}scored{}, {C:attention}randomly{} changes", "the {C:enhanced}Enhancement{} of this card"}},
            kranlaxs_mintseal_seal = {name = "Mint Seal", text = {"Doubles all {C:attention}listed probabilities{}", "on this card"}},
            p_kranlaxs_uno_store_3 = {name = "UNO Pack", text = {"Choose {C:attention}1{} of up to", "{C:attention}3{} {C:blue}UNO{} cards"}},
            p_kranlaxs_uno_store_5 = {name = "Jumbo UNO Pack", text = {"Choose {C:attention}1{} of up to", "{C:attention}5{} {C:blue}UNO{} cards"}},
            p_kranlaxs_invtarot_instant_3_1 = {name = "Inverse Tarot Pack", text = {"Choose {C:attention}1{} of up to", "{C:attention}3{} {C:purple}Inverse Tarot{} cards"}},
            p_kranlaxs_invtarot_instant_5_1 = {name = "Jumbo Inverse Tarot Pack", text = {"Choose {C:attention}1{} of up to", "{C:attention}5{} {C:purple}Inverse Tarot{} cards"}},
            p_kranlaxs_invtarot_instant_5_2 = {name = "Mega Inverse Tarot Pack", text = {"Choose {C:attention}2{} of up to", "{C:attention}5{} {C:purple}Inverse Tarot{} cards"}},
            p_kranlaxs_invtarot_store_3_1 = {name = "Stored Inverse Tarot", text = {"Choose {C:attention}1{} of up to", "{C:attention}3{} {C:purple}Inverse Tarot{} cards"}},
            p_kranlaxs_invtarot_store_5_1 = {name = "Stored Jumbo Inverse Tarot", text = {"Choose {C:attention}1{} of up to", "{C:attention}5{} {C:purple}Inverse Tarot{} cards"}},
            kranlaxs_deviled_sticker = {name = "Deviled Sticker", text = {"Used this Joker", "to win on {C:attention}Deviled Stake{}"}},
            kranlaxs_glass_sticker = {name = "Glass Sticker", text = {"Used this Joker", "to win on {C:attention}Glass Stake{}"}},
            p_kranlaxs_invtarot_store_5_2 = {name = "Stored Mega Inverse Tarot", text = {"Choose {C:attention}2{} of up to", "{C:attention}5{} {C:purple}Inverse Tarot{} cards"}}
        },

        Booster = {
            p_kranlaxs_uno_store_3 = {name = "UNO Pack", text = {"Choose {C:attention}1{} of up to", "{C:attention}3{} {C:blue}UNO{} cards"}},
            p_kranlaxs_uno_store_5 = {name = "Jumbo UNO Pack", text = {"Choose {C:attention}1{} of up to", "{C:attention}5{} {C:blue}UNO{} cards"}},
            p_kranlaxs_invtarot_instant_3_1 = {name = "Inverse Tarot Pack", text = {"Choose {C:attention}1{} of up to", "{C:attention}3{} {C:purple}Inverse Tarot{} cards"}},
            p_kranlaxs_invtarot_instant_5_1 = {name = "Jumbo Inverse Tarot Pack", text = {"Choose {C:attention}1{} of up to", "{C:attention}5{} {C:purple}Inverse Tarot{} cards"}},
            p_kranlaxs_invtarot_instant_5_2 = {name = "Mega Inverse Tarot Pack", text = {"Choose {C:attention}2{} of up to", "{C:attention}5{} {C:purple}Inverse Tarot{} cards"}},
            p_kranlaxs_invtarot_store_3_1 = {name = "Stored Inverse Tarot", text = {"Choose {C:attention}1{} of up to", "{C:attention}3{} {C:purple}Inverse Tarot{} cards"}},
            p_kranlaxs_invtarot_store_5_1 = {name = "Stored Jumbo Inverse Tarot", text = {"Choose {C:attention}1{} of up to", "{C:attention}5{} {C:purple}Inverse Tarot{} cards"}},
            p_kranlaxs_invtarot_store_5_2 = {name = "Stored Mega Inverse Tarot", text = {"Choose {C:attention}2{} of up to", "{C:attention}5{} {C:purple}Inverse Tarot{} cards"}}
        }
    },
    
    misc = {
        dictionary = {
            ["k_uno pack_pack"] = "UNO Pack",
            ["k_jumbo uno pack_pack"] = "Jumbo UNO Pack",
            ["k_inverse tarot pack_pack"] = "Inverse Tarot Pack",
            ["k_jumbo inverse tarot pack_pack"] = "Jumbo Inverse Tarot Pack",
            ["k_mega inverse tarot pack_pack"] = "Mega Inverse Tarot Pack",
            ["k_stored inverse tarot_pack"] = "Stored Inverse Tarot",
            ["k_stored jumbo inverse tarot_pack"] = "Stored Jumbo Inverse Tarot",
            ["k_stored mega inverse tarot_pack"] = "Stored Mega Inverse Tarot",
            
            k_uno_pack = "UNO Pack",
            k_inversetarot_pack = "Inverse Tarot Pack"
        },

        labels = {
            kranlaxs_magenta_sticker = "Magenta Sticker",
            kranlaxs_deviled_sticker = "Deviled Sticker",
            kranlaxs_glass_sticker = "Glass Sticker",
            kranlaxs_brown_sticker = "Brown Sticker",
            kranlaxs_turquoise_sticker = "Turquoise Sticker",
            kranlaxs_platinum_sticker = "Platinum Sticker",
            kranlaxs_orangeseal_seal = "Orange Seal", 
            kranlaxs_pinkseal_seal = "Pink Seal", 
            kranlaxs_whiteseal_seal = "White Seal", 
            kranlaxs_brownseal_seal = "Brown Seal", 
            kranlaxs_grayseal_seal = "Gray Seal", 
            kranlaxs_mintseal_seal = "Mint Seal", 
            clover = "Clover Sticker",
            p_kranlaxs_uno_store_3 = "UNO Pack",
            p_kranlaxs_uno_store_5 = "Jumbo UNO Pack",
            p_kranlaxs_invtarot_instant_3_1 = "Inverse Tarot Pack",
            p_kranlaxs_invtarot_instant_5_1 = "Jumbo Inverse Tarot Pack",
            p_kranlaxs_invtarot_instant_5_2 = "Mega Inverse Tarot Pack",
            p_kranlaxs_invtarot_store_3_1 = "Stored Inverse Tarot",
            p_kranlaxs_invtarot_store_5_1 = "Stored Jumbo Inverse Tarot",
            p_kranlaxs_invtarot_store_5_2 = "Stored Mega Inverse Tarot",
            kranlaxs_wave = "Aquatic"
        },

        v_text = {
            ch_c_kran_fijado_1 = {"All Jokers have the {C:attention}Pinned{} sticker"},
            ch_c_kran_abuela_1 = {"{C:attention}Scoring{} Jokers are {C:red}banned{}"},
            ch_c_kran_crisis_1 = {"The shop is {C:attention}20% more expensive{}"},
            ch_c_kran_crisis_2 = {"Base blind reward is {C:red}reduced{} by {X:money,C:white} $2 {}"},
            ch_c_kran_crisis_3 = {"The deck consists only of {C:attention}52 Aces{}"},
            ch_c_kran_doppel_1 = {"All Jokers are {C:red}banned{} from the shop"},
            ch_c_kran_anonimo_1 = {"Cards in hand and Jokers are {C:attention}face down{}"},
            ch_c_kran_jefes_1 = {"Small and Big Blinds are {C:attention}Boss Blinds{}"},
            ch_c_kran_premon_1 = {"All cards in your hand are {C:attention}face down{}"},
            ch_c_kran_tallo_1 = {"Other {C:attention}Jokers{} and {C:attention}Packs{} are {C:red}banned{}"},
            ch_c_gacha_rule_1 = {"No {C:attention}individual cards{} appear in the shop"},
            ch_c_kran_pobreza_1 = {"{C:attention}50%{} chance for a {C:common}Common{} to be {C:legendary}Legendary{}"},
            ch_c_kran_pobreza_2 = {"If your {C:attention}Monk{} Joker gets disappointed, {C:red}you lose the run{}"}
        }
    }
}