return {
    descriptions = {
        Joker = {
            j_kranlaxs_tagger = {name = "Etiquetador", text = {"Gana {C:red}+#1#{} multi por cada", "{C:attention}Etiqueta{} obtenida", "{C:inactive}(Actualmente {C:red}+#2#{C:inactive} multi){}"}, unlock = {"Compra los {C:attention}2{} Vales", "de descuento en una sola run"}},
            j_kranlaxs_Cashback = {name = "Reembolso", text = {"{C:green}#1# de #2#{} probabilidades de obtener {X:money,C:white} $3 {},", "al comprar una carta"}, unlock = {"Gana una partida en {C:attention}Pozo Rojo{}", "usando la {C:attention}Baraja Espacial{}"}},
            j_kranlaxs_underratedjoker = {name = "Joker Infravalorado", text = {"Este Joker gana {X:chips,C:white} X0.2 {} fichas", "si la mano jugada {C:attention}no es{}", "tu mano de póker más jugada", "{C:inactive}(Se reinicia si lo es){}", "{C:inactive}(Actualmente {X:chips,C:white} X#1# {C:inactive} fichas){}"}, unlock = {"Gana una partida en {C:attention}Pozo Azul{}", "usando la {C:attention}Baraja Espacial{}"}},
            j_kranlaxs_facelessaccountant = {name = "Contador Descarado", text = {"Este Joker gana {X:blue,C:white} X0.1 {} fichas por", "cada {C:attention}#2#{} puntuada", "{C:inactive}(Actualmente {X:blue,C:white} X#1# {C:inactive} fichas){}"}, unlock = {"Gana una partida sin jugar figuras,", "pero teniendo al menos {C:attention}1{} en tu baraja"}},
            j_kranlaxs_thefixer = {name = "El Sobornador", text = {"Vender un {C:attention}Joker{} durante una", "{C:purple}Ciega{} reduce la puntuación requerida", "{C:inactive}(Común: -10%, Inusual: -30%){}", "{C:inactive}(Rara: -60%, Legendaria: -95%){}"}, unlock = {"Vende al menos {C:attention}2{} comodines", "de cada rareza"}},
            j_kranlaxs_mysteriousgeode = {name = "Geoda Misteriosa", text = {"Cada {C:attention}Carta Versátil{} puntuada da", "un efecto {C:attention}aleatorio{}"}, unlock = {"Juega una mano", "con {C:attention}5{} Cartas Versátiles"}},
            j_kranlaxs_benchwarmer = {name = "Calientabancas", text = {"Da {C:attention}4 veces{} el valor en {C:blue}fichas{}", "de la carta con la categoría más alta en mano"}},
            j_kranlaxs_entropy2 = {name = "Vórtice", text = {"Gana {X:dark_edition,C:white} ^1 {} multi y {X:dark_edition,C:white} ^1 {} fichas", "por cada carta {C:attention}menor a 52{} en tu baraja", "{C:inactive}(Actualmente {X:dark_edition,C:white} ^#1# {C:inactive} multi y {X:dark_edition,C:white} ^#1# {C:inactive} fichas){}"}},
            j_kranlaxs_greedyleprachaun = {name = "Duende Avaricioso", text = {"Roba {C:attention}3 cartas adicionales{}", "en el primer {C:red}descarte{} de la ronda"}, unlock = {"Descarta {C:attention}1{} sola carta", "{C:attention}3{} veces seguidas"}},
            j_kranlaxs_charismaticbard = {name = "Bardo Carismático", text = {"{C:attention}-1{} tamaño de mano", "Reduce la {C:purple}Ciega{} un {C:attention}2%{} cada vez", "que juegas tu {C:attention}mano más jugada{}", "{C:inactive}(Máximo 90%){}", "Se reinicia si juegas otra mano", "{C:inactive}(Actualmente {C:attention}-#1#%{C:inactive} tamaño de Ciega){}"}},
            j_kranlaxs_russianroulette = {name = "Ruleta Rusa", text = {"{C:green}#1# de #2#{} probabilidades de {C:red}Perder la partida{}", "al seleccionar una ciega", "Si sobrevives, gana", "{X:mult,C:white} X3 {} multi y {X:chips,C:white} X3 {} fichas", "{C:inactive}(Actualmente {X:mult,C:white} X#3# {C:inactive} multi y {X:chips,C:white} X#3# {C:inactive} fichas){}"}, unlock = {"Gana una partida en {C:attention}Pozo Negro{}", "usando la {C:attention}Baraja Espacial{}"}},
            j_kranlaxs_fidelitycard = {name = "Pase de batalla", text = {"Después de comprar {C:attention}6{} cartas, la {C:attention}séptima{}", "carta comprada da {X:money,C:white} dinero {} igual al", "{C:attention}valor de venta{} de todos tus Jokers", "{C:inactive}(Actualmente {C:attention}#1#/6{C:inactive} cartas){}", "{C:inactive}(Valor de venta total: {X:money,C:white} $#2# {C:inactive}){}"}},
            j_kranlaxs_devioussheep = {name = "Oveja Glotona", text = {"{C:red}Devora{} un Joker al azar al", "seleccionar una {C:attention}Ciega{} y gana {X:mult,C:white} X0.4 {} multi", "{C:hearts}Fin de la Partida{} si no hay otros Jokers", "{C:inactive}(¡Prioriza ciertos objetivos para más multi!){}", "{C:inactive}(Actualmente {X:mult,C:white} X#1# {C:inactive} multi){}"}},
            j_kranlaxs_lifeassurance = {name = "Evita la muerte-", text = {"Evita un Fin de la Partida si", "tienes al menos {X:money,C:white} $#1# {}", "{C:inactive}(El precio se duplica tras cada uso){}"}, unlock = {"Pierde una partida con", "{X:money,C:white} $100 {} o más en tu poder", "antes del {C:attention}Ante 8{}"}},
            j_kranlaxs_sundaycheckpoint = {name = "Punto de Control", text = {"{C:red}Fin de la Partida{} si seleccionas", "una ciega en un {C:attention}día de semana{}", "De lo contrario, crea un Joker de {C:attention}Desafío Semanal{}", "al final de la ronda y se {C:red}destruye{} a sí mismo", "{C:inactive}(Día actual: #1#){}"}},
            j_kranlaxs_weeklychallenge = {name = "Desafío Semanal", text = {"Establece un desafío aleatorio para esta partida", "{C:clubs}Desafío actual:{} {C:attention}#1#{}", "{C:inactive}1:{} Tienes {X:money,C:white} -$100 {}, págalo antes del Ante 8", "{C:inactive}2:{} Tienda restringida", "{C:inactive}3:{} 1 Mano, 20 Descartes (Sin Vales extra)", "{C:inactive}4:{} Límite de {C:blue}#2#{} manos y {C:red}#3#{} descartes en la partida", "{C:inactive}5:{} Velocidad de juego estancada en 0.5x", "{C:inactive}6:{} 3 Triboulets Eternos (Máx 3 Jokers, Ante Rápido)", "{C:inactive}7:{} 1 de 6 prob. de GANAR al vencer la ciega (Pierdes en Ante 8)"}},
            j_kranlaxs_panda = {name = "Panda Esponjoso", text = {"Da {C:chips}+#1#{} fichas", "{C:attention}-1{} espacio de Joker"}},
            j_kranlaxs_miner = {name = "Minero", text = {"Gana {C:red}+5{} multi por cada", "{C:attention}Carta de Piedra{} puntuada", "{C:green}#2# de #3#{} probabilidades de ganar", "de {X:money,C:white} $#4# {} a {X:money,C:white} $#5# {} al jugar una mano", "{C:inactive}(Actualmente {C:red}+#1#{C:inactive} multi){}"}, unlock = {"Juega una mano", "con {C:attention}5{} Cartas de Piedra"}},
            j_kranlaxs_birthdaycake = {name = "Pastel de Cumpleaños", text = {"Da {X:dark_edition,C:white} ^#1# {} multi", "Pierde {X:dark_edition,C:white} ^0.25 {} después", "de cada mano jugada", "Al agotarse crea un {C:attention}Joker Reregalado{}"}, unlock = {"Gana una partida en dificultad", "{C:attention}Pozo Azul{} usando", "la baraja {C:attention}Reto Semanal{}"}},
            j_kranlaxs_vipsuscription = {name = "Suscripción V.I.P", text = {"Da {C:attention}+#2#{} espacios en la tienda,", "{C:attention}+1{} Vale y Sobre extra", "Resta {X:money,C:white} $#1# {} al abrir la tienda.", "El precio y el tamaño de la tienda", "{C:attention}aumentan{} al vencer a una {C:attention}Ciega Jefe{}"}, unlock = {"Gana una partida en dificultad", "{C:attention}Pozo Naranja{} usando", "la baraja {C:attention}Reto Semanal{}"}},
            j_kranlaxs_painterjoker = {name = "Joker Pintor", text = {"Al puntuar una mano, crea una", "{C:attention}Etiqueta de Malabarista{} por cada", "{C:attention}Carta Versátil{} en tu mano", "{C:inactive}(Cuesta {X:money,C:white} $#1# {C:inactive} por etiqueta){}"}, unlock = {"Gana una partida en dificultad", "{C:attention}Pozo Naranja{} usando", "la baraja {C:attention}Reto Semanal{}"}},
            j_kranlaxs_coronation = {name = "Coronación", text = {"Si la mano jugada contiene cartas puntuadas", "de categoría {C:attention}10 o menor{}, transforma", "la de menor valor en un {C:attention}Rey{}.", "Si no hay cartas bajas en la baraja,", "añade un {C:red}Sello Rojo{} al primer {C:attention}Rey{} puntuado."}, unlock = {"Juega una mano de exactamente", "{C:attention}5 Reyes{}. Todos deben tener", "{C:red}Sello Rojo{} y ser cartas de {C:attention}Acero{}"}},
            j_kranlaxs_speedrunner = {name = "Speedrunner", text = {"{X:mult,C:white} X#1# {} multi.", "Tienes {C:attention}#2# segundos{} para", "jugar una mano o descartar.", "Si el tiempo se acaba, {C:red}FIN DE LA PARTIDA{}."}, unlock = {"Gana una partida en dificultad", "{C:attention}Pozo Verde{} usando", "la baraja {C:attention}Reto Semanal{}"}},
            j_kranlaxs_passcode = {name = "Contraseña", text = {"Si la mano jugada coincide con alguno", "de los siguientes códigos, la mano", "cuenta como {C:attention}Cinco de color{}", "{C:inactive}1. {C:attention}#1#{}", "{C:inactive}2. {C:attention}#2#{}", "{C:inactive}3. {C:attention}#3#{}"}, unlock = {"Gana una partida en dificultad", "{C:attention}Pozo Negro{} usando", "la baraja {C:attention}Reto Semanal{}"}},
            j_kranlaxs_chronometer = {name = "Cronómetro", text = {"Al jugar una mano: ", "Da {C:chips}fichas{} igual a los {C:attention}Segundos{} actuales", "Da {C:mult}multi{} igual a los {C:attention}Minutos{} actuales", "Gana {C:money}dinero{} igual a las {C:attention}Horas{} actuales", "{C:inactive}(Actualmente: {C:chips}+#1#{C:inactive} fichas, {C:mult}+#2#{C:inactive} multi, {C:money}+$#3#{C:inactive}){}"}, unlock = {"Gana una partida en {C:attention}Pozo Dorado{}", "usando la {C:attention}Baraja Espacial{}"}},
            j_kranlaxs_zombiejoker = {name = "Yoker Sombi", text = {"{C:attention}destrulle{} la {C:attention}primer{} carta", "k no da putos y gana {C:red}+15{} multi", "pero pierds {C:red}-10{} multi", "xkada mano jugda en la rond", "si yega a {C:red}0{} multi", "{C:attention}se muere {}", "{C:inactive}(tines {C:red}+#1#{C:inactive} multi o algo asi){}"}, unlock = {"Gana una partida en {C:attention}Pozo Morado{}", "usando la {C:attention}Baraja Espacial{}"}},
            j_kranlaxs_thecousin = {name = "El Primo", text = {"Gana {C:chips}+13{} fichas por cada", "{C:attention}número primo{} puntuado", "{C:inactive}(Actualmente {C:chips}+#1#{C:inactive} fichas){}"}, unlock = {"Gana una partida en {C:attention}Pozo turquesa{}", "usando la {C:attention}Baraja Espacial{}"}},
            j_kranlaxs_colasoda = {name = "Refresco de Cola", text = {"Da {X:dark_edition,C:white} ^#1# {} multi", "Pierde {X:dark_edition,C:white} ^#2# {} por", "casi {C:attention}cualquier acción{} que realices"}, unlock = {"Gana una partida en dificultad", "{C:attention}Pozo Azul{} usando", "la baraja {C:attention}Reto Semanal{}"}},
            j_kranlaxs_icecreamsandwich = {name = "Sándwich de Helado", text = {"Gana {X:money,C:white} $#1# {} al final", "de la ronda", "La recompensa disminuye en {X:money,C:white} $#2# {}", "después de cada ronda"}, unlock = {"Gana {X:money,C:white} $50 {} o más", "como pago en", "una sola ronda"}},
            j_kranlaxs_dispensermachine = {name = "Máquina Expendedora", text = {"Si este Joker está {C:attention}seleccionado{}", "al salir de la tienda, gasta {X:money,C:white} $#1# {}", "y crea un {C:attention}Joker de Comida{}"}, unlock = {"Ten {C:attention}4{} comodines de", "comida al mismo tiempo"}},
            j_kranlaxs_bottledwater = {name = "Agua Embotellada", text = {"{X:chips,C:white} X#1# {} fichas", "Pierde {X:chips,C:white} X#2# {} por", "cada carta puntuada"}, unlock = {"Gana una partida en dificultad", "{C:attention}Pozo Azul{} usando", "la baraja {C:attention}Reto Semanal{}"}},
            j_kranlaxs_burrow = {name = "Madriguera", text = {"Gana {C:attention}+1{} Conejo por", "cada {C:attention}Ciega vencida{}", "Al ser {C:gold}vendido{}, crea {C:attention}#1#{} Conejos"}},
            j_kranlaxs_bunny = {name = "Conejo", text = {"Gana {X:mult,C:white} X#1# {} multi por cada", "Joker {C:attention}Conejo{} que tengas", "{C:inactive}(Actualmente {X:mult,C:white} X#2# {C:inactive} multi){}"}},
            j_kranlaxs_sushi = {name = "Sushi", text = {"Reduce el requisito de la", "Ciega un {C:attention}#1#%{}", "La reducción disminuye un {C:attention}#2#%{}", "después de vencer una {C:attention}Ciega{}"}, unlock = {"Gana una partida en dificultad", "{C:attention}Pozo Morado{} usando", "la baraja {C:attention}Reto Semanal{}"}},
            j_kranlaxs_gigachad = {name = "Gigachad", text = {"Gana {C:chips}+#2#{} fichas por casi", "{C:attention}cualquier acción{} que realices", "{C:inactive}(Actualmente {C:chips}+#1#{C:inactive} fichas){}"}, unlock = {"Gana una partida en dificultad", "{C:attention}Pozo Blanco{} usando", "la baraja {C:attention}Reto Semanal{}"}},
            j_kranlaxs_nft = {name = "Criptoestafa", text = {"Reduce la {C:attention}categoría{} de todas", "las cartas en tu mano en {C:attention}1{}", "al puntuar una mano", "{C:inactive}(No puede reducirse por debajo de 2){}"}},
            j_kranlaxs_beanstalk = {name = "Tallo de Frijol", text = {"Frijoles inútiles"}, unlock = {"Gana una partida en dificultad", "{C:attention}Pozo Blanco{} usando", "la baraja {C:attention}Reto Semanal{}"}},
            j_kranlaxs_suspiciousbeanstalk = {name = "Tallo de Frijol Sospechoso", text = {"¿Frijoles inútiles?..."}},
            j_kranlaxs_epicbeanstalk = {name = "Tallo de Frijol Épico", text = {"Tal vez no sean frijoles inútiles..."}},
            j_kranlaxs_zenithbeanstalk = {name = "Tallo de Frijol Cenit", text = {"Frijoles"}},
            j_kranlaxs_commonseed = {name = "Semilla Común", text = {"{C:attention}Crea{} un Joker", "{C:common}Común{} al azar"}},
            j_kranlaxs_weirdlookingseed = {name = "Semilla Rara", text = {"{C:attention}Crea{} un Joker", "{C:uncommon}Inusual{} al azar"}},
            j_kranlaxs_magnificentseed = {name = "Semilla Magnífica", text = {"{C:attention}Crea{} un Joker", "{C:rare}Raro{} al azar"}},
            j_kranlaxs_godseed = {name = "Semilla Divina", text = {"{C:attention}Crea{} un Joker", "{C:legendary}Legendario{} al azar"}},
            j_kranlaxs_anonymousjoker = {name = "Joker Anónimo", text = {"Al puntuar se voltea y da entre", "{X:mult,C:white} X1.5 {} y {X:mult,C:white} X4.0 {} de multi"}, unlock = {"Derrota a la ciega jefe", "{C:attention}Bellota Ambarina{} 1 vez"}},
            j_kranlaxs_littlebro = {name = "Hermanito", text = {"Si la mano jugada es {C:attention}Carta Alta{} y", "la carta puntuada es un {C:attention}#2#{},", "este Joker gana {X:red,C:white} X#3# {} multi", "La carta cambia cada ronda", "{C:inactive}(Actualmente {X:red,C:white} X#1# {C:inactive} multi){}"}, unlock = {"Juega {C:attention}Carta Alta{}", "{C:attention}30{} veces en", "una sola partida"}},
            j_kranlaxs_medusa = {name = "Medusa", text = {"{C:attention}Todas las cartas jugadas{}", "se convierten permanentemente en {C:attention}Cartas de Piedra{}", "después de jugar una mano", "{C:inactive}(Incluso las no puntuadas){}"}, unlock = {"Gana una partida en {C:attention}Pozo marrón{}", "usando la {C:attention}Baraja Espacial{}"}},
            j_kranlaxs_depression = {name = "Recesión Económica", text = {"Da {X:dark_edition,C:white}^#2#{} multi", "Aumenta en {X:dark_edition,C:white}^#1#{} por cada {X:money,C:white} $1 {}", "por debajo de {X:money,C:white} $0 {}"}, unlock = {"Entra a una tienda", "con {X:money,C:white} -$25 {} o menos"}},
            j_kranlaxs_grannyjoker = {name = "La Abuela", text = {"Da {X:dark_edition,C:white} ^3 {} fichas y {X:dark_edition,C:white} ^3 {} multi", "La velocidad de juego se bloquea en {C:attention}0.25x{}", "{C:inactive}(Se destruye si juegas una {C:attention}Escalera{}", "{C:inactive}o {C:attention}Escalera de Color{C:inactive}){}"}, unlock = {"Derrota {C:attention}12{} ciegas con la", "velocidad de juego en {C:attention}0.5{}"}},
            j_kranlaxs_lateshippment = {name = "Envío Tardío", text = {"Reactiva {C:attention}todas las cartas jugadas{}", "{C:attention}1 vez{} por cada mano jugada", "en la {C:attention}ronda anterior{}", "{C:inactive}(Actualmente {C:attention}#1#{C:inactive} reactivaciones){}"}, unlock = {"Gana una partida en {C:attention}Pozo Naranja{}", "usando la {C:attention}Baraja Espacial{}"}},
            j_kranlaxs_unkownfactor = {name = "Variable X", text = {"Todas las cartas jugadas son", "consideradas como {C:attention}#1#{}", "{C:inactive}(La categoría cambia al final de la ronda){}"}, unlock = {"Gana una partida en dificultad", "{C:attention}Pozo Dorado{} usando", "la baraja {C:attention}Reto Semanal{}"}},
            j_kranlaxs_thethreers = {name = "Las 3 R", text = {"Crea una {C:attention}copia{} de cada carta jugada", "y la añade a tu {C:attention}baraja{}", "{C:attention}Destruye{} todas las cartas puntuadas"}, unlock = {"Gana una partida en dificultad", "{C:attention}Pozo Dorado{} usando", "la baraja {C:attention}Reto Semanal{}"}},
            j_kranlaxs_the = {name = "Jok", text = {"Da {X:chips,C:white} X2 {} fichas y {X:mult,C:white} X2 {} multi", "solo en la {C:attention}primera mano{} de la ronda"}, unlock = {"Gana {C:attention}5{} ciegas usando", "solo {C:attention}1{} mano cada una"}},
            j_kranlaxs_chainreaction = {name = "Reacción en Cadena", text = {"Si la mano jugada es {C:attention}#2#{},", "gana {X:chips,C:white} X0.5 {} fichas y la mano cambia", "Se reinicia si la mano {C:attention}no coincide{}", "{C:inactive}(Actualmente {X:chips,C:white} X#1# {C:inactive} fichas){}"}, unlock = {"Juega todas las manos de póker", "al menos {C:attention}1{} vez en una partida"}},
            j_kranlaxs_anubis = {name = "Anubis", text = {"Equilibra las {C:blue}fichas{} y el {C:red}multi{}", "cuando una mano es puntuada"}, unlock = {"Gana una partida con la {C:attention}Baraja de Plasma{}", "en cada una de las dificultades"}},
            j_kranlaxs_erraticjoker = {name = "Joker Errático", text = {"Si la carta puntuada es una", "{C:attention}Carta Versátil{}, intercambia las", "{C:blue}fichas{} y el {C:red}multi{}"}, unlock = {"Gana una partida en {C:attention}Pozo Blanco{}", "usando la {C:attention}Baraja Espacial{}"}},
            j_kranlaxs_luckyseven = {name = "Los 7 Afortunados", text = {"Si la mano jugada es exactamente", "un {C:attention}Trío{} de solo {C:attention}7s{}, este Joker", "gana {C:blue}+7{} fichas, {C:red}+7{} multi y da {X:money,C:white} $7 {}", "{C:inactive}(Actualmente {C:blue}+#1#{} fichas, {C:red}+#2#{} multi)"}, unlock = {"Ten al menos {C:attention}10{} cartas", "con rango {C:attention}7{} en tu baraja"}},
            j_kranlaxs_certificateddocument = {name = "Documento Certificado", text = {"Reactiva {C:attention}todos{} los sellos"}, unlock = {"Gana una partida en dificultad", "{C:attention}Pozo Morado{} usando", "la baraja {C:attention}Reto Semanal{}"}},
            j_kranlaxs_platanito = {name = "Platanito", text = {"Cada vez que otro Joker se activa,", "da {X:mult,C:white} X#3# {} multi adicional", "{C:green}#1# de #2#{} probabilidades de", "ser destruido al final de la ronda"}, unlock = {"Gana una partida en {C:attention}Pozo de platino{}", "usando la {C:attention}Baraja Espacial{}"}},
            j_kranlaxs_cubicaljoker = {name = "Joker Cúbico", text = {"Da {C:mult}+#1#{} multi", "El valor se eleva al", "{C:attention}Cubo (^3){} por cada", "{C:attention}Ciega Jefe{} vencida"}},
            j_kranlaxs_grapesoda = {name = "Refresco de Uva", text = {"Al ser {C:gold}vendido{}, crea una carta", "{C:spectral}Espectral{} aleatoria", "con edición {C:dark_edition}Negativa{}"}, unlock = {"Gana una partida en {C:attention}Pozo magenta{}", "usando la {C:attention}Baraja Espacial{}"}},
            j_kranlaxs_telescope = {name = "Telescopio", text = {"Si se sube de nivel {C:attention}#1#{}, sube de nivel", "esa mano {C:attention}1{} vez adicional", "{C:inactive}(La mano cambia al final de la ronda){}"}, unlock = {"Gana una partida en dificultad", "{C:attention}Pozo Rojo{} usando", "la baraja {C:attention}Reto Semanal{}"}},
            j_kranlaxs_pandorabox = {name = "Caja de Pandora", text = {"Al vencer a una {C:attention}Ciega Jefe{},", "crea un Joker {C:attention}útil{} basado", "en tu baraja actual", "{C:inactive}(Debes tener espacio){}"}},
            j_kranlaxs_doppelganger = {name = "Doppelgänger", text = {"Copia la habilidad de un {C:attention}Joker{}", "aleatorio de todo el juego.", "El Joker copiado cambia tras", "vencer a una {C:attention}Ciega{}.", "{C:inactive}(Actualmente: {C:attention}#1#{C:inactive})"}, unlock = {"Gana una partida en dificultad", "{C:attention}Pozo Dorado{} usando", "la baraja {C:attention}Reto Semanal{}"}},
            j_kranlaxs_thechampion = {name = "El Campeón", text = {"Requisito de la ciega {C:attention}X#1#{}", "Gana {X:money,C:white} $#2# {} al final de la ronda"}, unlock = {"Llega a la {C:attention}Ante 16{}"}},
            j_kranlaxs_clerigo = {name = "Clérigo", text = {"Da {C:mult}+#1#{} de multi por cada", "carta en tu baraja completa", "Pierde {C:mult}-#2#{} de multi por cada carta", "con alguna mejora o sello", "{C:inactive}(Actualmente {C:mult}+#3#{C:inactive} de multi){}"}, unlock = {"Completa el reto:", "{C:attention}Receta Familiar{}"}},
            j_kranlaxs_entrenador = {name = "Entrenador", text = {"Da {X:mult,C:white} X#1# {} de multi si estás", "por debajo del Ante {C:attention}#3#{}", "De lo contrario, da {X:mult,C:white} X#2# {} de multi", "{C:inactive}(Actualmente {X:mult,C:white} X#4# {C:inactive} de multi){}"}, unlock = {"Completa el reto:", "{C:attention}Crisis Económica{}"}},
            j_kranlaxs_medium = {name = "Médium", text = {"Da {C:mult}+#1#{} de multi por cada", "partida {C:red}perdida{} en tu perfil", "{C:inactive}(Actualmente {C:mult}+#2#{C:inactive} de multi){}"}, unlock = {"Pierde {C:attention}1{} partida", "{C:inactive}(Progreso: {C:attention}#1#{C:inactive} / 1){}"}},
            j_kranlaxs_monk = {name = "Monje", text = {"Gana {X:chips,C:white} X#1# {} fichas si sales", "de la tienda sin gastar {X:money,C:white} dinero {}", "Se {C:red}reinicia{} si compras algo", "{C:inactive}(Actualmente {X:chips,C:white} X#2# {C:inactive} fichas){}"}, unlock = {"Completa el reto:", "{C:attention}Voto de Pobreza{}"}},
            j_kranlaxs_knight = {name = "Caballero", text = {"Tras puntuar {C:attention}#1#{} cartas de {C:attention}Acero{},", "{C:attention}Deshabilitará{} la siguiente {C:attention}Ciega Jefe{}", "{C:inactive}(Cartas puntuadas: #2#/#1#){}"}, unlock = {"Completa el reto:", "{C:attention}Sindicato de Jefes{}"}},
            j_kranlaxs_overpopulation = {name = "Sobrepoblación", text = {"Da {C:mult}+#1#{} de multi por cada", "{C:attention}figura{} por encima", "del límite de {C:attention}#2#{}", "en tu baraja", "{C:inactive}(Actualmente {C:mult}+#3#{C:inactive} de multi){}"}, unlock = {"Gana una partida en {C:attention}Pozo Verde{}", "usando la {C:attention}Baraja Espacial{}"}},
            j_kranlaxs_antisocial = {name = "Antisocial", text = {"Este comodín gana {C:mult}+#1#{} de multi", "si juegas exactamente {C:attention}1{} carta", "Se {C:red}reinicia{} si juegas más de 1", "{C:inactive}(Actualmente {C:mult}+#2#{C:inactive} de multi){}"}, unlock = {"Completa el reto:", "{C:attention}Fijación Total{}"}},
            j_kranlaxs_famous = {name = "Famoso", text = {"Da {C:chips}+#1#{} fichas si la", "mano jugada es una {C:attention}Quintilla{},", "{C:attention}Cinco de Color{} o {C:attention}Full House de Color{}"}},
            j_kranlaxs_influencer = {name = "Influencer", text = {"Da {C:mult}+#1#{} de multi si la", "mano jugada es una {C:attention}Quintilla{},", "{C:attention}Cinco de Color{} o {C:attention}Full House de Color{}"}},
            j_kranlaxs_potatobag = {name = "Bolsa de Papas", text = {"Acumula las fichas puntuadas", "Al llegar a {C:attention}#1#{}, aplica", "{X:mult,C:white} X#2# {} de multi en la", "siguiente mano y se vacía", "{C:inactive}(Acumulado: #3#/#1#){}"}},
            j_kranlaxs_simonsays = {name = "Simón Dice", text = {"Este comodín gana {X:mult,C:white} X#2# {} de multi", "al completar su petición", "Simón dice... {C:attention}#3#{}", "{C:inactive}(Actualmente {X:mult,C:white} X#1# {C:inactive} de multi){}"}, unlock = {"Completa el reto:", "{C:attention}El Gran Tallo{}"}},
            j_kranlaxs_cheater = {name = "Tramposo", text = {"Los comodines en la tienda", "tienen un {C:green}35%{} de probabilidad", "de ser reemplazados por", "{C:attention}Vales{} o {C:attention}Paquetes de mejora{}"}, unlock = {"Completa el reto:", "{C:attention}Gachapón{}"}},
            j_kranlaxs_philosopher = {name = "Filósofo", text = {"Muestra las siguientes {C:attention}5 cartas{}", "de tu baraja", "{C:inactive}(Cada carta tiene un 20%{}", "{C:inactive}de probabilidad de ocultarse){}", "{C:attention}#1#{}"}, unlock = {"Completa el reto:", "{C:attention}Premoniciones{}"}},
            j_kranlaxs_mandalajoker = {name = "Joker Mandala", text = {"Este Joker gana {X:mult,C:white} X0.5 {} multi", "por cada carta {C:spectral}Espectral{} usada", "{C:inactive}(Actualmente {X:mult,C:white} X#1# {C:inactive} multi){}"}, unlock = {"Usa {C:attention}20{} cartas {C:spectral}Espectrales{}", "{C:inactive}(Progreso: {C:attention}#1#{C:inactive} / 20){}"}},
            j_kranlaxs_regift = {name = "Joker Reregalado", text = {"Al ser {C:gold}vendido{}, crea un", "{C:attention}Joker aleatoriamente{}", "La rareza depende de la {C:attention}Ciega{} actual"}, unlock = {"Vende {C:attention}50{} comodines", "en total", "{C:inactive}(Progreso: {C:attention}#1#{C:inactive} / 50){}"}},
            j_kranlaxs_pyromaniac = {name = "Piromaníaco", text = {"Después de puntuar una mano, {C:red}destruye{}", "todas las cartas de {C:attention}número{} en tu mano", "{C:inactive}(Las cartas de Oro, Cristal y Acero están a salvo){}"}, unlock = {"Destruye {C:attention}100{} cartas", "que no sean figuras", "{C:inactive}(Progreso: {C:attention}#1#{C:inactive} / 100){}"}},
            j_kranlaxs_neverendinggambling = {name = "Ludopatía sin fin", text = {"Pierdes {X:money,C:white} $1 {} por cada acción que realices", "{C:inactive}(Solo si tienes {X:money,C:white} $5 {} o más){}", "Gira 3 números. ¡Si coinciden, ganas un premio!", "Si coinciden 2, recuperas {X:money,C:white} $1 {} como consolación", "{C:inactive}(Tirada actual: #1# - #2# - #3#){}"}, unlock = {"Falla {C:attention}30{} probabilidades de", "comodines o consumibles", "{C:inactive}(Progreso: {C:attention}#1#{C:inactive} / 30){}"}},
            j_kranlaxs_solarsystem = {name = "Sistema Solar", text = {"Al {C:attention}final de la ronda{}, crea una carta", "de {C:planet}Planeta{} en una secuencia fija", "{C:inactive}(Siguiente planeta: {C:planet}#1#{C:inactive}){}"}, unlock = {"Usa las {C:attention}12{} cartas de {C:planet}Planeta{}", "estándar al menos una vez", "en una sola partida", "{C:inactive}(Progreso: {C:attention}#1#{C:inactive} / 12){}"}},
            j_kranlaxs_deranged = {name = "Trastornado", text = {"Da {C:mult}+#1#{} de multi o {C:chips}+#2#{} fichas", "El efecto cambia cada vez", "que juegas una mano"}, unlock = {"Completa el reto:", "{C:attention}Crisis de Identidad{}"}},
            j_kranlaxs_deranged_mult = {name = "Trastornado", text = {"Da {C:mult}+#1#{} de multi", "El efecto cambia cada vez", "que juegas una mano"}},
            j_kranlaxs_deranged_chips = {name = "Trastornado", text = {"Da {C:chips}+#2#{} fichas", "El efecto cambia cada vez", "que juegas una mano"}},
            j_kranlaxs_tmtrainer = {
                name = "TMTRAINER", 
                text = {
                    "{C:dark_edition}#1#{}",
                    "{C:attention}#2#{}",
                    "{C:red}#3#{}",
                    "{C:chips}#4#{}"
                },
                unlock = {
                    "Completa el reto:",
                    "{C:attention}Crisis de Identidad{}"
                }
            },
            j_kranlaxs_bingocard = {name = "Tarjeta de Bingo", text = {"Gana {X:mult,C:white} X0.25 {} de multi", "por cada línea completada", "{C:inactive}(Total: {X:mult,C:white} X#2# {C:inactive} de multi){}", "{C:attention}#3#{}", "{C:attention}#4#{}", "{C:attention}#5#{}", "{C:attention}#6#{}", "{C:attention}#7#{}"}, unlock = {"Completa el reto:", "{C:attention}Anonimato Total{}"}}
        },

        Back = {
            b_kranlaxs_week_challenge = {name = "Reto Semanal", text = {"Empiezas con un Joker de {C:attention}Desafío Semanal{}", "{C:red}Superable{} cada {C:attention}fin de semana{}"}, unlock = {"Abre el juego durante un", "{C:attention}Sábado{} o {C:attention}Domingo{}"}},
            b_kranlaxs_chaos_deck = {name = "Baraja del Caos", text = {"Disfruta el caos"}, unlock = {"Desbloquea {C:legendary,E:1}TODO{} en", "tu colección"}},
            b_kranlaxs_dungeon_deck = {name = "Baraja de Mazmorra", text = {"Tras vencer a una {C:attention}Ciega Jefe{},", "elige entre 3 {C:attention}opciones{}", "con {C:green}pros{} y {C:red}contras{}"}, unlock = {"Gana una partida en {C:attention}Pozo Verde{}", "o superior usando la", "baraja del {C:attention}Reto Semanal{}"}},
            b_kranlaxs_space_deck = {name = "Baraja Espacial", text = {"{C:attention}0{} espacios de comodines, {C:attention}5{} de consumibles", "La tienda solo vende {C:attention}Cuarzos{}", "{C:attention}+1{} a la tienda, ciegas son {C:attention}7.5%{} mas pequeñas", "Apuesta ganadora: {C:attention}10{}"}, unlock = {"Gana una partida en {C:attention}Pozo Verde{}", "con la {C:attention}Baraja Mágica{}, la", "{C:attention}Baraja Nébula{} y la {C:attention}Baraja Zodiacal{}"}},
            b_kranlaxs_bugged_deck = {name = "Baraja Bugueada", text = {"!?"}, unlock = {"Adquiere un {C:attention}TMTRAINER{}", "por primera vez"}}
        },

        Stake = {
            stake_kranlaxs_magenta = {name = "Pozo magenta", text = {"Las cartas en la tienda pueden", "tener el sticker {C:attention}Fijado{}"}},
            stake_kranlaxs_brown = {name = "Pozo marrón", colour = "Marrón", text = {"{C:attention}-1{} espacio de", "{C:attention}Paquete de Mejora{} en la tienda"}},
            stake_kranlaxs_turquoise = {name = "Pozo turquesa", colour = "Turquesa", text = {"Las ciegas tienen un {C:attention}50%{} de", "probabilidad de {C:red}no poder saltarse{}"}},
            stake_kranlaxs_deviled = {name = "Pozo diabólico", colour = "Diabólico", text = {"{C:attention}-1{} espacio de {C:attention}Comodín{}"}},
            stake_kranlaxs_glass = {name = "Pozo de cristal", colour = "Cristal", text = {"La puntuación requerida aumenta", "aún más rápido en cada {C:attention}Ante{}"}},
            stake_kranlaxs_platinum = {name = "Pozo de platino", colour = "Platino", text = {"Debes vencer la {C:attention}Apuesta 10{}", "para ganar la partida"}}
        },

        UNOCards = {
            c_kranlaxs_skip = {name = "Saltar", text = {"Consigue {C:attention}al instante{} el requisito de la Ciega", "No funciona en {C:attention}Jefes Ciega{}"}},
            c_kranlaxs_stacking = {name = "Apilar", text = {"Añade un {C:attention}Sello rosa{} a", "{C:attention}1{} carta seleccionada en tu mano"}},
            c_kranlaxs_draw2 = {name = "Roba 2", text = {"Al usarse, {C:attention}roba 2 cartas adicionales{}", "a tu mano, pierdes {C:blue}1{} mano"}},
            c_kranlaxs_draw4 = {name = "Roba 4", text = {"Al usarse, {C:attention}roba 4 cartas adicionales{}", "a tu mano, pierdes {C:blue}1{} mano"}},
            c_kranlaxs_reverse = {name = "Reversa", text = {"Devuelve {C:attention}todas las cartas{} de tu", "mano a la baraja y las {C:attention}rebarajea{}"}},
            c_kranlaxs_wildcard = {name = "Comodín de Color", text = {"{C:attention}Convierte{} cada carta en", "tu mano a un {C:attention}palo al azar{}", "de forma {C:attention}independiente{}"}},
            c_kranlaxs_replay = {name = "Rejugar", text = {"Devuelve las cartas de la", "última mano jugada a tu mano", "{C:inactive}(Se reinicia tras su uso o", "{C:inactive}al finalizar la ronda)"}},
            c_kranlaxs_discardall = {name = "Descarta todo", text = {"Requiere {C:attention}1{} carta seleccionada.", "Descarta {C:red}todas{} las cartas", "de tu {C:attention}mano{} y {C:attention}mazo{} que", "compartan el mismo palo"}},
            c_kranlaxs_shield = {name = "Escudo", text = {"Pasivamente te protege de la muerte o", "puedes venderla para deshabilitar la {C:attention}Ciega Jefe{}"}},
            c_kranlaxs_misery = {name = "Miseria", text = {"Elige un {C:attention}Palo{}.", "Robarás cartas de tu mazo", "sin parar hasta que", "obtengas una de ese palo"}},
            c_kranlaxs_gift = {name = "Regalo", text = {"Otorga {C:attention}1{} de los siguientes", "premios al azar:", "• Un {C:attention}Comodín{} con Edición", "• Un {C:attention}Consumible{} Negativo", "• Una {C:attention}Carta{} con Mejora, Sello y Edición"}},
            c_kranlaxs_customdraw = {name = "Robo Personalizado", text = {"Roba la misma cantidad de cartas", "que descartes que hayas hecho", "{C:inactive}(Actualmente: {C:attention}#1#{C:inactive} cartas){}"}}
        },

        InverseTarot = {
            c_kranlaxs_thefool = {name = "¿El Loco?", text = {"Crea una carta {C:spectral}Espectral{} aleatoria", "{C:attention}Baja de nivel{} una mano de póker aleatoria"}},
            c_kranlaxs_themagician = {name = "¿El Mago?", text = {"Crea {C:attention}2{} cartas de la {C:attention}Suerte{} aleatorias"}},
            c_kranlaxs_thehighpriestess = {name = "¿La Sacerdotisa?", text = {"Crea un {C:spectral}Agujero Negro{}", "Tu {X:money,C:white} dinero {} {C:attention}disminuye{} un 20%"}},
            c_kranlaxs_theempress = {name = "¿La Emperatriz?", text = {"Añade {C:red}+8{} multi permanente", "hasta a {C:attention}2{} cartas seleccionadas"}},
            c_kranlaxs_theemperor = {name = "¿El Emperador?", text = {"Crea {C:attention}2{} {C:attention}Etiquetas{} aleatorias"}},
            c_kranlaxs_thehierophant = {name = "¿El Hierofante?", text = {"Añade {C:blue}+40{} fichas permanentes", "hasta a {C:attention}2{} cartas seleccionadas"}},
            c_kranlaxs_thelovers = {name = "¿Los Enamorados?", text = {"Gana {C:attention}+1{} de tamaño de mano si", "tienes una {C:attention}Carta Versátil{} en tu baraja"}},
            c_kranlaxs_thechariot = {name = "¿El Carro?", text = {"Crea {C:attention}1{} carta de {C:attention}Acero{} aleatoria", "con un Sello {C:attention}Rojo{}"}},
            c_kranlaxs_justice = {name = "¿La Justicia?", text = {"Añade {X:red,C:white} X2 {} multi permanente", "a {C:attention}1{} carta seleccionada", "Probabilidad de {C:green}#1# en #2#{} de {C:attention}destruir{} esta carta"}},
            c_kranlaxs_thehermit = {name = "¿El Ermitaño?", text = {"{C:attention}Establece{} tu {X:money,C:white} dinero {} a {X:money,C:white} $25 {} si", "tienes {C:attention}menos de{} {X:money,C:white} $25 {}"}},
            c_kranlaxs_thewheeloffortune = {name = "¿La Rueda de la Fortuna?", text = {"Probabilidad de {C:green}#1# en #2#{} de crear una {C:attention}copia{}", "de un Comodín aleatorio con edición {C:dark_edition}Negativa{}"}},
            c_kranlaxs_strenght = {name = "¿La Fuerza?", text = {"{C:attention}Reduce{} la {C:attention}categoría{} de hasta", "{C:attention}2{} cartas seleccionadas en {C:attention}1{}"}},
            c_kranlaxs_thehangedman = {name = "¿El Colgado?", text = {"{C:attention}Aleatoriza{} por completo hasta", "{C:attention}2{} cartas seleccionadas en mano"}},
            c_kranlaxs_death = {name = "¿La Muerte?", text = {"Crea una {C:attention}copia Negativa{} de un Comodín aleatorio", "Un Comodín aleatorio recibe un Sticker {C:attention}Perecedero{}"}},
            c_kranlaxs_temperance = {name = "¿La Templanza?", text = {"Vende {C:attention}TODOS{} los comodines (incluso Eternos)", "por el {C:money}triple{} de su valor de venta", "{C:inactive}(No vende comodines Fijados){}"}},
            c_kranlaxs_thedevil = {name = "¿El Diablo?", text = {"Añade {X:money,C:white} $2 {} permanentes", "hasta a {C:attention}2{} cartas seleccionadas"}},
            c_kranlaxs_thetower = {name = "¿La Torre?", text = {"{C:attention}Elimina{} todas las mejoras, sellos,", "ediciones y bonos de las cartas en mano", "Gana {X:money,C:white} $1 {} por cada modificación eliminada"}},
            c_kranlaxs_thestars = {name = "¿Las Estrellas?", text = {"Añade un {C:attention}Sello Blanco{} hasta a", "{C:attention}2{} cartas seleccionadas"}},
            c_kranlaxs_themoon = {name = "¿La Luna?", text = {"Añade un {C:attention}Sello Gris{} hasta a", "{C:attention}2{} cartas seleccionadas"}},
            c_kranlaxs_thesun = {name = "¿El Sol?", text = {"Añade un {C:attention}Sello Naranja{} hasta a", "{C:attention}2{} cartas seleccionadas"}},
            c_kranlaxs_judgement = {name = "¿El Juicio?", text = {"{C:attention}Canjea{} un {C:attention}Vale{} aleatorio", "{C:red}-1{} tamaño de mano"}},
            c_kranlaxs_theworld = {name = "¿El Mundo?", text = {"Añade un {C:attention}Sello Café{} hasta a", "{C:attention}2{} cartas seleccionadas"}}
        },

        Voucher = {
            v_kranlaxs_more_stock = {name = "Más Inventario", text = {"La tienda tiene {C:attention}1{} espacio", "adicional de {C:attention}Paquete{}"}},
            v_kranlaxs_even_more_stock = {name = "Aún Más Inventario", text = {"La tienda tiene {C:attention}1{} espacio", "adicional de {C:attention}Vale{}"}},
            v_kranlaxs_shiny_appearance = {name = "Aparición Inusual", text = {"Cartas legendarias y consumibles raros", "ahora pueden aparecer en la tienda"}},
            v_kranlaxs_stickerfever = {name = "Fiebre de Pegatinas", text = {"Cada vez que obtienes", "una {C:attention}Tag{}, obtienes", "{C:attention}1{} copia adicional"}},
            v_kranlaxs_stickeralbum = {name = "Álbum de Pegatinas", text = {"Cada vez que obtienes", "una {C:attention}Tag{}, obtienes", "{C:attention}1{} copia adicional más"}},
            v_kranlaxs_hotfix = {name = "Hotfix", text = {"Hacer {C:attention}Renovación{} en la tienda", "también actualiza los {C:attention}Vales{}", "y los {C:attention}Paquetes de Mejora{}"}},
            v_kranlaxs_version2 = {name = "Versión 2.0", text = {"Saltar ciegas te otorga el {X:money,C:white} dinero {}", "de recompensa de esa ciega.", "Requisito de ciegas {C:attention}-15%{}"}},
            v_kranlaxs_common_shinys = {name = "Avistamiento Legendario", text = {"Las cartas legendarias y los consumibles raros", "aparecerán con una mayor frecuencia"}},
            v_kranlaxs_blessing = {name = "Bendición", text = {"Empiezas con el {C:attention}10%{}", "del requisito de fichas", "completado en cada ciega"}},
            v_kranlaxs_protection = {name = "Protección Divina", text = {"Te protege de un {C:attention}Game Over{}.", "Al usarse, este voucher se destruye", "y puede volver a salir en la tienda,", "pero al {X:money,C:white} doble {} de su precio original"}}
        },

        Quartz = {
            c_kranlaxs_blackquartz = {name = "Obsidiana", text = {"Modifica algunas reglas", "bajo tu elección"}, unlock = {"Gana una partida en {C:attention}Pozo marrón{}", "usando la {C:attention}Baraja Mágica{}"}},
            c_kranlaxs_whitequartz = {name = "Perla", text = {"Crea el último", "consumible usado", "{C:inactive}(Última carta: {C:attention}#1#{C:inactive}){}"}, unlock = {"Gana una partida en {C:attention}Pozo marrón{}", "usando la {C:attention}Baraja Fantasma{}"}},
            c_kranlaxs_pinkquartz = {name = "Cuarzo rosa", text = {"Añade {C:dark_edition}Policroma{} a un {C:attention}Joker{}", "o a una {C:attention}carta{} seleccionada"}, unlock = {"Gana una partida en {C:attention}Pozo magenta{}", "o superior usando la {C:attention}Baraja de Mazmorra{}"}},
            c_kranlaxs_bluequartz = {name = "Zafiro", text = {"Añade {C:chips}Laminado{} a un", "{C:attention}Joker{} o {C:attention}carta{} seleccionada"}, unlock = {"Gana una partida en {C:attention}Pozo de platino{}", "usando la {C:attention}Baraja de Plasma{}"}},
            c_kranlaxs_lilacquartz = {name = "Kunzita", text = {"Añade {C:mult}Holográfico{} a un", "{C:attention}Joker{} o {C:attention}carta{} seleccionada"}, unlock = {"Gana una partida en {C:attention}Pozo marrón{}", "usando la {C:attention}Baraja Nébula{}"}},
            c_kranlaxs_grayquartz = {name = "Hematita", text = {"Añade {C:dark_edition}Negativo{} a un", "{C:attention}Joker{} o {C:attention}consumible{} seleccionado"}, unlock = {"Gana una partida en {C:attention}Pozo turquesa{}", "usando la {C:attention}Baraja Pintada{}"}},
            c_kranlaxs_transparentquartz = {name = "Diamante", text = {"{C:attention}Elimina{} todos los stickers o ediciones", "de un {C:attention}Joker{}, o sellos o", "ediciones de una {C:attention}carta{} seleccionada"}, unlock = {"Gana una partida en {C:attention}Pozo de platino{}", "usando la {C:attention}Baraja de Mazmorra{}"}},
            c_kranlaxs_redquartz = {name = "Rubí", text = {"Mientras {C:attention}poseas esto{},", "da {X:mult,C:white} X2 {} multi", "{C:inactive}(Pasivo){}"}, unlock = {"Gana una partida en {C:attention}Pozo magenta{}", "o superior usando la {C:attention}Baraja Roja{}"}},
            c_kranlaxs_celestequartz = {name = "Larimar", text = {"Mientras {C:attention}poseas esto{},", "da {X:chips,C:white} X1.5 {} fichas", "{C:inactive}(Pasivo){}"}, unlock = {"Gana una partida en {C:attention}Pozo turquesa{}", "usando la {C:attention}Baraja de Cuadros{}"}},
            c_kranlaxs_yellowquartz = {name = "Topacio", text = {"Crea al {C:attention}Joker{} indicado.", "El Joker cambia al azar", "después de cada {C:attention}ronda{}", "{C:inactive}(Destino: {C:attention}#1#{C:inactive}){}"}, unlock = {"Gana una partida en {C:attention}Pozo Azul{}", "usando la {C:attention}Baraja de Mazmorra{}"}},
            c_kranlaxs_greenquartz = {name = "Esmeralda", text = {"Mientras {C:attention}poseas esto{}, crea una", "{C:attention}Etiqueta{} tras vencer a una {C:attention}Ciega{}", "Se destruye tras crear {C:attention}#2#{} etiquetas", "{C:inactive}(Actuales: {C:attention}#1#{C:inactive}){}", "{C:inactive}(Pasivo){}"}, unlock = {"Gana una partida en {C:attention}Pozo magenta{}", "o superior usando la {C:attention}Baraja Verde{}"}},
            c_kranlaxs_brownquartz = {name = "Ojo de tigre", text = {"Crea la {C:attention}Carta{} indicada.", "La carta cambia al azar después", "de hacer {C:green}Renovación{} en la tienda", "{C:inactive}(Destino: {C:attention}#1#{C:inactive}){}"}, unlock = {"Gana una partida en {C:attention}Pozo turquesa{}", "usando la {C:attention}Baraja Anaglifo{}"}},
            c_kranlaxs_turquoisequartz = {name = "Turquesa", text = {"Mientras {C:attention}poseas esto{}, {C:attention}deshabilita{}", "todos los comodines excepto el primero", "Reactiva ese comodín {C:attention}2{} veces", "{C:inactive}(Pasivo){}"}, unlock = {"Gana una partida en {C:attention}Pozo turquesa{}", "usando la {C:attention}Baraja Zodiacal{}"}},
            c_kranlaxs_orangequartz = {name = "Citrino", text = {"Añade {C:green}Sello Menta{} a una {C:attention}carta{}", "o {C:green}Sticker Trebolado{} a un", "{C:attention}Joker{} seleccionado"}, unlock = {"Gana una partida en {C:attention}Pozo magenta{}", "o superior usando la {C:attention}Baraja Amarilla{}"}},
            c_kranlaxs_lapislazuli = {name = "Lapislázuli", text = {"Mientras {C:attention}poseas esto{}, añade", "{C:chips}+#1#{} fichas a la primera carta puntuada", "El efecto disminuye en {C:chips}-#2#{} cada uso.", "{C:inactive}(Inactivo al llegar a 0){}", "{C:inactive}(Pasivo){}"}, unlock = {"Gana una partida en {C:attention}Pozo magenta{}", "o superior usando la {C:attention}Baraja Azul{}"}},
            c_kranlaxs_cinnabar = {name = "Cinabrio", text = {"Mientras {C:attention}poseas esto{}, añade", "{C:mult}+#1#{} multi a la primera carta puntuada", "El efecto disminuye en {C:mult}-#2#{} cada uso.", "{C:inactive}(Inactivo al llegar a 0){}", "{C:inactive}(Pasivo){}"}, unlock = {"Gana una partida en {C:attention}Pozo marrón{}", "usando la {C:attention}Baraja Abandonada{}"}},
            c_kranlaxs_graphite = {name = "Grafito", text = {"Mientras {C:attention}poseas esto{}, {C:green}#1# en #2#{}", "probabilidades de crear una copia en tu", "mano de todas las cartas jugadas.", "La prob. baja al activarse.", "{C:inactive}(Inactivo al llegar a 0){}", "{C:inactive}(Pasivo){}"}, unlock = {"Gana una partida en {C:attention}Pozo magenta{}", "o superior usando la {C:attention}Baraja Negra{}"}},
            c_kranlaxs_uranium = {name = "Uranio", text = {"Mientras {C:attention}poseas esto{}, aplica 1 efecto", "aleatorio por ronda. Puede ser", "muy bueno o muy destructivo.", "{C:dark_edition}Estado actual:{}", "{C:red,E:2}#1#{}", "{C:inactive}(¿Te atreves a llevarlo?){}", "{C:inactive}(Pasivo){}"}, unlock = {"Gana una partida en {C:attention}Pozo de platino{}", "usando la {C:attention}Baraja Errática{}"}}
        },

        Tag = {
            tag_kranlaxs_mega_invtarot = {name = "Etiqueta Inversa Mega", text = {"Otorga un {C:attention}Mega Paquete Tarot Inverso{}", "sin coste al instante"}},
            tag_kranlaxs_mega_uno = {name = "Etiqueta UNO Jumbo", text = {"Otorga un {C:attention}Paquete UNO Jumbo{}", "sin coste al instante"}},
            tag_kranlaxs_mega_invtarot_store = {name = "Etiqueta Inversa Mega Guardada", text = {"Otorga un {C:attention}Mega Tarot Inverso Guardado{}", "sin coste al instante"}},
            tag_kranlaxs_quartz_tag = {name = "Etiqueta de Cuarzo", text = {"Crea un {C:attention}Cuarzo{} aleatorio", "{C:inactive}(Debes tener espacio){}"}},
            tag_kranlaxs_sticker_remover = {name = "Etiqueta Limpiadora", text = {"Elimina un sticker {C:attention}Eterno{},", "{C:attention}Perecedero{} o de {C:attention}Renta{} de", "un {C:attention}Comodín{} aleatorio", "{C:inactive}(Da {X:money,C:white} $5 {C:inactive} si no hay stickers){}"}},
            tag_kranlaxs_legendary = {name = "Etiqueta Legendaria", text = {"La tienda tiene un", "{C:legendary}Comodín Legendario{} gratis"}}
        },

        Other = {
            kranlaxs_magenta_sticker = {name = "Sticker magenta", text = {"Usaste este comodín", "para ganar la dificultad", "{C:attention}Pozo magenta{}"}},
            kranlaxs_brown_sticker = {name = "Sticker marrón", text = {"Usaste este comodín", "para ganar la dificultad", "{C:attention}Pozo marrón{}"}},
            kranlaxs_turquoise_sticker = {name = "Sticker turquesa", text = {"Usaste este comodín", "para ganar la dificultad", "{C:attention}Pozo turquesa{}"}},
            kranlaxs_platinum_sticker = {name = "Sticker de platino", text = {"Usaste este comodín", "para ganar la dificultad", "{C:attention}Pozo de platino{}"}},
            kranlaxs_orangeseal_seal = {name = "Sello Naranja", text = {"Si puntúa en la mano: {C:attention}#1#{},", "crea 1 {C:attention}#2#{}", "{C:inactive}Cambia después de usarse.{}", "{C:inactive}(Debe tener espacio){}"}},
            kranlaxs_pinkseal_seal = {name = "Sello Rosa", text = {"Aplica {X:dark_edition,C:white}^1.75{} de multi", "al {C:attention}puntuar{}"}},
            kranlaxs_whiteseal_seal = {name = "Sello Blanco", text = {"{C:attention}Siempre puntúa{}, inmune a", "ser {C:red}debilitada{}, {C:red}destruida{}", "o {C:attention}volteada{}"}},
            kranlaxs_brownseal_seal = {name = "Sello Café", text = {"{C:green}#1# de #2#{} probabilidades de", "{C:attention}duplicar{} esta carta", "mientras esté en la mano"}},
            kranlaxs_grayseal_seal = {name = "Sello Gris", text = {"Al {C:attention}puntuar{}, cambia {C:attention}aleatoriamente{}", "la {C:enhanced}Mejora{} de esta carta"}},
            kranlaxs_mintseal_seal = {name = "Sello Menta", text = {"Duplica las {C:attention}probabilidades{}", "de esta carta"}},
            p_kranlaxs_uno_store_3 = {name = "Paquete UNO", text = {"Elige {C:attention}1{} de hasta", "{C:attention}3{} cartas {C:blue}UNO{}"}},
            p_kranlaxs_uno_store_5 = {name = "Paquete UNO Jumbo", text = {"Elige {C:attention}1{} de hasta", "{C:attention}5{} cartas {C:blue}UNO{}"}},
            p_kranlaxs_invtarot_instant_3_1 = {name = "Paquete Tarot Inverso", text = {"Elige {C:attention}1{} de hasta", "{C:attention}3{} cartas {C:purple}Tarot Inverso{}"}},
            p_kranlaxs_invtarot_instant_5_1 = {name = "Paquete Tarot Inverso Jumbo", text = {"Elige {C:attention}1{} de hasta", "{C:attention}5{} cartas {C:purple}Tarot Inverso{}"}},
            p_kranlaxs_invtarot_instant_5_2 = {name = "Mega Paquete Tarot Inverso", text = {"Elige {C:attention}2{} de hasta", "{C:attention}5{} cartas {C:purple}Tarot Inverso{}"}},
            p_kranlaxs_invtarot_store_3_1 = {name = "Tarot Inverso Guardado", text = {"Elige {C:attention}1{} de hasta", "{C:attention}3{} cartas {C:purple}Tarot Inverso{}"}},
            p_kranlaxs_invtarot_store_5_1 = {name = "Tarot Inverso Guardado Jumbo", text = {"Elige {C:attention}1{} de hasta", "{C:attention}5{} cartas {C:purple}Tarot Inverso{}"}},
            kranlaxs_deviled_sticker = {name = "Sticker diabólico", text = {"Usaste este comodín", "para ganar la dificultad", "{C:attention}Pozo diabólico{}"}},
            kranlaxs_glass_sticker = {name = "Sticker de cristal", text = {"Usaste este comodín", "para ganar la dificultad", "{C:attention}Pozo de cristal{}"}},
            p_kranlaxs_invtarot_store_5_2 = {name = "Mega Tarot Inverso Guardado", text = {"Elige {C:attention}2{} de hasta", "{C:attention}5{} cartas {C:purple}Tarot Inverso{}"}}
        },

        Booster = {
            p_kranlaxs_uno_store_3 = {name = "Paquete UNO", text = {"Elige {C:attention}1{} de hasta", "{C:attention}3{} cartas {C:blue}UNO{}"}},
            p_kranlaxs_uno_store_5 = {name = "Paquete UNO Jumbo", text = {"Elige {C:attention}1{} de hasta", "{C:attention}5{} cartas {C:blue}UNO{}"}},
            p_kranlaxs_invtarot_instant_3_1 = {name = "Paquete Tarot Inverso", text = {"Elige {C:attention}1{} de hasta", "{C:attention}3{} cartas {C:purple}Tarot Inverso{}"}},
            p_kranlaxs_invtarot_instant_5_1 = {name = "Paquete Tarot Inverso Jumbo", text = {"Elige {C:attention}1{} de hasta", "{C:attention}5{} cartas {C:purple}Tarot Inverso{}"}},
            p_kranlaxs_invtarot_instant_5_2 = {name = "Mega Paquete Tarot Inverso", text = {"Elige {C:attention}2{} de hasta", "{C:attention}5{} cartas {C:purple}Tarot Inverso{}"}},
            p_kranlaxs_invtarot_store_3_1 = {name = "Tarot Inverso Guardado", text = {"Elige {C:attention}1{} de hasta", "{C:attention}3{} cartas {C:purple}Tarot Inverso{}"}},
            p_kranlaxs_invtarot_store_5_1 = {name = "Tarot Inverso Guardado Jumbo", text = {"Elige {C:attention}1{} de hasta", "{C:attention}5{} cartas {C:purple}Tarot Inverso{}"}},
            p_kranlaxs_invtarot_store_5_2 = {name = "Mega Tarot Inverso Guardado", text = {"Elige {C:attention}2{} de hasta", "{C:attention}5{} cartas {C:purple}Tarot Inverso{}"}}
        }
    },
    
    misc = {

        labels = {
            kranlaxs_magenta_sticker = "Sticker magenta",
            kranlaxs_brown_sticker = "Sticker marrón",
            kranlaxs_turquoise_sticker = "Sticker turquesa",
            kranlaxs_platinum_sticker = "Sticker de platino",
            kranlaxs_orangeseal_seal = "Sello Naranja", 
            kranlaxs_pinkseal_seal = "Sello Rosa", 
            kranlaxs_whiteseal_seal = "Sello Blanco", 
            kranlaxs_brownseal_seal = "Sello Café", 
            kranlaxs_grayseal_seal = "Sello Gris", 
            kranlaxs_mintseal_seal = "Sello Menta", 
            clover = "Sticker Trebolado",
            p_kranlaxs_uno_store_3 = "Paquete UNO",
            p_kranlaxs_uno_store_5 = "Paquete UNO Jumbo",
            p_kranlaxs_invtarot_instant_3_1 = "Paquete Tarot Inverso",
            p_kranlaxs_invtarot_instant_5_1 = "Paquete Tarot Inverso Jumbo",
            p_kranlaxs_invtarot_instant_5_2 = "Mega Paquete Tarot Inverso",
            p_kranlaxs_invtarot_store_3_1 = "Tarot Inverso Guardado",
            p_kranlaxs_invtarot_store_5_1 = "Tarot Inverso Guardado Jumbo",
            p_kranlaxs_invtarot_store_5_2 = "Mega Tarot Inverso Guardado",
            kranlaxs_deviled_sticker = "Sticker diabólico",
            kranlaxs_glass_sticker = "Sticker de cristal",
            kranlaxs_wave = "Acuática"
        },



        v_text = {
            ch_c_kran_fijado_1 = {"Todos los comodines tienen el sticker {C:attention}Fijado{}"},
            ch_c_kran_abuela_1 = {"Los comodines de {C:attention}puntuación{} están {C:red}baneados{}"},
            ch_c_kran_crisis_1 = {"La tienda es un {C:attention}20% más cara{}"},
            ch_c_kran_crisis_2 = {"El premio base de las ciegas se {C:red}reduce{} en {X:money,C:white} $2 {}"},
            ch_c_kran_crisis_3 = {"El mazo está compuesto únicamente de {C:attention}52 Ases{}"},
            ch_c_kran_doppel_1 = {"Todos los comodines están {C:red}baneados{} de la tienda"},
            ch_c_kran_anonimo_1 = {"Cartas en la mano y comodines están {C:attention}boca abajo{}"},
            ch_c_kran_jefes_1 = {"Las Ciegas Pequeñas y Grandes son {C:attention}Ciegas Jefe{}"},
            ch_c_kran_premon_1 = {"Todas las cartas en tu mano están {C:attention}boca abajo{}"},
            ch_c_kran_tallo_1 = {"Los demás {C:attention}comodines{} y {C:attention}Paquetes{} están {C:red}baneados{}"},
            ch_c_gacha_rule_1 = {"Ninguna {C:attention}carta individual{} aparece en la tienda"},
            ch_c_kran_pobreza_1 = {"{C:attention}50%{} de probabilidad de que un {C:common}Común{} sea {C:legendary}Legendario{}"},
            ch_c_kran_pobreza_2 = {"Si tu comodín {C:attention}Monje{} se decepciona, {C:red}pierdes la partida{}"}
        }
    }
}