return {
    descriptions = {
        Joker = {
            j_kranlaxs_tagger = {name = "Étiqueteur", text = {"Gagne {C:red}+#1#{} Mult pour chaque", "{C:attention}Tag{} obtenu", "{C:inactive}(Actuellement {C:red}+#2#{C:inactive} Mult){}"}, unlock = {"Achetez {C:attention}2{} Bons", "Vides en une seule partie"}},
            j_kranlaxs_Cashback = {name = "Remboursement", text = {"{C:green}#1# chance(s) sur #2#{} d'obtenir {X:money,C:white} $3 {},", "lors de l'achat d'une carte"}, unlock = {"Gagnez une partie en {C:attention}Mise Rouge{}", "en utilisant le {C:attention}Jeu Spatial{}"}},
            j_kranlaxs_underratedjoker = {name = "Joker Sous-estimé", text = {"Ce Joker gagne {X:chips,C:white} X0.2 {} Jetons", "si la main jouée {C:attention}n'est pas{}", "votre main de poker la plus jouée", "{C:inactive}(Se réinitialise si c'est le cas){}", "{C:inactive}(Actuellement {X:chips,C:white} X#1# {C:inactive} Jetons){}"}, unlock = {"Gagnez une partie en {C:attention}Mise Bleue{}", "en utilisant le {C:attention}Jeu Spatial{}"}},
            j_kranlaxs_facelessaccountant = {name = "Comptable Sans Visage", text = {"Ce Joker gagne {X:blue,C:white} X0.1 {} Jetons pour", "chaque {C:attention}#2#{} ayant marqué", "{C:inactive}(Actuellement {X:blue,C:white} X#1# {C:inactive} Jetons){}"}, unlock = {"Gagnez une partie sans jouer de têtes,", "tout en en ayant au moins {C:attention}1{} dans votre jeu"}},
            j_kranlaxs_thefixer = {name = "Le Corrupteur", text = {"Vendre un {C:attention}Joker{} pendant une", "{C:purple}Blinde{} réduit le score requis", "{C:inactive}(Commun : -10%, Inhabituel : -30%){}", "{C:inactive}(Rare : -60%, Légendaire : -95%){}"}, unlock = {"Vendez au moins {C:attention}2{} Jokers", "de chaque rareté"}},
            j_kranlaxs_mysteriousgeode = {name = "Géode Mystérieuse", text = {"Chaque {C:attention}Carte Joker{} (Wild) ayant marqué donne", "un effet {C:attention}aléatoire{}"}, unlock = {"Jouez une main", "avec {C:attention}5{} Cartes Joker (Wild)"}},
            j_kranlaxs_benchwarmer = {name = "Remplaçant", text = {"Donne {C:attention}4 fois{} la valeur en {C:blue}Jetons{}", "de la carte avec le rang le plus élevé en main"}},
            j_kranlaxs_entropy2 = {name = "Vortex", text = {"Gagne {X:dark_edition,C:white} ^1 {} Mult et {X:dark_edition,C:white} ^1 {} Jetons", "pour chaque carte {C:attention}en dessous de 52{} dans votre jeu", "{C:inactive}(Actuellement {X:dark_edition,C:white} ^#1# {C:inactive} Mult et {X:dark_edition,C:white} ^#1# {C:inactive} Jetons){}"}},
            j_kranlaxs_greedyleprachaun = {name = "Farfadet Avide", text = {"Piochez {C:attention}3 cartes supplémentaires{}", "lors de la première {C:red}défausse{} de la manche"}, unlock = {"Défaussez exactement {C:attention}1{} carte", "{C:attention}3{} fois de suite"}},
            j_kranlaxs_charismaticbard = {name = "Barde Charismatique", text = {"{C:attention}-1{} taille de main", "Réduit l'exigence de la {C:purple}Blinde{} de {C:attention}2%{} chaque fois", "que vous jouez votre {C:attention}main la plus jouée{}", "{C:inactive}(Maximum 90%){}", "Se réinitialise si vous jouez une autre main", "{C:inactive}(Actuellement {C:attention}-#1#%{C:inactive} taille de Blinde){}"}},
            j_kranlaxs_russianroulette = {name = "Roulette Russe", text = {"{C:green}#1# chance(s) sur #2#{} de {C:red}Perdre la partie{}", "en sélectionnant une blinde", "Si vous survivez, gagne", "{X:mult,C:white} X3 {} Mult et {X:chips,C:white} X3 {} Jetons", "{C:inactive}(Actuellement {X:mult,C:white} X#3# {C:inactive} Mult et {X:chips,C:white} X#3# {C:inactive} Jetons){}"}, unlock = {"Gagnez une partie en {C:attention}Mise Noire{}", "en utilisant le {C:attention}Jeu Spatial{}"}},
            j_kranlaxs_fidelitycard = {name = "Passe de Combat", text = {"Après avoir acheté {C:attention}6{} cartes, la {C:attention}septième{}", "carte achetée donne de l'{X:money,C:white} argent {} égal à la", "{C:attention}valeur de vente{} de tous vos Jokers", "{C:inactive}(Actuellement {C:attention}#1#/6{C:inactive} cartes){}", "{C:inactive}(Valeur de vente totale : {X:money,C:white} $#2# {C:inactive}){}"}},
            j_kranlaxs_devioussheep = {name = "Mouton Glouton", text = {"{C:red}Dévore{} un Joker aléatoire lors de la", "sélection d'une {C:attention}Blinde{} et gagne {X:mult,C:white} X0.4 {} Mult", "{C:hearts}Game Over{} s'il n'y a pas d'autres Jokers", "{C:inactive}(Priorisez certaines cibles pour plus de Mult !){}", "{C:inactive}(Actuellement {X:mult,C:white} X#1# {C:inactive} Mult){}"}},
            j_kranlaxs_lifeassurance = {name = "Assurance Vie", text = {"Évite un Game Over si", "vous avez au moins {X:money,C:white} $#1# {}", "{C:inactive}(Le prix double après chaque utilisation){}"}, unlock = {"Perdez une partie avec", "{X:money,C:white} $100 {} ou plus", "avant l'{C:attention}Ante 8{}"}},
            j_kranlaxs_sundaycheckpoint = {name = "Point de Contrôle", text = {"{C:red}Game Over{} si vous sélectionnez", "une blinde un {C:attention}jour de semaine{}", "Sinon, crée un Joker {C:attention}Défi Hebdomadaire{}", "à la fin de la manche et s'{C:red}autodétruit{}", "{C:inactive}(Jour actuel : #1#){}"}},
            j_kranlaxs_weeklychallenge = {name = "Défi Hebdomadaire", text = {"Définit un défi aléatoire pour cette partie", "{C:clubs}Défi actuel :{} {C:attention}#1#{}", "{C:inactive}1 :{} Vous avez {X:money,C:white} -$100 {}, payez-les avant l'Ante 8", "{C:inactive}2 :{} Boutique restreinte", "{C:inactive}3 :{} 1 Main, 20 Défausses (Pas de Bons supplémentaires)", "{C:inactive}4 :{} Limite de {C:blue}#2#{} mains et {C:red}#3#{} défausses dans la partie", "{C:inactive}5 :{} Vitesse de jeu bloquée à 0.5x", "{C:inactive}6 :{} 3 Triboulets Éternels (Max 3 Jokers, Ante Rapide)", "{C:inactive}7 :{} 1 chance sur 6 de GAGNER (Défaite à l'Ante 8)"}},
            j_kranlaxs_panda = {name = "Panda Pelucheux", text = {"Donne {C:chips}+#1#{} Jetons", "{C:attention}-1{} emplacement de Joker"}},
            j_kranlaxs_miner = {name = "Mineur", text = {"Gagne {C:red}+5{} Mult pour chaque", "{C:attention}Carte de Pierre{} ayant marqué", "{C:green}#2# chance(s) sur #3#{} de gagner", "de {X:money,C:white} $#4# {} à {X:money,C:white} $#5# {} en jouant une main", "{C:inactive}(Actuellement {C:red}+#1#{C:inactive} Mult){}"}, unlock = {"Jouez une main", "avec {C:attention}5{} Cartes de Pierre"}},
            j_kranlaxs_birthdaycake = {name = "Gâteau d'Anniversaire", text = {"Donne {X:dark_edition,C:white} ^#1# {} Mult", "Perd {X:dark_edition,C:white} ^0.25 {} après", "chaque main jouée", "Lorsqu'il est épuisé, crée un {C:attention}Joker Recyclé{}"}, unlock = {"Gagnez une partie en", "{C:attention}Mise Bleue{} en utilisant", "le jeu {C:attention}Défi Hebdomadaire{}"}},
            j_kranlaxs_vipsuscription = {name = "Abonnement V.I.P.", text = {"Donne {C:attention}+#2#{} emplacements de boutique,", "{C:attention}+1{} Bon et Paquet supplémentaire", "Soustrait {X:money,C:white} $#1# {} à l'ouverture de la boutique.", "Le prix et la taille de la boutique", "{C:attention}augmentent{} en battant une {C:attention}Blinde de Boss{}"}, unlock = {"Gagnez une partie en", "{C:attention}Mise Orange{} en utilisant", "le jeu {C:attention}Défi Hebdomadaire{}"}},
            j_kranlaxs_painterjoker = {name = "Joker Peintre", text = {"Lorsqu'une main marque, crée un", "{C:attention}Tag Jongleur{} pour chaque", "{C:attention}Carte Joker{} (Wild) dans votre main", "{C:inactive}(Coûte {X:money,C:white} $#1# {C:inactive} par tag){}"}, unlock = {"Gagnez une partie en", "{C:attention}Mise Orange{} en utilisant", "le jeu {C:attention}Défi Hebdomadaire{}"}},
            j_kranlaxs_coronation = {name = "Couronnement", text = {"Si la main jouée contient des cartes marquantes", "de rang {C:attention}10 ou inférieur{}, transforme", "la plus basse en un {C:attention}Roi{}.", "S'il n'y a pas de cartes basses en main,", "ajoute un {C:red}Sceau Rouge{} au premier {C:attention}Roi{} marquant."}, unlock = {"Jouez une main d'exactement", "{C:attention}5 Rois{}. Tous doivent avoir", "un {C:red}Sceau Rouge{} et être des cartes en {C:attention}Acier{}"}},
            j_kranlaxs_speedrunner = {name = "Speedrunner", text = {"{X:mult,C:white} X#1# {} Mult.", "Vous avez {C:attention}#2# secondes{} pour", "jouer une main ou défausser.", "Si le temps s'écoule, {C:red}GAME OVER{}."}, unlock = {"Gagnez une partie en", "{C:attention}Mise Verte{} en utilisant", "le jeu {C:attention}Défi Hebdomadaire{}"}},
            j_kranlaxs_passcode = {name = "Code Secret", text = {"Si la main jouée correspond à l'un", "des codes suivants, la main", "compte comme une {C:attention}Couleur Multiple{} (Flush Five)", "{C:inactive}1. {C:attention}#1#{}", "{C:inactive}2. {C:attention}#2#{}", "{C:inactive}3. {C:attention}#3#{}"}, unlock = {"Gagnez une partie en", "{C:attention}Mise Noire{} en utilisant", "le jeu {C:attention}Défi Hebdomadaire{}"}},
            j_kranlaxs_chronometer = {name = "Chronomètre", text = {"Lorsqu'une main est jouée : ", "Donne des {C:chips}Jetons{} égaux aux {C:attention}Secondes{} actuelles", "Donne du {C:mult}Mult{} égal aux {C:attention}Minutes{} actuelles", "Gagne de l'{C:money}argent{} égal aux {C:attention}Heures{} actuelles", "{C:inactive}(Actuellement : {C:chips}+#1#{C:inactive} Jetons, {C:mult}+#2#{C:inactive} Mult, {C:money}+$#3#{C:inactive}){}"}, unlock = {"Gagnez une partie en {C:attention}Mise Or{}", "en utilisant le {C:attention}Jeu Spatial{}"}},
            j_kranlaxs_zombiejoker = {name = "Joka Zombi", text = {"{C:attention}détruii{} la {C:attention}prmière{} carte", "ki dnne pas 2 pionts e gané {C:red}+15{} mult", "mé tu pèer {C:red}-10{} mult", "xpke main joué ds la mnche", "si y dssend à {C:red}0{} mult", "{C:attention}y mèurt {}", "{C:inactive}(t'as {C:red}+#1#{C:inactive} mult ou un truk cm sa){}"}, unlock = {"Gagnez une partie en {C:attention}Mise Violette{}", "en utilisant le {C:attention}Jeu Spatial{}"}},
            j_kranlaxs_thecousin = {name = "Le Cousin", text = {"Gagne {C:chips}+13{} Jetons pour chaque", "{C:attention}nombre premier{} ayant marqué", "{C:inactive}(Actuellement {C:chips}+#1#{C:inactive} Jetons){}"}, unlock = {"Gagnez une partie en {C:attention}Mise Turquoise{}", "en utilisant le {C:attention}Jeu Spatial{}"}},
            j_kranlaxs_colasoda = {name = "Soda Cola", text = {"Donne {X:dark_edition,C:white} ^#1# {} Mult", "Perd {X:dark_edition,C:white} ^#2# {} pour", "presque {C:attention}toute action{} que vous entreprenez"}, unlock = {"Gagnez une partie en", "{C:attention}Mise Bleue{} en utilisant", "le jeu {C:attention}Défi Hebdomadaire{}"}},
            j_kranlaxs_icecreamsandwich = {name = "Sandwich à la Crème Glacée", text = {"Gagnez {X:money,C:white} $#1# {} à la fin", "de la manche", "La récompense diminue de {X:money,C:white} $#2# {}", "après chaque manche"}, unlock = {"Gagnez {X:money,C:white} $50 {} ou plus", "comme paiement dans", "une seule manche"}},
            j_kranlaxs_dispensermachine = {name = "Distributeur Automatique", text = {"Si ce Joker est {C:attention}sélectionné{}", "en quittant la boutique, dépensez {X:money,C:white} $#1# {}", "et créez un {C:attention}Joker Nourriture{}"}, unlock = {"Avoir {C:attention}4{} Jokers de", "nourriture en même temps"}},
            j_kranlaxs_bottledwater = {name = "Eau en Bouteille", text = {"{X:chips,C:white} X#1# {} Jetons", "Perd {X:chips,C:white} X#2# {} pour", "chaque carte ayant marqué"}, unlock = {"Gagnez une partie en", "{C:attention}Mise Bleue{} en utilisant", "le jeu {C:attention}Défi Hebdomadaire{}"}},
            j_kranlaxs_burrow = {name = "Terrier", text = {"Gagne {C:attention}+1{} Lapin pour", "chaque {C:attention}Blinde battue{}", "Lorsqu'il est {C:gold}vendu{}, crée {C:attention}#1#{} Lapins"}},
            j_kranlaxs_bunny = {name = "Lapin", text = {"Gagne {X:mult,C:white} X#1# {} Mult pour chaque", "Joker {C:attention}Lapin{} que vous possédez", "{C:inactive}(Actuellement {X:mult,C:white} X#2# {C:inactive} Mult){}"}},
            j_kranlaxs_sushi = {name = "Sushi", text = {"Réduit l'exigence de la", "Blinde de {C:attention}#1#%{}", "La réduction diminue de {C:attention}#2#%{}", "après avoir battu une {C:attention}Blinde{}"}, unlock = {"Gagnez une partie en", "{C:attention}Mise Violette{} en utilisant", "le jeu {C:attention}Défi Hebdomadaire{}"}},
            j_kranlaxs_gigachad = {name = "Gigachad", text = {"Gagne {C:chips}+#2#{} Jetons pour presque", "{C:attention}toute action{} que vous entreprenez", "{C:inactive}(Actuellement {C:chips}+#1#{C:inactive} Jetons){}"}, unlock = {"Gagnez une partie en", "{C:attention}Mise Blanche{} en utilisant", "le jeu {C:attention}Défi Hebdomadaire{}"}},
            j_kranlaxs_nft = {name = "Arnaque Crypto", text = {"Réduit le {C:attention}rang{} de toutes", "les cartes dans votre main de {C:attention}1{}", "lorsqu'une main marque", "{C:inactive}(Ne peut pas être réduit en dessous de 2){}"}},
            j_kranlaxs_beanstalk = {name = "Haricot Magique", text = {"Haricots inutiles"}, unlock = {"Gagnez une partie en", "{C:attention}Mise Blanche{} en utilisant", "le jeu {C:attention}Défi Hebdomadaire{}"}},
            j_kranlaxs_suspiciousbeanstalk = {name = "Haricot Magique Suspect", text = {"Haricots inutiles ?..."}},
            j_kranlaxs_epicbeanstalk = {name = "Haricot Magique Épique", text = {"Peut-être qu'ils ne sont pas inutiles..."}},
            j_kranlaxs_zenithbeanstalk = {name = "Haricot Magique Zénith", text = {"Haricots"}},
            j_kranlaxs_commonseed = {name = "Graine Commune", text = {"{C:attention}Crée{} un Joker", "{C:common}Commun{} aléatoire"}},
            j_kranlaxs_weirdlookingseed = {name = "Graine Étrange", text = {"{C:attention}Crée{} un Joker", "{C:uncommon}Inhabituel{} aléatoire"}},
            j_kranlaxs_magnificentseed = {name = "Graine Magnifique", text = {"{C:attention}Crée{} un Joker", "{C:rare}Rare{} aléatoire"}},
            j_kranlaxs_godseed = {name = "Graine Divine", text = {"{C:attention}Crée{} un Joker", "{C:legendary}Légendaire{} aléatoire"}},
            j_kranlaxs_anonymousjoker = {name = "Joker Anonyme", text = {"En marquant, se retourne et donne entre", "{X:mult,C:white} X1.5 {} et {X:mult,C:white} X4.0 {} Mult"}, unlock = {"Battez la blinde de boss", "{C:attention}Gland d'Ambre{} 1 fois"}},
            j_kranlaxs_littlebro = {name = "Petit Frère", text = {"Si la main jouée est {C:attention}Carte Haute{} et que", "la carte marquante est un {C:attention}#2#{},", "ce Joker gagne {X:red,C:white} X#3# {} Mult", "Le rang change à chaque manche", "{C:inactive}(Actuellement {X:red,C:white} X#1# {C:inactive} Mult){}"}, unlock = {"Jouez {C:attention}Carte Haute{}", "{C:attention}30{} fois en", "une seule partie"}},
            j_kranlaxs_medusa = {name = "Méduse", text = {"{C:attention}Toutes les cartes jouées{}", "deviennent de manière permanente des {C:attention}Cartes de Pierre{}", "après avoir joué une main", "{C:inactive}(Même celles qui ne marquent pas){}"}, unlock = {"Gagnez une partie en {C:attention}Mise Marron{}", "en utilisant le {C:attention}Jeu Spatial{}"}},
            j_kranlaxs_depression = {name = "Récession Économique", text = {"Donne {X:dark_edition,C:white}^#2#{} Mult", "Augmente de {X:dark_edition,C:white}^#1#{} pour chaque {X:money,C:white} $1 {}", "en dessous de {X:money,C:white} $0 {}"}, unlock = {"Entrez dans une boutique", "avec {X:money,C:white} -$25 {} ou moins"}},
            j_kranlaxs_grannyjoker = {name = "Mamie", text = {"Donne {X:dark_edition,C:white} ^3 {} Jetons et {X:dark_edition,C:white} ^3 {} Mult", "La vitesse du jeu est bloquée à {C:attention}0.25x{}", "{C:inactive}(Détruit si vous jouez une {C:attention}Suite{}", "{C:inactive}ou une {C:attention}Quinte Flush{C:inactive}){}"}, unlock = {"Battez {C:attention}12{} blindes avec la", "vitesse du jeu à {C:attention}0.5{}"}},
            j_kranlaxs_lateshippment = {name = "Livraison en Retard", text = {"Redéclenche {C:attention}toutes les cartes jouées{}", "{C:attention}1 fois{} pour chaque main jouée", "dans la {C:attention}manche précédente{}", "{C:inactive}(Actuellement {C:attention}#1#{C:inactive} redéclenchements){}"}, unlock = {"Gagnez une partie en {C:attention}Mise Orange{}", "en utilisant le {C:attention}Jeu Spatial{}"}},
            j_kranlaxs_unkownfactor = {name = "Variable X", text = {"Toutes les cartes jouées sont", "considérées comme {C:attention}#1#{}", "{C:inactive}(Le rang change à la fin de la manche){}"}, unlock = {"Gagnez une partie en", "{C:attention}Mise Or{} en utilisant", "le jeu {C:attention}Défi Hebdomadaire{}"}},
            j_kranlaxs_thethreers = {name = "Les 3 R", text = {"Crée une {C:attention}copie{} de chaque carte jouée", "et l'ajoute à votre {C:attention}jeu{}", "{C:attention}Détruit{} toutes les cartes ayant marqué"}, unlock = {"Gagnez une partie en", "{C:attention}Mise Or{} en utilisant", "le jeu {C:attention}Défi Hebdomadaire{}"}},
            j_kranlaxs_the = {name = "Jok", text = {"Donne {X:chips,C:white} X2 {} Jetons et {X:mult,C:white} X2 {} Mult", "uniquement sur la {C:attention}première main{} de la manche"}, unlock = {"Battez {C:attention}5{} blindes en n'utilisant", "que {C:attention}1{} main pour chacune"}},
            j_kranlaxs_chainreaction = {name = "Réaction en Chaîne", text = {"Si la main jouée est {C:attention}#2#{},", "gagne {X:chips,C:white} X0.5 {} Jetons et la main change", "Se réinitialise si la main {C:attention}ne correspond pas{}", "{C:inactive}(Actuellement {X:chips,C:white} X#1# {C:inactive} Jetons){}"}, unlock = {"Jouez toutes les mains de poker", "au moins {C:attention}1{} fois dans une partie"}},
            j_kranlaxs_anubis = {name = "Anubis", text = {"Équilibre les {C:blue}Jetons{} et le {C:red}Mult{}", "lorsqu'une main marque"}, unlock = {"Gagnez une partie avec le {C:attention}Jeu Plasma{}", "dans chaque difficulté de mise"}},
            j_kranlaxs_erraticjoker = {name = "Joker Erratique", text = {"Si la carte marquante est une", "{C:attention}Carte Joker{} (Wild), échange les", "{C:blue}Jetons{} et le {C:red}Mult{}"}, unlock = {"Gagnez une partie en {C:attention}Mise Blanche{}", "en utilisant le {C:attention}Jeu Spatial{}"}},
            j_kranlaxs_luckyseven = {name = "Les 7 Chanceux", text = {"Si la main jouée est exactement", "un {C:attention}Brelan{} de {C:attention}7s{} uniquement, ce Joker", "gagne {C:blue}+7{} Jetons, {C:red}+7{} Mult et donne {X:money,C:white} $7 {}", "{C:inactive}(Actuellement {C:blue}+#1#{} Jetons, {C:red}+#2#{} Mult)"}, unlock = {"Avoir au moins {C:attention}10{} cartes", "de rang {C:attention}7{} dans votre jeu"}},
            j_kranlaxs_certificateddocument = {name = "Document Certifié", text = {"Redéclenche {C:attention}tous{} les sceaux"}, unlock = {"Gagnez une partie en", "{C:attention}Mise Violette{} en utilisant", "le jeu {C:attention}Défi Hebdomadaire{}"}},
            j_kranlaxs_platanito = {name = "Petite Banane", text = {"Chaque fois qu'un autre Joker s'active,", "donne {X:mult,C:white} X#3# {} Mult supplémentaire", "{C:green}#1# chance(s) sur #2#{} d'être", "détruit à la fin de la manche"}, unlock = {"Gagnez une partie en {C:attention}Mise Platine{}", "en utilisant le {C:attention}Jeu Spatial{}"}},
            j_kranlaxs_cubicaljoker = {name = "Joker Cubique", text = {"Donne {C:mult}+#1#{} Mult", "La valeur est élevée au", "{C:attention}Cube (^3){} pour chaque", "{C:attention}Blinde de Boss{} battue"}},
            j_kranlaxs_grapesoda = {name = "Soda au Raisin", text = {"Lorsqu'il est {C:gold}vendu{}, crée une carte", "{C:spectral}Spectrale{} aléatoire", "avec l'édition {C:dark_edition}Négative{}"}, unlock = {"Gagnez une partie en {C:attention}Mise Magenta{}", "en utilisant le {C:attention}Jeu Spatial{}"}},
            j_kranlaxs_telescope = {name = "Télescope", text = {"Si {C:attention}#1#{} monte de niveau, augmentez", "le niveau de cette main {C:attention}1{} fois supplémentaire", "{C:inactive}(La main change à la fin de la manche){}"}, unlock = {"Gagnez une partie en", "{C:attention}Mise Rouge{} en utilisant", "le jeu {C:attention}Défi Hebdomadaire{}"}},
            j_kranlaxs_pandorabox = {name = "Boîte de Pandore", text = {"En battant une {C:attention}Blinde de Boss{},", "crée un Joker {C:attention}utile{} basé", "sur votre jeu actuel", "{C:inactive}(Doit avoir de la place){}"}},
            j_kranlaxs_doppelganger = {name = "Doppelgänger", text = {"Copie la capacité d'un {C:attention}Joker{}", "aléatoire de tout le jeu.", "Le Joker copié change après", "avoir battu une {C:attention}Blinde{}.", "{C:inactive}(Actuellement : {C:attention}#1#{C:inactive})"}, unlock = {"Gagnez une partie en", "{C:attention}Mise Or{} en utilisant", "le jeu {C:attention}Défi Hebdomadaire{}"}},
            j_kranlaxs_thechampion = {name = "Le Champion", text = {"Exigence de la blinde {C:attention}X#1#{}", "Gagnez {X:money,C:white} $#2# {} à la fin de la manche"}, unlock = {"Atteignez l'{C:attention}Ante 16{}"}},
            j_kranlaxs_clerigo = {name = "Clerc", text = {"Donne {C:mult}+#1#{} Mult pour chaque", "carte dans votre jeu complet", "Perd {C:mult}-#2#{} Mult pour chaque carte", "avec une amélioration ou un sceau", "{C:inactive}(Actuellement {C:mult}+#3#{C:inactive} Mult){}"}, unlock = {"Terminez le défi :", "{C:attention}Recette Familiale{}"}},
            j_kranlaxs_entrenador = {name = "Entraîneur", text = {"Donne {X:mult,C:white} X#1# {} Mult si vous êtes", "en dessous de l'Ante {C:attention}#3#{}", "Sinon, donne {X:mult,C:white} X#2# {} Mult", "{C:inactive}(Actuellement {X:mult,C:white} X#4# {C:inactive} Mult){}"}, unlock = {"Terminez le défi :", "{C:attention}Crise Économique{}"}},
            j_kranlaxs_medium = {name = "Médium", text = {"Donne {C:mult}+#1#{} Mult pour chaque", "partie {C:red}perdue{} dans votre profil", "{C:inactive}(Actuellement {C:mult}+#2#{C:inactive} Mult){}"}, unlock = {"Perdez {C:attention}1{} partie", "{C:inactive}(Progression : {C:attention}#1#{C:inactive} / 1){}"}},
            j_kranlaxs_monk = {name = "Moine", text = {"Gagne {X:chips,C:white} X#1# {} Jetons si vous quittez", "la boutique sans dépenser d'{X:money,C:white} argent {}", "{C:red}Se réinitialise{} si vous achetez quelque chose", "{C:inactive}(Actuellement {X:chips,C:white} X#2# {C:inactive} Jetons){}"}, unlock = {"Terminez le défi :", "{C:attention}Vœu de Pauvreté{}"}},
            j_kranlaxs_knight = {name = "Chevalier", text = {"Après avoir marqué avec {C:attention}#1#{} cartes en {C:attention}Acier{},", "{C:attention}Désactive{} la prochaine {C:attention}Blinde de Boss{}", "{C:inactive}(Cartes marquées : #2#/#1#){}"}, unlock = {"Terminez le défi :", "{C:attention}Syndicat des Boss{}"}},
            j_kranlaxs_overpopulation = {name = "Surpopulation", text = {"Donne {C:mult}+#1#{} Mult pour chaque", "{C:attention}figure{} au-dessus", "de la limite de {C:attention}#2#{}", "dans votre jeu", "{C:inactive}(Actuellement {C:mult}+#3#{C:inactive} Mult){}"}, unlock = {"Gagnez une partie en {C:attention}Mise Verte{}", "en utilisant le {C:attention}Jeu Spatial{}"}},
            j_kranlaxs_antisocial = {name = "Antisocial", text = {"Ce Joker gagne {C:mult}+#1#{} Mult", "si vous jouez exactement {C:attention}1{} carte", "{C:red}Se réinitialise{} si vous en jouez plus de 1", "{C:inactive}(Actuellement {C:mult}+#2#{C:inactive} Mult){}"}, unlock = {"Terminez le défi :", "{C:attention}Fixation Totale{}"}},
            j_kranlaxs_famous = {name = "Célèbre", text = {"Donne {C:chips}+#1#{} Jetons si la", "main jouée est un {C:attention}Cinq d'une Sorte{},", "{C:attention}Couleur Multiple{} ou {C:attention}Full Couleur{}"}},
            j_kranlaxs_influencer = {name = "Influenceur", text = {"Donne {C:mult}+#1#{} Mult si la", "main jouée est un {C:attention}Cinq d'une Sorte{},", "{C:attention}Couleur Multiple{} ou {C:attention}Full Couleur{}"}},
            j_kranlaxs_potatobag = {name = "Sac de Pommes de Terre", text = {"Accumule les Jetons marqués", "En atteignant {C:attention}#1#{}, applique", "{X:mult,C:white} X#2# {} Mult à la", "prochaine main et se vide", "{C:inactive}(Accumulé : #3#/#1#){}"}},
            j_kranlaxs_simonsays = {name = "Jacques a Dit", text = {"Ce Joker gagne {X:mult,C:white} X#2# {} Mult", "en accomplissant sa demande", "Jacques a dit... {C:attention}#3#{}", "{C:inactive}(Actuellement {X:mult,C:white} X#1# {C:inactive} Mult){}"}, unlock = {"Terminez le défi :", "{C:attention}Le Grand Haricot Magique{}"}},
            j_kranlaxs_cheater = {name = "Tricheur", text = {"Les Jokers dans la boutique", "ont {C:green}35%{} de chances", "d'être remplacés par", "des {C:attention}Bons{} ou des {C:attention}Paquets Booster{}"}, unlock = {"Terminez le défi :", "{C:attention}Gachapon{}"}},
            j_kranlaxs_philosopher = {name = "Philosophe", text = {"Révèle les {C:attention}5 prochaines cartes{}", "de votre jeu", "{C:inactive}(Chaque carte a 20%{}", "{C:inactive}de chances d'être cachée){}", "{C:attention}#1#{}"}, unlock = {"Terminez le défi :", "{C:attention}Prémonitions{}"}},
            j_kranlaxs_mandalajoker = {name = "Joker Mandala", text = {"Ce Joker gagne {X:mult,C:white} X0.5 {} Mult", "pour chaque carte {C:spectral}Spectrale{} utilisée", "{C:inactive}(Actuellement {X:mult,C:white} X#1# {C:inactive} Mult){}"}, unlock = {"Utilisez {C:attention}20{} cartes {C:spectral}Spectrales{}", "{C:inactive}(Progression : {C:attention}#1#{C:inactive} / 20){}"}},
            j_kranlaxs_regift = {name = "Joker Recyclé", text = {"Lorsqu'il est {C:gold}vendu{}, crée un", "{C:attention}Joker aléatoire{}", "La rareté dépend de la {C:attention}Blinde{} actuelle"}, unlock = {"Vendez {C:attention}50{} Jokers", "au total", "{C:inactive}(Progression : {C:attention}#1#{C:inactive} / 50){}"}},
            j_kranlaxs_pyromaniac = {name = "Pyromane", text = {"Après avoir marqué avec une main, {C:red}détruit{}", "toutes les cartes {C:attention}numérotées{} de votre main", "{C:inactive}(Les cartes Or, Verre et Acier sont en sécurité){}"}, unlock = {"Détruisez {C:attention}100{} cartes", "qui ne sont pas des figures", "{C:inactive}(Progression : {C:attention}#1#{C:inactive} / 100){}"}},
            j_kranlaxs_neverendinggambling = {name = "Paris Sans Fin", text = {"Perdez {X:money,C:white} $1 {} pour chaque action que vous entreprenez", "{C:inactive}(Uniquement si vous avez {X:money,C:white} $5 {} ou plus){}", "Faites tourner 3 nombres. S'ils correspondent, gagnez un prix !", "Si 2 correspondent, récupérez {X:money,C:white} $1 {} en consolation", "{C:inactive}(Tour actuel : #1# - #2# - #3#){}"}, unlock = {"Échouez à {C:attention}30{} probabilités de", "Jokers ou de consommables", "{C:inactive}(Progression : {C:attention}#1#{C:inactive} / 30){}"}},
            j_kranlaxs_solarsystem = {name = "Système Solaire", text = {"À la {C:attention}fin de la manche{}, crée une carte", "{C:planet}Planète{} dans une séquence fixe", "{C:inactive}(Prochaine planète : {C:planet}#1#{C:inactive}){}"}, unlock = {"Utilisez les {C:attention}12{} cartes {C:planet}Planète{}", "standards au moins une fois", "dans une seule partie", "{C:inactive}(Progression : {C:attention}#1#{C:inactive} / 12){}"}},
            j_kranlaxs_deranged = {name = "Dérangé", text = {"Donne {C:mult}+#1#{} Mult ou {C:chips}+#2#{} Jetons", "L'effet change chaque fois", "que vous jouez une main"}, unlock = {"Terminez le défi :", "{C:attention}Crise d'Identité{}"}},
            j_kranlaxs_deranged_mult = {name = "Dérangé", text = {"Donne {C:mult}+#1#{} Mult", "L'effet change chaque fois", "que vous jouez une main"}},
            j_kranlaxs_deranged_chips = {name = "Dérangé", text = {"Donne {C:chips}+#2#{} Jetons", "L'effet change chaque fois", "que vous jouez une main"}},
            j_kranlaxs_tmtrainer = {name="TMTRAINER",text={"{C:dark_edition}#1#{}","{C:attention}#2#{}","{C:red}#3#{}","{C:chips}#4#{}"},unlock={"Terminez le défi :","{C:attention}Crise d'Identité{}"}},
            j_kranlaxs_bingocard = {name = "Carte de Bingo", text = {"Gagne {X:mult,C:white} X0.25 {} Mult", "pour chaque ligne complétée", "{C:inactive}(Total : {X:mult,C:white} X#2# {C:inactive} Mult){}", "{C:attention}#3#{}", "{C:attention}#4#{}", "{C:attention}#5#{}", "{C:attention}#6#{}", "{C:attention}#7#{}"}, unlock = {"Terminez le défi :", "{C:attention}Anonymat Total{}"}}
        },

        Back = {
            b_kranlaxs_week_challenge = {name = "Défi Hebdomadaire", text = {"Commencez avec un Joker {C:attention}Défi Hebdomadaire{}", "{C:red}Battable{} chaque {C:attention}week-end{}"}, unlock = {"Ouvrez le jeu un", "{C:attention}Samedi{} ou {C:attention}Dimanche{}"}},
            b_kranlaxs_chaos_deck = {name = "Jeu du Chaos", text = {"Profitez du chaos"}, unlock = {"Débloquez {C:legendary,E:1}TOUT{} dans", "votre collection"}},
            b_kranlaxs_dungeon_deck = {name = "Jeu de Donjon", text = {"Après avoir battu une {C:attention}Blinde de Boss{},", "choisissez entre 3 {C:attention}options{}", "avec des {C:green}avantages{} et des {C:red}inconvénients{}"}, unlock = {"Gagnez une partie en {C:attention}Mise Verte{}", "ou supérieure en utilisant le", "jeu {C:attention}Défi Hebdomadaire{}"}},
            b_kranlaxs_space_deck = {name = "Jeu Spatial", text = {"{C:attention}0{} emplacements de Joker, {C:attention}5{} de consommables", "La boutique ne vend que des {C:attention}Quartz{}", "{C:attention}+1{} à la boutique, les blindes sont {C:attention}7.5%{} plus petites", "Mise Gagnante : {C:attention}10{}"}, unlock = {"Gagnez une partie en {C:attention}Mise Verte{}", "avec le {C:attention}Jeu Magique{}, le", "{C:attention}Jeu Nébuleuse{} et le {C:attention}Jeu du Zodiaque{}"}},
            b_kranlaxs_bugged_deck = {name = "Jeu Buggé", text = {"!?"}, unlock = {"Acquérez un {C:attention}TMTRAINER{}", "pour la première fois"}}
        },

        Stake = {
            stake_kranlaxs_magenta = {name = "Mise Magenta", text = {"Les cartes de la boutique peuvent", "avoir l'autocollant {C:attention}Épinglé{}"}},
            stake_kranlaxs_brown = {name = "Mise Marron", colour = "Marron", text = {"{C:attention}-1{} emplacement de", "{C:attention}Paquet Booster{} dans la boutique"}},
            stake_kranlaxs_turquoise = {name = "Mise Turquoise", colour = "Turquoise", text = {"Les blindes ont {C:attention}50%{} de chances", "de {C:red}ne pas pouvoir être passées{}"}},
            stake_kranlaxs_deviled = {name = "Mise Diabolique", colour = "Diabolique", text = {"{C:attention}-1{} emplacement de {C:attention}Joker{}"}},
            stake_kranlaxs_glass = {name = "Mise de Verre", colour = "Verre", text = {"Le score requis augmente", "encore plus vite pour chaque {C:attention}Ante{}"}},
            stake_kranlaxs_platinum = {name = "Mise Platine", colour = "Platine", text = {"Doit battre l'{C:attention}Ante 10{}", "pour gagner la partie"}}
        },

        UNOCards = {
            c_kranlaxs_skip = {name = "Passe Ton Tour", text = {"Obtenez {C:attention}instantanément{} l'exigence de la Blinde", "Ne fonctionne pas sur les {C:attention}Blindes de Boss{}"}},
            c_kranlaxs_stacking = {name = "Superposition", text = {"Ajoute un {C:attention}Sceau Rose{} à", "{C:attention}1{} carte sélectionnée dans votre main"}},
            c_kranlaxs_draw2 = {name = "Plus 2", text = {"Lorsqu'il est utilisé, {C:attention}piochez 2 cartes extra{}", "dans votre main, perdez {C:blue}1{} main"}},
            c_kranlaxs_draw4 = {name = "Plus 4", text = {"Lorsqu'il est utilisé, {C:attention}piochez 4 cartes extra{}", "dans votre main, perdez {C:blue}1{} main"}},
            c_kranlaxs_reverse = {name = "Changement de Sens", text = {"Retourne {C:attention}toutes les cartes{} de votre", "main dans le jeu et les {C:attention}remélange{}"}},
            c_kranlaxs_wildcard = {name = "Joker (Couleur)", text = {"{C:attention}Convertit{} chaque carte dans", "votre main en une {C:attention}couleur aléatoire{}", "{C:attention}indépendamment{}"}},
            c_kranlaxs_replay = {name = "Rejouer", text = {"Renvoie les cartes de", "la dernière main jouée dans votre main", "{C:inactive}(Se réinitialise après utilisation ou", "{C:inactive}à la fin de la manche)"}},
            c_kranlaxs_discardall = {name = "Tout Défausser", text = {"Nécessite {C:attention}1{} carte sélectionnée.", "Défausse {C:red}toutes{} les cartes", "de votre {C:attention}main{} et {C:attention}jeu{} qui", "partagent la même couleur"}},
            c_kranlaxs_shield = {name = "Bouclier", text = {"Vous protège passivement de la mort ou", "peut être vendu pour désactiver la {C:attention}Blinde de Boss{}"}},
            c_kranlaxs_misery = {name = "Misère", text = {"Choisissez une {C:attention}Couleur{}.", "Pioche des cartes de votre jeu", "sans s'arrêter jusqu'à ce que", "vous en obteniez une de cette couleur"}},
            c_kranlaxs_gift = {name = "Cadeau", text = {"Accorde {C:attention}1{} des prix", "aléatoires suivants :", "• Un {C:attention}Joker{} avec Édition", "• Un {C:attention}Consommable{} Négatif", "• Une {C:attention}Carte{} avec Amélioration, Sceau et Édition"}},
            c_kranlaxs_customdraw = {name = "Pioche Personnalisée", text = {"Pioche la même quantité de cartes", "que de défausses que vous avez effectuées", "{C:inactive}(Actuellement : {C:attention}#1#{C:inactive} cartes){}"}}
        },

        InverseTarot = {
            c_kranlaxs_thefool = {name = "Le Fou ?", text = {"Crée une carte {C:spectral}Spectrale{} aléatoire", "{C:attention}Rétrograde{} une main de poker aléatoire"}},
            c_kranlaxs_themagician = {name = "Le Bateleur ?", text = {"Crée {C:attention}2{} cartes {C:attention}Chance{} aléatoires"}},
            c_kranlaxs_thehighpriestess = {name = "La Papesse ?", text = {"Crée un {C:spectral}Trou Noir{}", "Votre {X:money,C:white} argent {} {C:attention}diminue{} de 20%"}},
            c_kranlaxs_theempress = {name = "L'Impératrice ?", text = {"Ajoute {C:red}+8{} Mult permanent", "à jusqu'à {C:attention}2{} cartes sélectionnées"}},
            c_kranlaxs_theemperor = {name = "L'Empereur ?", text = {"Crée {C:attention}2{} {C:attention}Tags{} aléatoires"}},
            c_kranlaxs_thehierophant = {name = "Le Pape ?", text = {"Ajoute {C:blue}+40{} Jetons permanents", "à jusqu'à {C:attention}2{} cartes sélectionnées"}},
            c_kranlaxs_thelovers = {name = "L'Amoureux ?", text = {"Gagnez {C:attention}+1{} taille de main si", "vous avez une {C:attention}Carte Joker{} (Wild) dans votre jeu"}},
            c_kranlaxs_thechariot = {name = "Le Chariot ?", text = {"Crée {C:attention}1{} carte en {C:attention}Acier{} aléatoire", "avec un Sceau {C:attention}Rouge{}"}},
            c_kranlaxs_justice = {name = "La Justice ?", text = {"Ajoute {X:red,C:white} X2 {} Mult permanent", "à {C:attention}1{} carte sélectionnée", "{C:green}#1# chance(s) sur #2#{} de {C:attention}détruire{} cette carte"}},
            c_kranlaxs_thehermit = {name = "L'Ermite ?", text = {"{C:attention}Définit{} votre {X:money,C:white} argent {} à {X:money,C:white} $25 {} si", "vous avez {C:attention}moins de{} {X:money,C:white} $25 {}"}},
            c_kranlaxs_thewheeloffortune = {name = "La Roue de Fortune ?", text = {"{C:green}#1# chance(s) sur #2#{} de créer une {C:attention}copie{}", "d'un Joker aléatoire avec l'édition {C:dark_edition}Négative{}"}},
            c_kranlaxs_strenght = {name = "La Force ?", text = {"{C:attention}Réduit{} le {C:attention}rang{} de jusqu'à", "{C:attention}2{} cartes sélectionnées de {C:attention}1{}"}},
            c_kranlaxs_thehangedman = {name = "Le Pendu ?", text = {"{C:attention}Rend complètement aléatoire{} jusqu'à", "{C:attention}2{} cartes sélectionnées en main"}},
            c_kranlaxs_death = {name = "La Mort ?", text = {"Crée une {C:attention}copie Négative{} d'un Joker aléatoire", "Un Joker aléatoire reçoit un Autocollant {C:attention}Périssable{}"}},
            c_kranlaxs_temperance = {name = "Tempérance ?", text = {"Vend {C:attention}TOUS{} les Jokers (même les Éternels)", "pour le {C:money}triple{} de leur valeur de vente", "{C:inactive}(Ne vend pas les Jokers Épinglés){}"}},
            c_kranlaxs_thedevil = {name = "Le Diable ?", text = {"Ajoute {X:money,C:white} $2 {} permanents", "à jusqu'à {C:attention}2{} cartes sélectionnées"}},
            c_kranlaxs_thetower = {name = "La Maison Dieu ?", text = {"{C:attention}Supprime{} toutes les améliorations, sceaux,", "éditions et bonus des cartes en main", "Gagnez {X:money,C:white} $1 {} pour chaque modification retirée"}},
            c_kranlaxs_thestars = {name = "L'Étoile ?", text = {"Ajoute un {C:attention}Sceau Blanc{} à jusqu'à", "{C:attention}2{} cartes sélectionnées"}},
            c_kranlaxs_themoon = {name = "La Lune ?", text = {"Ajoute un {C:attention}Sceau Gris{} à jusqu'à", "{C:attention}2{} cartes sélectionnées"}},
            c_kranlaxs_thesun = {name = "Le Soleil ?", text = {"Ajoute un {C:attention}Sceau Orange{} à jusqu'à", "{C:attention}2{} cartes sélectionnées"}},
            c_kranlaxs_judgement = {name = "Le Jugement ?", text = {"{C:attention}Échange{} un {C:attention}Bon{} aléatoire", "{C:red}-1{} taille de main"}},
            c_kranlaxs_theworld = {name = "Le Monde ?", text = {"Ajoute un {C:attention}Sceau Marron{} à jusqu'à", "{C:attention}2{} cartes sélectionnées"}}
        },

        Voucher = {
            v_kranlaxs_more_stock = {name = "Plus de Stock", text = {"La boutique a {C:attention}1{} emplacement", "supplémentaire de {C:attention}Paquet Booster{}"}},
            v_kranlaxs_even_more_stock = {name = "Encore Plus de Stock", text = {"La boutique a {C:attention}1{} emplacement", "supplémentaire de {C:attention}Bon{}"}},
            v_kranlaxs_shiny_appearance = {name = "Apparition Brillante", text = {"Les cartes légendaires et les consommables rares", "peuvent désormais apparaître dans la boutique"}},
            v_kranlaxs_stickerfever = {name = "Fièvre des Autocollants", text = {"Chaque fois que vous obtenez", "un {C:attention}Tag{}, gagnez", "{C:attention}1{} copie supplémentaire"}},
            v_kranlaxs_stickeralbum = {name = "Album d'Autocollants", text = {"Chaque fois que vous obtenez", "un {C:attention}Tag{}, gagnez", "{C:attention}1{} autre copie supplémentaire"}},
            v_kranlaxs_hotfix = {name = "Hotfix", text = {"Le {C:attention}Renouvellement{} de la boutique", "rafraîchit également les {C:attention}Bons{}", "et les {C:attention}Paquets Booster{}"}},
            v_kranlaxs_version2 = {name = "Version 2.0", text = {"Passer les blindes vous accorde la récompense en {X:money,C:white} argent {}", "de cette blinde.", "Exigence de la blinde {C:attention}-15%{}"}},
            v_kranlaxs_common_shinys = {name = "Observation Légendaire", text = {"Les cartes légendaires et les consommables rares", "apparaîtront plus fréquemment"}},
            v_kranlaxs_blessing = {name = "Bénédiction", text = {"Vous commencez avec {C:attention}10%{}", "de l'exigence en jetons", "complétée sur chaque blinde"}},
            v_kranlaxs_protection = {name = "Protection Divine", text = {"Vous protège d'un {C:attention}Game Over{}.", "Lors de l'utilisation, ce bon est détruit", "et peut réapparaître dans la boutique,", "mais au {X:money,C:white} double {} de son prix d'origine"}}
        },

        Quartz = {
            c_kranlaxs_blackquartz = {name = "Obsidienne", text = {"Modifie certaines règles", "de votre choix"}, unlock = {"Gagnez une partie en {C:attention}Mise Marron{}", "en utilisant le {C:attention}Jeu Magique{}"}},
            c_kranlaxs_whitequartz = {name = "Perle", text = {"Crée le dernier", "consommable utilisé", "{C:inactive}(Dernière carte : {C:attention}#1#{C:inactive}){}"}, unlock = {"Gagnez une partie en {C:attention}Mise Marron{}", "en utilisant le {C:attention}Jeu Fantôme{}"}},
            c_kranlaxs_pinkquartz = {name = "Quartz Rose", text = {"Ajoute {C:dark_edition}Polychrome{} à un {C:attention}Joker{}", "ou une {C:attention}carte{} sélectionnée"}, unlock = {"Gagnez une partie en {C:attention}Mise Magenta{}", "ou supérieure en utilisant le {C:attention}Jeu de Donjon{}"}},
            c_kranlaxs_bluequartz = {name = "Saphir", text = {"Ajoute {C:chips}Foil{} à un", "{C:attention}Joker{} ou une {C:attention}carte{} sélectionnée"}, unlock = {"Gagnez une partie en {C:attention}Mise Platine{}", "en utilisant le {C:attention}Jeu Plasma{}"}},
            c_kranlaxs_lilacquartz = {name = "Kunzite", text = {"Ajoute {C:mult}Holographique{} à un", "{C:attention}Joker{} ou une {C:attention}carte{} sélectionnée"}, unlock = {"Gagnez une partie en {C:attention}Mise Marron{}", "en utilisant le {C:attention}Jeu Nébuleuse{}"}},
            c_kranlaxs_grayquartz = {name = "Hématite", text = {"Ajoute {C:dark_edition}Négatif{} à un", "{C:attention}Joker{} ou un {C:attention}consommable{} sélectionné"}, unlock = {"Gagnez une partie en {C:attention}Mise Turquoise{}", "en utilisant le {C:attention}Jeu Peint{}"}},
            c_kranlaxs_transparentquartz = {name = "Diamant", text = {"{C:attention}Supprime{} tous les autocollants ou éditions", "d'un {C:attention}Joker{}, ou les sceaux ou", "éditions d'une {C:attention}carte{} sélectionnée"}, unlock = {"Gagnez une partie en {C:attention}Mise Platine{}", "en utilisant le {C:attention}Jeu de Donjon{}"}},
            c_kranlaxs_redquartz = {name = "Rubis", text = {"Tant qu'il est {C:attention}détenu{},", "donne {X:mult,C:white} X2 {} Mult", "{C:inactive}(Passif){}"}, unlock = {"Gagnez une partie en {C:attention}Mise Magenta{}", "ou supérieure en utilisant le {C:attention}Jeu Rouge{}"}},
            c_kranlaxs_celestequartz = {name = "Larimar", text = {"Tant qu'il est {C:attention}détenu{},", "donne {X:chips,C:white} X1.5 {} Jetons", "{C:inactive}(Passif){}"}, unlock = {"Gagnez une partie en {C:attention}Mise Turquoise{}", "en utilisant le {C:attention}Jeu à Carreaux{}"}},
            c_kranlaxs_yellowquartz = {name = "Topaze", text = {"Crée le {C:attention}Joker{} indiqué.", "Le Joker change aléatoirement", "après chaque {C:attention}manche{}", "{C:inactive}(Cible : {C:attention}#1#{C:inactive}){}"}, unlock = {"Gagnez une partie en {C:attention}Mise Bleue{}", "en utilisant le {C:attention}Jeu de Donjon{}"}},
            c_kranlaxs_greenquartz = {name = "Émeraude", text = {"Tant qu'il est {C:attention}détenu{}, crée un", "{C:attention}Tag{} après avoir battu une {C:attention}Blinde{}", "Détruit après avoir créé {C:attention}#2#{} tags", "{C:inactive}(Actuels : {C:attention}#1#{C:inactive}){}", "{C:inactive}(Passif){}"}, unlock = {"Gagnez une partie en {C:attention}Mise Magenta{}", "ou supérieure en utilisant le {C:attention}Jeu Vert{}"}},
            c_kranlaxs_brownquartz = {name = "Œil de Tigre", text = {"Crée la {C:attention}Carte{} indiquée.", "La carte change aléatoirement après", "le {C:green}Renouvellement{} de la boutique", "{C:inactive}(Cible : {C:attention}#1#{C:inactive}){}"}, unlock = {"Gagnez une partie en {C:attention}Mise Turquoise{}", "en utilisant le {C:attention}Jeu Anaglyphe{}"}},
            c_kranlaxs_turquoisequartz = {name = "Turquoise", text = {"Tant qu'il est {C:attention}détenu{}, {C:attention}désactive{}", "tous les jokers sauf le premier", "Redéclenche ce joker {C:attention}2{} fois", "{C:inactive}(Passif){}"}, unlock = {"Gagnez une partie en {C:attention}Mise Turquoise{}", "en utilisant le {C:attention}Jeu du Zodiaque{}"}},
            c_kranlaxs_orangequartz = {name = "Citrine", text = {"Ajoute un {C:green}Sceau Menthe{} à une {C:attention}carte{}", "ou un {C:green}Autocollant Trèfle{} à un", "{C:attention}Joker{} sélectionné"}, unlock = {"Gagnez une partie en {C:attention}Mise Magenta{}", "ou supérieure en utilisant le {C:attention}Jeu Jaune{}"}},
            c_kranlaxs_lapislazuli = {name = "Lapis-Lazuli", text = {"Tant qu'il est {C:attention}détenu{}, ajoute", "{C:chips}+#1#{} Jetons à la première carte marquante", "L'effet diminue de {C:chips}-#2#{} à chaque utilisation.", "{C:inactive}(Inactif lorsqu'il atteint 0){}", "{C:inactive}(Passif){}"}, unlock = {"Gagnez une partie en {C:attention}Mise Magenta{}", "ou supérieure en utilisant le {C:attention}Jeu Bleu{}"}},
            c_kranlaxs_cinnabar = {name = "Cinabre", text = {"Tant qu'il est {C:attention}détenu{}, ajoute", "{C:mult}+#1#{} Mult à la première carte marquante", "L'effet diminue de {C:mult}-#2#{} à chaque utilisation.", "{C:inactive}(Inactif lorsqu'il atteint 0){}", "{C:inactive}(Passif){}"}, unlock = {"Gagnez une partie en {C:attention}Mise Marron{}", "en utilisant le {C:attention}Jeu Abandonné{}"}},
            c_kranlaxs_graphite = {name = "Graphite", text = {"Tant qu'il est {C:attention}détenu{}, {C:green}#1# chance(s) sur #2#{}", "de créer une copie dans votre", "main de toutes les cartes jouées.", "La chance chute lors du déclenchement.", "{C:inactive}(Inactif lorsqu'il atteint 0){}", "{C:inactive}(Passif){}"}, unlock = {"Gagnez une partie en {C:attention}Mise Magenta{}", "ou supérieure en utilisant le {C:attention}Jeu Noir{}"}},
            c_kranlaxs_uranium = {name = "Uranium", text = {"Tant qu'il est {C:attention}détenu{}, applique 1 effet", "aléatoire par manche. Il peut être", "très bon ou très destructeur.", "{C:dark_edition}Statut actuel :{}", "{C:red,E:2}#1#{}", "{C:inactive}(Osez-vous le porter ?){}", "{C:inactive}(Passif){}"}, unlock = {"Gagnez une partie en {C:attention}Mise Platine{}", "en utilisant le {C:attention}Jeu Erratique{}"}}
        },

        Tag = {
            tag_kranlaxs_mega_invtarot = {name = "Méga Tag Inverse", text = {"Accorde un {C:attention}Méga Paquet de Tarots Inverses{}", "gratuitement et instantanément"}},
            tag_kranlaxs_mega_uno = {name = "Tag UNO Jumbo", text = {"Accorde un {C:attention}Paquet UNO Jumbo{}", "gratuitement et instantanément"}},
            tag_kranlaxs_mega_invtarot_store = {name = "Méga Tag Inverse Stocké", text = {"Accorde un {C:attention}Méga Tarot Inverse Stocké{}", "gratuitement et instantanément"}},
            tag_kranlaxs_quartz_tag = {name = "Tag Quartz", text = {"Crée un {C:attention}Quartz{} aléatoire", "{C:inactive}(Doit avoir de la place){}"}},
            tag_kranlaxs_sticker_remover = {name = "Tag Nettoyeur", text = {"Retire un autocollant {C:attention}Éternel{},", "{C:attention}Périssable{} ou de {C:attention}Location{} d'un", "un {C:attention}Joker{} aléatoire", "{C:inactive}(Donne {X:money,C:white} $5 {C:inactive} s'il n'y a pas d'autocollant){}"}},
            tag_kranlaxs_legendary = {name = "Tag Légendaire", text = {"La boutique a un", "{C:legendary}Joker Légendaire{} gratuit"}}
        },

        Edition = {
            e_kranlaxs_wave = {name = "Aquatique", text = {"{X:chips,C:white} X#1# {} Jetons"}}
        },

        Other = {
            kranlaxs_magenta_sticker = {name = "Autocollant Magenta", text = {"A utilisé ce Joker", "pour gagner en {C:attention}Mise Magenta{}"}},
            kranlaxs_brown_sticker = {name = "Autocollant Marron", text = {"A utilisé ce Joker", "pour gagner en {C:attention}Mise Marron{}"}},
            kranlaxs_turquoise_sticker = {name = "Autocollant Turquoise", text = {"A utilisé ce Joker", "pour gagner en {C:attention}Mise Turquoise{}"}},
            kranlaxs_platinum_sticker = {name = "Autocollant Platine", text = {"A utilisé ce Joker", "pour gagner en {C:attention}Mise Platine{}"}},
            kranlaxs_orangeseal_seal = {name = "Sceau Orange", text = {"Si marqué en main : {C:attention}#1#{},", "crée 1 {C:attention}#2#{}", "{C:inactive}Change après utilisation.{}", "{C:inactive}(Doit avoir de la place){}"}},
            kranlaxs_deviled_sticker = {name = "Autocollant Diabolique", text = {"A utilisé ce Joker", "pour gagner en {C:attention}Mise Diabolique{}"}},
            kranlaxs_glass_sticker = {name = "Autocollant de Verre", text = {"A utilisé ce Joker", "pour gagner en {C:attention}Mise de Verre{}"}},
            kranlaxs_pinkseal_seal = {name = "Sceau Rose", text = {"Applique {X:dark_edition,C:white}^1.75{} Mult", "lorsqu'il {C:attention}marque{}"}},
            kranlaxs_whiteseal_seal = {name = "Sceau Blanc", text = {"{C:attention}Marque toujours{}, immunisé contre", "l'{C:red}affaiblissement{}, la {C:red}destruction{}", "ou le {C:attention}retournement{}"}},
            kranlaxs_brownseal_seal = {name = "Sceau Marron", text = {"{C:green}#1# chance(s) sur #2#{} de", "{C:attention}dupliquer{} cette carte", "pendant qu'elle est en main"}},
            kranlaxs_grayseal_seal = {name = "Sceau Gris", text = {"Lorsqu'il {C:attention}marque{}, change {C:attention}aléatoirement{}", "l'{C:enhanced}Amélioration{} de cette carte"}},
            kranlaxs_mintseal_seal = {name = "Sceau Menthe", text = {"Double toutes les {C:attention}probabilités indiquées{}", "sur cette carte"}},
            p_kranlaxs_uno_store_3 = {name = "Paquet UNO", text = {"Choisissez {C:attention}1{} carte parmi", "jusqu'à {C:attention}3{} cartes {C:blue}UNO{}"}},
            p_kranlaxs_uno_store_5 = {name = "Paquet UNO Jumbo", text = {"Choisissez {C:attention}1{} carte parmi", "jusqu'à {C:attention}5{} cartes {C:blue}UNO{}"}},
            p_kranlaxs_invtarot_instant_3_1 = {name = "Paquet de Tarots Inverses", text = {"Choisissez {C:attention}1{} carte parmi", "jusqu'à {C:attention}3{} cartes {C:purple}Tarot Inverse{}"}},
            p_kranlaxs_invtarot_instant_5_1 = {name = "Paquet de Tarots Inverses Jumbo", text = {"Choisissez {C:attention}1{} carte parmi", "jusqu'à {C:attention}5{} cartes {C:purple}Tarot Inverse{}"}},
            p_kranlaxs_invtarot_instant_5_2 = {name = "Méga Paquet de Tarots Inverses", text = {"Choisissez {C:attention}2{} cartes parmi", "jusqu'à {C:attention}5{} cartes {C:purple}Tarot Inverse{}"}},
            p_kranlaxs_invtarot_store_3_1 = {name = "Tarot Inverse Stocké", text = {"Choisissez {C:attention}1{} carte parmi", "jusqu'à {C:attention}3{} cartes {C:purple}Tarot Inverse{}"}},
            p_kranlaxs_invtarot_store_5_1 = {name = "Tarot Inverse Jumbo Stocké", text = {"Choisissez {C:attention}1{} carte parmi", "jusqu'à {C:attention}5{} cartes {C:purple}Tarot Inverse{}"}},
            p_kranlaxs_invtarot_store_5_2 = {name = "Méga Tarot Inverse Stocké", text = {"Choisissez {C:attention}2{} cartes parmi", "jusqu'à {C:attention}5{} cartes {C:purple}Tarot Inverse{}"}}
        },

        Booster = {
            p_kranlaxs_uno_store_3 = {name = "Paquet UNO", text = {"Choisissez {C:attention}1{} carte parmi", "jusqu'à {C:attention}3{} cartes {C:blue}UNO{}"}},
            p_kranlaxs_uno_store_5 = {name = "Paquet UNO Jumbo", text = {"Choisissez {C:attention}1{} carte parmi", "jusqu'à {C:attention}5{} cartes {C:blue}UNO{}"}},
            p_kranlaxs_invtarot_instant_3_1 = {name = "Paquet de Tarots Inverses", text = {"Choisissez {C:attention}1{} carte parmi", "jusqu'à {C:attention}3{} cartes {C:purple}Tarot Inverse{}"}},
            p_kranlaxs_invtarot_instant_5_1 = {name = "Paquet de Tarots Inverses Jumbo", text = {"Choisissez {C:attention}1{} carte parmi", "jusqu'à {C:attention}5{} cartes {C:purple}Tarot Inverse{}"}},
            p_kranlaxs_invtarot_instant_5_2 = {name = "Méga Paquet de Tarots Inverses", text = {"Choisissez {C:attention}2{} cartes parmi", "jusqu'à {C:attention}5{} cartes {C:purple}Tarot Inverse{}"}},
            p_kranlaxs_invtarot_store_3_1 = {name = "Tarot Inverse Stocké", text = {"Choisissez {C:attention}1{} carte parmi", "jusqu'à {C:attention}3{} cartes {C:purple}Tarot Inverse{}"}},
            p_kranlaxs_invtarot_store_5_1 = {name = "Tarot Inverse Jumbo Stocké", text = {"Choisissez {C:attention}1{} carte parmi", "jusqu'à {C:attention}5{} cartes {C:purple}Tarot Inverse{}"}},
            p_kranlaxs_invtarot_store_5_2 = {name = "Méga Tarot Inverse Stocké", text = {"Choisissez {C:attention}2{} cartes parmi", "jusqu'à {C:attention}5{} cartes {C:purple}Tarot Inverse{}"}}
        }
    },
    
    misc = {
        labels = {
            kranlaxs_magenta_sticker = "Autocollant Magenta",
            kranlaxs_brown_sticker = "Autocollant Marron",
            kranlaxs_turquoise_sticker = "Autocollant Turquoise",
            kranlaxs_platinum_sticker = "Autocollant Platine",
            kranlaxs_orangeseal_seal = "Sceau Orange", 
            kranlaxs_pinkseal_seal = "Sceau Rose", 
            kranlaxs_whiteseal_seal = "Sceau Blanc", 
            kranlaxs_brownseal_seal = "Sceau Marron", 
            kranlaxs_grayseal_seal = "Sceau Gris", 
            kranlaxs_mintseal_seal = "Sceau Menthe", 
            clover = "Autocollant Trèfle",
            kranlaxs_deviled_sticker = "Autocollant Diabolique",
            kranlaxs_glass_sticker = "Autocollant de Verre",
            p_kranlaxs_uno_store_3 = "Paquet UNO",
            p_kranlaxs_uno_store_5 = "Paquet UNO Jumbo",
            p_kranlaxs_invtarot_instant_3_1 = "Paquet de Tarots Inverses",
            p_kranlaxs_invtarot_instant_5_1 = "Paquet de Tarots Inverses Jumbo",
            p_kranlaxs_invtarot_instant_5_2 = "Méga Paquet de Tarots Inverses",
            p_kranlaxs_invtarot_store_3_1 = "Tarot Inverse Stocké",
            p_kranlaxs_invtarot_store_5_1 = "Tarot Inverse Jumbo Stocké",
            p_kranlaxs_invtarot_store_5_2 = "Méga Tarot Inverse Stocké",
            kranlaxs_wave = "Aquatique"
        },

        v_text = {
            ch_c_kran_fijado_1 = {"Tous les Jokers ont l'autocollant {C:attention}Épinglé{}"},
            ch_c_kran_abuela_1 = {"Les Jokers {C:attention}marquants{} sont {C:red}bannis{}"},
            ch_c_kran_crisis_1 = {"La boutique est {C:attention}20% plus chère{}"},
            ch_c_kran_crisis_2 = {"La récompense de base des blindes est {C:red}réduite{} de {X:money,C:white} $2 {}"},
            ch_c_kran_crisis_3 = {"Le jeu est composé uniquement de {C:attention}52 As{}"},
            ch_c_kran_doppel_1 = {"Tous les Jokers sont {C:red}bannis{} de la boutique"},
            ch_c_kran_anonimo_1 = {"Les cartes en main et les Jokers sont {C:attention}face cachée{}"},
            ch_c_kran_jefes_1 = {"Les Petites et Grosses Blindes sont des {C:attention}Blindes de Boss{}"},
            ch_c_kran_premon_1 = {"Toutes les cartes de votre main sont {C:attention}face cachée{}"},
            ch_c_kran_tallo_1 = {"Les autres {C:attention}Jokers{} et {C:attention}Paquets{} sont {C:red}bannis{}"},
            ch_c_gacha_rule_1 = {"Aucune {C:attention}carte individuelle{} n'apparaît dans la boutique"},
            ch_c_kran_pobreza_1 = {"{C:attention}50%{} de chances qu'un {C:common}Commun{} soit {C:legendary}Légendaire{}"},
            ch_c_kran_pobreza_2 = {"Si votre Joker {C:attention}Moine{} est déçu, {C:red}vous perdez la partie{}"}
        }
    }
}