return {
    descriptions = {
        Joker = {
            j_kranlaxs_tagger = {name = "Etichettatore", text = {"Ottieni {C:red}+#1#{} Mult per ogni", "{C:attention}Tag{} ottenuto", "{C:inactive}(Attualmente {C:red}+#2#{C:inactive} Mult){}"}, unlock = {"Compra i {C:attention}2{} Voucher", "Vuoti in una singola partita"}},
            j_kranlaxs_Cashback = {name = "Rimborso", text = {"{C:green}#1# su #2#{} probabilità di ottenere {X:money,C:white} $3 {},", "quando compri una carta"}, unlock = {"Vinci una partita a {C:attention}Puntata Rossa{}", "usando il {C:attention}Mazzo Spaziale{}"}},
            j_kranlaxs_underratedjoker = {name = "Jolly Sottovalutato", text = {"Questo Jolly ottiene {X:chips,C:white} X0.2 {} Fiches", "se la mano giocata {C:attention}non è{}", "la tua mano di poker più giocata", "{C:inactive}(Si azzera se lo è){}", "{C:inactive}(Attualmente {X:chips,C:white} X#1# {C:inactive} Fiches){}"}, unlock = {"Vinci una partita a {C:attention}Puntata Blu{}", "usando il {C:attention}Mazzo Spaziale{}"}},
            j_kranlaxs_facelessaccountant = {name = "Contabile Senza Volto", text = {"Questo Jolly ottiene {X:blue,C:white} X0.1 {} Fiches per", "ogni {C:attention}#2#{} che fa punteggio", "{C:inactive}(Attualmente {X:blue,C:white} X#1# {C:inactive} Fiches){}"}, unlock = {"Vinci una partita senza giocare figure,", "ma avendone almeno {C:attention}1{} nel tuo mazzo"}},
            j_kranlaxs_thefixer = {name = "Il Faccendiere", text = {"Vendere un {C:attention}Jolly{} durante un", "{C:purple}Buio{} riduce il punteggio richiesto", "{C:inactive}(Comune: -10%, Non Comune: -30%){}", "{C:inactive}(Raro: -60%, Leggendario: -95%){}"}, unlock = {"Vendi almeno {C:attention}2{} Jolly", "di ogni rarità"}},
            j_kranlaxs_mysteriousgeode = {name = "Geode Misterioso", text = {"Ogni {C:attention}Carta Jolly{} (Wild) che fa punteggio", "dà un effetto {C:attention}casuale{}"}, unlock = {"Gioca una mano", "con {C:attention}5{} Carte Jolly (Wild)"}},
            j_kranlaxs_benchwarmer = {name = "Scaldapanchina", text = {"Dà {C:attention}4 volte{} il valore in {C:blue}Fiches{}", "della carta di grado più alto in mano"}},
            j_kranlaxs_entropy2 = {name = "Vortice", text = {"Ottiene {X:dark_edition,C:white} ^1 {} Mult e {X:dark_edition,C:white} ^1 {} Fiches", "per ogni carta {C:attention}sotto il 52{} nel tuo mazzo", "{C:inactive}(Attualmente {X:dark_edition,C:white} ^#1# {C:inactive} Mult e {X:dark_edition,C:white} ^#1# {C:inactive} Fiches){}"}},
            j_kranlaxs_greedyleprachaun = {name = "Leprecauno Avido", text = {"Pesca {C:attention}3 carte extra{}", "al primo {C:red}scarto{} del round"}, unlock = {"Scarta esattamente {C:attention}1{} carta", "{C:attention}3{} volte di fila"}},
            j_kranlaxs_charismaticbard = {name = "Bardo Carismatico", text = {"{C:attention}-1{} dimensione della mano", "Riduce il requisito del {C:purple}Buio{} del {C:attention}2%{} ogni volta", "che giochi la tua {C:attention}mano più giocata{}", "{C:inactive}(Massimo 90%){}", "Si azzera se giochi un'altra mano", "{C:inactive}(Attualmente {C:attention}-#1#%{C:inactive} dimensione del Buio){}"}},
            j_kranlaxs_russianroulette = {name = "Roulette Russa", text = {"{C:green}#1# su #2#{} probabilità di {C:red}Perdere la partita{}", "quando selezioni un buio", "Se sopravvivi, ottiene", "{X:mult,C:white} X3 {} Mult e {X:chips,C:white} X3 {} Fiches", "{C:inactive}(Attualmente {X:mult,C:white} X#3# {C:inactive} Mult e {X:chips,C:white} X#3# {C:inactive} Fiches){}"}, unlock = {"Vinci una partita a {C:attention}Puntata Nera{}", "usando il {C:attention}Mazzo Spaziale{}"}},
            j_kranlaxs_fidelitycard = {name = "Pass Battaglia", text = {"Dopo aver comprato {C:attention}6{} carte, la {C:attention}settima{}", "carta comprata dà {X:money,C:white} denaro {} pari al", "{C:attention}valore di vendita{} di tutti i tuoi Jolly", "{C:inactive}(Attualmente {C:attention}#1#/6{C:inactive} carte){}", "{C:inactive}(Valore di vendita totale: {X:money,C:white} $#2# {C:inactive}){}"}},
            j_kranlaxs_devioussheep = {name = "Pecora Ingorda", text = {"{C:red}Divora{} un Jolly casuale quando", "selezioni un {C:attention}Buio{} e ottiene {X:mult,C:white} X0.4 {} Mult", "{C:hearts}Game Over{} se non ci sono altri Jolly", "{C:inactive}(Dai priorità a certi bersagli per più Mult!){}", "{C:inactive}(Attualmente {X:mult,C:white} X#1# {C:inactive} Mult){}"}},
            j_kranlaxs_lifeassurance = {name = "Assicurazione sulla Vita", text = {"Evita un Game Over se", "hai almeno {X:money,C:white} $#1# {}", "{C:inactive}(Il prezzo raddoppia dopo ogni uso){}"}, unlock = {"Perdi una partita con", "{X:money,C:white} $100 {} o più in tuo possesso", "prima dell'{C:attention}Ante 8{}"}},
            j_kranlaxs_sundaycheckpoint = {name = "Checkpoint", text = {"{C:red}Game Over{} se selezioni", "un buio in un {C:attention}giorno feriale{}", "Altrimenti, crea un Jolly {C:attention}Sfida Settimanale{}", "alla fine del round e si {C:red}autodistrugge{}", "{C:inactive}(Giorno attuale: #1#){}"}},
            j_kranlaxs_weeklychallenge = {name = "Sfida Settimanale", text = {"Imposta una sfida casuale per questa partita", "{C:clubs}Sfida attuale:{} {C:attention}#1#{}", "{C:inactive}1:{} Hai {X:money,C:white} -$100 {}, pagali prima dell'Ante 8", "{C:inactive}2:{} Negozio limitato", "{C:inactive}3:{} 1 Mano, 20 Scarti (Nessun Voucher extra)", "{C:inactive}4:{} Limite di {C:blue}#2#{} mani e {C:red}#3#{} scarti nella partita", "{C:inactive}5:{} Velocità di gioco bloccata a 0.5x", "{C:inactive}6:{} 3 Triboulet Eterni (Max 3 Jolly, Ante Veloce)", "{C:inactive}7:{} 1 su 6 probabilità di VINCERE (Perdi all'Ante 8)"}},
            j_kranlaxs_panda = {name = "Panda Soffice", text = {"Dà {C:chips}+#1#{} Fiches", "{C:attention}-1{} spazio per Jolly"}},
            j_kranlaxs_miner = {name = "Minatore", text = {"Ottieni {C:red}+5{} Mult per ogni", "{C:attention}Carta di Pietra{} che fa punteggio", "{C:green}#2# su #3#{} probabilità di guadagnare", "da {X:money,C:white} $#4# {} a {X:money,C:white} $#5# {} quando giochi una mano", "{C:inactive}(Attualmente {C:red}+#1#{C:inactive} Mult){}"}, unlock = {"Gioca una mano", "con {C:attention}5{} Carte di Pietra"}},
            j_kranlaxs_birthdaycake = {name = "Torta di Compleanno", text = {"Dà {X:dark_edition,C:white} ^#1# {} Mult", "Perde {X:dark_edition,C:white} ^0.25 {} dopo", "ogni mano giocata", "Una volta esaurita crea un {C:attention}Jolly Riciclato{}"}, unlock = {"Vinci una partita a difficoltà", "{C:attention}Puntata Blu{} usando", "il mazzo {C:attention}Sfida Settimanale{}"}},
            j_kranlaxs_vipsuscription = {name = "Abbonamento V.I.P.", text = {"Dà {C:attention}+#2#{} spazi nel negozio,", "{C:attention}+1{} Voucher e Pacchetto extra", "Sottrae {X:money,C:white} $#1# {} all'apertura del negozio.", "Il prezzo e la dimensione del negozio", "{C:attention}aumentano{} sconfiggendo un {C:attention}Buio Boss{}"}, unlock = {"Vinci una partita a difficoltà", "{C:attention}Puntata Arancione{} usando", "il mazzo {C:attention}Sfida Settimanale{}"}},
            j_kranlaxs_painterjoker = {name = "Jolly Pittore", text = {"Quando una mano fa punteggio, crea un", "{C:attention}Tag Giocoliere{} per ogni", "{C:attention}Carta Jolly{} (Wild) nella tua mano", "{C:inactive}(Costa {X:money,C:white} $#1# {C:inactive} per tag){}"}, unlock = {"Vinci una partita a difficoltà", "{C:attention}Puntata Arancione{} usando", "il mazzo {C:attention}Sfida Settimanale{}"}},
            j_kranlaxs_coronation = {name = "Incoronazione", text = {"Se la mano giocata contiene carte che fanno punteggio", "di grado {C:attention}10 o inferiore{}, trasforma", "la più bassa in un {C:attention}Re{}.", "Se non ci sono carte basse in mano,", "aggiunge un {C:red}Sigillo Rosso{} al primo {C:attention}Re{} che fa punteggio."}, unlock = {"Gioca una mano di esattamente", "{C:attention}5 Re{}. Tutti devono avere", "un {C:red}Sigillo Rosso{} ed essere carte d'{C:attention}Acciaio{}"}},
            j_kranlaxs_speedrunner = {name = "Speedrunner", text = {"{X:mult,C:white} X#1# {} Mult.", "Hai {C:attention}#2# secondi{} per", "giocare una mano o scartare.", "Se il tempo scade, {C:red}GAME OVER{}."}, unlock = {"Vinci una partita a difficoltà", "{C:attention}Puntata Verde{} usando", "il mazzo {C:attention}Sfida Settimanale{}"}},
            j_kranlaxs_passcode = {name = "Codice Segreto", text = {"Se la mano giocata corrisponde a uno", "dei seguenti codici, la mano", "conta come un {C:attention}Colore a Cinque{}", "{C:inactive}1. {C:attention}#1#{}", "{C:inactive}2. {C:attention}#2#{}", "{C:inactive}3. {C:attention}#3#{}"}, unlock = {"Vinci una partita a difficoltà", "{C:attention}Puntata Nera{} usando", "il mazzo {C:attention}Sfida Settimanale{}"}},
            j_kranlaxs_chronometer = {name = "Cronometro", text = {"Quando giochi una mano: ", "Dà {C:chips}Fiches{} pari ai {C:attention}Secondi{} attuali", "Dà {C:mult}Mult{} pari ai {C:attention}Minuti{} attuali", "Guadagni {C:money}denaro{} pari alle {C:attention}Ore{} attuali", "{C:inactive}(Attualmente: {C:chips}+#1#{C:inactive} Fiches, {C:mult}+#2#{C:inactive} Mult, {C:money}+$#3#{C:inactive}){}"}, unlock = {"Vinci una partita a {C:attention}Puntata Oro{}", "usando il {C:attention}Mazzo Spaziale{}"}},
            j_kranlaxs_zombiejoker = {name = "Joly Zombi", text = {"{C:attention}disstruge{} la {C:attention}prima{} carta", "k nn fa pntegio e ottn {C:red}+15{} mult", "ma perdi {C:red}-10{} mult", "xogni mna giocta nel rond", "se ariva a {C:red}0{} mult", "{C:attention}muore {}", "{C:inactive}(hai {C:red}+#1#{C:inactive} mult o roba sime){}"}, unlock = {"Vinci una partita a {C:attention}Puntata Viola{}", "usando il {C:attention}Mazzo Spaziale{}"}},
            j_kranlaxs_thecousin = {name = "Il Cugino", text = {"Ottieni {C:chips}+13{} Fiches per ogni", "{C:attention}numero primo{} che fa punteggio", "{C:inactive}(Attualmente {C:chips}+#1#{C:inactive} Fiches){}"}, unlock = {"Vinci una partita a {C:attention}Puntata Turchese{}", "usando il {C:attention}Mazzo Spaziale{}"}},
            j_kranlaxs_colasoda = {name = "Soda alla Cola", text = {"Dà {X:dark_edition,C:white} ^#1# {} Mult", "Perde {X:dark_edition,C:white} ^#2# {} per", "quasi {C:attention}qualsiasi azione{} tu faccia"}, unlock = {"Vinci una partita a difficoltà", "{C:attention}Puntata Blu{} usando", "il mazzo {C:attention}Sfida Settimanale{}"}},
            j_kranlaxs_icecreamsandwich = {name = "Sandwich Gelato", text = {"Guadagna {X:money,C:white} $#1# {} alla fine", "del round", "La ricompensa diminuisce di {X:money,C:white} $#2# {}", "dopo ogni round"}, unlock = {"Guadagna {X:money,C:white} $50 {} o più", "come pagamento in", "un singolo round"}},
            j_kranlaxs_dispensermachine = {name = "Distributore Automatico", text = {"Se questo Jolly è {C:attention}selezionato{}", "quando esci dal negozio, spendi {X:money,C:white} $#1# {}", "e crea un {C:attention}Jolly Cibo{}"}, unlock = {"Avere {C:attention}4{} Jolly", "cibo allo stesso tempo"}},
            j_kranlaxs_bottledwater = {name = "Acqua in Bottiglia", text = {"{X:chips,C:white} X#1# {} Fiches", "Perde {X:chips,C:white} X#2# {} per", "ogni carta che fa punteggio"}, unlock = {"Vinci una partita a difficoltà", "{C:attention}Puntata Blu{} usando", "il mazzo {C:attention}Sfida Settimanale{}"}},
            j_kranlaxs_burrow = {name = "Tana", text = {"Ottieni {C:attention}+1{} Coniglietto per", "ogni {C:attention}Buio sconfitto{}", "Quando {C:gold}venduto{}, crea {C:attention}#1#{} Coniglietti"}},
            j_kranlaxs_bunny = {name = "Coniglietto", text = {"Ottieni {X:mult,C:white} X#1# {} Mult per ogni", "Jolly {C:attention}Coniglietto{} che possiedi", "{C:inactive}(Attualmente {X:mult,C:white} X#2# {C:inactive} Mult){}"}},
            j_kranlaxs_sushi = {name = "Sushi", text = {"Riduce il requisito del", "Buio del {C:attention}#1#%{}", "La riduzione diminuisce del {C:attention}#2#%{}", "dopo aver sconfitto un {C:attention}Buio{}"}, unlock = {"Vinci una partita a difficoltà", "{C:attention}Puntata Viola{} usando", "il mazzo {C:attention}Sfida Settimanale{}"}},
            j_kranlaxs_gigachad = {name = "Gigachad", text = {"Ottieni {C:chips}+#2#{} Fiches per quasi", "{C:attention}qualsiasi azione{} tu faccia", "{C:inactive}(Attualmente {C:chips}+#1#{C:inactive} Fiches){}"}, unlock = {"Vinci una partita a difficoltà", "{C:attention}Puntata Bianca{} usando", "il mazzo {C:attention}Sfida Settimanale{}"}},
            j_kranlaxs_nft = {name = "Truffa Cripto", text = {"Riduce il {C:attention}grado{} di tutte", "le carte nella tua mano di {C:attention}1{}", "quando una mano fa punteggio", "{C:inactive}(Non può essere ridotto sotto il 2){}"}},
            j_kranlaxs_beanstalk = {name = "Pianta di Fagioli", text = {"Fagioli inutili"}, unlock = {"Vinci una partita a difficoltà", "{C:attention}Puntata Bianca{} usando", "il mazzo {C:attention}Sfida Settimanale{}"}},
            j_kranlaxs_suspiciousbeanstalk = {name = "Pianta di Fagioli Sospetta", text = {"Fagioli inutili?..."}},
            j_kranlaxs_epicbeanstalk = {name = "Pianta di Fagioli Epica", text = {"Forse non sono fagioli inutili..."}},
            j_kranlaxs_zenithbeanstalk = {name = "Pianta di Fagioli Zenit", text = {"Fagioli"}},
            j_kranlaxs_commonseed = {name = "Seme Comune", text = {"{C:attention}Crea{} un Jolly", "{C:common}Comune{} casuale"}},
            j_kranlaxs_weirdlookingseed = {name = "Seme Strano", text = {"{C:attention}Crea{} un Jolly", "{C:uncommon}Non Comune{} casuale"}},
            j_kranlaxs_magnificentseed = {name = "Seme Magnifico", text = {"{C:attention}Crea{} un Jolly", "{C:rare}Raro{} casuale"}},
            j_kranlaxs_godseed = {name = "Seme Divino", text = {"{C:attention}Crea{} un Jolly", "{C:legendary}Leggendario{} casuale"}},
            j_kranlaxs_anonymousjoker = {name = "Jolly Anonimo", text = {"Quando fa punteggio si gira e dà tra", "{X:mult,C:white} X1.5 {} e {X:mult,C:white} X4.0 {} Mult"}, unlock = {"Sconfiggi il buio boss", "{C:attention}Ghianda d'Ambra{} 1 volta"}},
            j_kranlaxs_littlebro = {name = "Fratellino", text = {"Se la mano giocata è {C:attention}Carta Alta{} e", "la carta che fa punteggio è un {C:attention}#2#{},", "questo Jolly ottiene {X:red,C:white} X#3# {} Mult", "La carta cambia ogni round", "{C:inactive}(Attualmente {X:red,C:white} X#1# {C:inactive} Mult){}"}, unlock = {"Gioca {C:attention}Carta Alta{}", "{C:attention}30{} volte in", "una singola partita"}},
            j_kranlaxs_medusa = {name = "Medusa", text = {"{C:attention}Tutte le carte giocate{}", "diventano permanentemente {C:attention}Carte di Pietra{}", "dopo aver giocato una mano", "{C:inactive}(Anche quelle che non fanno punteggio){}"}, unlock = {"Vinci una partita a {C:attention}Puntata Marrone{}", "usando il {C:attention}Mazzo Spaziale{}"}},
            j_kranlaxs_depression = {name = "Recessione Economica", text = {"Dà {X:dark_edition,C:white}^#2#{} Mult", "Aumenta di {X:dark_edition,C:white}^#1#{} per ogni {X:money,C:white} $1 {}", "al di sotto di {X:money,C:white} $0 {}"}, unlock = {"Entra in un negozio", "con {X:money,C:white} -$25 {} o meno"}},
            j_kranlaxs_grannyjoker = {name = "Nonnina", text = {"Dà {X:dark_edition,C:white} ^3 {} Fiches e {X:dark_edition,C:white} ^3 {} Mult", "La velocità di gioco si blocca a {C:attention}0.25x{}", "{C:inactive}(Si distrugge se giochi una {C:attention}Scala{}", "{C:inactive}o {C:attention}Scala Colore{C:inactive}){}"}, unlock = {"Sconfiggi {C:attention}12{} bui con la", "velocità di gioco a {C:attention}0.5{}"}},
            j_kranlaxs_lateshippment = {name = "Consegna in Ritardo", text = {"Riattiva {C:attention}tutte le carte giocate{}", "{C:attention}1 volta{} per ogni mano giocata", "nel {C:attention}round precedente{}", "{C:inactive}(Attualmente {C:attention}#1#{C:inactive} riattivazioni){}"}, unlock = {"Vinci una partita a {C:attention}Puntata Arancione{}", "usando il {C:attention}Mazzo Spaziale{}"}},
            j_kranlaxs_unkownfactor = {name = "Variabile X", text = {"Tutte le carte giocate sono", "considerate come {C:attention}#1#{}", "{C:inactive}(Il grado cambia alla fine del round){}"}, unlock = {"Vinci una partita a difficoltà", "{C:attention}Puntata Oro{} usando", "il mazzo {C:attention}Sfida Settimanale{}"}},
            j_kranlaxs_thethreers = {name = "Le 3 R", text = {"Crea una {C:attention}copia{} di ogni carta giocata", "e la aggiunge al tuo {C:attention}mazzo{}", "{C:attention}Distrugge{} tutte le carte che fanno punteggio"}, unlock = {"Vinci una partita a difficoltà", "{C:attention}Puntata Oro{} usando", "il mazzo {C:attention}Sfida Settimanale{}"}},
            j_kranlaxs_the = {name = "Jok", text = {"Dà {X:chips,C:white} X2 {} Fiches e {X:mult,C:white} X2 {} Mult", "solo nella {C:attention}prima mano{} del round"}, unlock = {"Sconfiggi {C:attention}5{} bui usando", "solo {C:attention}1{} mano ciascuno"}},
            j_kranlaxs_chainreaction = {name = "Reazione a Catena", text = {"Se la mano giocata è {C:attention}#2#{},", "ottiene {X:chips,C:white} X0.5 {} Fiches e la mano cambia", "Si azzera se la mano {C:attention}non corrisponde{}", "{C:inactive}(Attualmente {X:chips,C:white} X#1# {C:inactive} Fiches){}"}, unlock = {"Gioca tutte le mani di poker", "almeno {C:attention}1{} volta in una partita"}},
            j_kranlaxs_anubis = {name = "Anubi", text = {"Bilancia le {C:blue}Fiches{} e il {C:red}Mult{}", "quando una mano fa punteggio"}, unlock = {"Vinci una partita con il {C:attention}Mazzo Plasma{}", "in ciascuna delle difficoltà"}},
            j_kranlaxs_erraticjoker = {name = "Jolly Erratico", text = {"Se la carta che fa punteggio è una", "{C:attention}Carta Jolly{} (Wild), scambia le", "{C:blue}Fiches{} e il {C:red}Mult{}"}, unlock = {"Vinci una partita a {C:attention}Puntata Bianca{}", "usando il {C:attention}Mazzo Spaziale{}"}},
            j_kranlaxs_luckyseven = {name = "I 7 Fortunati", text = {"Se la mano giocata è esattamente", "un {C:attention}Tris{} di soli {C:attention}7{}, questo Jolly", "ottiene {C:blue}+7{} Fiches, {C:red}+7{} Mult e dà {X:money,C:white} $7 {}", "{C:inactive}(Attualmente {C:blue}+#1#{} Fiches, {C:red}+#2#{} Mult)"}, unlock = {"Avere almeno {C:attention}10{} carte", "di grado {C:attention}7{} nel tuo mazzo"}},
            j_kranlaxs_certificateddocument = {name = "Documento Certificato", text = {"Riattiva {C:attention}tutti{} i sigilli"}, unlock = {"Vinci una partita a difficoltà", "{C:attention}Puntata Viola{} usando", "il mazzo {C:attention}Sfida Settimanale{}"}},
            j_kranlaxs_platanito = {name = "Bananina", text = {"Ogni volta che un altro Jolly si attiva,", "dà {X:mult,C:white} X#3# {} Mult extra", "{C:green}#1# su #2#{} probabilità di", "essere distrutto alla fine del round"}, unlock = {"Vinci una partita a {C:attention}Puntata Platino{}", "usando il {C:attention}Mazzo Spaziale{}"}},
            j_kranlaxs_cubicaljoker = {name = "Jolly Cubico", text = {"Dà {C:mult}+#1#{} Mult", "Il valore viene elevato al", "{C:attention}Cubo (^3){} per ogni", "{C:attention}Buio Boss{} sconfitto"}},
            j_kranlaxs_grapesoda = {name = "Soda all'Uva", text = {"Quando viene {C:gold}venduto{}, crea una carta", "{C:spectral}Spettrale{} casuale", "con edizione {C:dark_edition}Negativa{}"}, unlock = {"Vinci una partita a {C:attention}Puntata Magenta{}", "usando il {C:attention}Mazzo Spaziale{}"}},
            j_kranlaxs_telescope = {name = "Telescopio", text = {"Se {C:attention}#1#{} sale di livello, fai salire di livello", "quella mano {C:attention}1{} volta aggiuntiva", "{C:inactive}(La mano cambia alla fine del round){}"}, unlock = {"Vinci una partita a difficoltà", "{C:attention}Puntata Rossa{} usando", "il mazzo {C:attention}Sfida Settimanale{}"}},
            j_kranlaxs_pandorabox = {name = "Vaso di Pandora", text = {"Sconfiggendo un {C:attention}Buio Boss{},", "crea un Jolly {C:attention}utile{} basato", "sul tuo mazzo attuale", "{C:inactive}(Devi avere spazio){}"}},
            j_kranlaxs_doppelganger = {name = "Doppelgänger", text = {"Copia l'abilità di un {C:attention}Jolly{}", "casuale di tutto il gioco.", "Il Jolly copiato cambia dopo", "aver sconfitto un {C:attention}Buio{}.", "{C:inactive}(Attualmente: {C:attention}#1#{C:inactive})"}, unlock = {"Vinci una partita a difficoltà", "{C:attention}Puntata Oro{} usando", "il mazzo {C:attention}Sfida Settimanale{}"}},
            j_kranlaxs_thechampion = {name = "Il Campione", text = {"Requisito del buio {C:attention}X#1#{}", "Guadagni {X:money,C:white} $#2# {} alla fine del round"}, unlock = {"Raggiungi l'{C:attention}Ante 16{}"}},
            j_kranlaxs_clerigo = {name = "Chierico", text = {"Dà {C:mult}+#1#{} Mult per ogni", "carta nel tuo mazzo completo", "Perde {C:mult}-#2#{} Mult per ogni carta", "con qualche miglioramento o sigillo", "{C:inactive}(Attualmente {C:mult}+#3#{C:inactive} Mult){}"}, unlock = {"Completa la sfida:", "{C:attention}Ricetta di Famiglia{}"}},
            j_kranlaxs_entrenador = {name = "Allenatore", text = {"Dà {X:mult,C:white} X#1# {} Mult se sei", "sotto l'Ante {C:attention}#3#{}", "Altrimenti, dà {X:mult,C:white} X#2# {} Mult", "{C:inactive}(Attualmente {X:mult,C:white} X#4# {C:inactive} Mult){}"}, unlock = {"Completa la sfida:", "{C:attention}Crisi Economica{}"}},
            j_kranlaxs_medium = {name = "Medium", text = {"Dà {C:mult}+#1#{} Mult per ogni", "partita {C:red}persa{} nel tuo profilo", "{C:inactive}(Attualmente {C:mult}+#2#{C:inactive} Mult){}"}, unlock = {"Perdi {C:attention}1{} partita", "{C:inactive}(Progresso: {C:attention}#1#{C:inactive} / 1){}"}},
            j_kranlaxs_monk = {name = "Monaco", text = {"Ottiene {X:chips,C:white} X#1# {} Fiches se esci", "dal negozio senza spendere {X:money,C:white} denaro {}", "Si {C:red}azzera{} se compri qualcosa", "{C:inactive}(Attualmente {X:chips,C:white} X#2# {C:inactive} Fiches){}"}, unlock = {"Completa la sfida:", "{C:attention}Voto di Povertà{}"}},
            j_kranlaxs_knight = {name = "Cavaliere", text = {"Dopo aver fatto punteggio con {C:attention}#1#{} carte d'{C:attention}Acciaio{},", "{C:attention}Disabiliterà{} il prossimo {C:attention}Buio Boss{}", "{C:inactive}(Carte andate a segno: #2#/#1#){}"}, unlock = {"Completa la sfida:", "{C:attention}Sindacato dei Boss{}"}},
            j_kranlaxs_overpopulation = {name = "Sovrappopolazione", text = {"Dà {C:mult}+#1#{} Mult per ogni", "{C:attention}figura{} sopra", "il limite di {C:attention}#2#{}", "nel tuo mazzo", "{C:inactive}(Attualmente {C:mult}+#3#{C:inactive} Mult){}"}, unlock = {"Vinci una partita a {C:attention}Puntata Verde{}", "usando il {C:attention}Mazzo Spaziale{}"}},
            j_kranlaxs_antisocial = {name = "Antisociale", text = {"Questo Jolly ottiene {C:mult}+#1#{} Mult", "se giochi esattamente {C:attention}1{} carta", "Si {C:red}azzera{} se ne giochi più di 1", "{C:inactive}(Attualmente {C:mult}+#2#{C:inactive} Mult){}"}, unlock = {"Completa la sfida:", "{C:attention}Fissazione Totale{}"}},
            j_kranlaxs_famous = {name = "Famoso", text = {"Dà {C:chips}+#1#{} Fiches se la", "mano giocata è un {C:attention}Pokerissimo{},", "{C:attention}Colore a Cinque{} o {C:attention}Full a Colore{}"}},
            j_kranlaxs_influencer = {name = "Influencer", text = {"Dà {C:mult}+#1#{} Mult se la", "mano giocata è un {C:attention}Pokerissimo{},", "{C:attention}Colore a Cinque{} o {C:attention}Full a Colore{}"}},
            j_kranlaxs_potatobag = {name = "Sacco di Patate", text = {"Accumula le Fiches che fanno punteggio", "Al raggiungimento di {C:attention}#1#{}, applica", "{X:mult,C:white} X#2# {} Mult alla", "mano successiva e si svuota", "{C:inactive}(Accumulato: #3#/#1#){}"}},
            j_kranlaxs_simonsays = {name = "Simon Dice", text = {"Questo Jolly ottiene {X:mult,C:white} X#2# {} Mult", "completando la sua richiesta", "Simon dice... {C:attention}#3#{}", "{C:inactive}(Attualmente {X:mult,C:white} X#1# {C:inactive} Mult){}"}, unlock = {"Completa la sfida:", "{C:attention}La Grande Pianta di Fagioli{}"}},
            j_kranlaxs_cheater = {name = "Imbroglione", text = {"I Jolly nel negozio", "hanno una probabilità del {C:green}35%{}", "di essere rimpiazzati da", "{C:attention}Voucher{} o {C:attention}Pacchetti{}"}, unlock = {"Completa la sfida:", "{C:attention}Gachapon{}"}},
            j_kranlaxs_philosopher = {name = "Filosofo", text = {"Rivela le prossime {C:attention}5 carte{}", "del tuo mazzo", "{C:inactive}(Ogni carta ha il 20%{}", "{C:inactive}di probabilità di nascondersi){}", "{C:attention}#1#{}"}, unlock = {"Completa la sfida:", "{C:attention}Premonizioni{}"}},
            j_kranlaxs_mandalajoker = {name = "Jolly Mandala", text = {"Questo Jolly ottiene {X:mult,C:white} X0.5 {} Mult", "per ogni carta {C:spectral}Spettrale{} usata", "{C:inactive}(Attualmente {X:mult,C:white} X#1# {C:inactive} Mult){}"}, unlock = {"Usa {C:attention}20{} carte {C:spectral}Spettrali{}", "{C:inactive}(Progresso: {C:attention}#1#{C:inactive} / 20){}"}},
            j_kranlaxs_regift = {name = "Jolly Riciclato", text = {"Quando viene {C:gold}venduto{}, crea un", "{C:attention}Jolly casuale{}", "La rarità dipende dal {C:attention}Buio{} attuale"}, unlock = {"Vendi {C:attention}50{} Jolly", "in totale", "{C:inactive}(Progresso: {C:attention}#1#{C:inactive} / 50){}"}},
            j_kranlaxs_pyromaniac = {name = "Piromane", text = {"Dopo aver fatto punteggio, {C:red}distrugge{}", "tutte le carte {C:attention}numeriche{} nella tua mano", "{C:inactive}(Le carte d'Oro, di Vetro e d'Acciaio sono al sicuro){}"}, unlock = {"Distruggi {C:attention}100{} carte", "che non sono figure", "{C:inactive}(Progresso: {C:attention}#1#{C:inactive} / 100){}"}},
            j_kranlaxs_neverendinggambling = {name = "Gioco d'Azzardo Infinito", text = {"Perdi {X:money,C:white} $1 {} per ogni azione che fai", "{C:inactive}(Solo se hai {X:money,C:white} $5 {} o più){}", "Gira 3 numeri. Se corrispondono, vinci un premio!", "Se ne corrispondono 2, recuperi {X:money,C:white} $1 {} come consolazione", "{C:inactive}(Giro attuale: #1# - #2# - #3#){}"}, unlock = {"Fallisci {C:attention}30{} probabilità di", "Jolly o consumabili", "{C:inactive}(Progresso: {C:attention}#1#{C:inactive} / 30){}"}},
            j_kranlaxs_solarsystem = {name = "Sistema Solare", text = {"Alla {C:attention}fine del round{}, crea una carta", "{C:planet}Pianeta{} in una sequenza fissa", "{C:inactive}(Prossimo pianeta: {C:planet}#1#{C:inactive}){}"}, unlock = {"Usa tutte le {C:attention}12{} carte {C:planet}Pianeta{}", "standard almeno una volta", "in una singola partita", "{C:inactive}(Progresso: {C:attention}#1#{C:inactive} / 12){}"}},
            j_kranlaxs_deranged = {name = "Squilibrato", text = {"Dà {C:mult}+#1#{} Mult o {C:chips}+#2#{} Fiches", "L'effetto cambia ogni volta", "che giochi una mano"}, unlock = {"Completa la sfida:", "{C:attention}Crisi d'Identità{}"}},
            j_kranlaxs_deranged_mult = {name = "Squilibrato", text = {"Dà {C:mult}+#1#{} Mult", "L'effetto cambia ogni volta", "che giochi una mano"}},
            j_kranlaxs_deranged_chips = {name = "Squilibrato", text = {"Dà {C:chips}+#2#{} Fiches", "L'effetto cambia ogni volta", "che giochi una mano"}},
            j_kranlaxs_tmtrainer = {name="TMTRAINER",text={"{C:dark_edition}#1#{}","{C:attention}#2#{}","{C:red}#3#{}","{C:chips}#4#{}"},unlock={"Completa la sfida:","{C:attention}Crisi d'Identità{}"}},
            j_kranlaxs_bingocard = {name = "Cartella del Bingo", text = {"Ottieni {X:mult,C:white} X0.25 {} Mult", "per ogni linea completata", "{C:inactive}(Totale: {X:mult,C:white} X#2# {C:inactive} Mult){}", "{C:attention}#3#{}", "{C:attention}#4#{}", "{C:attention}#5#{}", "{C:attention}#6#{}", "{C:attention}#7#{}"}, unlock = {"Completa la sfida:", "{C:attention}Anonimato Totale{}"}}
        },

        Back = {
            b_kranlaxs_week_challenge = {name = "Sfida Settimanale", text = {"Inizi con un Jolly {C:attention}Sfida Settimanale{}", "{C:red}Superabile{} ogni {C:attention}fine settimana{}"}, unlock = {"Apri il gioco di", "{C:attention}Sabato{} o {C:attention}Domenica{}"}},
            b_kranlaxs_chaos_deck = {name = "Mazzo del Caos", text = {"Goditi il caos"}, unlock = {"Sblocca {C:legendary,E:1}TUTTO{} nella", "tua collezione"}},
            b_kranlaxs_dungeon_deck = {name = "Mazzo Segreta", text = {"Dopo aver sconfitto un {C:attention}Buio Boss{},", "scegli tra 3 {C:attention}opzioni{}", "con {C:green}pro{} e {C:red}contro{}"}, unlock = {"Vinci una partita a {C:attention}Puntata Verde{}", "o superiore usando il", "mazzo {C:attention}Sfida Settimanale{}"}},
            b_kranlaxs_space_deck = {name = "Mazzo Spaziale", text = {"{C:attention}0{} slot per Jolly, {C:attention}5{} per consumabili", "Il negozio vende solo {C:attention}Quarzi{}", "{C:attention}+1{} al negozio, i bui sono {C:attention}7.5%{} più piccoli", "Puntata Vincente: {C:attention}10{}"}, unlock = {"Vinci una partita a {C:attention}Puntata Verde{}", "con il {C:attention}Mazzo Magico{}, il", "{C:attention}Mazzo Nebulosa{} e il {C:attention}Mazzo Zodiaco{}"}},
            b_kranlaxs_bugged_deck = {name = "Mazzo Buggato", text = {"!?"}, unlock = {"Acquisisci un {C:attention}TMTRAINER{}", "per la prima volta"}}
        },

        Stake = {
            stake_kranlaxs_magenta = {name = "Puntata Magenta", text = {"Le carte nel negozio possono", "avere l'adesivo {C:attention}Fissato{}"}},
            stake_kranlaxs_brown = {name = "Puntata Marrone", colour = "Marrone", text = {"{C:attention}-1{} spazio per", "{C:attention}Pacchetti{} nel negozio"}},
            stake_kranlaxs_turquoise = {name = "Puntata Turchese", colour = "Turchese", text = {"I bui hanno una probabilità del {C:attention}50%{}", "di {C:red}non poter essere saltati{}"}},
            stake_kranlaxs_deviled = {name = "Puntata Diabolica", colour = "Diabolica", text = {"{C:attention}-1{} spazio per {C:attention}Jolly{}"}},
            stake_kranlaxs_glass = {name = "Puntata di Vetro", colour = "Vetro", text = {"Il punteggio richiesto scala", "ancora più velocemente per ogni {C:attention}Ante{}"}},
            stake_kranlaxs_platinum = {name = "Puntata di Platino", colour = "Platino", text = {"Devi sconfiggere l'{C:attention}Ante 10{}", "per vincere la partita"}}
        },

        UNOCards = {
            c_kranlaxs_skip = {name = "Salta", text = {"Ottieni {C:attention}all'istante{} il requisito del Buio", "Non funziona sui {C:attention}Bui Boss{}"}},
            c_kranlaxs_stacking = {name = "Impila", text = {"Aggiunge un {C:attention}Sigillo Rosa{} a", "{C:attention}1{} carta selezionata nella tua mano"}},
            c_kranlaxs_draw2 = {name = "Pesca 2", text = {"Quando usata, {C:attention}pesca 2 carte extra{}", "nella tua mano, perdi {C:blue}1{} mano"}},
            c_kranlaxs_draw4 = {name = "Pesca 4", text = {"Quando usata, {C:attention}pesca 4 carte extra{}", "nella tua mano, perdi {C:blue}1{} mano"}},
            c_kranlaxs_reverse = {name = "Inverti", text = {"Restituisce {C:attention}tutte le carte{} dalla tua", "mano al mazzo e le {C:attention}rimescola{}"}},
            c_kranlaxs_wildcard = {name = "Jolly di Colore", text = {"{C:attention}Converte{} ogni carta nella", "tua mano in un {C:attention}seme casuale{}", "in modo {C:attention}indipendente{}"}},
            c_kranlaxs_replay = {name = "Rigioca", text = {"Restituisce le carte della", "tua ultima mano giocata in mano", "{C:inactive}(Si azzera dopo l'uso o", "{C:inactive}alla fine del round)"}},
            c_kranlaxs_discardall = {name = "Scarta Tutto", text = {"Richiede {C:attention}1{} carta selezionata.", "Scarta {C:red}tutte{} le carte", "dalla tua {C:attention}mano{} e dal {C:attention}mazzo{} che", "condividono lo stesso seme"}},
            c_kranlaxs_shield = {name = "Scudo", text = {"Ti protegge passivamente dalla morte o", "puoi venderla per disabilitare il {C:attention}Buio Boss{}"}},
            c_kranlaxs_misery = {name = "Miseria", text = {"Scegli un {C:attention}Seme{}.", "Pescherai carte dal tuo mazzo", "senza sosta finché", "non ne ottieni una di quel seme"}},
            c_kranlaxs_gift = {name = "Regalo", text = {"Concede {C:attention}1{} dei seguenti", "premi casuali:", "• Un {C:attention}Jolly{} con Edizione", "• Un {C:attention}Consumabile{} Negativo", "• Una {C:attention}Carta{} con Miglioramento, Sigillo ed Edizione"}},
            c_kranlaxs_customdraw = {name = "Pesca Personalizzata", text = {"Pesca la stessa quantità di carte", "degli scarti che hai fatto", "{C:inactive}(Attualmente: {C:attention}#1#{C:inactive} carte){}"}}
        },

        InverseTarot = {
            c_kranlaxs_thefool = {name = "Il Matto?", text = {"Crea una carta {C:spectral}Spettrale{} casuale", "{C:attention}Declassa{} una mano di poker casuale"}},
            c_kranlaxs_themagician = {name = "Il Mago?", text = {"Crea {C:attention}2{} carte {C:attention}Fortunate{} casuali"}},
            c_kranlaxs_thehighpriestess = {name = "La Papessa?", text = {"Crea un {C:spectral}Buco Nero{}", "Il tuo {X:money,C:white} denaro {} {C:attention}diminuisce{} del 20%"}},
            c_kranlaxs_theempress = {name = "L'Imperatrice?", text = {"Aggiunge {C:red}+8{} Mult permanente", "fino a {C:attention}2{} carte selezionate"}},
            c_kranlaxs_theemperor = {name = "L'Imperatore?", text = {"Crea {C:attention}2{} {C:attention}Tag{} casuali"}},
            c_kranlaxs_thehierophant = {name = "Il Papa?", text = {"Aggiunge {C:blue}+40{} Fiches permanenti", "fino a {C:attention}2{} carte selezionate"}},
            c_kranlaxs_thelovers = {name = "Gli Amanti?", text = {"Ottieni {C:attention}+1{} dimensione della mano se", "hai una {C:attention}Carta Jolly{} (Wild) nel tuo mazzo"}},
            c_kranlaxs_thechariot = {name = "Il Carro?", text = {"Crea {C:attention}1{} carta d'{C:attention}Acciaio{} casuale", "con un Sigillo {C:attention}Rosso{}"}},
            c_kranlaxs_justice = {name = "La Giustizia?", text = {"Aggiunge {X:red,C:white} X2 {} Mult permanente", "a {C:attention}1{} carta selezionata", "Probabilità di {C:green}#1# su #2#{} di {C:attention}distruggere{} questa carta"}},
            c_kranlaxs_thehermit = {name = "L'Eremita?", text = {"{C:attention}Imposta{} il tuo {X:money,C:white} denaro {} a {X:money,C:white} $25 {} se", "hai {C:attention}meno di{} {X:money,C:white} $25 {}"}},
            c_kranlaxs_thewheeloffortune = {name = "La Ruota della Fortuna?", text = {"Probabilità del {C:green}#1# su #2#{} di creare una {C:attention}copia{}", "di un Jolly casuale con edizione {C:dark_edition}Negativa{}"}},
            c_kranlaxs_strenght = {name = "La Forza?", text = {"{C:attention}Riduce{} il {C:attention}grado{} di", "fino a {C:attention}2{} carte selezionate di {C:attention}1{}"}},
            c_kranlaxs_thehangedman = {name = "L'Appeso?", text = {"Rende completamente {C:attention}casuali{} fino a", "{C:attention}2{} carte selezionate in mano"}},
            c_kranlaxs_death = {name = "La Morte?", text = {"Crea una {C:attention}copia Negativa{} di un Jolly casuale", "Un Jolly casuale riceve un Adesivo {C:attention}Deperibile{}"}},
            c_kranlaxs_temperance = {name = "La Temperanza?", text = {"Vende {C:attention}TUTTI{} i Jolly (inclusi gli Eterni)", "per il {C:money}triplo{} del loro valore di vendita", "{C:inactive}(Non vende i Jolly Fissati){}"}},
            c_kranlaxs_thedevil = {name = "Il Diavolo?", text = {"Aggiunge {X:money,C:white} $2 {} permanenti", "fino a {C:attention}2{} carte selezionate"}},
            c_kranlaxs_thetower = {name = "La Torre?", text = {"{C:attention}Rimuove{} tutti i miglioramenti, sigilli,", "edizioni e bonus dalle carte in mano", "Ottieni {X:money,C:white} $1 {} per ogni modifica rimossa"}},
            c_kranlaxs_thestars = {name = "Le Stelle?", text = {"Aggiunge un {C:attention}Sigillo Bianco{} fino a", "{C:attention}2{} carte selezionate"}},
            c_kranlaxs_themoon = {name = "La Luna?", text = {"Aggiunge un {C:attention}Sigillo Grigio{} fino a", "{C:attention}2{} carte selezionate"}},
            c_kranlaxs_thesun = {name = "Il Sole?", text = {"Aggiunge un {C:attention}Sigillo Arancione{} fino a", "{C:attention}2{} carte selezionate"}},
            c_kranlaxs_judgement = {name = "Il Giudizio?", text = {"{C:attention}Riscatta{} un {C:attention}Voucher{} casuale", "{C:red}-1{} dimensione della mano"}},
            c_kranlaxs_theworld = {name = "Il Mondo?", text = {"Aggiunge un {C:attention}Sigillo Marrone{} fino a", "{C:attention}2{} carte selezionate"}}
        },

        Voucher = {
            v_kranlaxs_more_stock = {name = "Più Scorte", text = {"Il negozio ha {C:attention}1{} spazio", "aggiuntivo per i {C:attention}Pacchetti{}"}},
            v_kranlaxs_even_more_stock = {name = "Ancora Più Scorte", text = {"Il negozio ha {C:attention}1{} spazio", "aggiuntivo per i {C:attention}Voucher{}"}},
            v_kranlaxs_shiny_appearance = {name = "Apparizione Rara", text = {"Le carte leggendarie e i consumabili rari", "possono ora apparire nel negozio"}},
            v_kranlaxs_stickerfever = {name = "Febbre da Adesivi", text = {"Ogni volta che ottieni", "un {C:attention}Tag{}, ottieni", "{C:attention}1{} copia extra"}},
            v_kranlaxs_stickeralbum = {name = "Album di Adesivi", text = {"Ogni volta che ottieni", "un {C:attention}Tag{}, ottieni", "un'ulteriore {C:attention}1{} copia extra"}},
            v_kranlaxs_hotfix = {name = "Hotfix", text = {"{C:attention}Aggiornare{} il negozio", "aggiorna anche i {C:attention}Voucher{}", "e i {C:attention}Pacchetti{}"}},
            v_kranlaxs_version2 = {name = "Versione 2.0", text = {"Saltare i bui ti concede la ricompensa in {X:money,C:white} denaro {}", "di quel buio.", "Requisito dei bui {C:attention}-15%{}"}},
            v_kranlaxs_common_shinys = {name = "Avvistamento Leggendario", text = {"Le carte leggendarie e i consumabili rari", "appariranno con maggiore frequenza"}},
            v_kranlaxs_blessing = {name = "Benedizione", text = {"Inizi con il {C:attention}10%{}", "del requisito di fiches", "completato in ogni buio"}},
            v_kranlaxs_protection = {name = "Protezione Divina", text = {"Ti protegge da un {C:attention}Game Over{}.", "Quando usato, questo voucher viene distrutto", "e può riapparire nel negozio,", "ma al {X:money,C:white} doppio {} del suo prezzo originale"}}
        },

        Quartz = {
            c_kranlaxs_blackquartz = {name = "Ossidiana", text = {"Modifica alcune regole", "a tua scelta"}, unlock = {"Vinci una partita a {C:attention}Puntata Marrone{}", "usando il {C:attention}Mazzo Magico{}"}},
            c_kranlaxs_whitequartz = {name = "Perla", text = {"Crea l'ultimo", "consumabile usato", "{C:inactive}(Ultima carta: {C:attention}#1#{C:inactive}){}"}, unlock = {"Vinci una partita a {C:attention}Puntata Marrone{}", "usando il {C:attention}Mazzo Spettro{}"}},
            c_kranlaxs_pinkquartz = {name = "Quarzo Rosa", text = {"Aggiunge {C:dark_edition}Policromo{} a un {C:attention}Jolly{}", "o a una {C:attention}carta{} selezionata"}, unlock = {"Vinci una partita a {C:attention}Puntata Magenta{}", "o superiore usando il {C:attention}Mazzo Segreta{}"}},
            c_kranlaxs_bluequartz = {name = "Zaffiro", text = {"Aggiunge {C:chips}Foil{} a un", "{C:attention}Jolly{} o {C:attention}carta{} selezionata"}, unlock = {"Vinci una partita a {C:attention}Puntata di Platino{}", "usando il {C:attention}Mazzo Plasma{}"}},
            c_kranlaxs_lilacquartz = {name = "Kunzite", text = {"Aggiunge {C:mult}Olografico{} a un", "{C:attention}Jolly{} o {C:attention}carta{} selezionata"}, unlock = {"Vinci una partita a {C:attention}Puntata Marrone{}", "usando il {C:attention}Mazzo Nebulosa{}"}},
            c_kranlaxs_grayquartz = {name = "Ematite", text = {"Aggiunge {C:dark_edition}Negativo{} a un", "{C:attention}Jolly{} o {C:attention}consumabile{} selezionato"}, unlock = {"Vinci una partita a {C:attention}Puntata Turchese{}", "usando il {C:attention}Mazzo Dipinto{}"}},
            c_kranlaxs_transparentquartz = {name = "Diamante", text = {"{C:attention}Rimuove{} tutti gli adesivi o edizioni", "da un {C:attention}Jolly{}, oppure sigilli o", "edizioni da una {C:attention}carta{} selezionata"}, unlock = {"Vinci una partita a {C:attention}Puntata di Platino{}", "usando il {C:attention}Mazzo Segreta{}"}},
            c_kranlaxs_redquartz = {name = "Rubino", text = {"Finché lo {C:attention}possiedi{},", "dà {X:mult,C:white} X2 {} Mult", "{C:inactive}(Passivo){}"}, unlock = {"Vinci una partita a {C:attention}Puntata Magenta{}", "o superiore usando il {C:attention}Mazzo Rosso{}"}},
            c_kranlaxs_celestequartz = {name = "Larimar", text = {"Finché lo {C:attention}possiedi{},", "dà {X:chips,C:white} X1.5 {} Fiches", "{C:inactive}(Passivo){}"}, unlock = {"Vinci una partita a {C:attention}Puntata Turchese{}", "usando il {C:attention}Mazzo a Scacchi{}"}},
            c_kranlaxs_yellowquartz = {name = "Topazio", text = {"Crea il {C:attention}Jolly{} indicato.", "Il Jolly cambia in modo casuale", "dopo ogni {C:attention}round{}", "{C:inactive}(Bersaglio: {C:attention}#1#{C:inactive}){}"}, unlock = {"Vinci una partita a {C:attention}Puntata Blu{}", "usando il {C:attention}Mazzo Segreta{}"}},
            c_kranlaxs_greenquartz = {name = "Smeraldo", text = {"Finché lo {C:attention}possiedi{}, crea un", "{C:attention}Tag{} dopo aver sconfitto un {C:attention}Buio{}", "Si distrugge dopo aver creato {C:attention}#2#{} tag", "{C:inactive}(Attuali: {C:attention}#1#{C:inactive}){}", "{C:inactive}(Passivo){}"}, unlock = {"Vinci una partita a {C:attention}Puntata Magenta{}", "o superiore usando il {C:attention}Mazzo Verde{}"}},
            c_kranlaxs_brownquartz = {name = "Occhio di Tigre", text = {"Crea la {C:attention}Carta{} indicata.", "La carta cambia casualmente dopo", "aver {C:green}Aggiornato{} il negozio", "{C:inactive}(Bersaglio: {C:attention}#1#{C:inactive}){}"}, unlock = {"Vinci una partita a {C:attention}Puntata Turchese{}", "usando il {C:attention}Mazzo Anaglifo{}"}},
            c_kranlaxs_turquoisequartz = {name = "Turchese", text = {"Finché lo {C:attention}possiedi{}, {C:attention}disabilita{}", "tutti i jolly tranne il primo", "Riattiva quel jolly {C:attention}2{} volte", "{C:inactive}(Passivo){}"}, unlock = {"Vinci una partita a {C:attention}Puntata Turchese{}", "usando il {C:attention}Mazzo Zodiaco{}"}},
            c_kranlaxs_orangequartz = {name = "Citrino", text = {"Aggiunge un {C:green}Sigillo Menta{} a una {C:attention}carta{}", "o un {C:green}Adesivo Trifoglio{} a un", "{C:attention}Jolly{} selezionato"}, unlock = {"Vinci una partita a {C:attention}Puntata Magenta{}", "o superiore usando il {C:attention}Mazzo Giallo{}"}},
            c_kranlaxs_lapislazuli = {name = "Lapislazzuli", text = {"Finché lo {C:attention}possiedi{}, aggiunge", "{C:chips}+#1#{} Fiches alla prima carta che fa punteggio", "L'effetto diminuisce di {C:chips}-#2#{} a ogni uso.", "{C:inactive}(Inattivo quando arriva a 0){}", "{C:inactive}(Passivo){}"}, unlock = {"Vinci una partita a {C:attention}Puntata Magenta{}", "o superiore usando il {C:attention}Mazzo Blu{}"}},
            c_kranlaxs_cinnabar = {name = "Cinabro", text = {"Finché lo {C:attention}possiedi{}, aggiunge", "{C:mult}+#1#{} Mult alla prima carta che fa punteggio", "L'effetto diminuisce di {C:mult}-#2#{} a ogni uso.", "{C:inactive}(Inattivo quando arriva a 0){}", "{C:inactive}(Passivo){}"}, unlock = {"Vinci una partita a {C:attention}Puntata Marrone{}", "usando il {C:attention}Mazzo Abbandonato{}"}},
            c_kranlaxs_graphite = {name = "Grafite", text = {"Finché lo {C:attention}possiedi{}, probabilità di {C:green}#1# su #2#{}", "di creare una copia nella tua", "mano di tutte le carte giocate.", "La prob. scende all'attivazione.", "{C:inactive}(Inattivo quando arriva a 0){}", "{C:inactive}(Passivo){}"}, unlock = {"Vinci una partita a {C:attention}Puntata Magenta{}", "o superiore usando il {C:attention}Mazzo Nero{}"}},
            c_kranlaxs_uranium = {name = "Uranio", text = {"Finché lo {C:attention}possiedi{}, applica 1 effetto", "casuale a round. Può essere", "molto buono o molto distruttivo.", "{C:dark_edition}Stato attuale:{}", "{C:red,E:2}#1#{}", "{C:inactive}(Osi portarlo con te?){}", "{C:inactive}(Passivo){}"}, unlock = {"Vinci una partita a {C:attention}Puntata di Platino{}", "usando il {C:attention}Mazzo Erratico{}"}}
        },

        Tag = {
            tag_kranlaxs_mega_invtarot = {name = "Mega Tag Inverso", text = {"Concede un {C:attention}Mega Pacchetto Tarocchi Inversi{}", "gratis all'istante"}},
            tag_kranlaxs_mega_uno = {name = "Tag UNO Jumbo", text = {"Concede un {C:attention}Pacchetto UNO Jumbo{}", "gratis all'istante"}},
            tag_kranlaxs_mega_invtarot_store = {name = "Mega Tag Inverso Salvato", text = {"Concede un {C:attention}Mega Tarocco Inverso Salvato{}", "gratis all'istante"}},
            tag_kranlaxs_quartz_tag = {name = "Tag di Quarzo", text = {"Crea un {C:attention}Quarzo{} casuale", "{C:inactive}(Devi avere spazio){}"}},
            tag_kranlaxs_sticker_remover = {name = "Tag Purgante", text = {"Rimuove un adesivo {C:attention}Eterno{},", "{C:attention}Deperibile{} o a {C:attention}Noleggio{} da", "un {C:attention}Jolly{} casuale", "{C:inactive}(Dà {X:money,C:white} $5 {C:inactive} se non ci sono adesivi){}"}},
            tag_kranlaxs_legendary = {name = "Tag Leggendario", text = {"Il negozio ha un", "{C:legendary}Jolly Leggendario{} gratis"}}
        },

        Edition = {
            e_kranlaxs_wave = {name = "Acquatico", text = {"{X:chips,C:white} X#1# {} Fiches"}}
        },

        Other = {
            kranlaxs_magenta_sticker = {name = "Adesivo Magenta", text = {"Hai usato questo Jolly", "per vincere a {C:attention}Puntata Magenta{}"}},
            kranlaxs_brown_sticker = {name = "Adesivo Marrone", text = {"Hai usato questo Jolly", "per vincere a {C:attention}Puntata Marrone{}"}},
            kranlaxs_turquoise_sticker = {name = "Adesivo Turchese", text = {"Hai usato questo Jolly", "per vincere a {C:attention}Puntata Turchese{}"}},
            kranlaxs_platinum_sticker = {name = "Adesivo di Platino", text = {"Hai usato questo Jolly", "per vincere a {C:attention}Puntata di Platino{}"}},
            kranlaxs_deviled_sticker = {name = "Adesivo Diabolico", text = {"Hai usato questo Jolly", "per vincere a {C:attention}Puntata Diabolica{}"}},
            kranlaxs_glass_sticker = {name = "Adesivo di Vetro", text = {"Hai usato questo Jolly", "per vincere a {C:attention}Puntata di Vetro{}"}},
            kranlaxs_orangeseal_seal = {name = "Sigillo Arancione", text = {"Se fa punteggio in mano: {C:attention}#1#{},", "crea 1 {C:attention}#2#{}", "{C:inactive}Cambia dopo l'uso.{}", "{C:inactive}(Devi avere spazio){}"}},
            kranlaxs_pinkseal_seal = {name = "Sigillo Rosa", text = {"Applica {X:dark_edition,C:white}^1.75{} Mult", "quando {C:attention}fa punteggio{}"}},
            kranlaxs_whiteseal_seal = {name = "Sigillo Bianco", text = {"{C:attention}Fa sempre punteggio{}, immune", "all'essere {C:red}depotenziata{}, {C:red}distrutta{}", "o {C:attention}girata{}"}},
            kranlaxs_brownseal_seal = {name = "Sigillo Marrone", text = {"Probabilità del {C:green}#1# su #2#{} di", "{C:attention}duplicare{} questa carta", "mentre è in mano"}},
            kranlaxs_grayseal_seal = {name = "Sigillo Grigio", text = {"Quando {C:attention}fa punteggio{}, cambia in modo {C:attention}casuale{}", "il {C:enhanced}Miglioramento{} di questa carta"}},
            kranlaxs_mintseal_seal = {name = "Sigillo Menta", text = {"Raddoppia tutte le {C:attention}probabilità indicate{}", "su questa carta"}},
            p_kranlaxs_uno_store_3 = {name = "Pacchetto UNO", text = {"Scegli {C:attention}1{} di un massimo di", "{C:attention}3{} carte {C:blue}UNO{}"}},
            p_kranlaxs_uno_store_5 = {name = "Pacchetto UNO Jumbo", text = {"Scegli {C:attention}1{} di un massimo di", "{C:attention}5{} carte {C:blue}UNO{}"}},
            p_kranlaxs_invtarot_instant_3_1 = {name = "Pacchetto Tarocchi Inversi", text = {"Scegli {C:attention}1{} di un massimo di", "{C:attention}3{} carte {C:purple}Tarocco Inverso{}"}},
            p_kranlaxs_invtarot_instant_5_1 = {name = "Pacchetto Tarocchi Inversi Jumbo", text = {"Scegli {C:attention}1{} di un massimo di", "{C:attention}5{} carte {C:purple}Tarocco Inverso{}"}},
            p_kranlaxs_invtarot_instant_5_2 = {name = "Mega Pacchetto Tarocchi Inversi", text = {"Scegli {C:attention}2{} di un massimo di", "{C:attention}5{} carte {C:purple}Tarocco Inverso{}"}},
            p_kranlaxs_invtarot_store_3_1 = {name = "Tarocco Inverso Salvato", text = {"Scegli {C:attention}1{} di un massimo di", "{C:attention}3{} carte {C:purple}Tarocco Inverso{}"}},
            p_kranlaxs_invtarot_store_5_1 = {name = "Tarocco Inverso Salvato Jumbo", text = {"Scegli {C:attention}1{} di un massimo di", "{C:attention}5{} carte {C:purple}Tarocco Inverso{}"}},
            p_kranlaxs_invtarot_store_5_2 = {name = "Mega Tarocco Inverso Salvato", text = {"Scegli {C:attention}2{} di un massimo di", "{C:attention}5{} carte {C:purple}Tarocco Inverso{}"}}
        },

        Booster = {
            p_kranlaxs_uno_store_3 = {name = "Pacchetto UNO", text = {"Scegli {C:attention}1{} di un massimo di", "{C:attention}3{} carte {C:blue}UNO{}"}},
            p_kranlaxs_uno_store_5 = {name = "Pacchetto UNO Jumbo", text = {"Scegli {C:attention}1{} di un massimo di", "{C:attention}5{} carte {C:blue}UNO{}"}},
            p_kranlaxs_invtarot_instant_3_1 = {name = "Pacchetto Tarocchi Inversi", text = {"Scegli {C:attention}1{} di un massimo di", "{C:attention}3{} carte {C:purple}Tarocco Inverso{}"}},
            p_kranlaxs_invtarot_instant_5_1 = {name = "Pacchetto Tarocchi Inversi Jumbo", text = {"Scegli {C:attention}1{} di un massimo di", "{C:attention}5{} carte {C:purple}Tarocco Inverso{}"}},
            p_kranlaxs_invtarot_instant_5_2 = {name = "Mega Pacchetto Tarocchi Inversi", text = {"Scegli {C:attention}2{} di un massimo di", "{C:attention}5{} carte {C:purple}Tarocco Inverso{}"}},
            p_kranlaxs_invtarot_store_3_1 = {name = "Tarocco Inverso Salvato", text = {"Scegli {C:attention}1{} di un massimo di", "{C:attention}3{} carte {C:purple}Tarocco Inverso{}"}},
            p_kranlaxs_invtarot_store_5_1 = {name = "Tarocco Inverso Salvato Jumbo", text = {"Scegli {C:attention}1{} di un massimo di", "{C:attention}5{} carte {C:purple}Tarocco Inverso{}"}},
            p_kranlaxs_invtarot_store_5_2 = {name = "Mega Tarocco Inverso Salvato", text = {"Scegli {C:attention}2{} di un massimo di", "{C:attention}5{} carte {C:purple}Tarocco Inverso{}"}}
        }
    },
    
    misc = {
        labels = {
            kranlaxs_magenta_sticker = "Adesivo Magenta",
            kranlaxs_brown_sticker = "Adesivo Marrone",
            kranlaxs_turquoise_sticker = "Adesivo Turchese",
            kranlaxs_platinum_sticker = "Adesivo di Platino",
            kranlaxs_orangeseal_seal = "Sigillo Arancione", 
            kranlaxs_pinkseal_seal = "Sigillo Rosa", 
            kranlaxs_whiteseal_seal = "Sigillo Bianco", 
            kranlaxs_brownseal_seal = "Sigillo Marrone", 
            kranlaxs_grayseal_seal = "Sigillo Grigio", 
            kranlaxs_mintseal_seal = "Sigillo Menta", 
            clover = "Adesivo Trifoglio",
            kranlaxs_deviled_sticker = "Adesivo Diabolico",
            kranlaxs_glass_sticker = "Adesivo di Vetro",
            p_kranlaxs_uno_store_3 = "Pacchetto UNO",
            p_kranlaxs_uno_store_5 = "Pacchetto UNO Jumbo",
            p_kranlaxs_invtarot_instant_3_1 = "Pacchetto Tarocchi Inversi",
            p_kranlaxs_invtarot_instant_5_1 = "Pacchetto Tarocchi Inversi Jumbo",
            p_kranlaxs_invtarot_instant_5_2 = "Mega Pacchetto Tarocchi Inversi",
            p_kranlaxs_invtarot_store_3_1 = "Tarocco Inverso Salvato",
            p_kranlaxs_invtarot_store_5_1 = "Tarocco Inverso Salvato Jumbo",
            p_kranlaxs_invtarot_store_5_2 = "Mega Tarocco Inverso Salvato",
            kranlaxs_wave = "Acquatico"
        },

        v_text = {
            ch_c_kran_fijado_1 = {"Tutti i Jolly hanno l'adesivo {C:attention}Fissato{}"},
            ch_c_kran_abuela_1 = {"I Jolly di {C:attention}punteggio{} sono {C:red}banditi{}"},
            ch_c_kran_crisis_1 = {"Il negozio è {C:attention}più caro del 20%{}"},
            ch_c_kran_crisis_2 = {"Il premio base dei bui è {C:red}ridotto{} di {X:money,C:white} $2 {}"},
            ch_c_kran_crisis_3 = {"Il mazzo è composto unicamente da {C:attention}52 Assi{}"},
            ch_c_kran_doppel_1 = {"Tutti i Jolly sono {C:red}banditi{} dal negozio"},
            ch_c_kran_anonimo_1 = {"Le carte in mano e i Jolly sono a {C:attention}faccia in giù{}"},
            ch_c_kran_jefes_1 = {"I Bui Piccoli e Grandi sono {C:attention}Bui Boss{}"},
            ch_c_kran_premon_1 = {"Tutte le carte nella tua mano sono a {C:attention}faccia in giù{}"},
            ch_c_kran_tallo_1 = {"Gli altri {C:attention}Jolly{} e {C:attention}Pacchetti{} sono {C:red}banditi{}"},
            ch_c_gacha_rule_1 = {"Nessuna {C:attention}carta singola{} compare nel negozio"},
            ch_c_kran_pobreza_1 = {"{C:attention}50%{} di probabilità che un {C:common}Comune{} sia {C:legendary}Leggendario{}"},
            ch_c_kran_pobreza_2 = {"Se il tuo Jolly {C:attention}Monaco{} si delude, {C:red}perdi la partita{}"}
        }
    }
}