return {
    descriptions = {
        Joker = {
            j_kranlaxs_tagger = {name = "タガー", text = {"獲得した{C:attention}タグ{}ごとに", "{C:red}+#1#{} マルチを獲得", "{C:inactive}(現在 {C:red}+#2#{C:inactive} マルチ){}"}, unlock = {"1回のランで{C:attention}空のバウチャー{}を", "{C:attention}2{}回購入する"}},
            j_kranlaxs_Cashback = {name = "キャッシュバック", text = {"カード購入時、{C:green}#1# / #2#{}の確率で", "{X:money,C:white} $3 {} を獲得する"}, unlock = {"{C:attention}スペースデッキ{}を使用して", "{C:attention}レッドステーク{}で勝利する"}},
            j_kranlaxs_underratedjoker = {name = "過小評価されたジョーカー", text = {"プレイした役が最もプレイした役で{C:attention}ない{}場合、", "このジョーカーは{X:chips,C:white} X0.2 {} チップを獲得", "{C:inactive}(最もプレイした役ならリセット){}", "{C:inactive}(現在 {X:chips,C:white} X#1# {C:inactive} チップ){}"}, unlock = {"{C:attention}スペースデッキ{}を使用して", "{C:attention}ブルーステーク{}で勝利する"}},
            j_kranlaxs_facelessaccountant = {name = "顔のない会計士", text = {"スコアに加算された{C:attention}#2#{}ごとに", "このジョーカーは{X:blue,C:white} X0.1 {} チップを獲得", "{C:inactive}(現在 {X:blue,C:white} X#1# {C:inactive} チップ){}"}, unlock = {"デッキに{C:attention}1{}枚以上絵札がある状態で、", "絵札を一度もプレイせずに勝利する"}},
            j_kranlaxs_thefixer = {name = "フィクサー", text = {"{C:purple}ブラインド{}中に{C:attention}ジョーカー{}を売却すると", "必要なスコアが減少する", "{C:inactive}(コモン: -10%, アンコモン: -30%){}", "{C:inactive}(レア: -60%, レジェンダリー: -95%){}"}, unlock = {"各レアリティのジョーカーを", "少なくとも{C:attention}2{}枚売却する"}},
            j_kranlaxs_mysteriousgeode = {name = "神秘的な晶洞", text = {"スコアに加算された{C:attention}ワイルドカード{}ごとに", "{C:attention}ランダム{}な効果を与える"}, unlock = {"{C:attention}5{}枚のワイルドカードを", "含むハンドをプレイする"}},
            j_kranlaxs_benchwarmer = {name = "ベンチウォーマー", text = {"手札にある最もランクの高いカードの", "{C:blue}チップ{}の{C:attention}4倍{}を与える"}},
            j_kranlaxs_entropy2 = {name = "渦", text = {"デッキ内の{C:attention}52未満{}のカードごとに", "{X:dark_edition,C:white} ^1 {} マルチと {X:dark_edition,C:white} ^1 {} チップを獲得", "{C:inactive}(現在 {X:dark_edition,C:white} ^#1# {C:inactive} マルチと {X:dark_edition,C:white} ^#1# {C:inactive} チップ){}"}},
            j_kranlaxs_greedyleprachaun = {name = "強欲なレプラコーン", text = {"ラウンドの最初の{C:red}ディスカード{}時、", "{C:attention}追加で3枚のカード{}を引く"}, unlock = {"正確に{C:attention}1{}枚のカードを", "{C:attention}3{}回連続でディスカードする"}},
            j_kranlaxs_charismaticbard = {name = "カリスマ的な吟遊詩人", text = {"ハンドサイズ {C:attention}-1{}", "{C:attention}最もプレイした役{}をプレイするたび、", "{C:purple}ブラインド{}のスコアを{C:attention}2%{}減少", "{C:inactive}(最大90%){}", "別の役をプレイするとリセット", "{C:inactive}(現在 {C:attention}-#1#%{C:inactive} ブラインド減少){}"}},
            j_kranlaxs_russianroulette = {name = "ロシアンルーレット", text = {"ブラインド選択時、", "{C:green}#1# / #2#{}の確率で{C:red}ゲームオーバー{}", "生き残った場合、", "{X:mult,C:white} X3 {} マルチと {X:chips,C:white} X3 {} チップを獲得", "{C:inactive}(現在 {X:mult,C:white} X#3# {C:inactive} マルチと {X:chips,C:white} X#3# {C:inactive} チップ){}"}, unlock = {"{C:attention}スペースデッキ{}を使用して", "{C:attention}ブラックステーク{}で勝利する"}},
            j_kranlaxs_fidelitycard = {name = "バトルパス", text = {"{C:attention}6{}枚のカードを購入した後、{C:attention}7枚目{}の購入で", "すべての所有ジョーカーの{C:attention}売値{}に", "等しい{X:money,C:white} お金 {}を獲得する", "{C:inactive}(現在 {C:attention}#1#/6{C:inactive} 枚){}", "{C:inactive}(合計売値: {X:money,C:white} $#2# {C:inactive}){}"}},
            j_kranlaxs_devioussheep = {name = "大食いの羊", text = {"{C:attention}ブラインド{}選択時、ランダムなジョーカーを", "{C:red}貪り食い{}、{X:mult,C:white} X0.4 {} マルチを獲得", "他のジョーカーがない場合は{C:hearts}ゲームオーバー{}", "{C:inactive}(特定のターゲットを優先してマルチを稼ごう！){}", "{C:inactive}(現在 {X:mult,C:white} X#1# {C:inactive} マルチ){}"}},
            j_kranlaxs_lifeassurance = {name = "生命保険", text = {"{X:money,C:white} $#1# {}以上持っている場合、", "ゲームオーバーを防ぐ", "{C:inactive}(価格は使用するたびに倍になる){}"}, unlock = {"{C:attention}アンティ 8{}の前に", "{X:money,C:white} $100 {}以上持った状態で", "敗北する"}},
            j_kranlaxs_sundaycheckpoint = {name = "チェックポイント", text = {"{C:attention}平日{}にブラインドを", "選択すると{C:red}ゲームオーバー{}", "それ以外の場合、ラウンド終了時に", "{C:attention}ウィークリーチャレンジ{}ジョーカーを生成し、{C:red}自壊する{}", "{C:inactive}(現在の日: #1#){}"}},
            j_kranlaxs_weeklychallenge = {name = "ウィークリーチャレンジ", text = {"このランにランダムなチャレンジを設定する", "{C:clubs}現在のチャレンジ:{} {C:attention}#1#{}", "{C:inactive}1:{} {X:money,C:white} -$100 {} から開始、アンティ 8 までに支払う", "{C:inactive}2:{} ショップ制限", "{C:inactive}3:{} 1ハンド、20ディスカード (追加バウチャーなし)", "{C:inactive}4:{} ラン全体で{C:blue}#2#{}ハンドと{C:red}#3#{}ディスカードの制限", "{C:inactive}5:{} ゲームスピードが0.5xに固定", "{C:inactive}6:{} 3枚の永遠トリブレット (最大ジョーカー3、高速アンティ)", "{C:inactive}7:{} ブラインド撃破時、1/6の確率で勝利 (アンティ 8 で敗北)"}},
            j_kranlaxs_panda = {name = "ふわふわパンダ", text = {"{C:chips}+#1#{} チップ", "ジョーカースロット {C:attention}-1{}"}},
            j_kranlaxs_miner = {name = "鉱夫", text = {"スコアに加算された{C:attention}石のカード{}ごとに", "{C:red}+5{} マルチを獲得", "ハンドプレイ時、{C:green}#2# / #3#{}の確率で", "{X:money,C:white} $#4# {} から {X:money,C:white} $#5# {} を獲得", "{C:inactive}(現在 {C:red}+#1#{C:inactive} マルチ){}"}, unlock = {"{C:attention}5{}枚の石のカードを", "含むハンドをプレイする"}},
            j_kranlaxs_birthdaycake = {name = "バースデーケーキ", text = {"{X:dark_edition,C:white} ^#1# {} マルチを与える", "ハンドをプレイするたび", "{X:dark_edition,C:white} ^0.25 {} 失う", "尽きると{C:attention}リギフトジョーカー{}を生成"}, unlock = {"{C:attention}ウィークリーチャレンジ{}デッキを使用して", "{C:attention}ブルーステーク{}で勝利する"}},
            j_kranlaxs_vipsuscription = {name = "V.I.P. サブスクリプション", text = {"ショップスロット {C:attention}+#2#{}", "バウチャーとパック {C:attention}+1{}", "ショップを開くと {X:money,C:white} $#1# {} 減る", "{C:attention}ボスブラインド{}を倒すと", "価格とショップサイズが{C:attention}増加する{}"}, unlock = {"{C:attention}ウィークリーチャレンジ{}デッキを使用して", "{C:attention}オレンジステーク{}で勝利する"}},
            j_kranlaxs_painterjoker = {name = "画家ジョーカー", text = {"ハンドでスコアを得たとき、", "手札の{C:attention}ワイルドカード{}ごとに", "{C:attention}ジャグラータグ{}を生成する", "{C:inactive}(タグ1つにつき {X:money,C:white} $#1# {C:inactive} かかる){}"}, unlock = {"{C:attention}ウィークリーチャレンジ{}デッキを使用して", "{C:attention}オレンジステーク{}で勝利する"}},
            j_kranlaxs_coronation = {name = "戴冠式", text = {"プレイしたハンドにスコア加算された", "ランク{C:attention}10以下{}のカードが含まれる場合、", "最も低いものを{C:attention}キング{}に変換する。", "手札に低いカードがない場合、スコア加算された", "最初の{C:attention}キング{}に{C:red}レッドシール{}を追加する。"}, unlock = {"正確に{C:attention}5枚のキング{}のハンドを", "プレイする。すべて{C:attention}スチール{}カードで", "{C:red}レッドシール{}を持っている必要がある"}},
            j_kranlaxs_speedrunner = {name = "スピードランナー", text = {"{X:mult,C:white} X#1# {} マルチ", "ハンドのプレイまたはディスカードに", "{C:attention}#2#秒{}の制限時間がある", "時間切れになると{C:red}ゲームオーバー{}。"}, unlock = {"{C:attention}ウィークリーチャレンジ{}デッキを使用して", "{C:attention}グリーンステーク{}で勝利する"}},
            j_kranlaxs_passcode = {name = "パスコード", text = {"プレイしたハンドが以下のコードの", "いずれかと一致した場合、そのハンドは", "{C:attention}フラッシュファイブ{}として扱われる", "{C:inactive}1. {C:attention}#1#{}", "{C:inactive}2. {C:attention}#2#{}", "{C:inactive}3. {C:attention}#3#{}"}, unlock = {"{C:attention}ウィークリーチャレンジ{}デッキを使用して", "{C:attention}ブラックステーク{}で勝利する"}},
            j_kranlaxs_chronometer = {name = "クロノメーター", text = {"ハンドをプレイしたとき: ", "現在の{C:attention}秒{}に等しい{C:chips}チップ{}を与える", "現在の{C:attention}分{}に等しい{C:mult}マルチ{}を与える", "現在の{C:attention}時間{}に等しい{C:money}お金{}を獲得する", "{C:inactive}(現在: {C:chips}+#1#{C:inactive} チップ, {C:mult}+#2#{C:inactive} マルチ, {C:money}+$#3#{C:inactive}){}"}, unlock = {"{C:attention}スペースデッキ{}を使用して", "{C:attention}ゴールドステーク{}で勝利する"}},
            j_kranlaxs_zombiejoker = {name = "ぞんび じょか", text = {"すこあに{C:attention}ならない{}さいしょの", "かーどを{C:attention}はかい{}して {C:red}+15{} まるち", "でもはんどをぷれいするたび", "{C:red}-10{} まるちうしなう", "{C:red}0{} まるちになると", "{C:attention}しぬ {}", "{C:inactive}(いま {C:red}+#1#{C:inactive} まるちくらい){}"}, unlock = {"{C:attention}スペースデッキ{}を使用して", "{C:attention}パープルステーク{}で勝利する"}},
            j_kranlaxs_thecousin = {name = "いとこ", text = {"スコアに加算された{C:attention}素数{}ごとに", "{C:chips}+13{} チップを獲得", "{C:inactive}(現在 {C:chips}+#1#{C:inactive} チップ){}"}, unlock = {"{C:attention}スペースデッキ{}を使用して", "{C:attention}ターコイズステーク{}で勝利する"}},
            j_kranlaxs_colasoda = {name = "コーラソーダ", text = {"{X:dark_edition,C:white} ^#1# {} マルチを与える", "ほぼ{C:attention}すべてのアクション{}で", "{X:dark_edition,C:white} ^#2# {} 失う"}, unlock = {"{C:attention}ウィークリーチャレンジ{}デッキを使用して", "{C:attention}ブルーステーク{}で勝利する"}},
            j_kranlaxs_icecreamsandwich = {name = "アイスクリームサンド", text = {"ラウンド終了時に", "{X:money,C:white} $#1# {} 獲得する", "報酬はラウンドごとに", "{X:money,C:white} $#2# {} 減少する"}, unlock = {"1回のラウンドの支払いで", "{X:money,C:white} $50 {} 以上を", "獲得する"}},
            j_kranlaxs_dispensermachine = {name = "自動販売機", text = {"ショップを出る際にこのジョーカーが", "{C:attention}選択{}されている場合、{X:money,C:white} $#1# {} を消費して", "{C:attention}食べ物ジョーカー{}を生成する"}, unlock = {"食べ物ジョーカーを", "{C:attention}4{}枚同時に持つ"}},
            j_kranlaxs_bottledwater = {name = "ボトルウォーター", text = {"{X:chips,C:white} X#1# {} チップ", "スコアに加算されたカードごとに", "{X:chips,C:white} X#2# {} 失う"}, unlock = {"{C:attention}ウィークリーチャレンジ{}デッキを使用して", "{C:attention}ブルーステーク{}で勝利する"}},
            j_kranlaxs_burrow = {name = "ウサギの巣穴", text = {"{C:attention}ブラインドを倒す{}ごとに", "ウサギを{C:attention}+1{}獲得する", "{C:gold}売却{}すると、{C:attention}#1#{}羽のウサギを生成する"}},
            j_kranlaxs_bunny = {name = "ウサギ", text = {"所有している{C:attention}ウサギ{}ジョーカーごとに", "{X:mult,C:white} X#1# {} マルチを獲得", "{C:inactive}(現在 {X:mult,C:white} X#2# {C:inactive} マルチ){}"}},
            j_kranlaxs_sushi = {name = "寿司", text = {"ブラインドの要件を", "{C:attention}#1#%{}減少させる", "{C:attention}ブラインド{}を倒すと、", "減少量が{C:attention}#2#%{}低下する"}, unlock = {"{C:attention}ウィークリーチャレンジ{}デッキを使用して", "{C:attention}パープルステーク{}で勝利する"}},
            j_kranlaxs_gigachad = {name = "ギガチャド", text = {"ほぼ{C:attention}すべてのアクション{}で", "{C:chips}+#2#{} チップを獲得", "{C:inactive}(現在 {C:chips}+#1#{C:inactive} チップ){}"}, unlock = {"{C:attention}ウィークリーチャレンジ{}デッキを使用して", "{C:attention}ホワイトステーク{}で勝利する"}},
            j_kranlaxs_nft = {name = "仮想通貨詐欺", text = {"ハンドでスコアを得たとき、", "手札にあるすべてのカードの", "{C:attention}ランク{}を{C:attention}1{}下げる", "{C:inactive}(2未満には下がらない){}"}},
            j_kranlaxs_beanstalk = {name = "豆の木", text = {"役立たずの豆"}, unlock = {"{C:attention}ウィークリーチャレンジ{}デッキを使用して", "{C:attention}ホワイトステーク{}で勝利する"}},
            j_kranlaxs_suspiciousbeanstalk = {name = "怪しい豆の木", text = {"役立たずの豆？..."}},
            j_kranlaxs_epicbeanstalk = {name = "壮大な豆の木", text = {"役立たずの豆ではないかもしれない..."}},
            j_kranlaxs_zenithbeanstalk = {name = "頂点の豆の木", text = {"豆"}},
            j_kranlaxs_commonseed = {name = "コモンシード", text = {"ランダムな{C:common}コモン{}の", "ジョーカーを{C:attention}生成{}する"}},
            j_kranlaxs_weirdlookingseed = {name = "奇妙なシード", text = {"ランダムな{C:uncommon}アンコモン{}の", "ジョーカーを{C:attention}生成{}する"}},
            j_kranlaxs_magnificentseed = {name = "壮麗なシード", text = {"ランダムな{C:rare}レア{}の", "ジョーカーを{C:attention}生成{}する"}},
            j_kranlaxs_godseed = {name = "神のシード", text = {"ランダムな{C:legendary}レジェンダリー{}の", "ジョーカーを{C:attention}生成{}する"}},
            j_kranlaxs_anonymousjoker = {name = "匿名ジョーカー", text = {"スコアを得たとき裏返り、", "{X:mult,C:white} X1.5 {} から {X:mult,C:white} X4.0 {} のマルチを与える"}, unlock = {"{C:attention}琥珀のどんぐり{}ボスブラインドを", "1回倒す"}},
            j_kranlaxs_littlebro = {name = "リトルブロ", text = {"プレイしたハンドが{C:attention}ハイカード{}で、", "スコアカードが{C:attention}#2#{}の場合、", "このジョーカーは{X:red,C:white} X#3# {} マルチを獲得", "カードのランクは毎ラウンド変わる", "{C:inactive}(現在 {X:red,C:white} X#1# {C:inactive} マルチ){}"}, unlock = {"1回のランで", "{C:attention}ハイカード{}を", "{C:attention}30{}回プレイする"}},
            j_kranlaxs_medusa = {name = "メデューサ", text = {"ハンドをプレイした後、", "{C:attention}プレイしたすべてのカード{}が", "永久に{C:attention}石のカード{}になる", "{C:inactive}(スコアに加算されないものも含む){}"}, unlock = {"{C:attention}スペースデッキ{}を使用して", "{C:attention}ブラウンステーク{}で勝利する"}},
            j_kranlaxs_depression = {name = "景気後退", text = {"{X:dark_edition,C:white}^#2#{} マルチを与える", "{X:money,C:white} $0 {} を下回る {X:money,C:white} $1 {} につき", "{X:dark_edition,C:white}^#1#{} 増加する"}, unlock = {"{X:money,C:white} -$25 {} 以下で", "ショップに入る"}},
            j_kranlaxs_grannyjoker = {name = "おばあちゃん", text = {"{X:dark_edition,C:white} ^3 {} チップと {X:dark_edition,C:white} ^3 {} マルチ", "ゲームスピードが{C:attention}0.25x{}に固定される", "{C:inactive}({C:attention}ストレート{C:inactive}か{C:attention}ストレートフラッシュ{}", "{C:inactive}をプレイすると破壊される){}"}, unlock = {"ゲームスピード{C:attention}0.5{}で", "{C:attention}12{}回ブラインドを倒す"}},
            j_kranlaxs_lateshippment = {name = "遅延配送", text = {"{C:attention}前のラウンド{}でプレイしたハンド1回につき", "{C:attention}プレイしたすべてのカード{}を", "{C:attention}1回{}再トリガーする", "{C:inactive}(現在 {C:attention}#1#{C:inactive} 回の再トリガー){}"}, unlock = {"{C:attention}スペースデッキ{}を使用して", "{C:attention}オレンジステーク{}で勝利する"}},
            j_kranlaxs_unkownfactor = {name = "変数 X", text = {"プレイしたすべてのカードは", "{C:attention}#1#{}として扱われる", "{C:inactive}(ラウンド終了時にランクが変わる){}"}, unlock = {"{C:attention}ウィークリーチャレンジ{}デッキを使用して", "{C:attention}ゴールドステーク{}で勝利する"}},
            j_kranlaxs_thethreers = {name = "3つの R", text = {"プレイした各カードの{C:attention}コピー{}を作成し", "{C:attention}デッキ{}に追加する", "スコアに加算されたカードをすべて{C:attention}破壊する{}"}, unlock = {"{C:attention}ウィークリーチャレンジ{}デッキを使用して", "{C:attention}ゴールドステーク{}で勝利する"}},
            j_kranlaxs_the = {name = "Jok", text = {"ラウンドの{C:attention}最初のハンド{}でのみ", "{X:chips,C:white} X2 {} チップと {X:mult,C:white} X2 {} マルチを与える"}, unlock = {"それぞれ{C:attention}1{}ハンドのみを使用して", "{C:attention}5{}回ブラインドを倒す"}},
            j_kranlaxs_chainreaction = {name = "連鎖反応", text = {"プレイしたハンドが{C:attention}#2#{}の場合、", "{X:chips,C:white} X0.5 {} チップを獲得し、ハンドが変わる", "ハンドが{C:attention}一致しない{}場合はリセット", "{C:inactive}(現在 {X:chips,C:white} X#1# {C:inactive} チップ){}"}, unlock = {"1回のランで", "すべてのポーカー役を最低{C:attention}1{}回プレイする"}},
            j_kranlaxs_anubis = {name = "アヌビス", text = {"ハンドでスコアを得たとき、", "{C:blue}チップ{}と{C:red}マルチ{}のバランスを取る"}, unlock = {"すべてのステーク難易度で", "{C:attention}プラズマデッキ{}を使用して勝利する"}},
            j_kranlaxs_erraticjoker = {name = "不安定なジョーカー", text = {"スコアに加算されたカードが", "{C:attention}ワイルドカード{}の場合、", "{C:blue}チップ{}と{C:red}マルチ{}を入れ替える"}, unlock = {"{C:attention}スペースデッキ{}を使用して", "{C:attention}ホワイトステーク{}で勝利する"}},
            j_kranlaxs_luckyseven = {name = "ラッキーセブン", text = {"プレイしたハンドが{C:attention}7{}のみの", "{C:attention}スリーカード{}の場合、このジョーカーは", "{C:blue}+7{} チップ, {C:red}+7{} マルチを獲得し、{X:money,C:white} $7 {} を与える", "{C:inactive}(現在 {C:blue}+#1#{} チップ, {C:red}+#2#{} マルチ)"}, unlock = {"デッキに{C:attention}7{}のランクのカードを", "少なくとも{C:attention}10{}枚持つ"}},
            j_kranlaxs_certificateddocument = {name = "証明書", text = {"{C:attention}すべて{}のシールを再トリガーする"}, unlock = {"{C:attention}ウィークリーチャレンジ{}デッキを使用して", "{C:attention}パープルステーク{}で勝利する"}},
            j_kranlaxs_platanito = {name = "リトルバナナ", text = {"他のジョーカーがトリガーされるたび、", "{X:mult,C:white} X#3# {} 追加マルチを与える", "ラウンド終了時に{C:green}#1# / #2#{}の", "確率で破壊される"}, unlock = {"{C:attention}スペースデッキ{}を使用して", "{C:attention}プラチナステーク{}で勝利する"}},
            j_kranlaxs_cubicaljoker = {name = "キュービックジョーカー", text = {"{C:mult}+#1#{} マルチを与える", "値は倒した{C:attention}ボスブラインド{}ごとに", "{C:attention}3乗 (^3){} になる"}},
            j_kranlaxs_grapesoda = {name = "グレープソーダ", text = {"{C:gold}売却{}すると、{C:dark_edition}ネガティブ{}版の", "ランダムな{C:spectral}スペクトル{}カードを", "作成する"}, unlock = {"{C:attention}スペースデッキ{}を使用して", "{C:attention}マゼンタステーク{}で勝利する"}},
            j_kranlaxs_telescope = {name = "望遠鏡", text = {"{C:attention}#1#{}がレベルアップした場合、", "その役をさらに{C:attention}1{}回レベルアップする", "{C:inactive}(役はラウンド終了時に変わる){}"}, unlock = {"{C:attention}ウィークリーチャレンジ{}デッキを使用して", "{C:attention}レッドステーク{}で勝利する"}},
            j_kranlaxs_pandorabox = {name = "パンドラの箱", text = {"{C:attention}ボスブラインド{}を倒したとき、", "現在のデッキに基づいて", "{C:attention}役立つ{}ジョーカーを作成する", "{C:inactive}(空きスロットが必要){}"}},
            j_kranlaxs_doppelganger = {name = "ドッペルゲンガー", text = {"ゲーム全体からランダムな", "{C:attention}ジョーカー{}の能力をコピーする。", "コピーしたジョーカーは", "{C:attention}ブラインド{}を倒すと変わる。", "{C:inactive}(現在: {C:attention}#1#{C:inactive})"}, unlock = {"{C:attention}ウィークリーチャレンジ{}デッキを使用して", "{C:attention}ゴールドステーク{}で勝利する"}},
            j_kranlaxs_thechampion = {name = "チャンピオン", text = {"ブラインドの要件 {C:attention}X#1#{}", "ラウンド終了時に {X:money,C:white} $#2# {} を獲得"}, unlock = {"{C:attention}アンティ 16{} に到達する"}},
            j_kranlaxs_clerigo = {name = "クレリック", text = {"フルデッキのカード1枚につき", "{C:mult}+#1#{} マルチを与える", "強化またはシールがあるカード1枚につき", "{C:mult}-#2#{} マルチを失う", "{C:inactive}(現在 {C:mult}+#3#{C:inactive} マルチ){}"}, unlock = {"チャレンジをクリアする:", "{C:attention}ファミリーレシピ{}"}},
            j_kranlaxs_entrenador = {name = "コーチ", text = {"アンティ {C:attention}#3#{} 未満の場合、", "{X:mult,C:white} X#1# {} マルチを与える", "それ以外の場合、{X:mult,C:white} X#2# {} マルチを与える", "{C:inactive}(現在 {X:mult,C:white} X#4# {C:inactive} マルチ){}"}, unlock = {"チャレンジをクリアする:", "{C:attention}経済危機{}"}},
            j_kranlaxs_medium = {name = "霊媒師", text = {"プロフィールにある{C:red}敗北{}したラン1つにつき", "{C:mult}+#1#{} マルチを与える", "{C:inactive}(現在 {C:mult}+#2#{C:inactive} マルチ){}"}, unlock = {"{C:attention}1{}回敗北する", "{C:inactive}(進行度: {C:attention}#1#{C:inactive} / 1){}"}},
            j_kranlaxs_monk = {name = "モンク", text = {"{X:money,C:white} お金 {}を消費せずにショップを出ると", "{X:chips,C:white} X#1# {} チップを獲得", "何かを購入すると{C:red}リセット{}", "{C:inactive}(現在 {X:chips,C:white} X#2# {C:inactive} チップ){}"}, unlock = {"チャレンジをクリアする:", "{C:attention}清貧の誓い{}"}},
            j_kranlaxs_knight = {name = "ナイト", text = {"{C:attention}#1#{}枚の{C:attention}スチール{}カードでスコアを得た後、", "次の{C:attention}ボスブラインド{}を{C:attention}無効化{}する", "{C:inactive}(スコアカード: #2#/#1#){}"}, unlock = {"チャレンジをクリアする:", "{C:attention}ボスシンジケート{}"}},
            j_kranlaxs_overpopulation = {name = "人口過多", text = {"デッキ内の{C:attention}#2#{}の制限を超えた", "{C:attention}絵札{}1枚につき、", "{C:mult}+#1#{} マルチを与える", "{C:inactive}(現在 {C:mult}+#3#{C:inactive} マルチ){}"}, unlock = {"{C:attention}スペースデッキ{}を使用して", "{C:attention}グリーンステーク{}で勝利する"}},
            j_kranlaxs_antisocial = {name = "反社会性", text = {"ちょうど{C:attention}1{}枚のカードをプレイした場合、", "このジョーカーは{C:mult}+#1#{} マルチを獲得", "1枚より多くプレイすると{C:red}リセット{}", "{C:inactive}(現在 {C:mult}+#2#{C:inactive} マルチ){}"}, unlock = {"チャレンジをクリアする:", "{C:attention}完全な執着{}"}},
            j_kranlaxs_famous = {name = "有名人", text = {"プレイしたハンドが{C:attention}ファイブカード{}、", "{C:attention}フラッシュファイブ{}または{C:attention}フラッシュハウス{}の場合、", "{C:chips}+#1#{} チップを与える"}},
            j_kranlaxs_influencer = {name = "インフルエンサー", text = {"プレイしたハンドが{C:attention}ファイブカード{}、", "{C:attention}フラッシュファイブ{}または{C:attention}フラッシュハウス{}の場合、", "{C:mult}+#1#{} マルチを与える"}},
            j_kranlaxs_potatobag = {name = "ポテトバッグ", text = {"スコアしたチップを蓄積する", "{C:attention}#1#{}に到達すると、次のハンドに", "{X:mult,C:white} X#2# {} マルチを適用して空になる", "{C:inactive}(蓄積: #3#/#1#){}"}},
            j_kranlaxs_simonsays = {name = "サイモンセズ", text = {"その要求を完了すると、", "このジョーカーは{X:mult,C:white} X#2# {} マルチを獲得", "サイモン曰く... {C:attention}#3#{}", "{C:inactive}(現在 {X:mult,C:white} X#1# {C:inactive} マルチ){}"}, unlock = {"チャレンジをクリアする:", "{C:attention}巨大な豆の木{}"}},
            j_kranlaxs_cheater = {name = "チーター", text = {"ショップのジョーカーは、", "{C:green}35%{}の確率で{C:attention}バウチャー{}または", "{C:attention}ブースターパック{}に置き換えられる"}, unlock = {"チャレンジをクリアする:", "{C:attention}ガチャポン{}"}},
            j_kranlaxs_philosopher = {name = "哲学者", text = {"デッキから次の{C:attention}5枚のカード{}を", "明らかにする", "{C:inactive}(各カードは20%の確率で{}", "{C:inactive}隠されたままになる){}", "{C:attention}#1#{}"}, unlock = {"チャレンジをクリアする:", "{C:attention}予感{}"}},
            j_kranlaxs_mandalajoker = {name = "マンダラジョーカー", text = {"使用した{C:spectral}スペクトル{}カード1枚につき", "このジョーカーは{X:mult,C:white} X0.5 {} マルチを獲得", "{C:inactive}(現在 {X:mult,C:white} X#1# {C:inactive} マルチ){}"}, unlock = {"{C:attention}20{}枚の{C:spectral}スペクトル{}カードを使用する", "{C:inactive}(進行度: {C:attention}#1#{C:inactive} / 20){}"}},
            j_kranlaxs_regift = {name = "リギフトジョーカー", text = {"{C:gold}売却{}すると、", "ランダムな{C:attention}ジョーカー{}を作成する", "レアリティは現在の{C:attention}ブラインド{}に依存する"}, unlock = {"合計で{C:attention}50{}枚のジョーカーを売却する", "{C:inactive}(進行度: {C:attention}#1#{C:inactive} / 50){}"}},
            j_kranlaxs_pyromaniac = {name = "放火魔", text = {"ハンドでスコアを得た後、手札にある", "すべての{C:attention}数字{}のカードを{C:red}破壊する{}", "{C:inactive}(ゴールド、ガラス、スチールカードは安全){}"}, unlock = {"絵札ではないカードを", "{C:attention}100{}枚破壊する", "{C:inactive}(進行度: {C:attention}#1#{C:inactive} / 100){}"}},
            j_kranlaxs_neverendinggambling = {name = "終わらないギャンブル", text = {"アクションを行うたびに {X:money,C:white} $1 {} 失う", "{C:inactive}({X:money,C:white} $5 {} 以上持っている場合のみ){}", "3つの数字をスピン。一致すれば賞金獲得！", "2つ一致で、慰めとして {X:money,C:white} $1 {} 回収", "{C:inactive}(現在のスピン: #1# - #2# - #3#){}"}, unlock = {"ジョーカーまたは消費アイテムの確率を", "{C:attention}30{}回外す", "{C:inactive}(進行度: {C:attention}#1#{C:inactive} / 30){}"}},
            j_kranlaxs_solarsystem = {name = "太陽系", text = {"{C:attention}ラウンド終了時{}、固定の順序で", "{C:planet}プラネット{}カードを生成する", "{C:inactive}(次の惑星: {C:planet}#1#{C:inactive}){}"}, unlock = {"1回のランで、すべての{C:attention}12{}枚の標準", "{C:planet}プラネット{}カードを少なくとも1回使用する", "{C:inactive}(進行度: {C:attention}#1#{C:inactive} / 12){}"}},
            j_kranlaxs_deranged = {name = "狂気", text = {"{C:mult}+#1#{} マルチまたは {C:chips}+#2#{} チップを与える", "効果はハンドをプレイする", "たびに切り替わる"}, unlock = {"チャレンジをクリアする:", "{C:attention}アイデンティティの危機{}"}},
            j_kranlaxs_deranged_mult = {name = "狂気", text = {"{C:mult}+#1#{} マルチを与える", "効果はハンドをプレイする", "たびに切り替わる"}},
            j_kranlaxs_deranged_chips = {name = "狂気", text = {"{C:chips}+#2#{} チップを与える", "効果はハンドをプレイする", "たびに切り替わる"}},
            j_kranlaxs_tmtrainer = {name="TMTRAINER",text={"{C:dark_edition}#1#{}","{C:attention}#2#{}","{C:red}#3#{}","{C:chips}#4#{}"},unlock={"チャレンジをクリアする:","{C:attention}アイデンティティの危機{}"}},
            j_kranlaxs_bingocard = {name = "ビンゴカード", text = {"完了したライン1つにつき", "{X:mult,C:white} X0.25 {} マルチを獲得", "{C:inactive}(合計: {X:mult,C:white} X#2# {C:inactive} マルチ){}", "{C:attention}#3#{}", "{C:attention}#4#{}", "{C:attention}#5#{}", "{C:attention}#6#{}", "{C:attention}#7#{}"}, unlock = {"チャレンジをクリアする:", "{C:attention}完全な匿名性{}"}}
        },

        Back = {
            b_kranlaxs_week_challenge = {name = "ウィークリーチャレンジ", text = {"{C:attention}ウィークリーチャレンジ{}ジョーカーを持って開始する", "毎{C:attention}週末{}に{C:red}クリア可能{}"}, unlock = {"{C:attention}土曜日{}または{C:attention}日曜日{}に", "ゲームを開く"}},
            b_kranlaxs_chaos_deck = {name = "カオスデッキ", text = {"混沌を楽しめ"}, unlock = {"コレクションの{C:legendary,E:1}すべて{}を", "アンロックする"}},
            b_kranlaxs_dungeon_deck = {name = "ダンジョンデッキ", text = {"{C:attention}ボスブラインド{}を倒した後、", "{C:green}長所{}と{C:red}短所{}がある", "3つの{C:attention}オプション{}から選択する"}, unlock = {"{C:attention}ウィークリーチャレンジ{}デッキを使用して", "{C:attention}グリーンステーク{}以上で勝利する"}},
            b_kranlaxs_space_deck = {name = "スペースデッキ", text = {"ジョーカースロット {C:attention}0{}、消費アイテムスロット {C:attention}5{}", "ショップは{C:attention}クォーツ{}のみ販売する", "ショップサイズ {C:attention}+1{}、ブラインドは{C:attention}7.5%{}小さい", "勝利アンティ: {C:attention}10{}"}, unlock = {"{C:attention}マジックデッキ{}、{C:attention}星雲デッキ{}、", "{C:attention}ゾディアックデッキ{}を使用して", "{C:attention}グリーンステーク{}で勝利する"}},
            b_kranlaxs_bugged_deck = {name = "バグデッキ", text = {"!?"}, unlock = {"初めて{C:attention}TMTRAINER{}を", "獲得する"}}
        },

        Stake = {
            stake_kranlaxs_magenta = {name = "マゼンタステーク", text = {"ショップのカードが{C:attention}固定{}", "ステッカーを持つ可能性がある"}},
            stake_kranlaxs_brown = {name = "ブラウンステーク", colour = "ブラウン", text = {"ショップの{C:attention}ブースターパック{}スロット {C:attention}-1{}"}},
            stake_kranlaxs_turquoise = {name = "ターコイズステーク", colour = "ターコイズ", text = {"ブラインドが{C:red}スキップ不可{}になる", "確率が{C:attention}50%{}ある"}},
            stake_kranlaxs_deviled = {name = "デビルドステーク", colour = "デビルド", text = {"{C:attention}ジョーカー{}スロット {C:attention}-1{}"}},
            stake_kranlaxs_glass = {name = "グラスステーク", colour = "グラス", text = {"必要なスコアが各{C:attention}アンティ{}で", "さらに早くスケールする"}},
            stake_kranlaxs_platinum = {name = "プラチナステーク", colour = "プラチナ", text = {"勝利するには{C:attention}アンティ 10{}を", "倒さなければならない"}}
        },

        UNOCards = {
            c_kranlaxs_skip = {name = "スキップ", text = {"{C:attention}即座に{}ブラインドの要件を獲得する", "{C:attention}ボスブラインド{}には効かない"}},
            c_kranlaxs_stacking = {name = "スタッキング", text = {"手札の選択した{C:attention}1{}枚のカードに", "{C:attention}ピンクシール{}を追加する"}},
            c_kranlaxs_draw2 = {name = "ドロー2", text = {"使用時、手札に{C:attention}追加で2枚のカードを引く{}", "ハンドを{C:blue}1{}失う"}},
            c_kranlaxs_draw4 = {name = "ドロー4", text = {"使用時、手札に{C:attention}追加で4枚のカードを引く{}", "ハンドを{C:blue}1{}失う"}},
            c_kranlaxs_reverse = {name = "リバース", text = {"手札の{C:attention}すべてのカード{}を", "デッキに戻し、{C:attention}シャッフル{}する"}},
            c_kranlaxs_wildcard = {name = "ワイルドカード", text = {"手札の各カードを{C:attention}独立して{}", "{C:attention}ランダムなスート{}に{C:attention}変換{}する"}},
            c_kranlaxs_replay = {name = "リプレイ", text = {"最後にプレイしたハンドの", "カードを手札に戻す", "{C:inactive}(使用後またはラウンド", "{C:inactive}終了時にリセット)"}},
            c_kranlaxs_discardall = {name = "すべてディスカード", text = {"選択したカードが{C:attention}1{}枚必要。", "手札とデッキから、同じスートを", "共有する{C:red}すべて{}のカードを", "ディスカードする"}},
            c_kranlaxs_shield = {name = "シールド", text = {"死からパッシブに保護するか、売却して", "{C:attention}ボスブラインド{}を無効にすることができる"}},
            c_kranlaxs_misery = {name = "ミザリー", text = {"{C:attention}スート{}を1つ選ぶ。", "そのスートのカードが出るまで", "デッキからカードを", "引き続ける"}},
            c_kranlaxs_gift = {name = "ギフト", text = {"以下のランダムな賞品の", "うち{C:attention}1{}つを与える:", "• エディション付きの{C:attention}ジョーカー{}", "• ネガティブの{C:attention}消費アイテム{}", "• 強化、シール、エディション付きの{C:attention}カード{}"}},
            c_kranlaxs_customdraw = {name = "カスタムドロー", text = {"これまでに行ったディスカードと", "同じ枚数のカードを引く", "{C:inactive}(現在: {C:attention}#1#{C:inactive} 枚){}"}}
        },

        InverseTarot = {
            c_kranlaxs_thefool = {name = "愚者？", text = {"ランダムな{C:spectral}スペクトル{}カードを生成する", "ランダムなポーカー役を{C:attention}ダウングレード{}する"}},
            c_kranlaxs_themagician = {name = "魔術師？", text = {"ランダムな{C:attention}ラッキー{}カードを{C:attention}2{}枚生成する"}},
            c_kranlaxs_thehighpriestess = {name = "女教皇？", text = {"{C:spectral}ブラックホール{}を生成する", "あなたの{X:money,C:white} お金 {}が20% {C:attention}減少{}する"}},
            c_kranlaxs_theempress = {name = "女帝？", text = {"最大{C:attention}2{}枚の選択したカードに", "永久的な {C:red}+8{} マルチを追加する"}},
            c_kranlaxs_theemperor = {name = "皇帝？", text = {"ランダムな{C:attention}タグ{}を{C:attention}2{}つ生成する"}},
            c_kranlaxs_thehierophant = {name = "教皇？", text = {"最大{C:attention}2{}枚の選択したカードに", "永久的な {C:blue}+40{} チップを追加する"}},
            c_kranlaxs_thelovers = {name = "恋人？", text = {"デッキに{C:attention}ワイルドカード{}がある場合、", "ハンドサイズ {C:attention}+1{} を獲得する"}},
            c_kranlaxs_thechariot = {name = "戦車？", text = {"{C:attention}レッド{}シールを持つランダムな", "{C:attention}スチール{}カードを{C:attention}1{}枚生成する"}},
            c_kranlaxs_justice = {name = "正義？", text = {"{C:attention}1{}枚の選択したカードに", "永久的な {X:red,C:white} X2 {} マルチを追加する", "{C:green}#1# / #2#{}の確率でこのカードを{C:attention}破壊{}する"}},
            c_kranlaxs_thehermit = {name = "隠者？", text = {"{X:money,C:white} $25 {} {C:attention}未満{}の場合、", "あなたの{X:money,C:white} お金 {}を {X:money,C:white} $25 {} に{C:attention}設定{}する"}},
            c_kranlaxs_thewheeloffortune = {name = "運命の輪？", text = {"{C:green}#1# / #2#{}の確率で、{C:dark_edition}ネガティブ{}版の", "ランダムなジョーカーの{C:attention}コピー{}を生成する"}},
            c_kranlaxs_strenght = {name = "力？", text = {"最大{C:attention}2{}枚の選択したカードの", "{C:attention}ランク{}を{C:attention}1{}つ{C:attention}下げる{}"}},
            c_kranlaxs_thehangedman = {name = "吊るされた男？", text = {"手札の最大{C:attention}2{}枚の選択したカードを", "完全に{C:attention}ランダム化{}する"}},
            c_kranlaxs_death = {name = "死神？", text = {"ランダムなジョーカーの{C:attention}ネガティブコピー{}を生成する", "ランダムなジョーカーが{C:attention}ペリシャブル{}ステッカーを受け取る"}},
            c_kranlaxs_temperance = {name = "節制？", text = {"{C:attention}すべて{}のジョーカー (永遠も含む) を", "売値の{C:money}3倍{}で売却する", "{C:inactive}(固定ジョーカーは売却しない){}"}},
            c_kranlaxs_thedevil = {name = "悪魔？", text = {"最大{C:attention}2{}枚の選択したカードに", "永久的な {X:money,C:white} $2 {} を追加する"}},
            c_kranlaxs_thetower = {name = "塔？", text = {"手札のカードからすべての強化、シール、", "エディション、ボーナスを{C:attention}削除{}する", "削除した変更1つにつき {X:money,C:white} $1 {} を獲得する"}},
            c_kranlaxs_thestars = {name = "星？", text = {"最大{C:attention}2{}枚の選択したカードに", "{C:attention}ホワイトシール{}を追加する"}},
            c_kranlaxs_themoon = {name = "月？", text = {"最大{C:attention}2{}枚の選択したカードに", "{C:attention}グレーシール{}を追加する"}},
            c_kranlaxs_thesun = {name = "太陽？", text = {"最大{C:attention}2{}枚の選択したカードに", "{C:attention}オレンジシール{}を追加する"}},
            c_kranlaxs_judgement = {name = "審判？", text = {"ランダムな{C:attention}バウチャー{}を{C:attention}引き換える{}", "ハンドサイズ {C:red}-1{}"}},
            c_kranlaxs_theworld = {name = "世界？", text = {"最大{C:attention}2{}枚の選択したカードに", "{C:attention}ブラウンシール{}を追加する"}}
        },

        Voucher = {
            v_kranlaxs_more_stock = {name = "在庫追加", text = {"ショップに{C:attention}ブースターパック{}の", "スロットが{C:attention}1{}つ追加される"}},
            v_kranlaxs_even_more_stock = {name = "さらに在庫追加", text = {"ショップに{C:attention}バウチャー{}の", "スロットが{C:attention}1{}つ追加される"}},
            v_kranlaxs_shiny_appearance = {name = "光る出現", text = {"レジェンダリーカードとレアな消費アイテムが", "ショップに出現するようになる"}},
            v_kranlaxs_stickerfever = {name = "ステッカーフィーバー", text = {"{C:attention}タグ{}を獲得するたび、", "追加のコピーを{C:attention}1{}つ得る"}},
            v_kranlaxs_stickeralbum = {name = "ステッカーアルバム", text = {"{C:attention}タグ{}を獲得するたび、", "さらなるコピーを{C:attention}1{}つ得る"}},
            v_kranlaxs_hotfix = {name = "ホットフィックス", text = {"ショップを{C:attention}リロール{}すると、", "{C:attention}バウチャー{}と{C:attention}ブースターパック{}も更新される"}},
            v_kranlaxs_version2 = {name = "バージョン 2.0", text = {"ブラインドをスキップすると、そのブラインドの", "{X:money,C:white} お金 {}の報酬を獲得できる。", "ブラインドの要件 {C:attention}-15%{}"}},
            v_kranlaxs_common_shinys = {name = "伝説の目撃", text = {"レジェンダリーカードとレアな消費アイテムが", "より頻繁に出現するようになる"}},
            v_kranlaxs_blessing = {name = "祝福", text = {"各ブラインドのチップ要件の{C:attention}10%{}が", "完了した状態で開始する"}},
            v_kranlaxs_protection = {name = "神の加護", text = {"{C:attention}ゲームオーバー{}から保護する。", "使用後、このバウチャーは破壊され、", "ショップに再出現する可能性があるが、", "元の価格の{X:money,C:white} 2倍 {}になる"}}
        },

        Quartz = {
            c_kranlaxs_blackquartz = {name = "黒曜石", text = {"選択した一部の", "ルールを変更する"}, unlock = {"{C:attention}マジックデッキ{}を使用して", "{C:attention}ブラウンステーク{}で勝利する"}},
            c_kranlaxs_whitequartz = {name = "真珠", text = {"最後に使用した", "消費アイテムを作成する", "{C:inactive}(最後のカード: {C:attention}#1#{C:inactive}){}"}, unlock = {"{C:attention}ゴーストデッキ{}を使用して", "{C:attention}ブラウンステーク{}で勝利する"}},
            c_kranlaxs_pinkquartz = {name = "ローズクォーツ", text = {"選択した{C:attention}ジョーカー{}または{C:attention}カード{}に", "{C:dark_edition}ポリクローム{}を追加する"}, unlock = {"{C:attention}ダンジョンデッキ{}を使用して", "{C:attention}マゼンタステーク{}以上で勝利する"}},
            c_kranlaxs_bluequartz = {name = "サファイア", text = {"選択した{C:attention}ジョーカー{}または{C:attention}カード{}に", "{C:chips}フォイル{}を追加する"}, unlock = {"{C:attention}プラズマデッキ{}を使用して", "{C:attention}プラチナステーク{}で勝利する"}},
            c_kranlaxs_lilacquartz = {name = "クンツァイト", text = {"選択した{C:attention}ジョーカー{}または{C:attention}カード{}に", "{C:mult}ホログラフィック{}を追加する"}, unlock = {"{C:attention}星雲デッキ{}を使用して", "{C:attention}ブラウンステーク{}で勝利する"}},
            c_kranlaxs_grayquartz = {name = "ヘマタイト", text = {"選択した{C:attention}ジョーカー{}または{C:attention}消費アイテム{}に", "{C:dark_edition}ネガティブ{}を追加する"}, unlock = {"{C:attention}ペイントデッキ{}を使用して", "{C:attention}ターコイズステーク{}で勝利する"}},
            c_kranlaxs_transparentquartz = {name = "ダイヤモンド", text = {"{C:attention}ジョーカー{}からすべてのステッカーや", "エディションを、または選択した{C:attention}カード{}から", "シールやエディションを{C:attention}削除{}する"}, unlock = {"{C:attention}ダンジョンデッキ{}を使用して", "{C:attention}プラチナステーク{}で勝利する"}},
            c_kranlaxs_redquartz = {name = "ルビー", text = {"{C:attention}持っている{}間、", "{X:mult,C:white} X2 {} マルチを与える", "{C:inactive}(パッシブ){}"}, unlock = {"{C:attention}レッドデッキ{}を使用して", "{C:attention}マゼンタステーク{}以上で勝利する"}},
            c_kranlaxs_celestequartz = {name = "ラリマー", text = {"{C:attention}持っている{}間、", "{X:chips,C:white} X1.5 {} チップを与える", "{C:inactive}(パッシブ){}"}, unlock = {"{C:attention}チェッカードデッキ{}を使用して", "{C:attention}ターコイズステーク{}で勝利する"}},
            c_kranlaxs_yellowquartz = {name = "トパーズ", text = {"指定された{C:attention}ジョーカー{}を作成する。", "ジョーカーは各{C:attention}ラウンド{}後に", "ランダムに変わる", "{C:inactive}(ターゲット: {C:attention}#1#{C:inactive}){}"}, unlock = {"{C:attention}ダンジョンデッキ{}を使用して", "{C:attention}ブルーステーク{}で勝利する"}},
            c_kranlaxs_greenquartz = {name = "エメラルド", text = {"{C:attention}持っている{}間、{C:attention}ブラインド{}を倒した後に", "{C:attention}タグ{}を1つ作成する", "{C:attention}#2#{}個のタグを作成すると破壊される", "{C:inactive}(現在: {C:attention}#1#{C:inactive}){}", "{C:inactive}(パッシブ){}"}, unlock = {"{C:attention}グリーンデッキ{}を使用して", "{C:attention}マゼンタステーク{}以上で勝利する"}},
            c_kranlaxs_brownquartz = {name = "タイガーアイ", text = {"指定された{C:attention}カード{}を作成する。", "ショップを{C:green}リロール{}した後、", "カードはランダムに変わる", "{C:inactive}(ターゲット: {C:attention}#1#{C:inactive}){}"}, unlock = {"{C:attention}アナグリフデッキ{}を使用して", "{C:attention}ターコイズステーク{}で勝利する"}},
            c_kranlaxs_turquoisequartz = {name = "ターコイズ", text = {"{C:attention}持っている{}間、最初のジョーカー", "以外のすべてを{C:attention}無効化{}する", "そのジョーカーを{C:attention}2{}回再トリガーする", "{C:inactive}(パッシブ){}"}, unlock = {"{C:attention}ゾディアックデッキ{}を使用して", "{C:attention}ターコイズステーク{}で勝利する"}},
            c_kranlaxs_orangequartz = {name = "シトリン", text = {"{C:attention}カード{}に{C:green}ミントシール{}を、", "または選択した{C:attention}ジョーカー{}に", "{C:green}クローバーステッカー{}を追加する"}, unlock = {"{C:attention}イエローデッキ{}を使用して", "{C:attention}マゼンタステーク{}以上で勝利する"}},
            c_kranlaxs_lapislazuli = {name = "ラピスラズリ", text = {"{C:attention}持っている{}間、最初にスコアしたカードに", "{C:chips}+#1#{} チップを追加する", "効果は使用するたびに {C:chips}-#2#{} 減少する。", "{C:inactive}(0になると無効){}", "{C:inactive}(パッシブ){}"}, unlock = {"{C:attention}ブルーデッキ{}を使用して", "{C:attention}マゼンタステーク{}以上で勝利する"}},
            c_kranlaxs_cinnabar = {name = "辰砂", text = {"{C:attention}持っている{}間、最初にスコアしたカードに", "{C:mult}+#1#{} マルチを追加する", "効果は使用するたびに {C:mult}-#2#{} 減少する。", "{C:inactive}(0になると無効){}", "{C:inactive}(パッシブ){}"}, unlock = {"{C:attention}見捨てられたデッキ{}を使用して", "{C:attention}ブラウンステーク{}で勝利する"}},
            c_kranlaxs_graphite = {name = "グラファイト", text = {"{C:attention}持っている{}間、{C:green}#1# / #2#{}の確率で", "プレイしたすべてのカードのコピーを", "手札に作成する。", "トリガーされると確率は下がる。", "{C:inactive}(0になると無効){}", "{C:inactive}(パッシブ){}"}, unlock = {"{C:attention}ブラックデッキ{}を使用して", "{C:attention}マゼンタステーク{}以上で勝利する"}},
            c_kranlaxs_uranium = {name = "ウラン", text = {"{C:attention}持っている{}間、ラウンドごとに1つの", "ランダムな効果を適用する。非常に良いか、", "非常に破滅的な可能性がある。", "{C:dark_edition}現在のステータス:{}", "{C:red,E:2}#1#{}", "{C:inactive}(持ち運ぶ勇気はあるか？){}", "{C:inactive}(パッシブ){}"}, unlock = {"{C:attention}エラティックデッキ{}を使用して", "{C:attention}プラチナステーク{}で勝利する"}}
        },

        Tag = {
            tag_kranlaxs_mega_invtarot = {name = "メガ反転タグ", text = {"無料の{C:attention}メガ反転タロットパック{}を", "即座に与える"}},
            tag_kranlaxs_mega_uno = {name = "ジャンボ UNO タグ", text = {"無料の{C:attention}ジャンボ UNO パック{}を", "即座に与える"}},
            tag_kranlaxs_mega_invtarot_store = {name = "保存されたメガ反転タグ", text = {"無料の{C:attention}保存されたメガ反転タロット{}を", "即座に与える"}},
            tag_kranlaxs_quartz_tag = {name = "クォーツタグ", text = {"ランダムな{C:attention}クォーツ{}を生成する", "{C:inactive}(空きスロットが必要){}"}},
            tag_kranlaxs_sticker_remover = {name = "クレンザータグ", text = {"ランダムな{C:attention}ジョーカー{}から{C:attention}永遠{}、", "{C:attention}ペリシャブル{}、または{C:attention}レンタル{}の", "ステッカーを削除する", "{C:inactive}(ステッカーがない場合は {X:money,C:white} $5 {C:inactive} を与える){}"}},
            tag_kranlaxs_legendary = {name = "レジェンダリータグ", text = {"ショップに無料の", "{C:legendary}レジェンダリージョーカー{}が並ぶ"}}
        },

        Edition = {
            e_kranlaxs_wave = {name = "水生", text = {"{X:chips,C:white} X#1# {} チップ"}}
        },

        Other = {
            kranlaxs_magenta_sticker = {name = "マゼンタステッカー", text = {"このジョーカーを使用して", "{C:attention}マゼンタステーク{}で勝利した"}},
            kranlaxs_brown_sticker = {name = "ブラウンステッカー", text = {"このジョーカーを使用して", "{C:attention}ブラウンステーク{}で勝利した"}},
            kranlaxs_turquoise_sticker = {name = "ターコイズステッカー", text = {"このジョーカーを使用して", "{C:attention}ターコイズステーク{}で勝利した"}},
            kranlaxs_platinum_sticker = {name = "プラチナステッカー", text = {"このジョーカーを使用して", "{C:attention}プラチナステーク{}で勝利した"}},
            kranlaxs_orangeseal_seal = {name = "オレンジシール", text = {"手札でスコアした場合: {C:attention}#1#{}、", "1枚の{C:attention}#2#{}を生成する", "{C:inactive}使用後に変化する。{}", "{C:inactive}(空きスロットが必要){}"}},
            kranlaxs_pinkseal_seal = {name = "ピンクシール", text = {"{C:attention}スコアした{}とき、", "{X:dark_edition,C:white}^1.75{} マルチを適用する"}},
            kranlaxs_whiteseal_seal = {name = "ホワイトシール", text = {"{C:attention}常にスコアする{}、", "{C:red}デバフ{}、{C:red}破壊{}、", "または{C:attention}裏返される{}ことに免疫がある"}},
            kranlaxs_brownseal_seal = {name = "ブラウンシール", text = {"手札にある間、{C:green}#1# / #2#{}の", "確率でこのカードを{C:attention}複製{}する"}},
            kranlaxs_grayseal_seal = {name = "グレーシール", text = {"{C:attention}スコアした{}とき、このカードの", "{C:enhanced}強化{}を{C:attention}ランダム{}に変更する"}},
            kranlaxs_mintseal_seal = {name = "ミントシール", text = {"このカードの", "{C:attention}すべての記載された確率{}を2倍にする"}},
            p_kranlaxs_uno_store_3 = {name = "UNO パック", text = {"最大{C:attention}3{}枚の{C:blue}UNO{}カードから", "{C:attention}1{}枚を選ぶ"}},
            p_kranlaxs_uno_store_5 = {name = "ジャンボ UNO パック", text = {"最大{C:attention}5{}枚の{C:blue}UNO{}カードから", "{C:attention}1{}枚を選ぶ"}},
            p_kranlaxs_invtarot_instant_3_1 = {name = "反転タロットパック", text = {"最大{C:attention}3{}枚の{C:purple}反転タロット{}カードから", "{C:attention}1{}枚を選ぶ"}},
            p_kranlaxs_invtarot_instant_5_1 = {name = "ジャンボ反転タロットパック", text = {"最大{C:attention}5{}枚の{C:purple}反転タロット{}カードから", "{C:attention}1{}枚を選ぶ"}},
            p_kranlaxs_invtarot_instant_5_2 = {name = "メガ反転タロットパック", text = {"最大{C:attention}5{}枚の{C:purple}反転タロット{}カードから", "{C:attention}2{}枚を選ぶ"}},
            p_kranlaxs_invtarot_store_3_1 = {name = "保存された反転タロット", text = {"最大{C:attention}3{}枚の{C:purple}反転タロット{}カードから", "{C:attention}1{}枚を選ぶ"}},
            p_kranlaxs_invtarot_store_5_1 = {name = "保存されたジャンボ反転タロット", text = {"最大{C:attention}5{}枚の{C:purple}反転タロット{}カードから", "{C:attention}1{}枚を選ぶ"}},
            kranlaxs_deviled_sticker = {name = "デビルドステッカー", text = {"このジョーカーを使用して", "{C:attention}デビルドステーク{}で勝利した"}},
            kranlaxs_glass_sticker = {name = "グラスステッカー", text = {"このジョーカーを使用して", "{C:attention}グラスステーク{}で勝利した"}},
            p_kranlaxs_invtarot_store_5_2 = {name = "保存されたメガ反転タロット", text = {"最大{C:attention}5{}枚の{C:purple}反転タロット{}カードから", "{C:attention}2{}枚を選ぶ"}}

        },

        Booster = {
            p_kranlaxs_uno_store_3 = {name = "UNO パック", text = {"最大{C:attention}3{}枚の{C:blue}UNO{}カードから", "{C:attention}1{}枚を選ぶ"}},
            p_kranlaxs_uno_store_5 = {name = "ジャンボ UNO パック", text = {"最大{C:attention}5{}枚の{C:blue}UNO{}カードから", "{C:attention}1{}枚を選ぶ"}},
            p_kranlaxs_invtarot_instant_3_1 = {name = "反転タロットパック", text = {"最大{C:attention}3{}枚の{C:purple}反転タロット{}カードから", "{C:attention}1{}枚を選ぶ"}},
            p_kranlaxs_invtarot_instant_5_1 = {name = "ジャンボ反転タロットパック", text = {"最大{C:attention}5{}枚の{C:purple}反転タロット{}カードから", "{C:attention}1{}枚を選ぶ"}},
            p_kranlaxs_invtarot_instant_5_2 = {name = "メガ反転タロットパック", text = {"最大{C:attention}5{}枚の{C:purple}反転タロット{}カードから", "{C:attention}2{}枚を選ぶ"}},
            p_kranlaxs_invtarot_store_3_1 = {name = "保存された反転タロット", text = {"最大{C:attention}3{}枚の{C:purple}反転タロット{}カードから", "{C:attention}1{}枚を選ぶ"}},
            p_kranlaxs_invtarot_store_5_1 = {name = "保存されたジャンボ反転タロット", text = {"最大{C:attention}5{}枚の{C:purple}反転タロット{}カードから", "{C:attention}1{}枚を選ぶ"}},
            p_kranlaxs_invtarot_store_5_2 = {name = "保存されたメガ反転タロット", text = {"最大{C:attention}5{}枚の{C:purple}反転タロット{}カードから", "{C:attention}2{}枚を選ぶ"}}
        }
    },
    
    misc = {
        labels = {
            kranlaxs_magenta_sticker = "マゼンタステッカー",
            kranlaxs_brown_sticker = "ブラウンステッカー",
            kranlaxs_turquoise_sticker = "ターコイズステッカー",
            kranlaxs_platinum_sticker = "プラチナステッカー",
            kranlaxs_orangeseal_seal = "オレンジシール", 
            kranlaxs_pinkseal_seal = "ピンクシール", 
            kranlaxs_whiteseal_seal = "ホワイトシール", 
            kranlaxs_brownseal_seal = "ブラウンシール", 
            kranlaxs_grayseal_seal = "グレーシール", 
            kranlaxs_mintseal_seal = "ミントシール", 
            clover = "クローバーステッカー",
            kranlaxs_deviled_sticker = "デビルドステッカー",
            kranlaxs_glass_sticker = "グラスステッカー",
            p_kranlaxs_uno_store_3 = "UNO パック",
            p_kranlaxs_uno_store_5 = "ジャンボ UNO パック",
            p_kranlaxs_invtarot_instant_3_1 = "反転タロットパック",
            p_kranlaxs_invtarot_instant_5_1 = "ジャンボ反転タロットパック",
            p_kranlaxs_invtarot_instant_5_2 = "メガ反転タロットパック",
            p_kranlaxs_invtarot_store_3_1 = "保存された反転タロット",
            p_kranlaxs_invtarot_store_5_1 = "保存されたジャンボ反転タロット",
            p_kranlaxs_invtarot_store_5_2 = "保存されたメガ反転タロット",
            kranlaxs_wave = "水生"
        },

        v_text = {
            ch_c_kran_fijado_1 = {"すべてのジョーカーに{C:attention}固定{}ステッカーがつく"},
            ch_c_kran_abuela_1 = {"{C:attention}スコア加算{}ジョーカーは{C:red}禁止{}される"},
            ch_c_kran_crisis_1 = {"ショップが{C:attention}20%高くなる{}"},
            ch_c_kran_crisis_2 = {"ブラインドの基本報酬が {X:money,C:white} $2 {} {C:red}減少{}する"},
            ch_c_kran_crisis_3 = {"デッキが{C:attention}52枚のエース{}のみで構成される"},
            ch_c_kran_doppel_1 = {"すべてのジョーカーがショップから{C:red}禁止{}される"},
            ch_c_kran_anonimo_1 = {"手札のカードとジョーカーが{C:attention}裏向き{}になる"},
            ch_c_kran_jefes_1 = {"スモールとビッグブラインドが{C:attention}ボスブラインド{}になる"},
            ch_c_kran_premon_1 = {"手札のすべてのカードが{C:attention}裏向き{}になる"},
            ch_c_kran_tallo_1 = {"他の{C:attention}ジョーカー{}と{C:attention}パック{}は{C:red}禁止{}される"},
            ch_c_gacha_rule_1 = {"ショップに{C:attention}個別のカード{}は出現しない"},
            ch_c_kran_pobreza_1 = {"{C:common}コモン{}が{C:legendary}レジェンダリー{}になる確率が{C:attention}50%{}"},
            ch_c_kran_pobreza_2 = {"{C:attention}モンク{}ジョーカーが失望した場合、{C:red}ランに敗北する{}"}
        }
    }
}