return {
    descriptions = {
        Joker = {
            j_kranlaxs_tagger = {name = "태거", text = {"획득한 {C:attention}태그{}마다", "{C:red}+#1#{} 배수 획득", "{C:inactive}(현재 {C:red}+#2#{C:inactive} 배수){}"}, unlock = {"한 번의 런에서 {C:attention}빈 바우처{}를", "{C:attention}2{}번 구매하기"}},
            j_kranlaxs_Cashback = {name = "캐시백", text = {"카드 구매 시, {C:green}#1# / #2#{} 확률로", "{X:money,C:white} $3 {} 획득"}, unlock = {"{C:attention}우주 덱{}으로", "{C:attention}레드 스테이크{}에서 승리하기"}},
            j_kranlaxs_underratedjoker = {name = "과소평가된 조커", text = {"낸 카드가 가장 많이 낸 족보가 {C:attention}아닐{} 경우", "이 조커가 {X:chips,C:white} X0.2 {} 칩 획득", "{C:inactive}(맞을 경우 초기화됨){}", "{C:inactive}(현재 {X:chips,C:white} X#1# {C:inactive} 칩){}"}, unlock = {"{C:attention}우주 덱{}으로", "{C:attention}블루 스테이크{}에서 승리하기"}},
            j_kranlaxs_facelessaccountant = {name = "얼굴 없는 회계사", text = {"점수를 획득한 {C:attention}#2#{}마다", "이 조커가 {X:blue,C:white} X0.1 {} 칩 획득", "{C:inactive}(현재 {X:blue,C:white} X#1# {C:inactive} 칩){}"}, unlock = {"얼굴 카드를 내지 않고 승리하되,", "덱에 얼굴 카드가 최소 {C:attention}1{}장 있어야 함"}},
            j_kranlaxs_thefixer = {name = "해결사", text = {"{C:purple}블라인드{} 도중 {C:attention}조커{}를 판매하면", "요구 점수가 감소함", "{C:inactive}(커먼: -10%, 언커먼: -30%){}", "{C:inactive}(레어: -60%, 레전더리: -95%){}"}, unlock = {"모든 희귀도의 조커를", "각각 최소 {C:attention}2{}개씩 판매하기"}},
            j_kranlaxs_mysteriousgeode = {name = "신비한 정동석", text = {"점수를 획득한 {C:attention}와일드 카드{}마다", "{C:attention}무작위{} 효과 제공"}, unlock = {"{C:attention}와일드 카드{}가 {C:attention}5{}장", "포함된 패 내기"}},
            j_kranlaxs_benchwarmer = {name = "벤치워머", text = {"손패에 있는 가장 높은 랭크 카드의", "{C:blue}칩{} 가치의 {C:attention}4배{}를 제공함"}},
            j_kranlaxs_entropy2 = {name = "소용돌이", text = {"덱에 있는 {C:attention}52 미만{}의 카드마다", "{X:dark_edition,C:white} ^1 {} 배수 및 {X:dark_edition,C:white} ^1 {} 칩 획득", "{C:inactive}(현재 {X:dark_edition,C:white} ^#1# {C:inactive} 배수 및 {X:dark_edition,C:white} ^#1# {C:inactive} 칩){}"}},
            j_kranlaxs_greedyleprachaun = {name = "탐욕스러운 레프러콘", text = {"라운드의 첫 번째 {C:red}버리기{} 시,", "{C:attention}3장{}의 카드를 추가로 뽑음"}, unlock = {"정확히 {C:attention}1{}장의 카드를", "연속으로 {C:attention}3{}번 버리기"}},
            j_kranlaxs_charismaticbard = {name = "카리스마 넘치는 음유시인", text = {"손패 크기 {C:attention}-1{}", "{C:attention}가장 많이 낸 족보{}를 낼 때마다", "{C:purple}블라인드{} 요구치가 {C:attention}2%{} 감소함", "{C:inactive}(최대 90%){}", "다른 족보를 내면 초기화됨", "{C:inactive}(현재 {C:attention}-#1#%{C:inactive} 블라인드 감소){}"}},
            j_kranlaxs_russianroulette = {name = "러시안 룰렛", text = {"블라인드 선택 시,", "{C:green}#1# / #2#{} 확률로 {C:red}게임 오버{}", "살아남으면", "{X:mult,C:white} X3 {} 배수 및 {X:chips,C:white} X3 {} 칩 획득", "{C:inactive}(현재 {X:mult,C:white} X#3# {C:inactive} 배수 및 {X:chips,C:white} X#3# {C:inactive} 칩){}"}, unlock = {"{C:attention}우주 덱{}으로", "{C:attention}블랙 스테이크{}에서 승리하기"}},
            j_kranlaxs_fidelitycard = {name = "배틀 패스", text = {"카드를 {C:attention}6{}장 구매한 후,", "{C:attention}일곱 번째{} 구매하는 카드가 모든", "보유 조커의 {C:attention}판매 가치{}만큼 {X:money,C:white} 돈 {}을 제공함", "{C:inactive}(현재 {C:attention}#1#/6{C:inactive} 장){}", "{C:inactive}(총 판매 가치: {X:money,C:white} $#2# {C:inactive}){}"}},
            j_kranlaxs_devioussheep = {name = "탐욕스러운 양", text = {"{C:attention}블라인드{} 선택 시 무작위 조커를 {C:red}잡아먹고{}", "{X:mult,C:white} X0.4 {} 배수 획득", "다른 조커가 없으면 {C:hearts}게임 오버{}", "{C:inactive}(더 많은 배수를 위해 타겟을 우선시하세요!){}", "{C:inactive}(현재 {X:mult,C:white} X#1# {C:inactive} 배수){}"}},
            j_kranlaxs_lifeassurance = {name = "생명 보험", text = {"{X:money,C:white} $#1# {} 이상 보유하고 있을 시,", "게임 오버를 방지함", "{C:inactive}(사용할 때마다 가격 2배){}"}, unlock = {"{C:attention}앤티 8{} 이전에", "{X:money,C:white} $100 {} 이상을 가진 채로", "패배하기"}},
            j_kranlaxs_sundaycheckpoint = {name = "체크포인트", text = {"{C:attention}평일{}에 블라인드를", "선택하면 {C:red}게임 오버{}", "그렇지 않으면 라운드 종료 시", "{C:attention}주간 도전{} 조커를 생성하고 {C:red}자폭함{}", "{C:inactive}(현재 요일: #1#){}"}},
            j_kranlaxs_weeklychallenge = {name = "주간 도전", text = {"이 런에 무작위 도전을 설정함", "{C:clubs}현재 도전:{} {C:attention}#1#{}", "{C:inactive}1:{} {X:money,C:white} -$100 {} 보유, 앤티 8 전에 지불해야 함", "{C:inactive}2:{} 상점 제한", "{C:inactive}3:{} 1 손패, 20 버리기 (추가 바우처 없음)", "{C:inactive}4:{} 런 동안 {C:blue}#2#{} 손패 및 {C:red}#3#{} 버리기 제한", "{C:inactive}5:{} 게임 속도 0.5x로 고정", "{C:inactive}6:{} 3개의 이터널 트리불레 (최대 조커 3개, 빠른 앤티)", "{C:inactive}7:{} 블라인드 클리어 시 1/6 확률로 승리 (앤티 8에서 패배)"}},
            j_kranlaxs_panda = {name = "푹신한 판다", text = {"{C:chips}+#1#{} 칩 제공", "조커 슬롯 {C:attention}-1{}"}},
            j_kranlaxs_miner = {name = "광부", text = {"점수를 획득한 {C:attention}돌 카드{}마다", "{C:red}+5{} 배수 획득", "패를 낼 때, {C:green}#2# / #3#{} 확률로", "{X:money,C:white} $#4# {} ~ {X:money,C:white} $#5# {} 획득", "{C:inactive}(현재 {C:red}+#1#{C:inactive} 배수){}"}, unlock = {"{C:attention}돌 카드{}가 {C:attention}5{}장", "포함된 패 내기"}},
            j_kranlaxs_birthdaycake = {name = "생일 케이크", text = {"{X:dark_edition,C:white} ^#1# {} 배수 제공", "패를 낼 때마다", "{X:dark_edition,C:white} ^0.25 {} 감소함", "모두 소진되면 {C:attention}선물받은 조커{} 생성"}, unlock = {"{C:attention}주간 도전{} 덱으로", "{C:attention}블루 스테이크{}에서 승리하기"}},
            j_kranlaxs_vipsuscription = {name = "V.I.P. 구독", text = {"상점 슬롯 {C:attention}+#2#{}", "추가 바우처 및 팩 {C:attention}+1{}", "상점을 열 때 {X:money,C:white} $#1# {} 소모.", "{C:attention}보스 블라인드{} 클리어 시", "가격과 상점 크기가 {C:attention}증가함{}"}, unlock = {"{C:attention}주간 도전{} 덱으로", "{C:attention}오렌지 스테이크{}에서 승리하기"}},
            j_kranlaxs_painterjoker = {name = "화가 조커", text = {"손패에서 점수를 얻었을 때,", "손패에 있는 {C:attention}와일드 카드{}마다", "{C:attention}저글러 태그{} 생성", "{C:inactive}(태그당 {X:money,C:white} $#1# {C:inactive} 소모){}"}, unlock = {"{C:attention}주간 도전{} 덱으로", "{C:attention}오렌지 스테이크{}에서 승리하기"}},
            j_kranlaxs_coronation = {name = "대관식", text = {"낸 패에 랭크 {C:attention}10 이하{}의", "점수 획득 카드가 포함된 경우,", "가장 낮은 카드를 {C:attention}킹{}으로 변환함.", "손패에 낮은 카드가 없으면,", "점수를 얻은 첫 번째 {C:attention}킹{}에 {C:red}레드 실{} 추가."}, unlock = {"정확히 {C:attention}5장의 킹{}으로 구성된 패 내기.", "모두 {C:red}레드 실{}을 가져야 하며", "{C:attention}강철{} 카드여야 함"}},
            j_kranlaxs_speedrunner = {name = "스피드러너", text = {"{X:mult,C:white} X#1# {} 배수.", "패를 내거나 버리는 데", "{C:attention}#2#초{}의 시간 제한이 있음.", "시간이 초과되면 {C:red}게임 오버{}."}, unlock = {"{C:attention}주간 도전{} 덱으로", "{C:attention}그린 스테이크{}에서 승리하기"}},
            j_kranlaxs_passcode = {name = "비밀번호", text = {"낸 패가 다음 코드 중 하나와", "일치하는 경우, 해당 패는", "{C:attention}플러시 파이브{}로 간주됨", "{C:inactive}1. {C:attention}#1#{}", "{C:inactive}2. {C:attention}#2#{}", "{C:inactive}3. {C:attention}#3#{}"}, unlock = {"{C:attention}주간 도전{} 덱으로", "{C:attention}블랙 스테이크{}에서 승리하기"}},
            j_kranlaxs_chronometer = {name = "크로노미터", text = {"패를 낼 때: ", "현재 {C:attention}초{}와 같은 {C:chips}칩{} 제공", "현재 {C:attention}분{}과 같은 {C:mult}배수{} 제공", "현재 {C:attention}시간{}과 같은 {C:money}돈{} 획득", "{C:inactive}(현재: {C:chips}+#1#{C:inactive} 칩, {C:mult}+#2#{C:inactive} 배수, {C:money}+$#3#{C:inactive}){}"}, unlock = {"{C:attention}우주 덱{}으로", "{C:attention}골드 스테이크{}에서 승리하기"}},
            j_kranlaxs_zombiejoker = {name = "좀비 조카", text = {"{C:attention}점수{} 안주는 {C:attention}첫번쨰{} 카드", "파괴하구 {C:red}+15{} 배수 어듬", "근데 라운드에서 손패 낼때마다", "{C:red}-10{} 배수 일음", "{C:red}0{} 배수 대면", "{C:attention}쥬금 {}", "{C:inactive}(지금 {C:red}+#1#{C:inactive} 배수쯤 이씀){}"}, unlock = {"{C:attention}우주 덱{}으로", "{C:attention}퍼플 스테이크{}에서 승리하기"}},
            j_kranlaxs_thecousin = {name = "사촌", text = {"점수를 획득한 {C:attention}소수{}마다", "{C:chips}+13{} 칩 획득", "{C:inactive}(현재 {C:chips}+#1#{C:inactive} 칩){}"}, unlock = {"{C:attention}우주 덱{}으로", "{C:attention}청록색 스테이크{}에서 승리하기"}},
            j_kranlaxs_colasoda = {name = "콜라 소다", text = {"{X:dark_edition,C:white} ^#1# {} 배수 제공", "당신이 취하는 거의 {C:attention}모든 행동{}에 대해", "{X:dark_edition,C:white} ^#2# {} 감소함"}, unlock = {"{C:attention}주간 도전{} 덱으로", "{C:attention}블루 스테이크{}에서 승리하기"}},
            j_kranlaxs_icecreamsandwich = {name = "아이스크림 샌드위치", text = {"라운드 종료 시", "{X:money,C:white} $#1# {} 획득", "라운드가 끝날 때마다", "보상이 {X:money,C:white} $#2# {} 감소함"}, unlock = {"한 라운드의 지불금으로", "{X:money,C:white} $50 {} 이상", "획득하기"}},
            j_kranlaxs_dispensermachine = {name = "자판기", text = {"상점을 나갈 때 이 조커가", "{C:attention}선택{}되어 있으면, {X:money,C:white} $#1# {} 소모 후", "{C:attention}음식 조커{} 생성"}, unlock = {"음식 조커를", "{C:attention}4{}개 동시에 소유하기"}},
            j_kranlaxs_bottledwater = {name = "생수", text = {"{X:chips,C:white} X#1# {} 칩", "점수를 획득한 카드마다", "{X:chips,C:white} X#2# {} 감소함"}, unlock = {"{C:attention}주간 도전{} 덱으로", "{C:attention}블루 스테이크{}에서 승리하기"}},
            j_kranlaxs_burrow = {name = "토끼굴", text = {"{C:attention}블라인드를 클리어{}할 때마다", "토끼 {C:attention}+1{}마리 획득", "{C:gold}판매{} 시, 토끼 {C:attention}#1#{}마리 생성"}},
            j_kranlaxs_bunny = {name = "토끼", text = {"소유한 {C:attention}토끼{} 조커마다", "{X:mult,C:white} X#1# {} 배수 획득", "{C:inactive}(현재 {X:mult,C:white} X#2# {C:inactive} 배수){}"}},
            j_kranlaxs_sushi = {name = "스시", text = {"블라인드 요구치를", "{C:attention}#1#%{} 감소시킴", "{C:attention}블라인드{} 클리어 후", "감소율이 {C:attention}#2#%{} 줄어듦"}, unlock = {"{C:attention}주간 도전{} 덱으로", "{C:attention}퍼플 스테이크{}에서 승리하기"}},
            j_kranlaxs_gigachad = {name = "기가채드", text = {"당신이 취하는 거의 {C:attention}모든 행동{}에 대해", "{C:chips}+#2#{} 칩 획득", "{C:inactive}(현재 {C:chips}+#1#{C:inactive} 칩){}"}, unlock = {"{C:attention}주간 도전{} 덱으로", "{C:attention}화이트 스테이크{}에서 승리하기"}},
            j_kranlaxs_nft = {name = "암호화폐 사기", text = {"손패에서 점수를 냈을 때,", "손패에 있는 모든 카드의", "{C:attention}랭크{}를 {C:attention}1{} 감소시킴", "{C:inactive}(2 미만으로 줄일 수 없음){}"}},
            j_kranlaxs_beanstalk = {name = "콩나무", text = {"쓸모없는 콩들"}, unlock = {"{C:attention}주간 도전{} 덱으로", "{C:attention}화이트 스테이크{}에서 승리하기"}},
            j_kranlaxs_suspiciousbeanstalk = {name = "수상한 콩나무", text = {"쓸모없는 콩들?..."}},
            j_kranlaxs_epicbeanstalk = {name = "에픽 콩나무", text = {"어쩌면 쓸모없는 콩이 아닐지도..."}},
            j_kranlaxs_zenithbeanstalk = {name = "제니스 콩나무", text = {"콩"}},
            j_kranlaxs_commonseed = {name = "커먼 씨앗", text = {"무작위 {C:common}커먼{}", "조커 {C:attention}생성{}"}},
            j_kranlaxs_weirdlookingseed = {name = "기묘한 씨앗", text = {"무작위 {C:uncommon}언커먼{}", "조커 {C:attention}생성{}"}},
            j_kranlaxs_magnificentseed = {name = "장엄한 씨앗", text = {"무작위 {C:rare}레어{}", "조커 {C:attention}생성{}"}},
            j_kranlaxs_godseed = {name = "신의 씨앗", text = {"무작위 {C:legendary}레전더리{}", "조커 {C:attention}생성{}"}},
            j_kranlaxs_anonymousjoker = {name = "익명 조커", text = {"점수 계산 시 뒤집어지며", "{X:mult,C:white} X1.5 {} ~ {X:mult,C:white} X4.0 {} 배수 제공"}, unlock = {"{C:attention}호박색 도토리{} 보스 블라인드", "1회 클리어"}},
            j_kranlaxs_littlebro = {name = "리틀 브로", text = {"낸 패가 {C:attention}하이 카드{}이고", "점수 카드가 {C:attention}#2#{}인 경우,", "이 조커가 {X:red,C:white} X#3# {} 배수 획득", "카드 랭크는 라운드마다 바뀜", "{C:inactive}(현재 {X:red,C:white} X#1# {C:inactive} 배수){}"}, unlock = {"한 런에서 {C:attention}하이 카드{}를", "{C:attention}30{}번 내기"}},
            j_kranlaxs_medusa = {name = "메두사", text = {"패를 낸 후,", "{C:attention}낸 모든 카드{}가 영구적으로", "{C:attention}돌 카드{}가 됨", "{C:inactive}(점수를 얻지 못한 카드 포함){}"}, unlock = {"{C:attention}우주 덱{}으로", "{C:attention}브라운 스테이크{}에서 승리하기"}},
            j_kranlaxs_depression = {name = "경제 불황", text = {"{X:dark_edition,C:white}^#2#{} 배수 제공", "{X:money,C:white} $0 {} 미만의 {X:money,C:white} $1 {}당", "{X:dark_edition,C:white}^#1#{} 증가"}, unlock = {"{X:money,C:white} -$25 {} 이하의 돈으로", "상점에 입장"}},
            j_kranlaxs_grannyjoker = {name = "할머니", text = {"{X:dark_edition,C:white} ^3 {} 칩 및 {X:dark_edition,C:white} ^3 {} 배수 제공", "게임 속도가 {C:attention}0.25x{}로 고정됨", "{C:inactive}({C:attention}스트레이트{} 또는 {C:attention}스트레이트 플러시{}", "{C:inactive}를 내면 파괴됨){}"}, unlock = {"게임 속도 {C:attention}0.5{}에서", "블라인드 {C:attention}12{}회 클리어"}},
            j_kranlaxs_lateshippment = {name = "지연 배송", text = {"{C:attention}이전 라운드{}에서", "낸 핸드 1개당 {C:attention}모든 낸 카드{}를", "{C:attention}1회{} 재발동함", "{C:inactive}(현재 {C:attention}#1#{C:inactive}회 재발동){}"}, unlock = {"{C:attention}우주 덱{}으로", "{C:attention}오렌지 스테이크{}에서 승리하기"}},
            j_kranlaxs_unkownfactor = {name = "변수 X", text = {"낸 모든 카드가", "{C:attention}#1#{}(으)로 간주됨", "{C:inactive}(라운드 종료 시 랭크 변경){}"}, unlock = {"{C:attention}주간 도전{} 덱으로", "{C:attention}골드 스테이크{}에서 승리하기"}},
            j_kranlaxs_thethreers = {name = "3R", text = {"낸 각 카드의 {C:attention}복사본{}을", "만들어 {C:attention}덱{}에 추가함", "점수를 얻은 모든 카드를 {C:attention}파괴함{}"}, unlock = {"{C:attention}주간 도전{} 덱으로", "{C:attention}골드 스테이크{}에서 승리하기"}},
            j_kranlaxs_the = {name = "Jok", text = {"라운드의 {C:attention}첫 번째 패{}에서만", "{X:chips,C:white} X2 {} 칩 및 {X:mult,C:white} X2 {} 배수 제공"}, unlock = {"각각 {C:attention}1{}번의 핸드만 사용하여", "블라인드 {C:attention}5{}회 클리어"}},
            j_kranlaxs_chainreaction = {name = "연쇄 반응", text = {"낸 패가 {C:attention}#2#{}인 경우,", "{X:chips,C:white} X0.5 {} 칩을 얻고 패 조건이 바뀜", "패가 {C:attention}일치하지 않으면{} 초기화", "{C:inactive}(현재 {X:chips,C:white} X#1# {C:inactive} 칩){}"}, unlock = {"한 런에서 모든 포커 족보를", "최소 {C:attention}1{}회씩 내기"}},
            j_kranlaxs_anubis = {name = "아누비스", text = {"손패에서 점수를 얻었을 때,", "{C:blue}칩{}과 {C:red}배수{}의 균형을 맞춤"}, unlock = {"모든 스테이크 난이도에서", "{C:attention}플라즈마 덱{}으로 승리하기"}},
            j_kranlaxs_erraticjoker = {name = "불규칙한 조커", text = {"점수 카드가", "{C:attention}와일드 카드{}인 경우, {C:blue}칩{}과", "{C:red}배수{}를 스왑함"}, unlock = {"{C:attention}우주 덱{}으로", "{C:attention}화이트 스테이크{}에서 승리하기"}},
            j_kranlaxs_luckyseven = {name = "럭키 세븐", text = {"낸 패가 정확히 {C:attention}7{}로만", "구성된 {C:attention}트리 플러시{}인 경우, 이 조커가", "{C:blue}+7{} 칩, {C:red}+7{} 배수를 얻고 {X:money,C:white} $7 {} 제공", "{C:inactive}(현재 {C:blue}+#1#{} 칩, {C:red}+#2#{} 배수)"}, unlock = {"덱에 랭크 {C:attention}7{} 카드를", "최소 {C:attention}10{}장 보유하기"}},
            j_kranlaxs_certificateddocument = {name = "인증서", text = {"{C:attention}모든{} 실을 재발동함"}, unlock = {"{C:attention}주간 도전{} 덱으로", "{C:attention}퍼플 스테이크{}에서 승리하기"}},
            j_kranlaxs_platanito = {name = "리틀 바나나", text = {"다른 조커가 발동될 때마다,", "{X:mult,C:white} X#3# {} 추가 배수 제공", "라운드 종료 시 {C:green}#1# / #2#{} 확률로", "파괴됨"}, unlock = {"{C:attention}우주 덱{}으로", "{C:attention}플래티넘 스테이크{}에서 승리하기"}},
            j_kranlaxs_cubicaljoker = {name = "큐빅 조커", text = {"{C:mult}+#1#{} 배수 제공", "클리어한 {C:attention}보스 블라인드{}마다", "가치가 {C:attention}세제곱 (^3){} 됨"}},
            j_kranlaxs_grapesoda = {name = "포도 소다", text = {"{C:gold}판매{} 시, {C:dark_edition}네거티브{} 에디션의", "무작위 {C:spectral}스펙트럴{} 카드를", "생성함"}, unlock = {"{C:attention}우주 덱{}으로", "{C:attention}마젠타 스테이크{}에서 승리하기"}},
            j_kranlaxs_telescope = {name = "망원경", text = {"{C:attention}#1#{}의 레벨이 오르면,", "해당 족보의 레벨이 {C:attention}1{}번 추가로 오름", "{C:inactive}(라운드 종료 시 조건 변경){}"}, unlock = {"{C:attention}주간 도전{} 덱으로", "{C:attention}레드 스테이크{}에서 승리하기"}},
            j_kranlaxs_pandorabox = {name = "판도라의 상자", text = {"{C:attention}보스 블라인드{} 클리어 시,", "현재 덱을 기반으로", "{C:attention}유용한{} 조커 생성", "{C:inactive}(빈 공간 필요){}"}},
            j_kranlaxs_doppelganger = {name = "도플갱어", text = {"게임 전체에서 무작위", "{C:attention}조커{}의 능력을 복사함.", "복사한 조커는 {C:attention}블라인드{}를", "클리어한 후 변경됨.", "{C:inactive}(현재: {C:attention}#1#{C:inactive})"}, unlock = {"{C:attention}주간 도전{} 덱으로", "{C:attention}골드 스테이크{}에서 승리하기"}},
            j_kranlaxs_thechampion = {name = "챔피언", text = {"블라인드 요구치 {C:attention}X#1#{}", "라운드 종료 시 {X:money,C:white} $#2# {} 획득"}, unlock = {"{C:attention}앤티 16{} 도달하기"}},
            j_kranlaxs_clerigo = {name = "성직자", text = {"풀 덱에 있는 카드마다", "{C:mult}+#1#{} 배수 제공", "강화 또는 실이 있는 카드마다", "{C:mult}-#2#{} 배수 손실", "{C:inactive}(현재 {C:mult}+#3#{C:inactive} 배수){}"}, unlock = {"도전 완료:", "{C:attention}가족 레시피{}"}},
            j_kranlaxs_entrenador = {name = "코치", text = {"앤티 {C:attention}#3#{} 미만인 경우,", "{X:mult,C:white} X#1# {} 배수 제공", "그 외에는 {X:mult,C:white} X#2# {} 배수 제공", "{C:inactive}(현재 {X:mult,C:white} X#4# {C:inactive} 배수){}"}, unlock = {"도전 완료:", "{C:attention}경제 위기{}"}},
            j_kranlaxs_medium = {name = "영매", text = {"프로필의 {C:red}패배한{} 런마다", "{C:mult}+#1#{} 배수 제공", "{C:inactive}(현재 {C:mult}+#2#{C:inactive} 배수){}"}, unlock = {"런에서 {C:attention}1{}회 패배", "{C:inactive}(진행도: {C:attention}#1#{C:inactive} / 1){}"}},
            j_kranlaxs_monk = {name = "수도사", text = {"{X:money,C:white} 돈 {}을 쓰지 않고 상점을 나가면", "{X:chips,C:white} X#1# {} 칩 획득", "무언가를 구매하면 {C:red}초기화됨{}", "{C:inactive}(현재 {X:chips,C:white} X#2# {C:inactive} 칩){}"}, unlock = {"도전 완료:", "{C:attention}청빈의 맹세{}"}},
            j_kranlaxs_knight = {name = "기사", text = {"{C:attention}강철{} 카드로 {C:attention}#1#{}번 점수를 얻으면,", "다음 {C:attention}보스 블라인드{}를 {C:attention}비활성화{}함", "{C:inactive}(점수 얻은 카드: #2#/#1#){}"}, unlock = {"도전 완료:", "{C:attention}보스 신디케이트{}"}},
            j_kranlaxs_overpopulation = {name = "인구 과잉", text = {"덱에 제한치 {C:attention}#2#{}장을 초과하는", "{C:attention}얼굴 카드{}마다", "{C:mult}+#1#{} 배수 제공", "{C:inactive}(현재 {C:mult}+#3#{C:inactive} 배수){}"}, unlock = {"{C:attention}우주 덱{}으로", "{C:attention}그린 스테이크{}에서 승리하기"}},
            j_kranlaxs_antisocial = {name = "반사회적", text = {"정확히 {C:attention}1{}장의 카드를 내면", "이 조커가 {C:mult}+#1#{} 배수 획득", "1장 이상을 내면 {C:red}초기화됨{}", "{C:inactive}(현재 {C:mult}+#2#{C:inactive} 배수){}"}, unlock = {"도전 완료:", "{C:attention}완전한 집착{}"}},
            j_kranlaxs_famous = {name = "유명인사", text = {"낸 패가 {C:attention}파이브 카인드{},", "{C:attention}플러시 파이브{} 또는 {C:attention}플러시 하우스{}인 경우", "{C:chips}+#1#{} 칩 제공"}},
            j_kranlaxs_influencer = {name = "인플루언서", text = {"낸 패가 {C:attention}파이브 카인드{},", "{C:attention}플러시 파이브{} 또는 {C:attention}플러시 하우스{}인 경우", "{C:mult}+#1#{} 배수 제공"}},
            j_kranlaxs_potatobag = {name = "감자 자루", text = {"점수 칩을 누적함", "{C:attention}#1#{}에 도달하면 다음 핸드에", "{X:mult,C:white} X#2# {} 배수를 적용하고 비움", "{C:inactive}(누적: #3#/#1#){}"}},
            j_kranlaxs_simonsays = {name = "사이먼 가라사대", text = {"요구 사항을 완료하면,", "이 조커가 {X:mult,C:white} X#2# {} 배수 획득", "사이먼 가라사대... {C:attention}#3#{}", "{C:inactive}(현재 {X:mult,C:white} X#1# {C:inactive} 배수){}"}, unlock = {"도전 완료:", "{C:attention}거대한 콩나무{}"}},
            j_kranlaxs_cheater = {name = "치터", text = {"상점의 조커가", "{C:green}35%{} 확률로", "{C:attention}바우처{} 또는 {C:attention}부스터 팩{}으로 대체됨"}, unlock = {"도전 완료:", "{C:attention}가챠폰{}"}},
            j_kranlaxs_philosopher = {name = "철학자", text = {"덱의 다음 {C:attention}5장 카드{}를 공개함", "{C:inactive}(각 카드는 20% 확률로{}", "{C:inactive}가려진 상태 유지){}", "{C:attention}#1#{}"}, unlock = {"도전 완료:", "{C:attention}예지몽{}"}},
            j_kranlaxs_mandalajoker = {name = "만다라 조커", text = {"사용한 {C:spectral}스펙트럴{} 카드마다", "이 조커가 {X:mult,C:white} X0.5 {} 배수 획득", "{C:inactive}(현재 {X:mult,C:white} X#1# {C:inactive} 배수){}"}, unlock = {"{C:attention}20{}장의 {C:spectral}스펙트럴{} 카드 사용하기", "{C:inactive}(진행도: {C:attention}#1#{C:inactive} / 20){}"}},
            j_kranlaxs_regift = {name = "선물받은 조커", text = {"{C:gold}판매{} 시,", "무작위 {C:attention}조커{}를 생성함", "희귀도는 현재 {C:attention}블라인드{}에 따라 다름"}, unlock = {"총 {C:attention}50{}개의 조커 판매하기", "{C:inactive}(진행도: {C:attention}#1#{C:inactive} / 50){}"}},
            j_kranlaxs_pyromaniac = {name = "방화범", text = {"핸드 점수를 얻은 후, 손패에 있는", "모든 {C:attention}숫자{} 카드를 {C:red}파괴함{}", "{C:inactive}(골드, 유리 및 강철 카드는 안전함){}"}, unlock = {"얼굴 카드가 아닌 카드를", "{C:attention}100{}장 파괴하기", "{C:inactive}(진행도: {C:attention}#1#{C:inactive} / 100){}"}},
            j_kranlaxs_neverendinggambling = {name = "끝없는 도박", text = {"행동을 취할 때마다 {X:money,C:white} $1 {} 잃음", "{C:inactive}({X:money,C:white} $5 {} 이상 있을 때만){}", "숫자 3개 회전. 일치하면 상품 획득!", "2개가 일치하면 위로금으로 {X:money,C:white} $1 {} 회수", "{C:inactive}(현재 회전: #1# - #2# - #3#){}"}, unlock = {"조커 또는 소비 카드 확률을", "{C:attention}30{}번 빗나가기", "{C:inactive}(진행도: {C:attention}#1#{C:inactive} / 30){}"}},
            j_kranlaxs_solarsystem = {name = "태양계", text = {"{C:attention}라운드 종료 시{}, 정해진 순서대로", "{C:planet}플래닛{} 카드 생성", "{C:inactive}(다음 행성: {C:planet}#1#{C:inactive}){}"}, unlock = {"한 런에서 모든 {C:attention}12{}종류의 기본", "{C:planet}플래닛{} 카드를 한 번씩 사용하기", "{C:inactive}(진행도: {C:attention}#1#{C:inactive} / 12){}"}},
            j_kranlaxs_deranged = {name = "광기", text = {"{C:mult}+#1#{} 배수 또는 {C:chips}+#2#{} 칩 제공", "핸드를 낼 때마다", "효과가 바뀜"}, unlock = {"도전 완료:", "{C:attention}정체성 위기{}"}},
            j_kranlaxs_deranged_mult = {name = "광기", text = {"{C:mult}+#1#{} 배수 제공", "핸드를 낼 때마다", "효과가 바뀜"}},
            j_kranlaxs_deranged_chips = {name = "광기", text = {"{C:chips}+#2#{} 칩 제공", "핸드를 낼 때마다", "효과가 바뀜"}},
            j_kranlaxs_tmtrainer = {name="TMTRAINER",text={"{C:dark_edition}#1#{}","{C:attention}#2#{}","{C:red}#3#{}","{C:chips}#4#{}"},unlock={"도전 완료:","{C:attention}정체성 위기{}"}},
            j_kranlaxs_bingocard = {name = "빙고 카드", text = {"완성된 줄마다", "{X:mult,C:white} X0.25 {} 배수 획득", "{C:inactive}(총합: {X:mult,C:white} X#2# {C:inactive} 배수){}", "{C:attention}#3#{}", "{C:attention}#4#{}", "{C:attention}#5#{}", "{C:attention}#6#{}", "{C:attention}#7#{}"}, unlock = {"도전 완료:", "{C:attention}완전한 익명성{}"}}
        },

        Back = {
            b_kranlaxs_week_challenge = {name = "주간 도전", text = {"{C:attention}주간 도전{} 조커와 함께 시작함", "매 {C:attention}주말{}마다 {C:red}클리어 가능{}"}, unlock = {"{C:attention}토요일{} 또는 {C:attention}일요일{}에", "게임 실행하기"}},
            b_kranlaxs_chaos_deck = {name = "혼돈의 덱", text = {"혼돈을 즐기세요"}, unlock = {"컬렉션의 {C:legendary,E:1}모든 것{}을", "해금하기"}},
            b_kranlaxs_dungeon_deck = {name = "던전 덱", text = {"{C:attention}보스 블라인드{} 클리어 후,", "{C:green}장점{}과 {C:red}단점{}이 있는", "3개의 {C:attention}옵션{} 중 하나를 선택함"}, unlock = {"{C:attention}주간 도전{} 덱으로", "{C:attention}그린 스테이크{} 이상에서 승리하기"}},
            b_kranlaxs_space_deck = {name = "우주 덱", text = {"조커 슬롯 {C:attention}0{}개, 소비 아이템 슬롯 {C:attention}5{}개", "상점은 {C:attention}석영{}만 판매함", "상점 크기 {C:attention}+1{}, 블라인드 {C:attention}7.5%{} 감소", "승리 앤티: {C:attention}10{}"}, unlock = {"{C:attention}마법 덱{}, {C:attention}성운 덱{},", "그리고 {C:attention}황도 덱{}으로", "{C:attention}그린 스테이크{}에서 승리하기"}},
            b_kranlaxs_bugged_deck = {name = "버그 덱", text = {"!?"}, unlock = {"처음으로 {C:attention}TMTRAINER{}를", "획득하기"}}
        },

        Stake = {
            stake_kranlaxs_magenta = {name = "마젠타 스테이크", text = {"상점 카드에 {C:attention}고정{} 스티커가", "붙을 수 있음"}},
            stake_kranlaxs_brown = {name = "브라운 스테이크", colour = "브라운", text = {"상점의 {C:attention}부스터 팩{} 슬롯 {C:attention}-1{}"}},
            stake_kranlaxs_turquoise = {name = "청록색 스테이크", colour = "청록색", text = {"블라인드가 {C:red}건너뛰기 불가{}가", "될 확률 {C:attention}50%{}"}},
            stake_kranlaxs_deviled = {name = "데블드 스테이크", colour = "데블드", text = {"{C:attention}조커{} 슬롯 {C:attention}-1{}"}},
            stake_kranlaxs_glass = {name = "글래스 스테이크", colour = "글래스", text = {"각 {C:attention}앤티{}마다 요구 점수가", "훨씬 더 빠르게 증가함"}},
            stake_kranlaxs_platinum = {name = "플래티넘 스테이크", colour = "플래티넘", text = {"게임에서 승리하려면", "{C:attention}앤티 10{}을 클리어해야 함"}}
        },

        UNOCards = {
            c_kranlaxs_skip = {name = "스킵", text = {"{C:attention}즉시{} 블라인드 요구치를 달성함", "{C:attention}보스 블라인드{}에는 통하지 않음"}},
            c_kranlaxs_stacking = {name = "스태킹", text = {"손패에서 선택한 {C:attention}1{}장의 카드에", "{C:attention}핑크 실{}을 추가함"}},
            c_kranlaxs_draw2 = {name = "드로우 2", text = {"사용 시, 손패로 카드를 {C:attention}2장 더 뽑음{}", "손패 {C:blue}1{} 잃음"}},
            c_kranlaxs_draw4 = {name = "드로우 4", text = {"사용 시, 손패로 카드를 {C:attention}4장 더 뽑음{}", "손패 {C:blue}1{} 잃음"}},
            c_kranlaxs_reverse = {name = "리버스", text = {"손패의 {C:attention}모든 카드{}를", "덱으로 돌려보내고 {C:attention}다시 섞음{}"}},
            c_kranlaxs_wildcard = {name = "와일드 카드", text = {"손패의 각 카드를 {C:attention}독립적으로{}", "{C:attention}무작위 무늬{}로 {C:attention}변환{}함"}},
            c_kranlaxs_replay = {name = "리플레이", text = {"마지막으로 낸 패의 카드를", "손패로 되돌림", "{C:inactive}(사용 후 또는 라운드", "{C:inactive}종료 시 초기화됨)"}},
            c_kranlaxs_discardall = {name = "모두 버리기", text = {"선택한 카드 {C:attention}1{}장이 필요함.", "손패와 덱에서 같은 무늬를 공유하는", "{C:red}모든{} 카드를 버림"}},
            c_kranlaxs_shield = {name = "실드", text = {"죽음으로부터 패시브로 보호하거나", "판매하여 {C:attention}보스 블라인드{}를 비활성화할 수 있음"}},
            c_kranlaxs_misery = {name = "비참함", text = {"{C:attention}무늬{}를 선택하세요.", "해당 무늬를 얻을 때까지", "덱에서 카드를", "계속해서 뽑음"}},
            c_kranlaxs_gift = {name = "선물", text = {"다음 무작위 보상 중", "{C:attention}1{}개를 줌:", "• 에디션이 있는 {C:attention}조커{}", "• 네거티브 {C:attention}소비 카드{}", "• 강화, 실 및 에디션이 있는 {C:attention}카드{}"}},
            c_kranlaxs_customdraw = {name = "커스텀 드로우", text = {"버린 횟수만큼의", "카드를 뽑음", "{C:inactive}(현재: {C:attention}#1#{C:inactive} 장){}"}}
        },

        InverseTarot = {
            c_kranlaxs_thefool = {name = "바보?", text = {"무작위 {C:spectral}스펙트럴{} 카드 생성", "무작위 포커 족보의 레벨 {C:attention}하락{}"}},
            c_kranlaxs_themagician = {name = "마술사?", text = {"무작위 {C:attention}럭키{} 카드 {C:attention}2{}장 생성"}},
            c_kranlaxs_thehighpriestess = {name = "여사제?", text = {"{C:spectral}블랙홀{} 생성", "{X:money,C:white} 돈 {}이 20% {C:attention}감소{}함"}},
            c_kranlaxs_theempress = {name = "여황제?", text = {"선택한 카드 최대 {C:attention}2{}장에", "영구적인 {C:red}+8{} 배수 추가"}},
            c_kranlaxs_theemperor = {name = "황제?", text = {"무작위 {C:attention}태그{} {C:attention}2{}개 생성"}},
            c_kranlaxs_thehierophant = {name = "교황?", text = {"선택한 카드 최대 {C:attention}2{}장에", "영구적인 {C:blue}+40{} 칩 추가"}},
            c_kranlaxs_thelovers = {name = "연인?", text = {"덱에 {C:attention}와일드 카드{}가 있으면", "손패 크기 {C:attention}+1{} 획득"}},
            c_kranlaxs_thechariot = {name = "전차?", text = {"{C:attention}레드{} 실이 있는 무작위", "{C:attention}강철{} 카드 {C:attention}1{}장 생성"}},
            c_kranlaxs_justice = {name = "정의?", text = {"선택한 {C:attention}1{}장의 카드에", "영구적인 {X:red,C:white} X2 {} 배수 추가", "{C:green}#1# / #2#{} 확률로 이 카드를 {C:attention}파괴{}함"}},
            c_kranlaxs_thehermit = {name = "은둔자?", text = {"{X:money,C:white} $25 {} {C:attention}미만{}일 경우,", "{X:money,C:white} 돈 {}을 {X:money,C:white} $25 {}(으)로 {C:attention}설정{}함"}},
            c_kranlaxs_thewheeloffortune = {name = "운명의 수레바퀴?", text = {"{C:green}#1# / #2#{} 확률로 {C:dark_edition}네거티브{} 에디션의", "무작위 조커 {C:attention}복사본{} 생성"}},
            c_kranlaxs_strenght = {name = "힘?", text = {"선택한 카드 최대 {C:attention}2{}장의", "{C:attention}랭크{}를 {C:attention}1{} {C:attention}감소{}시킴"}},
            c_kranlaxs_thehangedman = {name = "매달린 사람?", text = {"손패에 있는 선택한 카드 최대 {C:attention}2{}장을", "완전히 {C:attention}무작위화{}함"}},
            c_kranlaxs_death = {name = "죽음?", text = {"무작위 조커의 {C:attention}네거티브 복사본{} 생성", "무작위 조커가 {C:attention}페리셔블{} 스티커를 받음"}},
            c_kranlaxs_temperance = {name = "절제?", text = {"{C:attention}모든{} 조커(이터널 포함)를", "판매 가치의 {C:money}3배{}로 판매함", "{C:inactive}(고정 조커는 판매하지 않음){}"}},
            c_kranlaxs_thedevil = {name = "악마?", text = {"선택한 카드 최대 {C:attention}2{}장에", "영구적인 {X:money,C:white} $2 {} 추가"}},
            c_kranlaxs_thetower = {name = "탑?", text = {"손패의 카드에서 모든 강화, 실,", "에디션 및 보너스를 {C:attention}제거{}함", "제거된 수정 사항당 {X:money,C:white} $1 {} 획득"}},
            c_kranlaxs_thestars = {name = "별?", text = {"선택한 카드 최대 {C:attention}2{}장에", "{C:attention}화이트 실{} 추가"}},
            c_kranlaxs_themoon = {name = "달?", text = {"선택한 카드 최대 {C:attention}2{}장에", "{C:attention}그레이 실{} 추가"}},
            c_kranlaxs_thesun = {name = "태양?", text = {"선택한 카드 최대 {C:attention}2{}장에", "{C:attention}오렌지 실{} 추가"}},
            c_kranlaxs_judgement = {name = "심판?", text = {"무작위 {C:attention}바우처{} 교환", "손패 크기 {C:red}-1{}"}},
            c_kranlaxs_theworld = {name = "세계?", text = {"선택한 카드 최대 {C:attention}2{}장에", "{C:attention}브라운 실{} 추가"}}
        },

        Voucher = {
            v_kranlaxs_more_stock = {name = "재고 추가", text = {"상점에 {C:attention}부스터 팩{} 슬롯이", "{C:attention}1{}개 추가됨"}},
            v_kranlaxs_even_more_stock = {name = "재고 더 추가", text = {"상점에 {C:attention}바우처{} 슬롯이", "{C:attention}1{}개 추가됨"}},
            v_kranlaxs_shiny_appearance = {name = "희귀한 등장", text = {"레전더리 카드와 레어 소비 아이템이", "이제 상점에 나타날 수 있음"}},
            v_kranlaxs_stickerfever = {name = "스티커 피버", text = {"{C:attention}태그{}를 얻을 때마다,", "추가 복사본 {C:attention}1{}개 획득"}},
            v_kranlaxs_stickeralbum = {name = "스티커 앨범", text = {"{C:attention}태그{}를 얻을 때마다,", "추가 복사본을 {C:attention}1{}개 더 획득"}},
            v_kranlaxs_hotfix = {name = "핫픽스", text = {"상점을 {C:attention}리롤{}하면", "{C:attention}바우처{}와 {C:attention}부스터 팩{}도 갱신됨"}},
            v_kranlaxs_version2 = {name = "버전 2.0", text = {"블라인드를 건너뛰면 해당 블라인드의", "{X:money,C:white} 돈 {} 보상을 줌.", "블라인드 요구치 {C:attention}-15%{}"}},
            v_kranlaxs_common_shinys = {name = "레전더리 목격", text = {"레전더리 카드와 레어 소비 아이템이", "더 자주 나타남"}},
            v_kranlaxs_blessing = {name = "축복", text = {"각 블라인드에서 칩 요구치의", "{C:attention}10%{}가 완료된 상태로 시작함"}},
            v_kranlaxs_protection = {name = "신의 가호", text = {"{C:attention}게임 오버{}로부터 보호함.", "사용 시 이 바우처는 파괴되며", "상점에 다시 나타날 수 있지만,", "원래 가격의 {X:money,C:white} 2배 {}가 됨"}}
        },

        Quartz = {
            c_kranlaxs_blackquartz = {name = "흑요석", text = {"원하는 대로", "일부 규칙을 수정함"}, unlock = {"{C:attention}매직 덱{}으로", "{C:attention}브라운 스테이크{}에서 승리하기"}},
            c_kranlaxs_whitequartz = {name = "진주", text = {"마지막으로 사용한", "소비 아이템 생성", "{C:inactive}(마지막 카드: {C:attention}#1#{C:inactive}){}"}, unlock = {"{C:attention}고스트 덱{}으로", "{C:attention}브라운 스테이크{}에서 승리하기"}},
            c_kranlaxs_pinkquartz = {name = "장미석영", text = {"선택한 {C:attention}조커{}나", "{C:attention}카드{}에 {C:dark_edition}폴리크롬{} 추가"}, unlock = {"{C:attention}던전 덱{}으로", "{C:attention}마젠타 스테이크{} 이상에서 승리하기"}},
            c_kranlaxs_bluequartz = {name = "사파이어", text = {"선택한 {C:attention}조커{}나 {C:attention}카드{}에", "{C:chips}포일{} 추가"}, unlock = {"{C:attention}플라즈마 덱{}으로", "{C:attention}플래티넘 스테이크{}에서 승리하기"}},
            c_kranlaxs_lilacquartz = {name = "쿤차이트", text = {"선택한 {C:attention}조커{}나 {C:attention}카드{}에", "{C:mult}홀로그래픽{} 추가"}, unlock = {"{C:attention}성운 덱{}으로", "{C:attention}브라운 스테이크{}에서 승리하기"}},
            c_kranlaxs_grayquartz = {name = "적철석", text = {"선택한 {C:attention}조커{}나", "{C:attention}소비 아이템{}에 {C:dark_edition}네거티브{} 추가"}, unlock = {"{C:attention}페인트 덱{}으로", "{C:attention}청록색 스테이크{}에서 승리하기"}},
            c_kranlaxs_transparentquartz = {name = "다이아몬드", text = {"{C:attention}조커{}의 모든 스티커나 에디션을,", "또는 선택한 {C:attention}카드{}의 실이나", "에디션을 {C:attention}제거{}함"}, unlock = {"{C:attention}던전 덱{}으로", "{C:attention}플래티넘 스테이크{}에서 승리하기"}},
            c_kranlaxs_redquartz = {name = "루비", text = {"{C:attention}보유{}하는 동안,", "{X:mult,C:white} X2 {} 배수 제공", "{C:inactive}(패시브){}"}, unlock = {"{C:attention}레드 덱{}으로", "{C:attention}마젠타 스테이크{} 이상에서 승리하기"}},
            c_kranlaxs_celestequartz = {name = "라리마", text = {"{C:attention}보유{}하는 동안,", "{X:chips,C:white} X1.5 {} 칩 제공", "{C:inactive}(패시브){}"}, unlock = {"{C:attention}체크 덱{}으로", "{C:attention}청록색 스테이크{}에서 승리하기"}},
            c_kranlaxs_yellowquartz = {name = "토파즈", text = {"표시된 {C:attention}조커{}를 생성함.", "각 {C:attention}라운드{}가 끝난 후", "조커는 무작위로 바뀜", "{C:inactive}(목표: {C:attention}#1#{C:inactive}){}"}, unlock = {"{C:attention}던전 덱{}으로", "{C:attention}블루 스테이크{}에서 승리하기"}},
            c_kranlaxs_greenquartz = {name = "에메랄드", text = {"{C:attention}보유{}하는 동안, {C:attention}블라인드{}를 깬 후", "{C:attention}태그{} 생성", "{C:attention}#2#{}개의 태그를 생성하면 파괴됨", "{C:inactive}(현재: {C:attention}#1#{C:inactive}){}", "{C:inactive}(패시브){}"}, unlock = {"{C:attention}그린 덱{}으로", "{C:attention}마젠타 스테이크{} 이상에서 승리하기"}},
            c_kranlaxs_brownquartz = {name = "호안석", text = {"표시된 {C:attention}카드{}를 생성함.", "상점을 {C:green}리롤{}한 후", "카드는 무작위로 바뀜", "{C:inactive}(목표: {C:attention}#1#{C:inactive}){}"}, unlock = {"{C:attention}애너글리프 덱{}으로", "{C:attention}청록색 스테이크{}에서 승리하기"}},
            c_kranlaxs_turquoisequartz = {name = "터콰이즈", text = {"{C:attention}보유{}하는 동안, 첫 번째 조커를", "제외한 모든 조커를 {C:attention}비활성화{}함", "해당 조커를 {C:attention}2{}번 재발동함", "{C:inactive}(패시브){}"}, unlock = {"{C:attention}황도 덱{}으로", "{C:attention}청록색 스테이크{}에서 승리하기"}},
            c_kranlaxs_orangequartz = {name = "시트린", text = {"{C:attention}카드{}에 {C:green}민트 실{}을 추가하거나", "선택한 {C:attention}조커{}에", "{C:green}클로버 스티커{}를 추가함"}, unlock = {"{C:attention}옐로우 덱{}으로", "{C:attention}마젠타 스테이크{} 이상에서 승리하기"}},
            c_kranlaxs_lapislazuli = {name = "라피스 라줄리", text = {"{C:attention}보유{}하는 동안, 첫 번째", "점수 카드에 {C:chips}+#1#{} 칩 추가", "효과는 사용할 때마다 {C:chips}-#2#{} 감소함.", "{C:inactive}(0이 되면 비활성){}", "{C:inactive}(패시브){}"}, unlock = {"{C:attention}블루 덱{}으로", "{C:attention}마젠타 스테이크{} 이상에서 승리하기"}},
            c_kranlaxs_cinnabar = {name = "진사", text = {"{C:attention}보유{}하는 동안, 첫 번째", "점수 카드에 {C:mult}+#1#{} 배수 추가", "효과는 사용할 때마다 {C:mult}-#2#{} 감소함.", "{C:inactive}(0이 되면 비활성){}", "{C:inactive}(패시브){}"}, unlock = {"{C:attention}버려진 덱{}으로", "{C:attention}브라운 스테이크{}에서 승리하기"}},
            c_kranlaxs_graphite = {name = "흑연", text = {"{C:attention}보유{}하는 동안, {C:green}#1# / #2#{} 확률로", "낸 모든 카드의 복사본을", "손패에 생성함.", "발동 시 확률이 떨어짐.", "{C:inactive}(0이 되면 비활성){}", "{C:inactive}(패시브){}"}, unlock = {"{C:attention}블랙 덱{}으로", "{C:attention}마젠타 스테이크{} 이상에서 승리하기"}},
            c_kranlaxs_uranium = {name = "우라늄", text = {"{C:attention}보유{}하는 동안, 라운드마다 1개의", "무작위 효과를 적용함. 아주 좋거나", "매우 파괴적일 수 있음.", "{C:dark_edition}현재 상태:{}", "{C:red,E:2}#1#{}", "{C:inactive}(가질 용기가 있는가?){}", "{C:inactive}(패시브){}"}, unlock = {"{C:attention}에러틱 덱{}으로", "{C:attention}플래티넘 스테이크{}에서 승리하기"}}
        },

        Tag = {
            tag_kranlaxs_mega_invtarot = {name = "메가 리버스 태그", text = {"무료 {C:attention}메가 리버스 타로 팩{}을", "즉시 제공함"}},
            tag_kranlaxs_mega_uno = {name = "점보 우노 태그", text = {"무료 {C:attention}점보 우노 팩{}을", "즉시 제공함"}},
            tag_kranlaxs_mega_invtarot_store = {name = "저장된 메가 리버스 태그", text = {"무료 {C:attention}저장된 메가 리버스 타로{}를", "즉시 제공함"}},
            tag_kranlaxs_quartz_tag = {name = "석영 태그", text = {"무작위 {C:attention}석영{} 생성", "{C:inactive}(빈 공간 필요){}"}},
            tag_kranlaxs_sticker_remover = {name = "클렌저 태그", text = {"무작위 {C:attention}조커{}에서", "{C:attention}이터널{}, {C:attention}페리셔블{} 또는 {C:attention}렌탈{} 스티커 제거", "{C:inactive}(스티커가 없으면 {X:money,C:white} $5 {C:inactive} 제공){}"}},
            tag_kranlaxs_legendary = {name = "레전더리 태그", text = {"상점에 무료", "{C:legendary}레전더리 조커{}가 있음"}}
        },

        Edition = {
            e_kranlaxs_wave = {name = "아쿠아틱", text = {"{X:chips,C:white} X#1# {} 칩"}}
        },

        Other = {
            kranlaxs_magenta_sticker = {name = "마젠타 스티커", text = {"이 조커를 사용하여", "{C:attention}마젠타 스테이크{}에서 승리함"}},
            kranlaxs_brown_sticker = {name = "브라운 스티커", text = {"이 조커를 사용하여", "{C:attention}브라운 스테이크{}에서 승리함"}},
            kranlaxs_turquoise_sticker = {name = "청록색 스티커", text = {"이 조커를 사용하여", "{C:attention}청록색 스테이크{}에서 승리함"}},
            kranlaxs_platinum_sticker = {name = "플래티넘 스티커", text = {"이 조커를 사용하여", "{C:attention}플래티넘 스테이크{}에서 승리함"}},
            kranlaxs_orangeseal_seal = {name = "오렌지 실", text = {"손패에서 점수를 얻으면: {C:attention}#1#{},", "1개의 {C:attention}#2#{} 생성", "{C:inactive}사용 후 변경됨.{}", "{C:inactive}(빈 공간 필요){}"}},
            kranlaxs_pinkseal_seal = {name = "핑크 실", text = {"{C:attention}점수 계산{} 시,", "{X:dark_edition,C:white}^1.75{} 배수 적용"}},
            kranlaxs_whiteseal_seal = {name = "화이트 실", text = {"{C:attention}항상 점수를 내며{}, {C:red}디버프{},", "{C:red}파괴{} 또는 {C:attention}뒤집히는{} 것에 면역"}},
            kranlaxs_brownseal_seal = {name = "브라운 실", text = {"손패에 있을 때,", "{C:green}#1# / #2#{} 확률로 이 카드를 {C:attention}복사{}함"}},
            kranlaxs_grayseal_seal = {name = "그레이 실", text = {"{C:attention}점수 계산{} 시, 이 카드의", "{C:enhanced}강화{}를 {C:attention}무작위{}로 변경함"}},
            kranlaxs_mintseal_seal = {name = "민트 실", text = {"이 카드에 적힌", "{C:attention}모든 확률{}을 2배로 만듦"}},
            p_kranlaxs_uno_store_3 = {name = "우노 팩", text = {"최대 {C:attention}3{}장의 {C:blue}UNO{} 카드 중", "{C:attention}1{}장 선택"}},
            p_kranlaxs_uno_store_5 = {name = "점보 우노 팩", text = {"최대 {C:attention}5{}장의 {C:blue}UNO{} 카드 중", "{C:attention}1{}장 선택"}},
            p_kranlaxs_invtarot_instant_3_1 = {name = "리버스 타로 팩", text = {"최대 {C:attention}3{}장의 {C:purple}리버스 타로{} 카드 중", "{C:attention}1{}장 선택"}},
            p_kranlaxs_invtarot_instant_5_1 = {name = "점보 리버스 타로 팩", text = {"최대 {C:attention}5{}장의 {C:purple}리버스 타로{} 카드 중", "{C:attention}1{}장 선택"}},
            p_kranlaxs_invtarot_instant_5_2 = {name = "메가 리버스 타로 팩", text = {"최대 {C:attention}5{}장의 {C:purple}리버스 타로{} 카드 중", "{C:attention}2{}장 선택"}},
            p_kranlaxs_invtarot_store_3_1 = {name = "저장된 리버스 타로", text = {"최대 {C:attention}3{}장의 {C:purple}리버스 타로{} 카드 중", "{C:attention}1{}장 선택"}},
            p_kranlaxs_invtarot_store_5_1 = {name = "저장된 점보 리버스 타로", text = {"최대 {C:attention}5{}장의 {C:purple}리버스 타로{} 카드 중", "{C:attention}1{}장 선택"}},
            kranlaxs_deviled_sticker = {name = "데블드 스티커", text = {"이 조커를 사용하여", "{C:attention}데블드 스테이크{}에서 승리함"}},
            kranlaxs_glass_sticker = {name = "글래스 스티커", text = {"이 조커를 사용하여", "{C:attention}글래스 스테이크{}에서 승리함"}},
            p_kranlaxs_invtarot_store_5_2 = {name = "저장된 메가 리버스 타로", text = {"최대 {C:attention}5{}장의 {C:purple}리버스 타로{} 카드 중", "{C:attention}2{}장 선택"}}
        },

        Booster = {
            p_kranlaxs_uno_store_3 = {name = "우노 팩", text = {"최대 {C:attention}3{}장의 {C:blue}UNO{} 카드 중", "{C:attention}1{}장 선택"}},
            p_kranlaxs_uno_store_5 = {name = "점보 우노 팩", text = {"최대 {C:attention}5{}장의 {C:blue}UNO{} 카드 중", "{C:attention}1{}장 선택"}},
            p_kranlaxs_invtarot_instant_3_1 = {name = "리버스 타로 팩", text = {"최대 {C:attention}3{}장의 {C:purple}리버스 타로{} 카드 중", "{C:attention}1{}장 선택"}},
            p_kranlaxs_invtarot_instant_5_1 = {name = "점보 리버스 타로 팩", text = {"최대 {C:attention}5{}장의 {C:purple}리버스 타로{} 카드 중", "{C:attention}1{}장 선택"}},
            p_kranlaxs_invtarot_instant_5_2 = {name = "메가 리버스 타로 팩", text = {"최대 {C:attention}5{}장의 {C:purple}리버스 타로{} 카드 중", "{C:attention}2{}장 선택"}},
            p_kranlaxs_invtarot_store_3_1 = {name = "저장된 리버스 타로", text = {"최대 {C:attention}3{}장의 {C:purple}리버스 타로{} 카드 중", "{C:attention}1{}장 선택"}},
            p_kranlaxs_invtarot_store_5_1 = {name = "저장된 점보 리버스 타로", text = {"최대 {C:attention}5{}장의 {C:purple}리버스 타로{} 카드 중", "{C:attention}1{}장 선택"}},
            p_kranlaxs_invtarot_store_5_2 = {name = "저장된 메가 리버스 타로", text = {"최대 {C:attention}5{}장의 {C:purple}리버스 타로{} 카드 중", "{C:attention}2{}장 선택"}}
        }
    },
    
    misc = {
        labels = {
            kranlaxs_magenta_sticker = "마젠타 스티커",
            kranlaxs_brown_sticker = "브라운 스티커",
            kranlaxs_turquoise_sticker = "청록색 스티커",
            kranlaxs_platinum_sticker = "플래티넘 스티커",
            kranlaxs_orangeseal_seal = "오렌지 실", 
            kranlaxs_pinkseal_seal = "핑크 실", 
            kranlaxs_whiteseal_seal = "화이트 실", 
            kranlaxs_brownseal_seal = "브라운 실", 
            kranlaxs_grayseal_seal = "그레이 실", 
            kranlaxs_mintseal_seal = "민트 실", 
            clover = "클로버 스티커",
            kranlaxs_deviled_sticker = "데블드 스티커",
            kranlaxs_glass_sticker = "글래스 스티커",
            p_kranlaxs_uno_store_3 = "우노 팩",
            p_kranlaxs_uno_store_5 = "점보 우노 팩",
            p_kranlaxs_invtarot_instant_3_1 = "리버스 타로 팩",
            p_kranlaxs_invtarot_instant_5_1 = "점보 리버스 타로 팩",
            p_kranlaxs_invtarot_instant_5_2 = "메가 리버스 타로 팩",
            p_kranlaxs_invtarot_store_3_1 = "저장된 리버스 타로",
            p_kranlaxs_invtarot_store_5_1 = "저장된 점보 리버스 타로",
            p_kranlaxs_invtarot_store_5_2 = "저장된 메가 리버스 타로",
            kranlaxs_wave = "아쿠아틱"
        },

        v_text = {
            ch_c_kran_fijado_1 = {"모든 조커에 {C:attention}고정{} 스티커가 붙음"},
            ch_c_kran_abuela_1 = {"{C:attention}점수를 내는{} 조커는 {C:red}금지됨{}"},
            ch_c_kran_crisis_1 = {"상점 가격이 {C:attention}20% 더 비싸짐{}"},
            ch_c_kran_crisis_2 = {"블라인드 기본 보상이 {X:money,C:white} $2 {} {C:red}감소함{}"},
            ch_c_kran_crisis_3 = {"덱이 {C:attention}52장의 에이스{}로만 구성됨"},
            ch_c_kran_doppel_1 = {"상점에서 모든 조커가 {C:red}금지됨{}"},
            ch_c_kran_anonimo_1 = {"손패의 카드와 조커가 {C:attention}뒤집힌 상태{}가 됨"},
            ch_c_kran_jefes_1 = {"스몰 블라인드와 빅 블라인드가 {C:attention}보스 블라인드{}가 됨"},
            ch_c_kran_premon_1 = {"손패에 있는 모든 카드가 {C:attention}뒤집힌 상태{}가 됨"},
            ch_c_kran_tallo_1 = {"다른 {C:attention}조커{} 및 {C:attention}팩{}은 {C:red}금지됨{}"},
            ch_c_gacha_rule_1 = {"상점에 {C:attention}개별 카드{}가 등장하지 않음"},
            ch_c_kran_pobreza_1 = {"{C:common}커먼{} 카드가 {C:legendary}레전더리{}가 될 확률 {C:attention}50%{}"},
            ch_c_kran_pobreza_2 = {"{C:attention}수도사{} 조커가 실망하면, {C:red}게임에서 패배함{}"}
        }
    }
}