return {
    descriptions = {
        Joker = {
            j_kranlaxs_tagger = {name = "Marcador", text = {"Ganha {C:red}+#1#{} Mult por cada", "{C:attention}Marcador{} obtido", "{C:inactive}(Atualmente {C:red}+#2#{C:inactive} Mult){}"}, unlock = {"Compre os {C:attention}2{} Cupons", "de desconto em uma única rodada"}},
            j_kranlaxs_Cashback = {name = "Reembolso", text = {"{C:green}#1# em #2#{} chances de obter {X:money,C:white} $3 {},", "ao comprar uma carta"}, unlock = {"Vença uma partida na {C:attention}Aposta Vermelha{}", "usando o {C:attention}Baralho Espacial{}"}},
            j_kranlaxs_underratedjoker = {name = "Coringa Subestimado", text = {"Este Coringa ganha {X:chips,C:white} X0.2 {} Fichas", "se a mão jogada {C:attention}não for{}", "sua mão de pôquer mais jogada", "{C:inactive}(Zera se for){}", "{C:inactive}(Atualmente {X:chips,C:white} X#1# {C:inactive} Fichas){}"}, unlock = {"Vença uma partida na {C:attention}Aposta Azul{}", "usando o {C:attention}Baralho Espacial{}"}},
            j_kranlaxs_facelessaccountant = {name = "Contador Sem Rosto", text = {"Este Coringa ganha {X:blue,C:white} X0.1 {} Fichas por", "cada {C:attention}#2#{} pontuada", "{C:inactive}(Atualmente {X:blue,C:white} X#1# {C:inactive} Fichas){}"}, unlock = {"Vença uma partida sem jogar figuras,", "mas tendo pelo menos {C:attention}1{} no baralho"}},
            j_kranlaxs_thefixer = {name = "O Subornador", text = {"Vender um {C:attention}Coringa{} durante um", "{C:purple}Blind{} reduz a pontuação exigida", "{C:inactive}(Comum: -10%, Incomum: -30%){}", "{C:inactive}(Raro: -60%, Lendário: -95%){}"}, unlock = {"Venda pelo menos {C:attention}2{} Coringas", "de cada raridade"}},
            j_kranlaxs_mysteriousgeode = {name = "Geodo Misterioso", text = {"Cada {C:attention}Carta Curinga{} pontuada dá", "um efeito {C:attention}aleatório{}"}, unlock = {"Jogue uma mão", "com {C:attention}5{} Cartas Curingas"}},
            j_kranlaxs_benchwarmer = {name = "Esquenta Banco", text = {"Dá {C:attention}4 vezes{} o valor em {C:blue}Fichas{}", "da carta com a categoria mais alta na mão"}},
            j_kranlaxs_entropy2 = {name = "Vórtice", text = {"Ganha {X:dark_edition,C:white} ^1 {} Mult e {X:dark_edition,C:white} ^1 {} Fichas", "por cada carta {C:attention}menor que 52{} no seu baralho", "{C:inactive}(Atualmente {X:dark_edition,C:white} ^#1# {C:inactive} Mult e {X:dark_edition,C:white} ^#1# {C:inactive} Fichas){}"}},
            j_kranlaxs_greedyleprachaun = {name = "Duende Ganancioso", text = {"Compre {C:attention}3 cartas extras{}", "no primeiro {C:red}descarte{} da rodada"}, unlock = {"Descarte {C:attention}1{} única carta", "{C:attention}3{} vezes seguidas"}},
            j_kranlaxs_charismaticbard = {name = "Bardo Carismático", text = {"{C:attention}-1{} tamanho da mão", "Reduz o requisito do {C:purple}Blind{} em {C:attention}2%{} cada vez", "que você joga sua {C:attention}mão mais jogada{}", "{C:inactive}(Máximo de 90%){}", "Zera se você jogar outra mão", "{C:inactive}(Atualmente {C:attention}-#1#%{C:inactive} requisito do Blind){}"}},
            j_kranlaxs_russianroulette = {name = "Roleta Russa", text = {"{C:green}#1# em #2#{} chances de {C:red}Perder a partida{}", "ao selecionar um blind", "Se sobreviver, ganha", "{X:mult,C:white} X3 {} Mult e {X:chips,C:white} X3 {} Fichas", "{C:inactive}(Atualmente {X:mult,C:white} X#3# {C:inactive} Mult e {X:chips,C:white} X#3# {C:inactive} Fichas){}"}, unlock = {"Vença uma partida na {C:attention}Aposta Preta{}", "usando o {C:attention}Baralho Espacial{}"}},
            j_kranlaxs_fidelitycard = {name = "Passe de Batalha", text = {"Após comprar {C:attention}6{} cartas, a {C:attention}sétima{}", "carta comprada dá {X:money,C:white} dinheiro {} igual ao", "{C:attention}valor de venda{} de todos os seus Coringas", "{C:inactive}(Atualmente {C:attention}#1#/6{C:inactive} cartas){}", "{C:inactive}(Valor de venda total: {X:money,C:white} $#2# {C:inactive}){}"}},
            j_kranlaxs_devioussheep = {name = "Ovelha Gulosa", text = {"{C:red}Devora{} um Coringa aleatório ao", "selecionar um {C:attention}Blind{} e ganha {X:mult,C:white} X0.4 {} Mult", "{C:hearts}Fim de Jogo{} se não houver outros Coringas", "{C:inactive}(Priorize certos alvos para mais Mult!){}", "{C:inactive}(Atualmente {X:mult,C:white} X#1# {C:inactive} Mult){}"}},
            j_kranlaxs_lifeassurance = {name = "Seguro de Vida", text = {"Evita um Fim de Jogo se", "você tiver pelo menos {X:money,C:white} $#1# {}", "{C:inactive}(O preço dobra após cada uso){}"}, unlock = {"Perca uma partida com", "{X:money,C:white} $100 {} ou mais", "antes do {C:attention}Ante 8{}"}},
            j_kranlaxs_sundaycheckpoint = {name = "Ponto de Controle", text = {"{C:red}Fim de Jogo{} se você selecionar", "um blind em um {C:attention}dia da semana{}", "Caso contrário, cria um Coringa de {C:attention}Desafio Semanal{}", "no final da rodada e se {C:red}destrói{}", "{C:inactive}(Dia atual: #1#){}"}},
            j_kranlaxs_weeklychallenge = {name = "Desafio Semanal", text = {"Define um desafio aleatório para esta partida", "{C:clubs}Desafio atual:{} {C:attention}#1#{}", "{C:inactive}1:{} Você tem {X:money,C:white} -$100 {}, pague antes do Ante 8", "{C:inactive}2:{} Loja restrita", "{C:inactive}3:{} 1 Mão, 20 Descartes (Sem Cupons extras)", "{C:inactive}4:{} Limite de {C:blue}#2#{} mãos e {C:red}#3#{} descartes na partida", "{C:inactive}5:{} Velocidade do jogo travada em 0.5x", "{C:inactive}6:{} 3 Triboulets Eternos (Máx 3 Coringas, Ante Rápido)", "{C:inactive}7:{} 1 em 6 chances de VENCER ao derrotar o blind (Perde no Ante 8)"}},
            j_kranlaxs_panda = {name = "Panda Fofinho", text = {"Dá {C:chips}+#1#{} Fichas", "{C:attention}-1{} espaço de Coringa"}},
            j_kranlaxs_miner = {name = "Mineiro", text = {"Ganha {C:red}+5{} Mult por cada", "{C:attention}Carta de Pedra{} pontuada", "{C:green}#2# em #3#{} chances de ganhar", "de {X:money,C:white} $#4# {} a {X:money,C:white} $#5# {} ao jogar uma mão", "{C:inactive}(Atualmente {C:red}+#1#{C:inactive} Mult){}"}, unlock = {"Jogue uma mão", "com {C:attention}5{} Cartas de Pedra"}},
            j_kranlaxs_birthdaycake = {name = "Bolo de Aniversário", text = {"Dá {X:dark_edition,C:white} ^#1# {} Mult", "Perde {X:dark_edition,C:white} ^0.25 {} após", "cada mão jogada", "Ao esgotar, cria um {C:attention}Coringa Repassado{}"}, unlock = {"Vença uma partida na", "{C:attention}Aposta Azul{} usando", "o baralho {C:attention}Desafio Semanal{}"}},
            j_kranlaxs_vipsuscription = {name = "Assinatura V.I.P", text = {"Dá {C:attention}+#2#{} espaços na loja,", "{C:attention}+1{} Cupom e Pacote extra", "Subtrai {X:money,C:white} $#1# {} ao abrir a loja.", "O preço e o tamanho da loja", "{C:attention}aumentam{} ao derrotar um {C:attention}Blind Chefe{}"}, unlock = {"Vença uma partida na", "{C:attention}Aposta Laranja{} usando", "o baralho {C:attention}Desafio Semanal{}"}},
            j_kranlaxs_painterjoker = {name = "Coringa Pintor", text = {"Ao pontuar uma mão, cria um", "{C:attention}Marcador de Malabarista{} por cada", "{C:attention}Carta Curinga{} na sua mão", "{C:inactive}(Custa {X:money,C:white} $#1# {C:inactive} por marcador){}"}, unlock = {"Vença uma partida na", "{C:attention}Aposta Laranja{} usando", "o baralho {C:attention}Desafio Semanal{}"}},
            j_kranlaxs_coronation = {name = "Coroação", text = {"Se a mão jogada contiver cartas pontuadas", "de categoria {C:attention}10 ou menor{}, transforma", "a de menor valor em um {C:attention}Rei{}.", "Se não houver cartas baixas no baralho,", "adiciona um {C:red}Selo Vermelho{} ao primeiro {C:attention}Rei{} pontuado."}, unlock = {"Jogue uma mão de exatamente", "{C:attention}5 Reis{}. Todos devem ter", "{C:red}Selo Vermelho{} e serem cartas de {C:attention}Aço{}"}},
            j_kranlaxs_speedrunner = {name = "Speedrunner", text = {"{X:mult,C:white} X#1# {} Mult.", "Você tem {C:attention}#2# segundos{} para", "jogar uma mão ou descartar.", "Se o tempo acabar, {C:red}FIM DE JOGO{}."}, unlock = {"Vença uma partida na", "{C:attention}Aposta Verde{} usando", "o baralho {C:attention}Desafio Semanal{}"}},
            j_kranlaxs_passcode = {name = "Senha", text = {"Se a mão jogada coincidir com algum", "dos seguintes códigos, a mão", "conta como {C:attention}Cinco do Mesmo Naipe{}", "{C:inactive}1. {C:attention}#1#{}", "{C:inactive}2. {C:attention}#2#{}", "{C:inactive}3. {C:attention}#3#{}"}, unlock = {"Vença uma partida na", "{C:attention}Aposta Preta{} usando", "o baralho {C:attention}Desafio Semanal{}"}},
            j_kranlaxs_chronometer = {name = "Cronômetro", text = {"Ao jogar uma mão: ", "Dá {C:chips}fichas{} iguais aos {C:attention}Segundos{} atuais", "Dá {C:mult}mult{} igual aos {C:attention}Minutos{} atuais", "Ganha {C:money}dinheiro{} igual às {C:attention}Horas{} atuais", "{C:inactive}(Atualmente: {C:chips}+#1#{C:inactive} fichas, {C:mult}+#2#{C:inactive} mult, {C:money}+$#3#{C:inactive}){}"}, unlock = {"Vença uma partida na {C:attention}Aposta Dourada{}", "usando o {C:attention}Baralho Espacial{}"}},
            j_kranlaxs_zombiejoker = {name = "Zambi Yoker", text = {"{C:attention}destrois{} a {C:attention}prmera{} carta", "k nn dá pionts e gnh {C:red}+15{} mult", "ms vc perd {C:red}-10{} mult", "x cda mao jgada no round", "s xgr em {C:red}0{} mult", "{C:attention}ele morr {}", "{C:inactive}(vc tem {C:red}+#1#{C:inactive} mult ou qulqr coi){}"}, unlock = {"Vença uma partida na {C:attention}Aposta Roxa{}", "usando o {C:attention}Baralho Espacial{}"}},
            j_kranlaxs_thecousin = {name = "O Primo", text = {"Ganha {C:chips}+13{} Fichas por cada", "{C:attention}número primo{} pontuado", "{C:inactive}(Atualmente {C:chips}+#1#{C:inactive} Fichas){}"}, unlock = {"Vença uma partida na {C:attention}Aposta Turquesa{}", "usando o {C:attention}Baralho Espacial{}"}},
            j_kranlaxs_colasoda = {name = "Refrigerante de Cola", text = {"Dá {X:dark_edition,C:white} ^#1# {} Mult", "Perde {X:dark_edition,C:white} ^#2# {} por", "quase {C:attention}qualquer ação{} que realizar"}, unlock = {"Vença uma partida na", "{C:attention}Aposta Azul{} usando", "o baralho {C:attention}Desafio Semanal{}"}},
            j_kranlaxs_icecreamsandwich = {name = "Sanduíche de Sorvete", text = {"Ganha {X:money,C:white} $#1# {} no final", "da rodada", "A recompensa diminui em {X:money,C:white} $#2# {}", "após cada rodada"}, unlock = {"Ganha {X:money,C:white} $50 {} ou mais", "como pagamento em", "uma única rodada"}},
            j_kranlaxs_dispensermachine = {name = "Máquina de Vendas", text = {"Se este Coringa estiver {C:attention}selecionado{}", "ao sair da loja, gasta {X:money,C:white} $#1# {}", "e cria um {C:attention}Coringa de Comida{}"}, unlock = {"Tenha {C:attention}4{} Coringas de", "comida ao mesmo tempo"}},
            j_kranlaxs_bottledwater = {name = "Água Engarrafada", text = {"{X:chips,C:white} X#1# {} Fichas", "Perde {X:chips,C:white} X#2# {} por", "cada carta pontuada"}, unlock = {"Vença uma partida na", "{C:attention}Aposta Azul{} usando", "o baralho {C:attention}Desafio Semanal{}"}},
            j_kranlaxs_burrow = {name = "Toca", text = {"Ganha {C:attention}+1{} Coelho por", "cada {C:attention}Blind derrotado{}", "Ao ser {C:gold}vendido{}, cria {C:attention}#1#{} Coelhos"}},
            j_kranlaxs_bunny = {name = "Coelho", text = {"Ganha {X:mult,C:white} X#1# {} Mult por cada", "Coringa {C:attention}Coelho{} que possuir", "{C:inactive}(Atualmente {X:mult,C:white} X#2# {C:inactive} Mult){}"}},
            j_kranlaxs_sushi = {name = "Sushi", text = {"Reduz o requisito do", "Blind em {C:attention}#1#%{}", "A redução diminui em {C:attention}#2#%{}", "após derrotar um {C:attention}Blind{}"}, unlock = {"Vença uma partida na", "{C:attention}Aposta Roxa{} usando", "o baralho {C:attention}Desafio Semanal{}"}},
            j_kranlaxs_gigachad = {name = "Gigachad", text = {"Ganha {C:chips}+#2#{} Fichas por quase", "{C:attention}qualquer ação{} que realizar", "{C:inactive}(Atualmente {C:chips}+#1#{C:inactive} Fichas){}"}, unlock = {"Vença uma partida na", "{C:attention}Aposta Branca{} usando", "o baralho {C:attention}Desafio Semanal{}"}},
            j_kranlaxs_nft = {name = "Golpe Cripto", text = {"Reduz a {C:attention}categoria{} de todas", "as cartas na sua mão em {C:attention}1{}", "ao pontuar uma mão", "{C:inactive}(Não pode ser reduzido abaixo de 2){}"}},
            j_kranlaxs_beanstalk = {name = "Pé de Feijão", text = {"Feijões inúteis"}, unlock = {"Vença uma partida na", "{C:attention}Aposta Branca{} usando", "o baralho {C:attention}Desafio Semanal{}"}},
            j_kranlaxs_suspiciousbeanstalk = {name = "Pé de Feijão Suspeito", text = {"Feijões inúteis?..."}},
            j_kranlaxs_epicbeanstalk = {name = "Pé de Feijão Épico", text = {"Talvez não sejam feijões inúteis..."}},
            j_kranlaxs_zenithbeanstalk = {name = "Pé de Feijão Zênite", text = {"Feijões"}},
            j_kranlaxs_commonseed = {name = "Semente Comum", text = {"{C:attention}Cria{} um Coringa", "{C:common}Comum{} aleatório"}},
            j_kranlaxs_weirdlookingseed = {name = "Semente Estranha", text = {"{C:attention}Cria{} um Coringa", "{C:uncommon}Incomum{} aleatório"}},
            j_kranlaxs_magnificentseed = {name = "Semente Magnífica", text = {"{C:attention}Cria{} um Coringa", "{C:rare}Raro{} aleatório"}},
            j_kranlaxs_godseed = {name = "Semente Divina", text = {"{C:attention}Cria{} um Coringa", "{C:legendary}Lendário{} aleatório"}},
            j_kranlaxs_anonymousjoker = {name = "Coringa Anônimo", text = {"Ao pontuar, vira e dá entre", "{X:mult,C:white} X1.5 {} e {X:mult,C:white} X4.0 {} de Mult"}, unlock = {"Derrote o Blind Chefe", "{C:attention}Bolota Âmbar{} 1 vez"}},
            j_kranlaxs_littlebro = {name = "Irmãozinho", text = {"Se a mão jogada for {C:attention}Carta Alta{} e", "a carta pontuada for um {C:attention}#2#{},", "este Coringa ganha {X:red,C:white} X#3# {} Mult", "A carta muda cada rodada", "{C:inactive}(Atualmente {X:red,C:white} X#1# {C:inactive} Mult){}"}, unlock = {"Jogue {C:attention}Carta Alta{}", "{C:attention}30{} vezes em", "uma única partida"}},
            j_kranlaxs_medusa = {name = "Medusa", text = {"{C:attention}Todas as cartas jogadas{}", "se convertem permanentemente em {C:attention}Cartas de Pedra{}", "após jogar uma mão", "{C:inactive}(Mesmo as não pontuadas){}"}, unlock = {"Vença uma partida na {C:attention}Aposta Marrom{}", "usando o {C:attention}Baralho Espacial{}"}},
            j_kranlaxs_depression = {name = "Recessão Econômica", text = {"Dá {X:dark_edition,C:white}^#2#{} Mult", "Aumenta em {X:dark_edition,C:white}^#1#{} por cada {X:money,C:white} $1 {}", "abaixo de {X:money,C:white} $0 {}"}, unlock = {"Entre numa loja", "com {X:money,C:white} -$25 {} ou menos"}},
            j_kranlaxs_grannyjoker = {name = "A Vó", text = {"Dá {X:dark_edition,C:white} ^3 {} Fichas e {X:dark_edition,C:white} ^3 {} Mult", "A velocidade do jogo trava em {C:attention}0.25x{}", "{C:inactive}(Se destrói se você jogar uma {C:attention}Sequência{}", "{C:inactive}ou {C:attention}Straight Flush{C:inactive}){}"}, unlock = {"Derrote {C:attention}12{} blinds com a", "velocidade de jogo em {C:attention}0.5{}"}},
            j_kranlaxs_lateshippment = {name = "Entrega Atrasada", text = {"Reativa {C:attention}todas as cartas jogadas{}", "{C:attention}1 vez{} por cada mão jogada", "na {C:attention}rodada anterior{}", "{C:inactive}(Atualmente {C:attention}#1#{C:inactive} reativações){}"}, unlock = {"Vença uma partida na {C:attention}Aposta Laranja{}", "usando o {C:attention}Baralho Espacial{}"}},
            j_kranlaxs_unkownfactor = {name = "Variável X", text = {"Todas as cartas jogadas são", "consideradas como {C:attention}#1#{}", "{C:inactive}(A categoria muda no final da rodada){}"}, unlock = {"Vença uma partida na", "{C:attention}Aposta Dourada{} usando", "o baralho {C:attention}Desafio Semanal{}"}},
            j_kranlaxs_thethreers = {name = "Os 3 R's", text = {"Cria uma {C:attention}cópia{} de cada carta jogada", "e a adiciona ao seu {C:attention}baralho{}", "{C:attention}Destrói{} todas as cartas pontuadas"}, unlock = {"Vença uma partida na", "{C:attention}Aposta Dourada{} usando", "o baralho {C:attention}Desafio Semanal{}"}},
            j_kranlaxs_the = {name = "Cori", text = {"Dá {X:chips,C:white} X2 {} Fichas e {X:mult,C:white} X2 {} Mult", "apenas na {C:attention}primeira mão{} da rodada"}, unlock = {"Vença {C:attention}5{} blinds usando", "apenas {C:attention}1{} mão cada uma"}},
            j_kranlaxs_chainreaction = {name = "Reação em Cadeia", text = {"Se a mão jogada for {C:attention}#2#{},", "ganha {X:chips,C:white} X0.5 {} Fichas e a mão muda", "Zera se a mão {C:attention}não coincidir{}", "{C:inactive}(Atualmente {X:chips,C:white} X#1# {C:inactive} Fichas){}"}, unlock = {"Jogue todas as mãos de pôquer", "pelo menos {C:attention}1{} vez na partida"}},
            j_kranlaxs_anubis = {name = "Anúbis", text = {"Equilibra as {C:blue}Fichas{} e o {C:red}Mult{}", "quando uma mão é pontuada"}, unlock = {"Vença uma partida com o {C:attention}Baralho de Plasma{}", "em todas as dificuldades de aposta"}},
            j_kranlaxs_erraticjoker = {name = "Coringa Errático", text = {"Se a carta pontuada for uma", "{C:attention}Carta Curinga{}, inverte as", "{C:blue}Fichas{} e o {C:red}Mult{}"}, unlock = {"Vença uma partida na {C:attention}Aposta Branca{}", "usando o {C:attention}Baralho Espacial{}"}},
            j_kranlaxs_luckyseven = {name = "Os 7 Sortudos", text = {"Se a mão jogada for exatamente", "uma {C:attention}Trinca{} apenas de {C:attention}7s{}, este Coringa", "ganha {C:blue}+7{} Fichas, {C:red}+7{} Mult e dá {X:money,C:white} $7 {}", "{C:inactive}(Atualmente {C:blue}+#1#{} Fichas, {C:red}+#2#{} Mult)"}, unlock = {"Tenha pelo menos {C:attention}10{} cartas", "com a categoria {C:attention}7{} no seu baralho"}},
            j_kranlaxs_certificateddocument = {name = "Documento Certificado", text = {"Reativa {C:attention}todos{} os selos"}, unlock = {"Vença uma partida na", "{C:attention}Aposta Roxa{} usando", "o baralho {C:attention}Desafio Semanal{}"}},
            j_kranlaxs_platanito = {name = "Bananinha", text = {"Sempre que outro Coringa for ativado,", "dá {X:mult,C:white} X#3# {} Mult extra", "{C:green}#1# em #2#{} chances de", "ser destruído no final da rodada"}, unlock = {"Vença uma partida na {C:attention}Aposta de Platina{}", "usando o {C:attention}Baralho Espacial{}"}},
            j_kranlaxs_cubicaljoker = {name = "Coringa Cúbico", text = {"Dá {C:mult}+#1#{} Mult", "O valor é elevado ao", "{C:attention}Cubo (^3){} por cada", "{C:attention}Blind Chefe{} derrotado"}},
            j_kranlaxs_grapesoda = {name = "Refrigerante de Uva", text = {"Ao ser {C:gold}vendido{}, cria uma carta", "{C:spectral}Espectral{} aleatória", "com edição {C:dark_edition}Negativa{}"}, unlock = {"Vença uma partida na {C:attention}Aposta Magenta{}", "usando o {C:attention}Baralho Espacial{}"}},
            j_kranlaxs_telescope = {name = "Telescópio", text = {"Se a mão {C:attention}#1#{} subir de nível, sobe de nível", "essa mão {C:attention}1{} vez adicional", "{C:inactive}(A mão muda no final da rodada){}"}, unlock = {"Vença uma partida na", "{C:attention}Aposta Vermelha{} usando", "o baralho {C:attention}Desafio Semanal{}"}},
            j_kranlaxs_pandorabox = {name = "Caixa de Pandora", text = {"Ao derrotar um {C:attention}Blind Chefe{},", "cria um Coringa {C:attention}útil{} baseado", "no seu baralho atual", "{C:inactive}(Deve ter espaço){}"}},
            j_kranlaxs_doppelganger = {name = "Doppelgänger", text = {"Copia a habilidade de um {C:attention}Coringa{}", "aleatório de todo o jogo.", "O Coringa copiado muda após", "derrotar um {C:attention}Blind{}.", "{C:inactive}(Atualmente: {C:attention}#1#{C:inactive})"}, unlock = {"Vença uma partida na", "{C:attention}Aposta Dourada{} usando", "o baralho {C:attention}Desafio Semanal{}"}},
            j_kranlaxs_thechampion = {name = "O Campeão", text = {"Requisito do blind {C:attention}X#1#{}", "Ganha {X:money,C:white} $#2# {} no final da rodada"}, unlock = {"Alcance o {C:attention}Ante 16{}"}},
            j_kranlaxs_clerigo = {name = "Clérigo", text = {"Dá {C:mult}+#1#{} Mult por cada", "carta no seu baralho completo", "Perde {C:mult}-#2#{} Mult por cada carta", "com algum aprimoramento ou selo", "{C:inactive}(Atualmente {C:mult}+#3#{C:inactive} Mult){}"}, unlock = {"Complete o desafio:", "{C:attention}Receita de Família{}"}},
            j_kranlaxs_entrenador = {name = "Treinador", text = {"Dá {X:mult,C:white} X#1# {} Mult se você estiver", "abaixo do Ante {C:attention}#3#{}", "Caso contrário, dá {X:mult,C:white} X#2# {} Mult", "{C:inactive}(Atualmente {X:mult,C:white} X#4# {C:inactive} Mult){}"}, unlock = {"Complete o desafio:", "{C:attention}Crise Econômica{}"}},
            j_kranlaxs_medium = {name = "Médium", text = {"Dá {C:mult}+#1#{} Mult por cada", "partida {C:red}perdida{} no seu perfil", "{C:inactive}(Atualmente {C:mult}+#2#{C:inactive} Mult){}"}, unlock = {"Perca {C:attention}1{} partida", "{C:inactive}(Progresso: {C:attention}#1#{C:inactive} / 1){}"}},
            j_kranlaxs_monk = {name = "Monge", text = {"Ganha {X:chips,C:white} X#1# {} Fichas se você sair", "da loja sem gastar {X:money,C:white} dinheiro {}", "{C:red}Zera{} se você comprar algo", "{C:inactive}(Atualmente {X:chips,C:white} X#2# {C:inactive} Fichas){}"}, unlock = {"Complete o desafio:", "{C:attention}Voto de Pobreza{}"}},
            j_kranlaxs_knight = {name = "Cavaleiro", text = {"Após pontuar {C:attention}#1#{} cartas de {C:attention}Aço{},", "{C:attention}Desativará{} o próximo {C:attention}Blind Chefe{}", "{C:inactive}(Cartas pontuadas: #2#/#1#){}"}, unlock = {"Complete o desafio:", "{C:attention}Sindicato de Chefes{}"}},
            j_kranlaxs_overpopulation = {name = "Superpopulação", text = {"Dá {C:mult}+#1#{} Mult por cada", "{C:attention}figura{} acima", "do limite de {C:attention}#2#{}", "no seu baralho", "{C:inactive}(Atualmente {C:mult}+#3#{C:inactive} Mult){}"}, unlock = {"Vença uma partida na {C:attention}Aposta Verde{}", "usando o {C:attention}Baralho Espacial{}"}},
            j_kranlaxs_antisocial = {name = "Antissocial", text = {"Este Coringa ganha {C:mult}+#1#{} Mult", "se você jogar exatamente {C:attention}1{} carta", "{C:red}Zera{} se você jogar mais de 1", "{C:inactive}(Atualmente {C:mult}+#2#{C:inactive} Mult){}"}, unlock = {"Complete o desafio:", "{C:attention}Fixação Total{}"}},
            j_kranlaxs_famous = {name = "Famoso", text = {"Dá {C:chips}+#1#{} Fichas se a", "mão jogada for uma {C:attention}Cinco do Mesmo Naipe{},", "{C:attention}Flush Five{} ou {C:attention}Flush House{}"}},
            j_kranlaxs_influencer = {name = "Influencer", text = {"Dá {C:mult}+#1#{} Mult se a", "mão jogada for uma {C:attention}Cinco do Mesmo Naipe{},", "{C:attention}Flush Five{} ou {C:attention}Flush House{}"}},
            j_kranlaxs_potatobag = {name = "Saco de Batatas", text = {"Acumula as Fichas pontuadas", "Ao atingir {C:attention}#1#{}, aplica", "{X:mult,C:white} X#2# {} Mult na", "próxima mão e esvazia", "{C:inactive}(Acumulado: #3#/#1#){}"}},
            j_kranlaxs_simonsays = {name = "Simon Diz", text = {"Este Coringa ganha {X:mult,C:white} X#2# {} Mult", "ao completar sua exigência", "Simon diz... {C:attention}#3#{}", "{C:inactive}(Atualmente {X:mult,C:white} X#1# {C:inactive} Mult){}"}, unlock = {"Complete o desafio:", "{C:attention}O Grande Pé de Feijão{}"}},
            j_kranlaxs_cheater = {name = "Trapaceiro", text = {"Os Coringas na loja", "têm {C:green}35%{} de chances", "de serem substituídos por", "{C:attention}Cupons{} ou {C:attention}Pacotes de Melhoria{}"}, unlock = {"Complete o desafio:", "{C:attention}Gachapon{}"}},
            j_kranlaxs_philosopher = {name = "Filósofo", text = {"Mostra as próximas {C:attention}5 cartas{}", "do seu baralho", "{C:inactive}(Cada carta tem 20%{}", "{C:inactive}de chance de ficar oculta){}", "{C:attention}#1#{}"}, unlock = {"Complete o desafio:", "{C:attention}Premonições{}"}},
            j_kranlaxs_mandalajoker = {name = "Coringa Mandala", text = {"Este Coringa ganha {X:mult,C:white} X0.5 {} Mult", "por cada carta {C:spectral}Espectral{} usada", "{C:inactive}(Atualmente {X:mult,C:white} X#1# {C:inactive} Mult){}"}, unlock = {"Use {C:attention}20{} cartas {C:spectral}Espectrais{}", "{C:inactive}(Progresso: {C:attention}#1#{C:inactive} / 20){}"}},
            j_kranlaxs_regift = {name = "Coringa Repassado", text = {"Ao ser {C:gold}vendido{}, cria um", "{C:attention}Coringa{} aleatório", "A raridade depende do {C:attention}Blind{} atual"}, unlock = {"Venda {C:attention}50{} Coringas", "no total", "{C:inactive}(Progresso: {C:attention}#1#{C:inactive} / 50){}"}},
            j_kranlaxs_pyromaniac = {name = "Piromaníaco", text = {"Após pontuar uma mão, {C:red}destrói{}", "todas as cartas de {C:attention}número{} na sua mão", "{C:inactive}(Cartas de Ouro, Vidro e Aço estão salvas){}"}, unlock = {"Destrua {C:attention}100{} cartas", "que não sejam figuras", "{C:inactive}(Progresso: {C:attention}#1#{C:inactive} / 100){}"}},
            j_kranlaxs_neverendinggambling = {name = "Aposta Sem Fim", text = {"Perde {X:money,C:white} $1 {} por cada ação que realizar", "{C:inactive}(Apenas se tiver {X:money,C:white} $5 {} ou mais){}", "Role 3 números. Se combinarem, ganhe um prêmio!", "Se 2 combinarem, recupera {X:money,C:white} $1 {} como consolação", "{C:inactive}(Rolagem atual: #1# - #2# - #3#){}"}, unlock = {"Falhe em {C:attention}30{} probabilidades de", "coringas ou consumíveis", "{C:inactive}(Progresso: {C:attention}#1#{C:inactive} / 30){}"}},
            j_kranlaxs_solarsystem = {name = "Sistema Solar", text = {"No {C:attention}final da rodada{}, cria uma carta", "de {C:planet}Planeta{} em uma sequência fixa", "{C:inactive}(Próximo planeta: {C:planet}#1#{C:inactive}){}"}, unlock = {"Use as {C:attention}12{} cartas de {C:planet}Planeta{}", "padrão pelo menos uma vez", "em uma única partida", "{C:inactive}(Progresso: {C:attention}#1#{C:inactive} / 12){}"}},
            j_kranlaxs_deranged = {name = "Transtornado", text = {"Dá {C:mult}+#1#{} Mult ou {C:chips}+#2#{} Fichas", "O efeito muda toda vez", "que você joga uma mão"}, unlock = {"Complete o desafio:", "{C:attention}Crise de Identidade{}"}},
            j_kranlaxs_deranged_mult = {name = "Transtornado", text = {"Dá {C:mult}+#1#{} Mult", "O efeito muda toda vez", "que você joga uma mão"}},
            j_kranlaxs_deranged_chips = {name = "Transtornado", text = {"Dá {C:chips}+#2#{} Fichas", "O efeito muda toda vez", "que você joga uma mão"}},
            j_kranlaxs_tmtrainer = {
                name = "TMTRAINER", 
                text = {
                    "{C:dark_edition}#1#{}",
                    "{C:attention}#2#{}",
                    "{C:red}#3#{}",
                    "{C:chips}#4#{}"
                },
                unlock = {
                    "Complete o desafio:",
                    "{C:attention}Crise de Identidade{}"
                }
            },
            j_kranlaxs_bingocard = {name = "Cartela de Bingo", text = {"Ganha {X:mult,C:white} X0.25 {} Mult", "por cada linha completada", "{C:inactive}(Total: {X:mult,C:white} X#2# {C:inactive} Mult){}", "{C:attention}#3#{}", "{C:attention}#4#{}", "{C:attention}#5#{}", "{C:attention}#6#{}", "{C:attention}#7#{}"}, unlock = {"Complete o desafio:", "{C:attention}Anonimato Total{}"}}
        },

        Back = {
            b_kranlaxs_week_challenge = {name = "Desafio Semanal", text = {"Começa com um Coringa de {C:attention}Desafio Semanal{}", "{C:red}Vencível{} a cada {C:attention}final de semana{}"}, unlock = {"Abra o jogo durante um", "{C:attention}Sábado{} ou {C:attention}Domingo{}"}},
            b_kranlaxs_chaos_deck = {name = "Baralho do Caos", text = {"Aproveite o caos"}, unlock = {"Desbloqueie {C:legendary,E:1}TUDO{} na", "sua coleção"}},
            b_kranlaxs_dungeon_deck = {name = "Baralho de Masmorra", text = {"Após derrotar um {C:attention}Blind Chefe{},", "escolha entre 3 {C:attention}opções{}", "com {C:green}prós{} e {C:red}contras{}"}, unlock = {"Vença uma partida na {C:attention}Aposta Verde{}", "ou superior usando o", "baralho {C:attention}Desafio Semanal{}"}},
            b_kranlaxs_space_deck = {name = "Baralho Espacial", text = {"{C:attention}0{} espaços de coringa, {C:attention}5{} de consumíveis", "A loja só vende {C:attention}Quartze{}", "{C:attention}+1{} espaço na loja, Blinds são {C:attention}7.5%{} menores", "Aposta Vencedora: {C:attention}10{}"}, unlock = {"Vença uma partida na {C:attention}Aposta Verde{}", "com o {C:attention}Baralho Mágico{}, o", "{C:attention}Baralho Nebuloso{} e o {C:attention}Baralho Zodiacal{}"}},
            b_kranlaxs_bugged_deck = {name = "Baralho Bugado", text = {"!?"}, unlock = {"Adquira um {C:attention}TMTRAINER{}", "pela primeira vez"}}
        },

        Stake = {
            stake_kranlaxs_magenta = {name = "Aposta Magenta", text = {"As cartas na loja podem", "ter o adesivo {C:attention}Fixado{}"}},
            stake_kranlaxs_brown = {name = "Aposta Marrom", colour = "Marrom", text = {"{C:attention}-1{} espaço de", "{C:attention}Pacote de Melhoria{} na loja"}},
            stake_kranlaxs_turquoise = {name = "Aposta Turquesa", colour = "Turquesa", text = {"Os blinds têm {C:attention}50%{} de", "chance de {C:red}não poder pular{}"}},
            stake_kranlaxs_deviled = {name = "Aposta Diabólica", colour = "Diabólica", text = {"{C:attention}-1{} espaço de {C:attention}Coringa{}"}},
            stake_kranlaxs_glass = {name = "Aposta de Vidro", colour = "Vidro", text = {"A pontuação exigida aumenta", "ainda mais rápido a cada {C:attention}Ante{}"}},
            stake_kranlaxs_platinum = {name = "Aposta de Platina", colour = "Platina", text = {"Deve vencer o {C:attention}Ante 10{}", "para ganhar a partida"}}
        },

        UNOCards = {
            c_kranlaxs_skip = {name = "Pular", text = {"Consegue {C:attention}instantaneamente{} o requisito do Blind", "Não funciona em {C:attention}Blinds Chefes{}"}},
            c_kranlaxs_stacking = {name = "Empilhar", text = {"Adiciona um {C:attention}Selo Rosa{} a", "{C:attention}1{} carta selecionada na sua mão"}},
            c_kranlaxs_draw2 = {name = "Compra 2", text = {"Ao ser usado, {C:attention}compra 2 cartas extras{}", "para a sua mão, perde {C:blue}1{} mão"}},
            c_kranlaxs_draw4 = {name = "Compra 4", text = {"Ao ser usado, {C:attention}compra 4 cartas extras{}", "para a sua mão, perde {C:blue}1{} mão"}},
            c_kranlaxs_reverse = {name = "Reverso", text = {"Devolve {C:attention}todas as cartas{} da sua", "mão ao baralho e as {C:attention}reembaralha{}"}},
            c_kranlaxs_wildcard = {name = "Coringa de Cores", text = {"{C:attention}Converte{} cada carta na", "sua mão para um {C:attention}naipe aleatório{}", "de forma {C:attention}independente{}"}},
            c_kranlaxs_replay = {name = "Repetir", text = {"Devolve as cartas da", "última mão jogada para a sua mão", "{C:inactive}(Zera após o uso ou", "{C:inactive}no final da rodada)"}},
            c_kranlaxs_discardall = {name = "Descartar Tudo", text = {"Requer {C:attention}1{} carta selecionada.", "Descarta {C:red}todas{} as cartas", "da sua {C:attention}mão{} e {C:attention}baralho{} que", "compartilham o mesmo naipe"}},
            c_kranlaxs_shield = {name = "Escudo", text = {"Passivamente te protege da morte ou", "pode ser vendido para desativar o {C:attention}Blind Chefe{}"}},
            c_kranlaxs_misery = {name = "Miséria", text = {"Escolha um {C:attention}Naipe{}.", "Você comprará cartas do seu baralho", "sem parar até", "conseguir uma desse naipe"}},
            c_kranlaxs_gift = {name = "Presente", text = {"Concede {C:attention}1{} dos seguintes", "prêmios aleatórios:", "• Um {C:attention}Coringa{} com Edição", "• Um {C:attention}Consumível{} Negativo", "• Uma {C:attention}Carta{} com Melhoria, Selo e Edição"}},
            c_kranlaxs_customdraw = {name = "Compra Personalizada", text = {"Compra a mesma quantidade de cartas", "que descartes você fez", "{C:inactive}(Atualmente: {C:attention}#1#{C:inactive} cartas){}"}}
        },

        InverseTarot = {
            c_kranlaxs_thefool = {name = "O Louco?", text = {"Cria uma carta {C:spectral}Espectral{} aleatória", "{C:attention}Rebaixa o nível{} de uma mão de pôquer aleatória"}},
            c_kranlaxs_themagician = {name = "O Mago?", text = {"Cria {C:attention}2{} cartas da {C:attention}Sorte{} aleatórias"}},
            c_kranlaxs_thehighpriestess = {name = "A Sacerdotisa?", text = {"Cria um {C:spectral}Buraco Negro{}", "O seu {X:money,C:white} dinheiro {} {C:attention}diminui{} em 20%"}},
            c_kranlaxs_theempress = {name = "A Imperatriz?", text = {"Adiciona {C:red}+8{} Mult permanente", "em até {C:attention}2{} cartas selecionadas"}},
            c_kranlaxs_theemperor = {name = "O Imperador?", text = {"Cria {C:attention}2{} {C:attention}Marcadores{} aleatórios"}},
            c_kranlaxs_thehierophant = {name = "O Hierofante?", text = {"Adiciona {C:blue}+40{} Fichas permanentes", "em até {C:attention}2{} cartas selecionadas"}},
            c_kranlaxs_thelovers = {name = "Os Enamorados?", text = {"Ganha {C:attention}+1{} tamanho de mão se", "você tiver uma {C:attention}Carta Curinga{} no baralho"}},
            c_kranlaxs_thechariot = {name = "O Carro?", text = {"Cria {C:attention}1{} carta de {C:attention}Aço{} aleatória", "com um Selo {C:attention}Vermelho{}"}},
            c_kranlaxs_justice = {name = "A Justiça?", text = {"Adiciona {X:red,C:white} X2 {} Mult permanente", "a {C:attention}1{} carta selecionada", "{C:green}#1# em #2#{} chance de {C:attention}destruir{} esta carta"}},
            c_kranlaxs_thehermit = {name = "O Eremita?", text = {"{C:attention}Define{} o seu {X:money,C:white} dinheiro {} para {X:money,C:white} $25 {} se", "você tiver {C:attention}menos de{} {X:money,C:white} $25 {}"}},
            c_kranlaxs_thewheeloffortune = {name = "A Roda da Fortuna?", text = {"{C:green}#1# em #2#{} chance de criar uma {C:attention}cópia{}", "de um Coringa aleatório com edição {C:dark_edition}Negativa{}"}},
            c_kranlaxs_strenght = {name = "A Força?", text = {"{C:attention}Reduz{} a {C:attention}categoria{} de até", "{C:attention}2{} cartas selecionadas em {C:attention}1{}"}},
            c_kranlaxs_thehangedman = {name = "O Enforcado?", text = {"Totalmente {C:attention}aleatoriza{} até", "{C:attention}2{} cartas selecionadas na mão"}},
            c_kranlaxs_death = {name = "A Morte?", text = {"Cria uma {C:attention}cópia Negativa{} de um Coringa aleatório", "Um Coringa aleatório recebe um Adesivo {C:attention}Perecível{}"}},
            c_kranlaxs_temperance = {name = "A Temperança?", text = {"Vende {C:attention}TODOS{} os Coringas (mesmo os Eternos)", "pelo {C:money}triplo{} de seu valor de venda", "{C:inactive}(Não vende Coringas Fixados){}"}},
            c_kranlaxs_thedevil = {name = "O Diabo?", text = {"Adiciona {X:money,C:white} $2 {} permanentes", "em até {C:attention}2{} cartas selecionadas"}},
            c_kranlaxs_thetower = {name = "A Torre?", text = {"{C:attention}Remove{} todas as melhorias, selos,", "edições e bônus das cartas na mão", "Ganha {X:money,C:white} $1 {} por cada modificação removida"}},
            c_kranlaxs_thestars = {name = "As Estrelas?", text = {"Adiciona um {C:attention}Selo Branco{} em até", "{C:attention}2{} cartas selecionadas"}},
            c_kranlaxs_themoon = {name = "A Lua?", text = {"Adiciona um {C:attention}Selo Cinza{} em até", "{C:attention}2{} cartas selecionadas"}},
            c_kranlaxs_thesun = {name = "O Sol?", text = {"Adiciona um {C:attention}Selo Laranja{} em até", "{C:attention}2{} cartas selecionadas"}},
            c_kranlaxs_judgement = {name = "O Julgamento?", text = {"{C:attention}Resgata{} um {C:attention}Cupom{} aleatório", "{C:red}-1{} tamanho de mão"}},
            c_kranlaxs_theworld = {name = "O Mundo?", text = {"Adiciona um {C:attention}Selo Marrom{} em até", "{C:attention}2{} cartas selecionadas"}}
        },

        Voucher = {
            v_kranlaxs_more_stock = {name = "Mais Estoque", text = {"A loja tem {C:attention}1{} espaço", "extra de {C:attention}Pacote{}"}},
            v_kranlaxs_even_more_stock = {name = "Ainda Mais Estoque", text = {"A loja tem {C:attention}1{} espaço", "extra de {C:attention}Cupom{}"}},
            v_kranlaxs_shiny_appearance = {name = "Aparência Incomum", text = {"Cartas lendárias e consumíveis raros", "agora podem aparecer na loja"}},
            v_kranlaxs_stickerfever = {name = "Febre de Adesivos", text = {"Sempre que você obtiver", "um {C:attention}Marcador{}, ganhe", "{C:attention}1{} cópia extra"}},
            v_kranlaxs_stickeralbum = {name = "Álbum de Adesivos", text = {"Sempre que você obtiver", "um {C:attention}Marcador{}, ganhe", "{C:attention}1{} cópia extra a mais"}},
            v_kranlaxs_hotfix = {name = "Hotfix", text = {"{C:attention}Atualizar{} a loja", "também atualiza os {C:attention}Cupons{}", "e os {C:attention}Pacotes de Melhoria{}"}},
            v_kranlaxs_version2 = {name = "Versão 2.0", text = {"Pular blinds concede o {X:money,C:white} dinheiro {}", "de recompensa daquele blind.", "Requisito do blind {C:attention}-15%{}"}},
            v_kranlaxs_common_shinys = {name = "Avistamento Lendário", text = {"Cartas lendárias e consumíveis raros", "aparecerão com maior frequência"}},
            v_kranlaxs_blessing = {name = "Bênção", text = {"Você começa com {C:attention}10%{}", "do requisito de fichas", "concluído em cada blind"}},
            v_kranlaxs_protection = {name = "Proteção Divina", text = {"Protege você de um {C:attention}Fim de Jogo{}.", "Ao ser usado, este cupom é destruído", "e pode reaparecer na loja,", "mas pelo {X:money,C:white} dobro {} de seu preço original"}}
        },

        Quartz = {
            c_kranlaxs_blackquartz = {name = "Obsidiana", text = {"Modifica algumas regras", "de sua escolha"}, unlock = {"Vença uma partida na {C:attention}Aposta Marrom{}", "usando o {C:attention}Baralho Mágico{}"}},
            c_kranlaxs_whitequartz = {name = "Pérola", text = {"Cria o último", "consumível usado", "{C:inactive}(Última carta: {C:attention}#1#{C:inactive}){}"}, unlock = {"Vença uma partida na {C:attention}Aposta Marrom{}", "usando o {C:attention}Baralho Fantasma{}"}},
            c_kranlaxs_pinkquartz = {name = "Quartzo Rosa", text = {"Adiciona {C:dark_edition}Policromo{} a um {C:attention}Coringa{}", "ou {C:attention}carta{} selecionada"}, unlock = {"Vença uma partida na {C:attention}Aposta Magenta{}", "ou superior usando o {C:attention}Baralho de Masmorra{}"}},
            c_kranlaxs_bluequartz = {name = "Safira", text = {"Adiciona {C:chips}Foil{} a um", "{C:attention}Coringa{} ou {C:attention}carta{} selecionada"}, unlock = {"Vença uma partida na {C:attention}Aposta de Platina{}", "usando o {C:attention}Baralho de Plasma{}"}},
            c_kranlaxs_lilacquartz = {name = "Kunzita", text = {"Adiciona {C:mult}Holográfico{} a um", "{C:attention}Coringa{} ou {C:attention}carta{} selecionada"}, unlock = {"Vença uma partida na {C:attention}Aposta Marrom{}", "usando o {C:attention}Baralho Nebuloso{}"}},
            c_kranlaxs_grayquartz = {name = "Hematita", text = {"Adiciona {C:dark_edition}Negativo{} a um", "{C:attention}Coringa{} ou {C:attention}consumível{} selecionado"}, unlock = {"Vença uma partida na {C:attention}Aposta Turquesa{}", "usando o {C:attention}Baralho Pintado{}"}},
            c_kranlaxs_transparentquartz = {name = "Diamante", text = {"{C:attention}Remove{} todos os adesivos ou edições", "de um {C:attention}Coringa{}, ou selos ou", "edições de uma {C:attention}carta{} selecionada"}, unlock = {"Vença uma partida na {C:attention}Aposta de Platina{}", "usando o {C:attention}Baralho de Masmorra{}"}},
            c_kranlaxs_redquartz = {name = "Rubi", text = {"Enquanto {C:attention}segurado{},", "dá {X:mult,C:white} X2 {} Mult", "{C:inactive}(Passivo){}"}, unlock = {"Vença uma partida na {C:attention}Aposta Magenta{}", "ou superior usando o {C:attention}Baralho Vermelho{}"}},
            c_kranlaxs_celestequartz = {name = "Larimar", text = {"Enquanto {C:attention}segurado{},", "dá {X:chips,C:white} X1.5 {} Fichas", "{C:inactive}(Passivo){}"}, unlock = {"Vença uma partida na {C:attention}Aposta Turquesa{}", "usando o {C:attention}Baralho Xadrez{}"}},
            c_kranlaxs_yellowquartz = {name = "Topázio", text = {"Cria o {C:attention}Coringa{} indicado.", "O Coringa muda aleatoriamente", "após cada {C:attention}rodada{}", "{C:inactive}(Alvo: {C:attention}#1#{C:inactive}){}"}, unlock = {"Vença uma partida na {C:attention}Aposta Azul{}", "usando o {C:attention}Baralho de Masmorra{}"}},
            c_kranlaxs_greenquartz = {name = "Esmeralda", text = {"Enquanto {C:attention}segurado{}, cria um", "{C:attention}Marcador{} após derrotar um {C:attention}Blind{}", "Destruído após criar {C:attention}#2#{} marcadores", "{C:inactive}(Atuais: {C:attention}#1#{C:inactive}){}", "{C:inactive}(Passivo){}"}, unlock = {"Vença uma partida na {C:attention}Aposta Magenta{}", "ou superior usando o {C:attention}Baralho Verde{}"}},
            c_kranlaxs_brownquartz = {name = "Olho de Tigre", text = {"Cria a {C:attention}Carta{} indicada.", "A carta muda aleatoriamente após", "{C:green}Atualizar{} a loja", "{C:inactive}(Alvo: {C:attention}#1#{C:inactive}){}"}, unlock = {"Vença uma partida na {C:attention}Aposta Turquesa{}", "usando o {C:attention}Baralho Anáglifo{}"}},
            c_kranlaxs_turquoisequartz = {name = "Turquesa", text = {"Enquanto {C:attention}segurado{}, {C:attention}desativa{}", "todos os coringas exceto o primeiro", "Reativa esse coringa {C:attention}2{} vezes", "{C:inactive}(Passivo){}"}, unlock = {"Vença uma partida na {C:attention}Aposta Turquesa{}", "usando o {C:attention}Baralho Zodiacal{}"}},
            c_kranlaxs_orangequartz = {name = "Citrino", text = {"Adiciona {C:green}Selo de Menta{} a uma {C:attention}carta{}", "ou {C:green}Adesivo Trevo{} a um", "{C:attention}Coringa{} selecionado"}, unlock = {"Vença uma partida na {C:attention}Aposta Magenta{}", "ou superior usando o {C:attention}Baralho Amarelo{}"}},
            c_kranlaxs_lapislazuli = {name = "Lápis-lazúli", text = {"Enquanto {C:attention}segurado{}, adiciona", "{C:chips}+#1#{} Fichas à primeira carta pontuada", "O efeito diminui em {C:chips}-#2#{} cada uso.", "{C:inactive}(Inativo ao chegar a 0){}", "{C:inactive}(Passivo){}"}, unlock = {"Vença uma partida na {C:attention}Aposta Magenta{}", "ou superior usando o {C:attention}Baralho Azul{}"}},
            c_kranlaxs_cinnabar = {name = "Cinábrio", text = {"Enquanto {C:attention}segurado{}, adiciona", "{C:mult}+#1#{} Mult à primeira carta pontuada", "O efeito diminui em {C:mult}-#2#{} cada uso.", "{C:inactive}(Inativo ao chegar a 0){}", "{C:inactive}(Passivo){}"}, unlock = {"Vença uma partida na {C:attention}Aposta Marrom{}", "usando o {C:attention}Baralho Abandonado{}"}},
            c_kranlaxs_graphite = {name = "Grafite", text = {"Enquanto {C:attention}segurado{}, {C:green}#1# em #2#{}", "chances de criar uma cópia na sua", "mão de todas as cartas jogadas.", "A chance cai ao ativar.", "{C:inactive}(Inativo ao chegar a 0){}", "{C:inactive}(Passivo){}"}, unlock = {"Vença uma partida na {C:attention}Aposta Magenta{}", "ou superior usando o {C:attention}Baralho Preto{}"}},
            c_kranlaxs_uranium = {name = "Urânio", text = {"Enquanto {C:attention}segurado{}, aplica 1 efeito", "aleatório por rodada. Pode ser", "muito bom ou muito destrutivo.", "{C:dark_edition}Estado atual:{}", "{C:red,E:2}#1#{}", "{C:inactive}(Ousa carregá-lo?){}", "{C:inactive}(Passivo){}"}, unlock = {"Vença uma partida na {C:attention}Aposta de Platina{}", "usando o {C:attention}Baralho Errático{}"}}
        },

        Tag = {
            tag_kranlaxs_mega_invtarot = {name = "Mega Marcador Inverso", text = {"Concede um {C:attention}Mega Pacote Tarot Inverso{}", "grátis instantaneamente"}},
            tag_kranlaxs_mega_uno = {name = "Marcador UNO Jumbo", text = {"Concede um {C:attention}Pacote UNO Jumbo{}", "grátis instantaneamente"}},
            tag_kranlaxs_mega_invtarot_store = {name = "Mega Marcador Inverso Guardado", text = {"Concede um {C:attention}Mega Tarot Inverso Guardado{}", "grátis instantaneamente"}},
            tag_kranlaxs_quartz_tag = {name = "Marcador de Quartzo", text = {"Cria um {C:attention}Quartzo{} aleatório", "{C:inactive}(Deve ter espaço){}"}},
            tag_kranlaxs_sticker_remover = {name = "Marcador Limpador", text = {"Remove um adesivo {C:attention}Eterno{},", "{C:attention}Perecível{} ou de {C:attention}Aluguel{} de", "um {C:attention}Coringa{} aleatório", "{C:inactive}(Dá {X:money,C:white} $5 {C:inactive} se não houver adesivos){}"}},
            tag_kranlaxs_legendary = {name = "Marcador Lendário", text = {"A loja tem um", "{C:legendary}Coringa Lendário{} grátis"}}
        },

        Edition = {
            e_kranlaxs_wave = {name = "Aquática", text = {"{X:chips,C:white} X#1# {} Fichas"}}
        },

        Other = {
            kranlaxs_magenta_sticker = {name = "Adesivo Magenta", text = {"Usou este Coringa", "para vencer na {C:attention}Aposta Magenta{}"}},
            kranlaxs_brown_sticker = {name = "Adesivo Marrom", text = {"Usou este Coringa", "para vencer na {C:attention}Aposta Marrom{}"}},
            kranlaxs_turquoise_sticker = {name = "Adesivo Turquesa", text = {"Usou este Coringa", "para vencer na {C:attention}Aposta Turquesa{}"}},
            kranlaxs_platinum_sticker = {name = "Adesivo de Platina", text = {"Usou este Coringa", "para vencer na {C:attention}Aposta de Platina{}"}},
            kranlaxs_deviled_sticker = {name = "Adesivo Diabólico", text = {"Usou este Coringa", "para vencer na {C:attention}Aposta Diabólica{}"}},
            kranlaxs_glass_sticker = {name = "Adesivo de Vidro", text = {"Usou este Coringa", "para vencer na {C:attention}Aposta de Vidro{}"}},
            kranlaxs_orangeseal_seal = {name = "Selo Laranja", text = {"Se pontuada na mão: {C:attention}#1#{},", "cria 1 {C:attention}#2#{}", "{C:inactive}Muda após o uso.{}", "{C:inactive}(Deve ter espaço){}"}},
            kranlaxs_pinkseal_seal = {name = "Selo Rosa", text = {"Aplica {X:dark_edition,C:white}^1.75{} de Mult", "ao ser {C:attention}pontuada{}"}},
            kranlaxs_whiteseal_seal = {name = "Selo Branco", text = {"{C:attention}Sempre pontua{}, imune a", "ser {C:red}debuffada{}, {C:red}destruída{}", "ou {C:attention}virada{}"}},
            kranlaxs_brownseal_seal = {name = "Selo Marrom", text = {"{C:green}#1# em #2#{} chances de", "{C:attention}duplicar{} esta carta", "enquanto estiver na mão"}},
            kranlaxs_grayseal_seal = {name = "Selo Cinza", text = {"Ao {C:attention}pontuar{}, muda {C:attention}aleatoriamente{}", "a {C:enhanced}Melhoria{} desta carta"}},
            kranlaxs_mintseal_seal = {name = "Selo de Menta", text = {"Dobra as {C:attention}probabilidades{}", "desta carta"}},
            p_kranlaxs_uno_store_3 = {name = "Pacote UNO", text = {"Escolha {C:attention}1{} de até", "{C:attention}3{} cartas {C:blue}UNO{}"}},
            p_kranlaxs_uno_store_5 = {name = "Pacote UNO Jumbo", text = {"Escolha {C:attention}1{} de até", "{C:attention}5{} cartas {C:blue}UNO{}"}},
            p_kranlaxs_invtarot_instant_3_1 = {name = "Pacote Tarot Inverso", text = {"Escolha {C:attention}1{} de até", "{C:attention}3{} cartas {C:purple}Tarot Inverso{}"}},
            p_kranlaxs_invtarot_instant_5_1 = {name = "Pacote Tarot Inverso Jumbo", text = {"Escolha {C:attention}1{} de até", "{C:attention}5{} cartas {C:purple}Tarot Inverso{}"}},
            p_kranlaxs_invtarot_instant_5_2 = {name = "Mega Pacote Tarot Inverso", text = {"Escolha {C:attention}2{} de até", "{C:attention}5{} cartas {C:purple}Tarot Inverso{}"}},
            p_kranlaxs_invtarot_store_3_1 = {name = "Tarot Inverso Guardado", text = {"Escolha {C:attention}1{} de até", "{C:attention}3{} cartas {C:purple}Tarot Inverso{}"}},
            p_kranlaxs_invtarot_store_5_1 = {name = "Tarot Inverso Guardado Jumbo", text = {"Escolha {C:attention}1{} de até", "{C:attention}5{} cartas {C:purple}Tarot Inverso{}"}},
            p_kranlaxs_invtarot_store_5_2 = {name = "Mega Tarot Inverso Guardado", text = {"Escolha {C:attention}2{} de até", "{C:attention}5{} cartas {C:purple}Tarot Inverso{}"}}
        },

        Booster = {
            p_kranlaxs_uno_store_3 = {name = "Pacote UNO", text = {"Escolha {C:attention}1{} de até", "{C:attention}3{} cartas {C:blue}UNO{}"}},
            p_kranlaxs_uno_store_5 = {name = "Pacote UNO Jumbo", text = {"Escolha {C:attention}1{} de até", "{C:attention}5{} cartas {C:blue}UNO{}"}},
            p_kranlaxs_invtarot_instant_3_1 = {name = "Pacote Tarot Inverso", text = {"Escolha {C:attention}1{} de até", "{C:attention}3{} cartas {C:purple}Tarot Inverso{}"}},
            p_kranlaxs_invtarot_instant_5_1 = {name = "Pacote Tarot Inverso Jumbo", text = {"Escolha {C:attention}1{} de até", "{C:attention}5{} cartas {C:purple}Tarot Inverso{}"}},
            p_kranlaxs_invtarot_instant_5_2 = {name = "Mega Pacote Tarot Inverso", text = {"Escolha {C:attention}2{} de até", "{C:attention}5{} cartas {C:purple}Tarot Inverso{}"}},
            p_kranlaxs_invtarot_store_3_1 = {name = "Tarot Inverso Guardado", text = {"Escolha {C:attention}1{} de até", "{C:attention}3{} cartas {C:purple}Tarot Inverso{}"}},
            p_kranlaxs_invtarot_store_5_1 = {name = "Tarot Inverso Guardado Jumbo", text = {"Escolha {C:attention}1{} de até", "{C:attention}5{} cartas {C:purple}Tarot Inverso{}"}},
            p_kranlaxs_invtarot_store_5_2 = {name = "Mega Tarot Inverso Guardado", text = {"Escolha {C:attention}2{} de até", "{C:attention}5{} cartas {C:purple}Tarot Inverso{}"}}
        }
    },
    
    misc = {

        labels = {
            kranlaxs_magenta_sticker = "Adesivo Magenta",
            kranlaxs_brown_sticker = "Adesivo Marrom",
            kranlaxs_turquoise_sticker = "Adesivo Turquesa",
            kranlaxs_platinum_sticker = "Adesivo de Platina",
            kranlaxs_orangeseal_seal = "Selo Laranja", 
            kranlaxs_pinkseal_seal = "Selo Rosa", 
            kranlaxs_whiteseal_seal = "Selo Branco", 
            kranlaxs_brownseal_seal = "Selo Marrom", 
            kranlaxs_grayseal_seal = "Selo Cinza", 
            kranlaxs_mintseal_seal = "Selo de Menta", 
            clover = "Adesivo Trevo",
            kranlaxs_deviled_sticker = "Adesivo Diabólico",
            kranlaxs_glass_sticker = "Adesivo de Vidro",
            p_kranlaxs_uno_store_3 = "Pacote UNO",
            p_kranlaxs_uno_store_5 = "Pacote UNO Jumbo",
            p_kranlaxs_invtarot_instant_3_1 = "Pacote Tarot Inverso",
            p_kranlaxs_invtarot_instant_5_1 = "Pacote Tarot Inverso Jumbo",
            p_kranlaxs_invtarot_instant_5_2 = "Mega Pacote Tarot Inverso",
            p_kranlaxs_invtarot_store_3_1 = "Tarot Inverso Guardado",
            p_kranlaxs_invtarot_store_5_1 = "Tarot Inverso Guardado Jumbo",
            p_kranlaxs_invtarot_store_5_2 = "Mega Tarot Inverso Guardado",
            kranlaxs_wave = "Aquática"
        },

        v_text = {
            ch_c_kran_fijado_1 = {"Todos os coringas têm o adesivo {C:attention}Fixado{}"},
            ch_c_kran_abuela_1 = {"Coringas de {C:attention}pontuação{} estão {C:red}banidos{}"},
            ch_c_kran_crisis_1 = {"A loja está {C:attention}20% mais cara{}"},
            ch_c_kran_crisis_2 = {"O prêmio base dos blinds é {C:red}reduzido{} em {X:money,C:white} $2 {}"},
            ch_c_kran_crisis_3 = {"O baralho é composto apenas por {C:attention}52 Ases{}"},
            ch_c_kran_doppel_1 = {"Todos os coringas estão {C:red}banidos{} da loja"},
            ch_c_kran_anonimo_1 = {"Cartas na mão e coringas estão {C:attention}virados para baixo{}"},
            ch_c_kran_jefes_1 = {"Blinds Pequenos e Grandes são {C:attention}Blinds Chefes{}"},
            ch_c_kran_premon_1 = {"Todas as cartas na sua mão estão {C:attention}viradas para baixo{}"},
            ch_c_kran_tallo_1 = {"Os outros {C:attention}Coringas{} e {C:attention}Pacotes{} estão {C:red}banidos{}"},
            ch_c_gacha_rule_1 = {"Nenhuma {C:attention}carta individual{} aparece na loja"},
            ch_c_kran_pobreza_1 = {"{C:attention}50%{} de chance de um {C:common}Comum{} ser {C:legendary}Lendário{}"},
            ch_c_kran_pobreza_2 = {"Se o seu Coringa {C:attention}Monge{} se decepcionar, {C:red}você perde a partida{}"}
        }
    }
}