return {
    descriptions = {
        Joker = {
            j_kranlaxs_tagger = {name = "Маркер", text = {"Дает {C:red}+#1#{} к Множ. за каждый", "полученный {C:attention}Тег{}", "{C:inactive}(Сейчас {C:red}+#2#{C:inactive} Множ.){}"}, unlock = {"Купите {C:attention}2{} Пустых", "ваучера за один забег"}},
            j_kranlaxs_Cashback = {name = "Кэшбэк", text = {"Шанс {C:green}#1# из #2#{} получить {X:money,C:white} $3 {},", "при покупке карты"}, unlock = {"Победите на {C:attention}Красной Ставке{}", "используя {C:attention}Космическую Колоду{}"}},
            j_kranlaxs_underratedjoker = {name = "Недооцененный Джокер", text = {"Этот джокер получает {X:chips,C:white} X0.2 {} к Фишкам", "если сыгранная рука {C:attention}не является{}", "вашей самой частой покерной комбинацией", "{C:inactive}(Сбрасывается, если это она){}", "{C:inactive}(Сейчас {X:chips,C:white} X#1# {C:inactive} Фишек){}"}, unlock = {"Победите на {C:attention}Синей Ставке{}", "используя {C:attention}Космическую Колоду{}"}},
            j_kranlaxs_facelessaccountant = {name = "Безликий Бухгалтер", text = {"Этот джокер получает {X:blue,C:white} X0.1 {} к Фишкам за", "каждую набравшую очки {C:attention}#2#{}", "{C:inactive}(Сейчас {X:blue,C:white} X#1# {C:inactive} Фишек){}"}, unlock = {"Победите, не играя карт с картинками,", "имея по крайней мере {C:attention}1{} в колоде"}},
            j_kranlaxs_thefixer = {name = "Чистильщик", text = {"Продажа {C:attention}Джокера{} во время", "{C:purple}Блайнда{} снижает требования к счету", "{C:inactive}(Обыч: -10%, Необыч: -30%){}", "{C:inactive}(Редкий: -60%, Легендарный: -95%){}"}, unlock = {"Продайте как минимум {C:attention}2{} джокеров", "каждой редкости"}},
            j_kranlaxs_mysteriousgeode = {name = "Таинственная Жеода", text = {"Каждая набравшая очки {C:attention}Универсальная Карта{}", "дает {C:attention}случайный{} эффект"}, unlock = {"Сыграйте руку", "с {C:attention}5{} Универсальными Картами"}},
            j_kranlaxs_benchwarmer = {name = "Запасной", text = {"Дает в {C:attention}4 раза больше{} {C:blue}Фишек{}", "номинала самой старшей карты в руке"}},
            j_kranlaxs_entropy2 = {name = "Вихрь", text = {"Получает {X:dark_edition,C:white} ^1 {} к Множ. и {X:dark_edition,C:white} ^1 {} к Фишкам", "за каждую карту {C:attention}ниже 52{} в колоде", "{C:inactive}(Сейчас {X:dark_edition,C:white} ^#1# {C:inactive} Множ. и {X:dark_edition,C:white} ^#1# {C:inactive} Фишек){}"}},
            j_kranlaxs_greedyleprachaun = {name = "Жадный Лепрекон", text = {"Вытяните {C:attention}3 доп. карты{}", "при первом {C:red}сбросе{} в раунде"}, unlock = {"Сбросьте ровно {C:attention}1{} карту", "{C:attention}3{} раза подряд"}},
            j_kranlaxs_charismaticbard = {name = "Харизматичный Бард", text = {"{C:attention}-1{} к размеру руки", "Снижает требование {C:purple}Блайнда{} на {C:attention}2%{} каждый раз,", "когда вы играете свою {C:attention}самую частую руку{}", "{C:inactive}(Максимум 90%){}", "Сбрасывается, если сыграть другую руку", "{C:inactive}(Сейчас {C:attention}-#1#%{C:inactive} размер Блайнда){}"}},
            j_kranlaxs_russianroulette = {name = "Русская Рулетка", text = {"Шанс {C:green}#1# из #2#{} {C:red}Проиграть забег{}", "при выборе блайнда", "Если выживете, получает", "{X:mult,C:white} X3 {} к Множ. и {X:chips,C:white} X3 {} к Фишкам", "{C:inactive}(Сейчас {X:mult,C:white} X#3# {C:inactive} Множ. и {X:chips,C:white} X#3# {C:inactive} Фишек){}"}, unlock = {"Победите на {C:attention}Черной Ставке{}", "используя {C:attention}Космическую Колоду{}"}},
            j_kranlaxs_fidelitycard = {name = "Боевой Пропуск", text = {"После покупки {C:attention}6{} карт, {C:attention}седьмая{}", "купленная карта дает {X:money,C:white} деньги {} равные", "{C:attention}цене продажи{} всех ваших джокеров", "{C:inactive}(Сейчас {C:attention}#1#/6{C:inactive} карт){}", "{C:inactive}(Общая цена продажи: {X:money,C:white} $#2# {C:inactive}){}"}},
            j_kranlaxs_devioussheep = {name = "Прожорливая Овца", text = {"{C:red}Пожирает{} случайного Джокера при", "выборе {C:attention}Блайнда{} и получает {X:mult,C:white} X0.4 {} к Множ.", "{C:hearts}Конец Игры{}, если других Джокеров нет", "{C:inactive}(Расставьте приоритеты для большего множителя!){}", "{C:inactive}(Сейчас {X:mult,C:white} X#1# {C:inactive} к Множ.){}"}},
            j_kranlaxs_lifeassurance = {name = "Страхование Жизни", text = {"Предотвращает Конец Игры, если", "у вас есть как минимум {X:money,C:white} $#1# {}", "{C:inactive}(Цена удваивается после каждого использования){}"}, unlock = {"Проиграйте забег с", "{X:money,C:white} $100 {} или более", "до {C:attention}Анте 8{}"}},
            j_kranlaxs_sundaycheckpoint = {name = "Чекпойнт", text = {"{C:red}Конец Игры{}, если выбрать блайнд", "в {C:attention}будний день{}", "Иначе создает джокера {C:attention}Еженедельного Вызова{}", "в конце раунда и {C:red}самоуничтожается{}", "{C:inactive}(Текущий день: #1#){}"}},
            j_kranlaxs_weeklychallenge = {name = "Еженедельный Вызов", text = {"Устанавливает случайное испытание для этого забега", "{C:clubs}Текущее испытание:{} {C:attention}#1#{}", "{C:inactive}1:{} У вас {X:money,C:white} -$100 {}, оплатите до Анте 8", "{C:inactive}2:{} Ограниченный магазин", "{C:inactive}3:{} 1 Рука, 20 Сбросов (Без доп. ваучеров)", "{C:inactive}4:{} Лимит в {C:blue}#2#{} рук и {C:red}#3#{} сбросов на забег", "{C:inactive}5:{} Скорость игры заблокирована на 0.5x", "{C:inactive}6:{} 3 Вечных Трибуле (Макс. 3 Джокера, Быстрый Анте)", "{C:inactive}7:{} Шанс 1 из 6 ПОБЕДИТЬ при поражении блайнда (Поражение на Анте 8)"}},
            j_kranlaxs_panda = {name = "Пушистая Панда", text = {"Дает {C:chips}+#1#{} Фишек", "{C:attention}-1{} слот для Джокера"}},
            j_kranlaxs_miner = {name = "Шахтер", text = {"Получает {C:red}+5{} к Множ. за каждую", "сыгранную {C:attention}Каменную Карту{}", "Шанс {C:green}#2# из #3#{} получить", "от {X:money,C:white} $#4# {} до {X:money,C:white} $#5# {} при розыгрыше руки", "{C:inactive}(Сейчас {C:red}+#1#{C:inactive} к Множ.){}"}, unlock = {"Сыграйте руку", "с {C:attention}5{} Каменными Картами"}},
            j_kranlaxs_birthdaycake = {name = "Именинный Торт", text = {"Дает {X:dark_edition,C:white} ^#1# {} к Множ.", "Теряет {X:dark_edition,C:white} ^0.25 {} после", "каждой сыгранной руки", "При истощении создает {C:attention}Передаренного Джокера{}"}, unlock = {"Победите на", "{C:attention}Синей Ставке{} используя", "колоду {C:attention}Еженедельного Вызова{}"}},
            j_kranlaxs_vipsuscription = {name = "V.I.P. Подписка", text = {"Дает {C:attention}+#2#{} слота в магазине,", "{C:attention}+1{} доп. ваучер и набор", "Вычитает {X:money,C:white} $#1# {} при открытии магазина.", "Цена и размер магазина", "{C:attention}увеличиваются{} при победе над {C:attention}Босс Блайндом{}"}, unlock = {"Победите на", "{C:attention}Оранжевой Ставке{} используя", "колоду {C:attention}Еженедельного Вызова{}"}},
            j_kranlaxs_painterjoker = {name = "Джокер-Художник", text = {"Когда рука набирает очки, создает", "{C:attention}Тег Жонглера{} за каждую", "{C:attention}Универсальную Карту{} в вашей руке", "{C:inactive}(Стоит {X:money,C:white} $#1# {C:inactive} за тег){}"}, unlock = {"Победите на", "{C:attention}Оранжевой Ставке{} используя", "колоду {C:attention}Еженедельного Вызова{}"}},
            j_kranlaxs_coronation = {name = "Коронация", text = {"Если сыгранная рука содержит карты", "ранга {C:attention}10 или ниже{}, превращает", "карту с наименьшим номиналом в {C:attention}Короля{}.", "Если мелких карт нет,", "добавляет {C:red}Красную Печать{} первому {C:attention}Королю{}."}, unlock = {"Сыграйте руку ровно из", "{C:attention}5 Королей{}. Все должны иметь", "{C:red}Красную Печать{} и быть {C:attention}Стальными{}"}},
            j_kranlaxs_speedrunner = {name = "Спидраннер", text = {"{X:mult,C:white} X#1# {} к Множ.", "У вас есть {C:attention}#2# секунд{} чтобы", "сыграть руку или сбросить.", "Если время выйдет, {C:red}КОНЕЦ ИГРЫ{}."}, unlock = {"Победите на", "{C:attention}Зеленой Ставке{} используя", "колоду {C:attention}Еженедельного Вызова{}"}},
            j_kranlaxs_passcode = {name = "Пароль", text = {"Если сыгранная рука совпадает с одним", "из следующих кодов, рука", "считается {C:attention}Флеш-Пятеркой{}", "{C:inactive}1. {C:attention}#1#{}", "{C:inactive}2. {C:attention}#2#{}", "{C:inactive}3. {C:attention}#3#{}"}, unlock = {"Победите на", "{C:attention}Черной Ставке{} используя", "колоду {C:attention}Еженедельного Вызова{}"}},
            j_kranlaxs_chronometer = {name = "Хронометр", text = {"При розыгрыше руки: ", "Дает {C:chips}Фишки{} равные текущим {C:attention}Секундам{}", "Дает {C:mult}Множ.{} равный текущим {C:attention}Минутам{}", "Приносит {C:money}деньги{} равные текущим {C:attention}Часам{}", "{C:inactive}(Сейчас: {C:chips}+#1#{C:inactive} Фишек, {C:mult}+#2#{C:inactive} Множ., {C:money}+$#3#{C:inactive}){}"}, unlock = {"Победите на {C:attention}Золотой Ставке{}", "используя {C:attention}Космическую Колоду{}"}},
            j_kranlaxs_zombiejoker = {name = "Зомби Джока", text = {"{C:attention}унечтожает{} {C:attention}перву{} крту", "котор не дает очков и плучает {C:red}+15{} множ", "н ты трчешь {C:red}-10{} множ", "зкаждую разиграную руку", "если упад до {C:red}0{} множ", "{C:attention}он умерает {}", "{C:inactive}(у тя {C:red}+#1#{C:inactive} множ или тип тоо){}"}, unlock = {"Победите на {C:attention}Фиолетовой Ставке{}", "используя {C:attention}Космическую Колоду{}"}},
            j_kranlaxs_thecousin = {name = "Кузен", text = {"Дает {C:chips}+13{} к Фишкам за каждое", "сыгранное {C:attention}простое число{}", "{C:inactive}(Сейчас {C:chips}+#1#{C:inactive} Фишек){}"}, unlock = {"Победите на {C:attention}Бирюзовой Ставке{}", "используя {C:attention}Космическую Колоду{}"}},
            j_kranlaxs_colasoda = {name = "Газировка Кола", text = {"Дает {X:dark_edition,C:white} ^#1# {} к Множ.", "Теряет {X:dark_edition,C:white} ^#2# {} за", "почти {C:attention}любое ваше действие{}"}, unlock = {"Победите на", "{C:attention}Синей Ставке{} используя", "колоду {C:attention}Еженедельного Вызова{}"}},
            j_kranlaxs_icecreamsandwich = {name = "Сэндвич с Мороженым", text = {"Заработайте {X:money,C:white} $#1# {} в конце", "раунда", "Награда уменьшается на {X:money,C:white} $#2# {}", "после каждого раунда"}, unlock = {"Заработайте {X:money,C:white} $50 {} или больше", "в качестве выплаты за", "один раунд"}},
            j_kranlaxs_dispensermachine = {name = "Торговый Автомат", text = {"Если этот Джокер {C:attention}выбран{}", "при выходе из магазина, тратит {X:money,C:white} $#1# {}", "и создает {C:attention}Пищевого Джокера{}"}, unlock = {"Имейте {C:attention}4{} пищевых", "Джокеров одновременно"}},
            j_kranlaxs_bottledwater = {name = "Бутилированная Вода", text = {"{X:chips,C:white} X#1# {} к Фишкам", "Теряет {X:chips,C:white} X#2# {} за", "каждую набравшую очки карту"}, unlock = {"Победите на", "{C:attention}Синей Ставке{} используя", "колоду {C:attention}Еженедельного Вызова{}"}},
            j_kranlaxs_burrow = {name = "Нора", text = {"Получает {C:attention}+1{} Кролика за", "каждый {C:attention}побежденный Блайнд{}", "При {C:gold}продаже{}, создает {C:attention}#1#{} Кроликов"}},
            j_kranlaxs_bunny = {name = "Кролик", text = {"Дает {X:mult,C:white} X#1# {} к Множ. за каждого", "Джокера {C:attention}Кролика{}, который у вас есть", "{C:inactive}(Сейчас {X:mult,C:white} X#2# {C:inactive} к Множ.){}"}},
            j_kranlaxs_sushi = {name = "Суши", text = {"Снижает требование", "Блайнда на {C:attention}#1#%{}", "Снижение уменьшается на {C:attention}#2#%{}", "после победы над {C:attention}Блайндом{}"}, unlock = {"Победите на", "{C:attention}Фиолетовой Ставке{} используя", "колоду {C:attention}Еженедельного Вызова{}"}},
            j_kranlaxs_gigachad = {name = "Гигачад", text = {"Дает {C:chips}+#2#{} к Фишкам за почти", "{C:attention}любое ваше действие{}", "{C:inactive}(Сейчас {C:chips}+#1#{C:inactive} Фишек){}"}, unlock = {"Победите на", "{C:attention}Белой Ставке{} используя", "колоду {C:attention}Еженедельного Вызова{}"}},
            j_kranlaxs_nft = {name = "Криптоскам", text = {"Снижает {C:attention}ранг{} всех", "карт в вашей руке на {C:attention}1{}", "при розыгрыше руки", "{C:inactive}(Не может быть снижен ниже 2){}"}},
            j_kranlaxs_beanstalk = {name = "Бобовый Стебель", text = {"Бесполезные бобы"}, unlock = {"Победите на", "{C:attention}Белой Ставке{} используя", "колоду {C:attention}Еженедельного Вызова{}"}},
            j_kranlaxs_suspiciousbeanstalk = {name = "Подозрительный Стебель", text = {"Бесполезные бобы?..."}},
            j_kranlaxs_epicbeanstalk = {name = "Эпический Стебель", text = {"Возможно, не такие уж и бесполезные..."}},
            j_kranlaxs_zenithbeanstalk = {name = "Стебель-Зенит", text = {"Бобы"}},
            j_kranlaxs_commonseed = {name = "Обычное Семечко", text = {"{C:attention}Создает{} случайного", "{C:common}Обычного{} Джокера"}},
            j_kranlaxs_weirdlookingseed = {name = "Странное Семечко", text = {"{C:attention}Создает{} случайного", "{C:uncommon}Необычного{} Джокера"}},
            j_kranlaxs_magnificentseed = {name = "Великолепное Семечко", text = {"{C:attention}Создает{} случайного", "{C:rare}Редкого{} Джокера"}},
            j_kranlaxs_godseed = {name = "Божественное Семечко", text = {"{C:attention}Создает{} случайного", "{C:legendary}Легендарного{} Джокера"}},
            j_kranlaxs_anonymousjoker = {name = "Анонимный Джокер", text = {"При наборе очков переворачивается и дает от", "{X:mult,C:white} X1.5 {} до {X:mult,C:white} X4.0 {} к Множ."}, unlock = {"Победите Босс-Блайнда", "{C:attention}Янтарный Желудь{} 1 раз"}},
            j_kranlaxs_littlebro = {name = "Младший Брат", text = {"Если сыгранная рука {C:attention}Старшая Карта{} и", "карта набравшая очки - {C:attention}#2#{},", "этот Джокер получает {X:red,C:white} X#3# {} к Множ.", "Ранг карты меняется каждый раунд", "{C:inactive}(Сейчас {X:red,C:white} X#1# {C:inactive} к Множ.){}"}, unlock = {"Сыграйте {C:attention}Старшую Карту{}", "{C:attention}30{} раз за", "один забег"}},
            j_kranlaxs_medusa = {name = "Медуза", text = {"{C:attention}Все сыгранные карты{}", "навсегда становятся {C:attention}Каменными Картами{}", "после розыгрыша руки", "{C:inactive}(Даже те, что не набрали очки){}"}, unlock = {"Победите на {C:attention}Коричневой Ставке{}", "используя {C:attention}Космическую Колоду{}"}},
            j_kranlaxs_depression = {name = "Экономический Спад", text = {"Дает {X:dark_edition,C:white}^#2#{} к Множ.", "Увеличивается на {X:dark_edition,C:white}^#1#{} за каждый {X:money,C:white} $1 {}", "ниже {X:money,C:white} $0 {}"}, unlock = {"Войдите в магазин", "имея {X:money,C:white} -$25 {} или меньше"}},
            j_kranlaxs_grannyjoker = {name = "Бабуля", text = {"Дает {X:dark_edition,C:white} ^3 {} к Фишкам и {X:dark_edition,C:white} ^3 {} к Множ.", "Скорость игры зафиксирована на {C:attention}0.25x{}", "{C:inactive}(Уничтожается, если вы сыграете {C:attention}Стрит{}", "{C:inactive}или {C:attention}Стрит-Флеш{C:inactive}){}"}, unlock = {"Победите {C:attention}12{} блайндов со", "скоростью игры на {C:attention}0.5{}"}},
            j_kranlaxs_lateshippment = {name = "Запоздалая Доставка", text = {"Срабатывают {C:attention}все сыгранные карты{} еще раз", "{C:attention}1 раз{} за каждую руку, сыгранную", "в {C:attention}предыдущем раунде{}", "{C:inactive}(Сейчас {C:attention}#1#{C:inactive} повторов){}"}, unlock = {"Победите на {C:attention}Оранжевой Ставке{}", "используя {C:attention}Космическую Колоду{}"}},
            j_kranlaxs_unkownfactor = {name = "Переменная X", text = {"Все сыгранные карты", "считаются {C:attention}#1#{}", "{C:inactive}(Ранг меняется в конце раунда){}"}, unlock = {"Победите на", "{C:attention}Золотой Ставке{} используя", "колоду {C:attention}Еженедельного Вызова{}"}},
            j_kranlaxs_thethreers = {name = "3 Правила", text = {"Создает {C:attention}копию{} каждой сыгранной карты", "и добавляет ее в вашу {C:attention}колоду{}", "{C:attention}Уничтожает{} все набравшие очки карты"}, unlock = {"Победите на", "{C:attention}Золотой Ставке{} используя", "колоду {C:attention}Еженедельного Вызова{}"}},
            j_kranlaxs_the = {name = "Джок", text = {"Дает {X:chips,C:white} X2 {} к Фишкам и {X:mult,C:white} X2 {} к Множ.", "только в {C:attention}первой руке{} раунда"}, unlock = {"Победите {C:attention}5{} блайндов, используя", "только {C:attention}1{} руку на каждый"}},
            j_kranlaxs_chainreaction = {name = "Цепная Реакция", text = {"Если сыгранная рука - {C:attention}#2#{},", "получает {X:chips,C:white} X0.5 {} к Фишкам, рука меняется", "Сбрасывается, если рука {C:attention}не совпадает{}", "{C:inactive}(Сейчас {X:chips,C:white} X#1# {C:inactive} к Фишкам){}"}, unlock = {"Сыграйте все покерные руки", "хотя бы {C:attention}1{} раз за забег"}},
            j_kranlaxs_anubis = {name = "Анубис", text = {"Уравнивает {C:blue}Фишки{} и {C:red}Множ.{}", "когда рука набирает очки"}, unlock = {"Победите колодой {C:attention}Плазменная Колода{}", "на всех уровнях сложности"}},
            j_kranlaxs_erraticjoker = {name = "Случайный Джокер", text = {"Если набравшая очки карта", "является {C:attention}Универсальной{}, меняет местами", "{C:blue}Фишки{} и {C:red}Множ.{}"}, unlock = {"Победите на {C:attention}Белой Ставке{}", "используя {C:attention}Космическую Колоду{}"}},
            j_kranlaxs_luckyseven = {name = "Счастливые Семерки", text = {"Если сыгранная рука - это ровно", "{C:attention}Сет{} только из {C:attention}7{}, этот Джокер", "получает {C:blue}+7{} к Фишкам, {C:red}+7{} к Множ. и дает {X:money,C:white} $7 {}", "{C:inactive}(Сейчас {C:blue}+#1#{} Фишек, {C:red}+#2#{} к Множ.)"}, unlock = {"Имейте как минимум {C:attention}10{} карт", "ранга {C:attention}7{} в вашей колоде"}},
            j_kranlaxs_certificateddocument = {name = "Сертифицированный Документ", text = {"Заставляет срабатывать {C:attention}все{} печати еще раз"}, unlock = {"Победите на", "{C:attention}Фиолетовой Ставке{} используя", "колоду {C:attention}Еженедельного Вызова{}"}},
            j_kranlaxs_platanito = {name = "Бананчик", text = {"Всякий раз, когда срабатывает другой Джокер,", "дает {X:mult,C:white} X#3# {} доп. Множ.", "Шанс {C:green}#1# из #2#{}", "уничтожиться в конце раунда"}, unlock = {"Победите на {C:attention}Платиновой Ставке{}", "используя {C:attention}Космическую Колоду{}"}},
            j_kranlaxs_cubicaljoker = {name = "Кубический Джокер", text = {"Дает {C:mult}+#1#{} к Множ.", "Значение возводится в", "{C:attention}Куб (^3){} за каждого", "побежденного {C:attention}Босс Блайнда{}"}},
            j_kranlaxs_grapesoda = {name = "Виноградная Газировка", text = {"При {C:gold}продаже{}, создает", "случайную {C:spectral}Спектральную{} карту", "с {C:dark_edition}Негативным{} изданием"}, unlock = {"Победите на {C:attention}Пурпурной Ставке{}", "используя {C:attention}Космическую Колоду{}"}},
            j_kranlaxs_telescope = {name = "Телескоп", text = {"Если {C:attention}#1#{} повышает уровень, повышает", "эту руку еще {C:attention}1{} доп. раз", "{C:inactive}(Рука меняется в конце раунда){}"}, unlock = {"Победите на", "{C:attention}Красной Ставке{} используя", "колоду {C:attention}Еженедельного Вызова{}"}},
            j_kranlaxs_pandorabox = {name = "Ящик Пандоры", text = {"При победе над {C:attention}Босс Блайндом{},", "создает {C:attention}полезного{} Джокера на основе", "вашей текущей колоды", "{C:inactive}(Нужно место){}"}},
            j_kranlaxs_doppelganger = {name = "Доппельгангер", text = {"Копирует способность случайного", "{C:attention}Джокера{} из всей игры.", "Скопированный Джокер меняется после", "победы над {C:attention}Блайндом{}.", "{C:inactive}(Сейчас: {C:attention}#1#{C:inactive})"}, unlock = {"Победите на", "{C:attention}Золотой Ставке{} используя", "колоду {C:attention}Еженедельного Вызова{}"}},
            j_kranlaxs_thechampion = {name = "Чемпион", text = {"Требование блайнда {C:attention}X#1#{}", "Дает {X:money,C:white} $#2# {} в конце раунда"}, unlock = {"Достигните {C:attention}Анте 16{}"}},
            j_kranlaxs_clerigo = {name = "Священник", text = {"Дает {C:mult}+#1#{} к Множ. за каждую", "карту в вашей полной колоде", "Теряет {C:mult}-#2#{} к Множ. за каждую карту", "с улучшением или печатью", "{C:inactive}(Сейчас {C:mult}+#3#{C:inactive} к Множ.){}"}, unlock = {"Завершите испытание:", "{C:attention}Семейный Рецепт{}"}},
            j_kranlaxs_entrenador = {name = "Тренер", text = {"Дает {X:mult,C:white} X#1# {} к Множ. если вы", "ниже Анте {C:attention}#3#{}", "Иначе дает {X:mult,C:white} X#2# {} к Множ.", "{C:inactive}(Сейчас {X:mult,C:white} X#4# {C:inactive} к Множ.){}"}, unlock = {"Завершите испытание:", "{C:attention}Экономический Кризис{}"}},
            j_kranlaxs_medium = {name = "Медиум", text = {"Дает {C:mult}+#1#{} к Множ. за каждый", "{C:red}проигранный{} забег в вашем профиле", "{C:inactive}(Сейчас {C:mult}+#2#{C:inactive} к Множ.){}"}, unlock = {"Проиграйте {C:attention}1{} забег", "{C:inactive}(Прогресс: {C:attention}#1#{C:inactive} / 1){}"}},
            j_kranlaxs_monk = {name = "Монах", text = {"Получает {X:chips,C:white} X#1# {} к Фишкам если вы выходите", "из магазина не потратив {X:money,C:white} денег {}", "{C:red}Сбрасывается{}, если вы что-то покупаете", "{C:inactive}(Сейчас {X:chips,C:white} X#2# {C:inactive} Фишек){}"}, unlock = {"Завершите испытание:", "{C:attention}Обет Нищеты{}"}},
            j_kranlaxs_knight = {name = "Рыцарь", text = {"После розыгрыша {C:attention}#1#{} {C:attention}Стальных{} карт,", "{C:attention}Отключает{} следующий {C:attention}Босс Блайнд{}", "{C:inactive}(Розыграно карт: #2#/#1#){}"}, unlock = {"Завершите испытание:", "{C:attention}Синдикат Боссов{}"}},
            j_kranlaxs_overpopulation = {name = "Перенаселение", text = {"Дает {C:mult}+#1#{} к Множ. за каждую", "{C:attention}карту с картинкой{} сверх", "лимита в {C:attention}#2#{}", "в вашей колоде", "{C:inactive}(Сейчас {C:mult}+#3#{C:inactive} к Множ.){}"}, unlock = {"Победите на {C:attention}Зеленой Ставке{}", "используя {C:attention}Космическую Колоду{}"}},
            j_kranlaxs_antisocial = {name = "Антисоциальный", text = {"Этот джокер получает {C:mult}+#1#{} к Множ.", "если вы играете ровно {C:attention}1{} карту", "{C:red}Сбрасывается{}, если вы играете больше 1", "{C:inactive}(Сейчас {C:mult}+#2#{C:inactive} к Множ.){}"}, unlock = {"Завершите испытание:", "{C:attention}Полная Фиксация{}"}},
            j_kranlaxs_famous = {name = "Знаменитость", text = {"Дает {C:chips}+#1#{} к Фишкам если", "сыгранная рука - {C:attention}Стрит-Флеш{},", "{C:attention}Флеш-Пятерка{} или {C:attention}Флеш-Фулл-Хаус{}"}},
            j_kranlaxs_influencer = {name = "Инфлюенсер", text = {"Дает {C:mult}+#1#{} к Множ. если", "сыгранная рука - {C:attention}Стрит-Флеш{},", "{C:attention}Флеш-Пятерка{} или {C:attention}Флеш-Фулл-Хаус{}"}},
            j_kranlaxs_potatobag = {name = "Мешок Картошки", text = {"Накапливает набранные Фишки", "При достижении {C:attention}#1#{}, применяет", "{X:mult,C:white} X#2# {} к Множ. к", "следующей руке и опустошается", "{C:inactive}(Накоплено: #3#/#1#){}"}},
            j_kranlaxs_simonsays = {name = "Саймон Говорит", text = {"Этот джокер получает {X:mult,C:white} X#2# {} к Множ.", "при выполнении его просьбы", "Саймон говорит... {C:attention}#3#{}", "{C:inactive}(Сейчас {X:mult,C:white} X#1# {C:inactive} к Множ.){}"}, unlock = {"Завершите испытание:", "{C:attention}Огромный Бобовый Стебель{}"}},
            j_kranlaxs_cheater = {name = "Читер", text = {"Джокеры в магазине", "имеют {C:green}35%{} шанс", "быть замененными на", "{C:attention}Ваучеры{} или {C:attention}Наборы{}"}, unlock = {"Завершите испытание:", "{C:attention}Гачапон{}"}},
            j_kranlaxs_philosopher = {name = "Философ", text = {"Раскрывает следующие {C:attention}5 карт{}", "из вашей колоды", "{C:inactive}(Каждая карта имеет 20%{}", "{C:inactive}шанс быть скрытой){}", "{C:attention}#1#{}"}, unlock = {"Завершите испытание:", "{C:attention}Предчувствия{}"}},
            j_kranlaxs_mandalajoker = {name = "Джокер-Мандала", text = {"Этот Джокер получает {X:mult,C:white} X0.5 {} к Множ.", "за каждую использованную {C:spectral}Спектральную{} карту", "{C:inactive}(Сейчас {X:mult,C:white} X#1# {C:inactive} к Множ.){}"}, unlock = {"Используйте {C:attention}20{} {C:spectral}Спектральных{} карт", "{C:inactive}(Прогресс: {C:attention}#1#{C:inactive} / 20){}"}},
            j_kranlaxs_regift = {name = "Передаренный Джокер", text = {"При {C:gold}продаже{}, создает", "случайного {C:attention}Джокера{}", "Редкость зависит от текущего {C:attention}Блайнда{}"}, unlock = {"Продайте {C:attention}50{} джокеров", "в общем", "{C:inactive}(Прогресс: {C:attention}#1#{C:inactive} / 50){}"}},
            j_kranlaxs_pyromaniac = {name = "Пироман", text = {"После розыгрыша руки, {C:red}уничтожает{}", "все карты {C:attention}с цифрами{} в вашей руке", "{C:inactive}(Золотые, Стеклянные и Стальные в безопасности){}"}, unlock = {"Уничтожьте {C:attention}100{} карт", "которые не являются картинками", "{C:inactive}(Прогресс: {C:attention}#1#{C:inactive} / 100){}"}},
            j_kranlaxs_neverendinggambling = {name = "Бесконечный Азарт", text = {"Вы теряете {X:money,C:white} $1 {} за каждое действие", "{C:inactive}(Только если у вас есть {X:money,C:white} $5 {} или больше){}", "Крутите 3 числа. При совпадении - приз!", "Если совпадут 2, вы получите {X:money,C:white} $1 {} как утешение", "{C:inactive}(Текущая прокрутка: #1# - #2# - #3#){}"}, unlock = {"Потерпите неудачу в {C:attention}30{} вероятностях", "джокеров или расходников", "{C:inactive}(Прогресс: {C:attention}#1#{C:inactive} / 30){}"}},
            j_kranlaxs_solarsystem = {name = "Солнечная Система", text = {"В {C:attention}конце раунда{} создает", "карту {C:planet}Планеты{} в фиксированной последовательности", "{C:inactive}(Следующая планета: {C:planet}#1#{C:inactive}){}"}, unlock = {"Используйте все {C:attention}12{} стандартных", "карт {C:planet}Планет{} хотя бы один раз", "за один забег", "{C:inactive}(Прогресс: {C:attention}#1#{C:inactive} / 12){}"}},
            j_kranlaxs_deranged = {name = "Безумный", text = {"Дает {C:mult}+#1#{} к Множ. или {C:chips}+#2#{} к Фишкам", "Эффект меняется каждый раз", "когда вы играете руку"}, unlock = {"Завершите испытание:", "{C:attention}Кризис Личности{}"}},
            j_kranlaxs_deranged_mult = {name = "Безумный", text = {"Дает {C:mult}+#1#{} к Множ.", "Эффект меняется каждый раз", "когда вы играете руку"}},
            j_kranlaxs_deranged_chips = {name = "Безумный", text = {"Дает {C:chips}+#2#{} к Фишкам", "Эффект меняется каждый раз", "когда вы играете руку"}},
            j_kranlaxs_tmtrainer = {
                name = "TMTRAINER", 
                text = {
                    "{C:dark_edition}#1#{}",
                    "{C:attention}#2#{}",
                    "{C:red}#3#{}",
                    "{C:chips}#4#{}"
                },
                unlock = {
                    "Завершите испытание:",
                    "{C:attention}Кризис Личности{}"
                }
            },
            j_kranlaxs_bingocard = {name = "Бинго-Карта", text = {"Дает {X:mult,C:white} X0.25 {} к Множ.", "за каждую заполненную линию", "{C:inactive}(Всего: {X:mult,C:white} X#2# {C:inactive} к Множ.){}", "{C:attention}#3#{}", "{C:attention}#4#{}", "{C:attention}#5#{}", "{C:attention}#6#{}", "{C:attention}#7#{}"}, unlock = {"Завершите испытание:", "{C:attention}Полная Анонимность{}"}}
        },

        Back = {
            b_kranlaxs_week_challenge = {name = "Еженедельный Вызов", text = {"Начинается с Джокером {C:attention}Еженедельный Вызов{}", "{C:red}Проходимо{} каждые {C:attention}выходные{}"}, unlock = {"Зайдите в игру в", "{C:attention}Субботу{} или {C:attention}Воскресенье{}"}},
            b_kranlaxs_chaos_deck = {name = "Колода Хаоса", text = {"Наслаждайтесь хаосом"}, unlock = {"Разблокируйте {C:legendary,E:1}ВСЁ{} в", "вашей коллекции"}},
            b_kranlaxs_dungeon_deck = {name = "Колода Подземелья", text = {"После победы над {C:attention}Босс Блайндом{},", "выберите один из 3 {C:attention}вариантов{}", "с {C:green}плюсами{} и {C:red}минусами{}"}, unlock = {"Победите на {C:attention}Зеленой Ставке{}", "или выше, используя", "колоду {C:attention}Еженедельного Вызова{}"}},
            b_kranlaxs_space_deck = {name = "Космическая Колода", text = {"{C:attention}0{} слотов джокеров, {C:attention}5{} слотов расходников", "Магазин продает только {C:attention}Кварц{}", "{C:attention}+1{} к размеру магазина, Блайнды на {C:attention}7.5%{} меньше", "Победный Анте: {C:attention}10{}"}, unlock = {"Победите на {C:attention}Зеленой Ставке{}", "с {C:attention}Магической Колодой{},", "{C:attention}Колодой Туманности{} и {C:attention}Колодой Зодиака{}"}},
            b_kranlaxs_bugged_deck = {name = "Забагованная Колода", text = {"!?"}, unlock = {"Получите {C:attention}TMTRAINER{}", "в первый раз"}}
        },

        Stake = {
            stake_kranlaxs_magenta = {name = "Пурпурная Ставка", text = {"Карты в магазине могут", "иметь стикер {C:attention}Закреплено{}"}},
            stake_kranlaxs_brown = {name = "Коричневая Ставка", colour = "Коричневая", text = {"{C:attention}-1{} слот", "{C:attention}Бустерных Наборов{} в магазине"}},
            stake_kranlaxs_turquoise = {name = "Бирюзовая Ставка", colour = "Бирюзовая", text = {"Блайнды имеют {C:attention}50%{} шанс", "быть {C:red}непропускаемыми{}"}},
            stake_kranlaxs_deviled = {name = "Дьявольская Ставка", colour = "Дьявольская", text = {"{C:attention}-1{} слот {C:attention}Джокера{}"}},
            stake_kranlaxs_glass = {name = "Стеклянная Ставка", colour = "Стеклянная", text = {"Требуемый счет растет", "еще быстрее с каждым {C:attention}Анте{}"}},
            stake_kranlaxs_platinum = {name = "Платиновая Ставка", colour = "Платиновая", text = {"Нужно пройти {C:attention}Анте 10{}", "чтобы выиграть забег"}}
        },

        UNOCards = {
            c_kranlaxs_skip = {name = "Пропуск", text = {"{C:attention}Мгновенно{} получите требование Блайнда", "Не работает на {C:attention}Босс Блайндах{}"}},
            c_kranlaxs_stacking = {name = "Стек", text = {"Добавляет {C:attention}Розовую Печать{} к", "{C:attention}1{} выбранной карте в руке"}},
            c_kranlaxs_draw2 = {name = "Взять 2", text = {"При использовании, {C:attention}вытягивает 2 доп. карты{}", "в руку, вы теряете {C:blue}1{} руку"}},
            c_kranlaxs_draw4 = {name = "Взять 4", text = {"При использовании, {C:attention}вытягивает 4 доп. карты{}", "в руку, вы теряете {C:blue}1{} руку"}},
            c_kranlaxs_reverse = {name = "Реверс", text = {"Возвращает {C:attention}все карты{} из вашей", "руки в колоду и {C:attention}перетасовывает{} их"}},
            c_kranlaxs_wildcard = {name = "Дикая Карта", text = {"{C:attention}Превращает{} каждую карту в", "вашей руке в {C:attention}случайную масть{}", "{C:attention}независимо{}"}},
            c_kranlaxs_replay = {name = "Повтор", text = {"Возвращает карты из", "последней сыгранной руки в вашу руку", "{C:inactive}(Сбрасывается после использования", "{C:inactive}или в конце раунда)"}},
            c_kranlaxs_discardall = {name = "Сбросить Всё", text = {"Требуется {C:attention}1{} выбранная карта.", "Сбрасывает {C:red}все{} карты", "из вашей {C:attention}руки{} и {C:attention}колоды{}, которые", "имеют ту же масть"}},
            c_kranlaxs_shield = {name = "Щит", text = {"Пассивно защищает от смерти, или", "можно продать, чтобы отключить {C:attention}Босс Блайнд{}"}},
            c_kranlaxs_misery = {name = "Страдание", text = {"Выберите {C:attention}Масть{}.", "Безостановочно вытягивает карты", "из вашей колоды, пока", "вы не получите карту этой масти"}},
            c_kranlaxs_gift = {name = "Подарок", text = {"Дает {C:attention}1{} из следующих", "случайных призов:", "• {C:attention}Джокер{} с Изданием", "• Негативный {C:attention}Расходник{}", "• {C:attention}Карта{} с Улучшением, Печатью и Изданием"}},
            c_kranlaxs_customdraw = {name = "Пользовательский Взятие", text = {"Вытягивает столько же карт", "сколько вы сбросили", "{C:inactive}(Сейчас: {C:attention}#1#{C:inactive} карт){}"}}
        },

        InverseTarot = {
            c_kranlaxs_thefool = {name = "Шут?", text = {"Создает случайную {C:spectral}Спектральную{} карту", "{C:attention}Понижает уровень{} случайной покерной руки"}},
            c_kranlaxs_themagician = {name = "Маг?", text = {"Создает {C:attention}2{} случайные карты {C:attention}Удачи{}"}},
            c_kranlaxs_thehighpriestess = {name = "Жрица?", text = {"Создает {C:spectral}Черную Дыру{}", "Ваши {X:money,C:white} деньги {} {C:attention}уменьшаются{} на 20%"}},
            c_kranlaxs_theempress = {name = "Императрица?", text = {"Добавляет постоянные {C:red}+8{} к Множ.", "к не более чем {C:attention}2{} выбранным картам"}},
            c_kranlaxs_theemperor = {name = "Император?", text = {"Создает {C:attention}2{} случайных {C:attention}Тега{}"}},
            c_kranlaxs_thehierophant = {name = "Иерофант?", text = {"Добавляет постоянные {C:blue}+40{} к Фишкам", "к не более чем {C:attention}2{} выбранным картам"}},
            c_kranlaxs_thelovers = {name = "Влюбленные?", text = {"Дает {C:attention}+1{} к размеру руки, если", "в вашей колоде есть {C:attention}Универсальная Карта{}"}},
            c_kranlaxs_thechariot = {name = "Колесница?", text = {"Создает {C:attention}1{} случайную {C:attention}Стальную{} карту", "с {C:attention}Красной{} Печатью"}},
            c_kranlaxs_justice = {name = "Справедливость?", text = {"Добавляет постоянный {X:red,C:white} X2 {} к Множ.", "к {C:attention}1{} выбранной карте", "Шанс {C:green}#1# из #2#{} {C:attention}уничтожить{} эту карту"}},
            c_kranlaxs_thehermit = {name = "Отшельник?", text = {"{C:attention}Устанавливает{} ваши {X:money,C:white} деньги {} на {X:money,C:white} $25 {}, если", "у вас {C:attention}меньше{} {X:money,C:white} $25 {}"}},
            c_kranlaxs_thewheeloffortune = {name = "Колесо Фортуны?", text = {"Шанс {C:green}#1# из #2#{} создать {C:attention}копию{}", "случайного Джокера с {C:dark_edition}Негативным{} изданием"}},
            c_kranlaxs_strenght = {name = "Сила?", text = {"{C:attention}Снижает{} {C:attention}ранг{} до", "{C:attention}2{} выбранных карт на {C:attention}1{}"}},
            c_kranlaxs_thehangedman = {name = "Повешенный?", text = {"Полностью {C:attention}рандомизирует{} до", "{C:attention}2{} выбранных карт в руке"}},
            c_kranlaxs_death = {name = "Смерть?", text = {"Создает {C:attention}Негативную копию{} случайного Джокера", "Случайный Джокер получает {C:attention}Скоропортящийся{} стикер"}},
            c_kranlaxs_temperance = {name = "Умеренность?", text = {"Продает {C:attention}ВСЕХ{} Джокеров (даже Вечных)", "за {C:money}тройную{} цену продажи", "{C:inactive}(Не продает Закрепленных Джокеров){}"}},
            c_kranlaxs_thedevil = {name = "Дьявол?", text = {"Добавляет постоянные {X:money,C:white} $2 {}", "к не более чем {C:attention}2{} выбранным картам"}},
            c_kranlaxs_thetower = {name = "Башня?", text = {"{C:attention}Удаляет{} все улучшения, печати,", "издания и бонусы с карт в руке", "Дает {X:money,C:white} $1 {} за каждую удаленную модификацию"}},
            c_kranlaxs_thestars = {name = "Звезды?", text = {"Добавляет {C:attention}Белую Печать{} к", "не более чем {C:attention}2{} выбранным картам"}},
            c_kranlaxs_themoon = {name = "Луна?", text = {"Добавляет {C:attention}Серую Печать{} к", "не более чем {C:attention}2{} выбранным картам"}},
            c_kranlaxs_thesun = {name = "Солнце?", text = {"Добавляет {C:attention}Оранжевую Печать{} к", "не более чем {C:attention}2{} выбранным картам"}},
            c_kranlaxs_judgement = {name = "Суд?", text = {"{C:attention}Активирует{} случайный {C:attention}Ваучер{}", "{C:red}-1{} к размеру руки"}},
            c_kranlaxs_theworld = {name = "Мир?", text = {"Добавляет {C:attention}Коричневую Печать{} к", "не более чем {C:attention}2{} выбранным картам"}}
        },

        Voucher = {
            v_kranlaxs_more_stock = {name = "Больше Товаров", text = {"Магазин имеет {C:attention}1{} доп.", "слот {C:attention}Набора{}"}},
            v_kranlaxs_even_more_stock = {name = "Ещё Больше Товаров", text = {"Магазин имеет {C:attention}1{} доп.", "слот {C:attention}Ваучера{}"}},
            v_kranlaxs_shiny_appearance = {name = "Редкое Появление", text = {"Легендарные карты и редкие расходники", "теперь могут появляться в магазине"}},
            v_kranlaxs_stickerfever = {name = "Теговая Лихорадка", text = {"Всякий раз, когда вы получаете", "{C:attention}Тег{}, вы получаете", "{C:attention}1{} доп. копию"}},
            v_kranlaxs_stickeralbum = {name = "Альбом Тегов", text = {"Всякий раз, когда вы получаете", "{C:attention}Тег{}, вы получаете", "еще {C:attention}1{} доп. копию"}},
            v_kranlaxs_hotfix = {name = "Хотфикс", text = {"{C:attention}Обновление{} магазина", "также обновляет {C:attention}Ваучеры{}", "и {C:attention}Наборы{}"}},
            v_kranlaxs_version2 = {name = "Версия 2.0", text = {"Пропуск блайндов дает вам {X:money,C:white} деньги {}", "награды за этот блайнд.", "Требование блайнда {C:attention}-15%{}"}},
            v_kranlaxs_common_shinys = {name = "Легендарное Зрелище", text = {"Легендарные карты и редкие расходники", "будут появляться чаще"}},
            v_kranlaxs_blessing = {name = "Благословение", text = {"Вы начинаете с {C:attention}10%{}", "требований по фишкам", "завершенными на каждом блайнде"}},
            v_kranlaxs_protection = {name = "Божественная Защита", text = {"Защищает вас от {C:attention}Конца Игры{}.", "После использования этот ваучер уничтожается", "и может снова появиться в магазине,", "но за {X:money,C:white} двойную {} цену"}}
        },

        Quartz = {
            c_kranlaxs_blackquartz = {name = "Обсидиан", text = {"Изменяет некоторые правила", "по вашему выбору"}, unlock = {"Победите на {C:attention}Коричневой Ставке{}", "используя {C:attention}Магическую Колоду{}"}},
            c_kranlaxs_whitequartz = {name = "Жемчуг", text = {"Создает последний", "использованный расходник", "{C:inactive}(Последняя карта: {C:attention}#1#{C:inactive}){}"}, unlock = {"Победите на {C:attention}Коричневой Ставке{}", "используя {C:attention}Призрачную Колоду{}"}},
            c_kranlaxs_pinkquartz = {name = "Розовый Кварц", text = {"Добавляет {C:dark_edition}Полихром{} к {C:attention}Джокеру{}", "или выбранной {C:attention}карте{}"}, unlock = {"Победите на {C:attention}Пурпурной Ставке{}", "или выше, используя {C:attention}Колоду Подземелья{}"}},
            c_kranlaxs_bluequartz = {name = "Сапфир", text = {"Добавляет {C:chips}Фольгу{} к", "выбранному {C:attention}Джокеру{} или {C:attention}карте{}"}, unlock = {"Победите на {C:attention}Платиновой Ставке{}", "используя {C:attention}Плазменную Колоду{}"}},
            c_kranlaxs_lilacquartz = {name = "Кунцит", text = {"Добавляет {C:mult}Голограмму{} к", "выбранному {C:attention}Джокеру{} или {C:attention}карте{}"}, unlock = {"Победите на {C:attention}Коричневой Ставке{}", "используя {C:attention}Колоду Туманности{}"}},
            c_kranlaxs_grayquartz = {name = "Гематит", text = {"Добавляет {C:dark_edition}Негатив{} к", "выбранному {C:attention}Джокеру{} или {C:attention}расходнику{}"}, unlock = {"Победите на {C:attention}Бирюзовой Ставке{}", "используя {C:attention}Раскрашенную Колоду{}"}},
            c_kranlaxs_transparentquartz = {name = "Алмаз", text = {"{C:attention}Удаляет{} все наклейки или издания", "с {C:attention}Джокера{}, или печати и", "издания с выбранной {C:attention}карты{}"}, unlock = {"Победите на {C:attention}Платиновой Ставке{}", "используя {C:attention}Колоду Подземелья{}"}},
            c_kranlaxs_redquartz = {name = "Рубин", text = {"Пока {C:attention}в инвентаре{},", "дает {X:mult,C:white} X2 {} к Множ.", "{C:inactive}(Пассивно){}"}, unlock = {"Победите на {C:attention}Пурпурной Ставке{}", "или выше, используя {C:attention}Красную Колоду{}"}},
            c_kranlaxs_celestequartz = {name = "Ларимар", text = {"Пока {C:attention}в инвентаре{},", "дает {X:chips,C:white} X1.5 {} к Фишкам", "{C:inactive}(Пассивно){}"}, unlock = {"Победите на {C:attention}Бирюзовой Ставке{}", "используя {C:attention}Шахматную Колоду{}"}},
            c_kranlaxs_yellowquartz = {name = "Топаз", text = {"Создает указанного {C:attention}Джокера{}.", "Джокер меняется случайно", "после каждого {C:attention}раунда{}", "{C:inactive}(Цель: {C:attention}#1#{C:inactive}){}"}, unlock = {"Победите на {C:attention}Синей Ставке{}", "используя {C:attention}Колоду Подземелья{}"}},
            c_kranlaxs_greenquartz = {name = "Изумруд", text = {"Пока {C:attention}в инвентаре{}, создает", "{C:attention}Тег{} после победы над {C:attention}Блайндом{}", "Уничтожается после создания {C:attention}#2#{} тегов", "{C:inactive}(Сейчас: {C:attention}#1#{C:inactive}){}", "{C:inactive}(Пассивно){}"}, unlock = {"Победите на {C:attention}Пурпурной Ставке{}", "или выше, используя {C:attention}Зеленую Колоду{}"}},
            c_kranlaxs_brownquartz = {name = "Тигровый Глаз", text = {"Создает указанную {C:attention}Карту{}.", "Карта меняется случайно после", "{C:green}Обновления{} магазина", "{C:inactive}(Цель: {C:attention}#1#{C:inactive}){}"}, unlock = {"Победите на {C:attention}Бирюзовой Ставке{}", "используя {C:attention}Анаглифную Колоду{}"}},
            c_kranlaxs_turquoisequartz = {name = "Бирюза", text = {"Пока {C:attention}в инвентаре{}, {C:attention}отключает{}", "всех джокеров кроме первого", "Активирует этого джокера еще {C:attention}2{} раза", "{C:inactive}(Пассивно){}"}, unlock = {"Победите на {C:attention}Бирюзовой Ставке{}", "используя {C:attention}Колоду Зодиака{}"}},
            c_kranlaxs_orangequartz = {name = "Цитрин", text = {"Добавляет {C:green}Мятную Печать{} к {C:attention}карте{}", "или {C:green}Наклейку Клевера{} к", "выбранному {C:attention}Джокеру{}"}, unlock = {"Победите на {C:attention}Пурпурной Ставке{}", "или выше, используя {C:attention}Желтую Колоду{}"}},
            c_kranlaxs_lapislazuli = {name = "Лазурит", text = {"Пока {C:attention}в инвентаре{}, добавляет", "{C:chips}+#1#{} к Фишкам первой сыгранной карте", "Эффект снижается на {C:chips}-#2#{} за использование.", "{C:inactive}(Неактивен при достижении 0){}", "{C:inactive}(Пассивно){}"}, unlock = {"Победите на {C:attention}Пурпурной Ставке{}", "или выше, используя {C:attention}Синюю Колоду{}"}},
            c_kranlaxs_cinnabar = {name = "Киноварь", text = {"Пока {C:attention}в инвентаре{}, добавляет", "{C:mult}+#1#{} к Множ. первой сыгранной карте", "Эффект снижается на {C:mult}-#2#{} за использование.", "{C:inactive}(Неактивен при достижении 0){}", "{C:inactive}(Пассивно){}"}, unlock = {"Победите на {C:attention}Коричневой Ставке{}", "используя {C:attention}Заброшенную Колоду{}"}},
            c_kranlaxs_graphite = {name = "Графит", text = {"Пока {C:attention}в инвентаре{}, шанс {C:green}#1# из #2#{}", "создать копию в вашей руке", "всех сыгранных карт.", "Шанс падает при срабатывании.", "{C:inactive}(Неактивен при достижении 0){}", "{C:inactive}(Пассивно){}"}, unlock = {"Победите на {C:attention}Пурпурной Ставке{}", "или выше, используя {C:attention}Черную Колоду{}"}},
            c_kranlaxs_uranium = {name = "Уран", text = {"Пока {C:attention}в инвентаре{}, применяет 1 случайный", "эффект за раунд. Он может быть", "очень хорошим или разрушительным.", "{C:dark_edition}Текущий статус:{}", "{C:red,E:2}#1#{}", "{C:inactive}(Осмелишься взять его?){}", "{C:inactive}(Пассивно){}"}, unlock = {"Победите на {C:attention}Платиновой Ставке{}", "используя {C:attention}Ошибочную Колоду{}"}}
        },

        Tag = {
            tag_kranlaxs_mega_invtarot = {name = "Мега-Обратный Тег", text = {"Мгновенно дает бесплатный", "{C:attention}Мега-Набор Обратное Таро{}"}},
            tag_kranlaxs_mega_uno = {name = "Джамбо UNO Тег", text = {"Мгновенно дает бесплатный", "{C:attention}Набор UNO Джамбо{}"}},
            tag_kranlaxs_mega_invtarot_store = {name = "Сохраненный Мега-Обратный Тег", text = {"Мгновенно дает бесплатный", "{C:attention}Сохраненное Мега-Обратное Таро{}"}},
            tag_kranlaxs_quartz_tag = {name = "Тег Кварца", text = {"Создает случайный {C:attention}Кварц{}", "{C:inactive}(Нужно место){}"}},
            tag_kranlaxs_sticker_remover = {name = "Тег Очищения", text = {"Удаляет {C:attention}Вечный{},", "{C:attention}Скоропортящийся{} или {C:attention}Арендный{} стикер с", "со случайного {C:attention}Джокера{}", "{C:inactive}(Дает {X:money,C:white} $5 {C:inactive} если стикеров нет){}"}},
            tag_kranlaxs_legendary = {name = "Легендарный Тег", text = {"В магазине есть бесплатный", "{C:legendary}Легендарный Джокер{}"}}
        },


        Other = {
            kranlaxs_magenta_sticker = {name = "Пурпурный Стикер", text = {"Использовали этого Джокера,", "чтобы победить на {C:attention}Пурпурной Ставке{}"}},
            kranlaxs_brown_sticker = {name = "Коричневый Стикер", text = {"Использовали этого Джокера,", "чтобы победить на {C:attention}Коричневой Ставке{}"}},
            kranlaxs_turquoise_sticker = {name = "Бирюзовый Стикер", text = {"Использовали этого Джокера,", "чтобы победить на {C:attention}Бирюзовой Ставке{}"}},
            kranlaxs_platinum_sticker = {name = "Платиновый Стикер", text = {"Использовали этого Джокера,", "чтобы победить на {C:attention}Платиновой Ставке{}"}},
            kranlaxs_orangeseal_seal = {name = "Оранжевая Печать", text = {"Если приносит очки в руке: {C:attention}#1#{},", "создает 1 {C:attention}#2#{}", "{C:inactive}Изменяется после использования.{}", "{C:inactive}(Нужно место){}"}},
            kranlaxs_deviled_sticker = {name = "Дьявольский Стикер", text = {"Использовали этого Джокера,", "чтобы победить на {C:attention}Дьявольской Ставке{}"}},
            kranlaxs_glass_sticker = {name = "Стеклянный Стикер", text = {"Использовали этого Джокера,", "чтобы победить на {C:attention}Стеклянной Ставке{}"}},
            kranlaxs_pinkseal_seal = {name = "Розовая Печать", text = {"Применяет {X:dark_edition,C:white}^1.75{} к Множ.", "при {C:attention}начислении очков{}"}},
            kranlaxs_whiteseal_seal = {name = "Белая Печать", text = {"{C:attention}Всегда начисляет очки{}, неуязвима", "к {C:red}отключению{}, {C:red}уничтожению{}", "или {C:attention}перевороту{}"}},
            kranlaxs_brownseal_seal = {name = "Коричневая Печать", text = {"Шанс {C:green}#1# из #2#{}", "{C:attention}дублировать{} эту карту,", "пока она в руке"}},
            kranlaxs_grayseal_seal = {name = "Серая Печать", text = {"При {C:attention}начислении очков{}, {C:attention}случайно{} меняет", "{C:enhanced}Улучшение{} этой карты"}},
            kranlaxs_mintseal_seal = {name = "Мятная Печать", text = {"Удваивает все {C:attention}указанные вероятности{}", "на этой карте"}},
            p_kranlaxs_uno_store_3 = {name = "Набор UNO", text = {"Выберите {C:attention}1{} из до", "{C:attention}3{} карт {C:blue}UNO{}"}},
            p_kranlaxs_uno_store_5 = {name = "Набор UNO Джамбо", text = {"Выберите {C:attention}1{} из до", "{C:attention}5{} карт {C:blue}UNO{}"}},
            p_kranlaxs_invtarot_instant_3_1 = {name = "Набор Обратное Таро", text = {"Выберите {C:attention}1{} из до", "{C:attention}3{} карт {C:purple}Обратного Таро{}"}},
            p_kranlaxs_invtarot_instant_5_1 = {name = "Набор Обратное Таро Джамбо", text = {"Выберите {C:attention}1{} из до", "{C:attention}5{} карт {C:purple}Обратного Таро{}"}},
            p_kranlaxs_invtarot_instant_5_2 = {name = "Мега-Набор Обратное Таро", text = {"Выберите {C:attention}2{} из до", "{C:attention}5{} карт {C:purple}Обратного Таро{}"}},
            p_kranlaxs_invtarot_store_3_1 = {name = "Сохраненное Обратное Таро", text = {"Выберите {C:attention}1{} из до", "{C:attention}3{} карт {C:purple}Обратного Таро{}"}},
            p_kranlaxs_invtarot_store_5_1 = {name = "Сохраненное Обратное Таро Джамбо", text = {"Выберите {C:attention}1{} из до", "{C:attention}5{} карт {C:purple}Обратного Таро{}"}},
            p_kranlaxs_invtarot_store_5_2 = {name = "Сохраненное Мега-Обратное Таро", text = {"Выберите {C:attention}2{} из до", "{C:attention}5{} карт {C:purple}Обратного Таро{}"}}
        },

        Booster = {
            p_kranlaxs_uno_store_3 = {name = "Набор UNO", text = {"Выберите {C:attention}1{} из до", "{C:attention}3{} карт {C:blue}UNO{}"}},
            p_kranlaxs_uno_store_5 = {name = "Набор UNO Джамбо", text = {"Выберите {C:attention}1{} из до", "{C:attention}5{} карт {C:blue}UNO{}"}},
            p_kranlaxs_invtarot_instant_3_1 = {name = "Набор Обратное Таро", text = {"Выберите {C:attention}1{} из до", "{C:attention}3{} карт {C:purple}Обратного Таро{}"}},
            p_kranlaxs_invtarot_instant_5_1 = {name = "Набор Обратное Таро Джамбо", text = {"Выберите {C:attention}1{} из до", "{C:attention}5{} карт {C:purple}Обратного Таро{}"}},
            p_kranlaxs_invtarot_instant_5_2 = {name = "Мега-Набор Обратное Таро", text = {"Выберите {C:attention}2{} из до", "{C:attention}5{} карт {C:purple}Обратного Таро{}"}},
            p_kranlaxs_invtarot_store_3_1 = {name = "Сохраненное Обратное Таро", text = {"Выберите {C:attention}1{} из до", "{C:attention}3{} карт {C:purple}Обратного Таро{}"}},
            p_kranlaxs_invtarot_store_5_1 = {name = "Сохраненное Обратное Таро Джамбо", text = {"Выберите {C:attention}1{} из до", "{C:attention}5{} карт {C:purple}Обратного Таро{}"}},
            p_kranlaxs_invtarot_store_5_2 = {name = "Сохраненное Мега-Обратное Таро", text = {"Выберите {C:attention}2{} из до", "{C:attention}5{} карт {C:purple}Обратного Таро{}"}}
        }
    },
    
    misc = {
        

        labels = {
            kranlaxs_magenta_sticker = "Пурпурный Стикер",
            kranlaxs_brown_sticker = "Коричневый Стикер",
            kranlaxs_turquoise_sticker = "Бирюзовый Стикер",
            kranlaxs_platinum_sticker = "Платиновый Стикер",
            kranlaxs_orangeseal_seal = "Оранжевая Печать", 
            kranlaxs_pinkseal_seal = "Розовая Печать", 
            kranlaxs_whiteseal_seal = "Белая Печать", 
            kranlaxs_brownseal_seal = "Коричневая Печать", 
            kranlaxs_grayseal_seal = "Серая Печать", 
            kranlaxs_mintseal_seal = "Мятная Печать", 
            kranlaxs_deviled_sticker = "Дьявольский Стикер",
            kranlaxs_glass_sticker = "Стеклянный Стикер",
            clover = "Наклейка Клевера",
            p_kranlaxs_uno_store_3 = "Набор UNO",
            p_kranlaxs_uno_store_5 = "Набор UNO Джамбо",
            p_kranlaxs_invtarot_instant_3_1 = "Набор Обратное Таро",
            p_kranlaxs_invtarot_instant_5_1 = "Набор Обратное Таро Джамбо",
            p_kranlaxs_invtarot_instant_5_2 = "Мега-Набор Обратное Таро",
            p_kranlaxs_invtarot_store_3_1 = "Сохраненное Обратное Таро",
            p_kranlaxs_invtarot_store_5_1 = "Сохраненное Обратное Таро Джамбо",
            p_kranlaxs_invtarot_store_5_2 = "Сохраненное Мега-Обратное Таро",
            kranlaxs_wave = "Водный"
        },

        v_text = {
            ch_c_kran_fijado_1 = {"Все джокеры имеют стикер {C:attention}Закреплено{}"},
            ch_c_kran_abuela_1 = {"{C:attention}Начисляющие очки{} джокеры {C:red}запрещены{}"},
            ch_c_kran_crisis_1 = {"Магазин на {C:attention}20% дороже{}"},
            ch_c_kran_crisis_2 = {"Базовая награда блайнда {C:red}снижена{} на {X:money,C:white} $2 {}"},
            ch_c_kran_crisis_3 = {"Колода состоит только из {C:attention}52 Тузов{}"},
            ch_c_kran_doppel_1 = {"Все джокеры {C:red}запрещены{} в магазине"},
            ch_c_kran_anonimo_1 = {"Карты в руке и джокеры лежат {C:attention}лицом вниз{}"},
            ch_c_kran_jefes_1 = {"Малый и Большой Блайнды становятся {C:attention}Босс Блайндами{}"},
            ch_c_kran_premon_1 = {"Все карты в вашей руке лежат {C:attention}лицом вниз{}"},
            ch_c_kran_tallo_1 = {"Остальные {C:attention}джокеры{} и {C:attention}наборы{} {C:red}запрещены{}"},
            ch_c_gacha_rule_1 = {"Никакие {C:attention}отдельные карты{} не появляются в магазине"},
            ch_c_kran_pobreza_1 = {"Шанс {C:attention}50%{} что {C:common}Обычный{} джокер станет {C:legendary}Легендарным{}"},
            ch_c_kran_pobreza_2 = {"Если ваш джокер {C:attention}Монах{} разочаруется, {C:red}вы проиграете забег{}"}
        }
    }
}