return {
    descriptions = {
        Joker = {
            j_kranlaxs_tagger = {name = "标记器", text = {"每获得一个{C:attention}标签{}，", "获得{C:red}+#1#{}倍率", "{C:inactive}(当前{C:red}+#2#{C:inactive}倍率){}"}, unlock = {"在单次游戏中", "购买{C:attention}2{}张空白优惠券"}},
            j_kranlaxs_Cashback = {name = "现金返还", text = {"购买卡牌时，有{C:green}#1#/#2#{}的几率", "获得{X:money,C:white} $3 {}"}, unlock = {"使用{C:attention}太空卡组{}", "在{C:attention}红色底注{}下赢得一次游戏"}},
            j_kranlaxs_underratedjoker = {name = "被低估的小丑", text = {"如果打出的牌型{C:attention}不是{}", "你最常打出的扑克牌型，", "此小丑获得{X:chips,C:white} X0.2 {}筹码", "{C:inactive}(如果是则重置){}", "{C:inactive}(当前{X:chips,C:white} X#1# {C:inactive}筹码){}"}, unlock = {"使用{C:attention}太空卡组{}", "在{C:attention}蓝色底注{}下赢得一次游戏"}},
            j_kranlaxs_facelessaccountant = {name = "无面会计师", text = {"每有一张计分的{C:attention}#2#{}，", "此小丑获得{X:blue,C:white} X0.1 {}筹码", "{C:inactive}(当前{X:blue,C:white} X#1# {C:inactive}筹码){}"}, unlock = {"在不打出人头牌的情况下赢得游戏，", "且卡组中至少包含{C:attention}1{}张人头牌"}},
            j_kranlaxs_thefixer = {name = "调停者", text = {"在{C:purple}盲注{}期间出售{C:attention}小丑牌{}", "会降低分数要求", "{C:inactive}(常见：-10%，罕见：-30%){}", "{C:inactive}(稀有：-60%，传奇：-95%){}"}, unlock = {"出售每种稀有度的", "小丑牌至少{C:attention}2{}张"}},
            j_kranlaxs_mysteriousgeode = {name = "神秘晶洞", text = {"每张计分的{C:attention}万能牌{}", "提供一个{C:attention}随机{}效果"}, unlock = {"打出包含{C:attention}5{}张", "万能牌的牌型"}},
            j_kranlaxs_benchwarmer = {name = "替补队员", text = {"提供手中点数最高的卡牌", "的{C:blue}筹码{}值的{C:attention}4倍{}"}},
            j_kranlaxs_entropy2 = {name = "漩涡", text = {"卡组中每有一张{C:attention}低于52{}的卡牌", "获得{X:dark_edition,C:white} ^1 {}倍率和{X:dark_edition,C:white} ^1 {}筹码", "{C:inactive}(当前{X:dark_edition,C:white} ^#1# {C:inactive}倍率和{X:dark_edition,C:white} ^#1# {C:inactive}筹码){}"}},
            j_kranlaxs_greedyleprachaun = {name = "贪婪的小妖精", text = {"在回合的第一次{C:red}弃牌{}时，", "额外抽取{C:attention}3张牌{}"}, unlock = {"连续{C:attention}3{}次", "准确弃掉{C:attention}1{}张牌"}},
            j_kranlaxs_charismaticbard = {name = "魅力吟游诗人", text = {"{C:attention}-1{}手牌上限", "每次打出{C:attention}最常打出的牌型{}时，", "降低{C:purple}盲注{}要求{C:attention}2%{}", "{C:inactive}(最高90%){}", "打出其他牌型时重置", "{C:inactive}(当前降低{C:attention}-#1#%{C:inactive}盲注){}"}},
            j_kranlaxs_russianroulette = {name = "俄罗斯轮盘", text = {"选择盲注时，", "有{C:green}#1#/#2#{}的几率{C:red}输掉游戏{}", "如果你活下来，获得", "{X:mult,C:white} X3 {}倍率和{X:chips,C:white} X3 {}筹码", "{C:inactive}(当前{X:mult,C:white} X#3# {C:inactive}倍率和{X:chips,C:white} X#3# {C:inactive}筹码){}"}, unlock = {"使用{C:attention}太空卡组{}", "在{C:attention}黑色底注{}下赢得一次游戏"}},
            j_kranlaxs_fidelitycard = {name = "战斗通行证", text = {"购买{C:attention}6{}张卡牌后，第{C:attention}七张{}", "购买的卡牌提供等同于你所有", "小丑牌{C:attention}售价{}的{X:money,C:white}金钱{}", "{C:inactive}(当前{C:attention}#1#/6{C:inactive}张卡牌){}", "{C:inactive}(总售价：{X:money,C:white} $#2# {C:inactive}){}"}},
            j_kranlaxs_devioussheep = {name = "贪吃羊", text = {"选择{C:attention}盲注{}时，{C:red}吞噬{}一个", "随机小丑牌并获得{X:mult,C:white} X0.4 {}倍率", "如果没有其他小丑牌则{C:hearts}游戏结束{}", "{C:inactive}(优先选择特定目标以获得更多倍率！){}", "{C:inactive}(当前{X:mult,C:white} X#1# {C:inactive}倍率){}"}},
            j_kranlaxs_lifeassurance = {name = "人寿保险", text = {"如果你至少有{X:money,C:white} $#1# {}", "则防止一次游戏结束", "{C:inactive}(每次使用后价格翻倍){}"}, unlock = {"在{C:attention}底注8{}之前", "带着{X:money,C:white} $100 {}或以上", "输掉一次游戏"}},
            j_kranlaxs_sundaycheckpoint = {name = "检查点", text = {"如果在{C:attention}工作日{}选择盲注", "则{C:red}游戏结束{}", "否则，在回合结束时创建一个", "{C:attention}每周挑战{}小丑牌并{C:red}自我销毁{}", "{C:inactive}(当前星期：#1#){}"}},
            j_kranlaxs_weeklychallenge = {name = "每周挑战", text = {"为本次游戏设置一个随机挑战", "{C:clubs}当前挑战：{} {C:attention}#1#{}", "{C:inactive}1：{}你有{X:money,C:white} -$100 {}，在底注8之前还清", "{C:inactive}2：{}受限商店", "{C:inactive}3：{}1次出牌，20次弃牌（无额外优惠券）", "{C:inactive}4：{}本次游戏限制{C:blue}#2#{}次出牌和{C:red}#3#{}次弃牌", "{C:inactive}5：{}游戏速度锁定为0.5x", "{C:inactive}6：{}3张永恒的特里布莱（最多3个小丑，快速底注）", "{C:inactive}7：{}击败盲注时有1/6的几率获胜（在底注8时失败）"}},
            j_kranlaxs_panda = {name = "毛绒熊猫", text = {"提供{C:chips}+#1#{}筹码", "{C:attention}-1{}小丑牌槽位"}},
            j_kranlaxs_miner = {name = "矿工", text = {"每有一张计分的{C:attention}石头牌{}", "获得{C:red}+5{}倍率", "打出牌型时，有{C:green}#2#/#3#{}的几率", "获得{X:money,C:white} $#4# {}至{X:money,C:white} $#5# {}", "{C:inactive}(当前{C:red}+#1#{C:inactive}倍率){}"}, unlock = {"打出包含{C:attention}5{}张", "石头牌的牌型"}},
            j_kranlaxs_birthdaycake = {name = "生日蛋糕", text = {"提供{X:dark_edition,C:white} ^#1# {}倍率", "每次出牌后", "失去{X:dark_edition,C:white} ^0.25 {}", "耗尽时创建一个{C:attention}转赠小丑{}"}, unlock = {"使用{C:attention}每周挑战{}卡组", "在{C:attention}蓝色底注{}下赢得一次游戏"}},
            j_kranlaxs_vipsuscription = {name = "V.I.P 订阅", text = {"商店槽位{C:attention}+#2#{}", "额外优惠券和补充包{C:attention}+1{}", "打开商店时扣除{X:money,C:white} $#1# {}", "击败{C:attention}Boss盲注{}后", "价格和商店规模会{C:attention}增加{}"}, unlock = {"使用{C:attention}每周挑战{}卡组", "在{C:attention}橙色底注{}下赢得一次游戏"}},
            j_kranlaxs_painterjoker = {name = "画家小丑", text = {"牌型计分时，你手中每有一张", "{C:attention}万能牌{}，创建一个{C:attention}杂耍者标签{}", "{C:inactive}(每个标签花费{X:money,C:white} $#1# {C:inactive}){}"}, unlock = {"使用{C:attention}每周挑战{}卡组", "在{C:attention}橙色底注{}下赢得一次游戏"}},
            j_kranlaxs_coronation = {name = "加冕", text = {"如果打出的牌型包含点数为{C:attention}10或以下{}", "的计分牌，将最低的一张转化为{C:attention}K{}。", "如果手中没有小点数牌，", "则为第一张计分的{C:attention}K{}添加{C:red}红色印章{}。"}, unlock = {"打出完全由{C:attention}5张K{}组成的牌型。", "所有牌必须具有{C:red}红色印章{}", "且是{C:attention}钢铁{}牌"}},
            j_kranlaxs_speedrunner = {name = "速通者", text = {"{X:mult,C:white} X#1# {}倍率。", "你有{C:attention}#2#秒{}的时间", "来出牌或弃牌。", "如果时间耗尽，{C:red}游戏结束{}。"}, unlock = {"使用{C:attention}每周挑战{}卡组", "在{C:attention}绿色底注{}下赢得一次游戏"}},
            j_kranlaxs_passcode = {name = "密码", text = {"如果打出的牌型匹配", "以下任意代码，该牌型", "计为{C:attention}同花五条{}", "{C:inactive}1. {C:attention}#1#{}", "{C:inactive}2. {C:attention}#2#{}", "{C:inactive}3. {C:attention}#3#{}"}, unlock = {"使用{C:attention}每周挑战{}卡组", "在{C:attention}黑色底注{}下赢得一次游戏"}},
            j_kranlaxs_chronometer = {name = "天文台表", text = {"出牌时：", "提供等同于当前{C:attention}秒数{}的{C:chips}筹码{}", "提供等同于当前{C:attention}分钟数{}的{C:mult}倍率{}", "赚取等同于当前{C:attention}小时数{}的{C:money}金钱{}", "{C:inactive}(当前：{C:chips}+#1#{C:inactive}筹码，{C:mult}+#2#{C:inactive}倍率，{C:money}+$#3#{C:inactive}){}"}, unlock = {"使用{C:attention}太空卡组{}", "在{C:attention}金色底注{}下赢得一次游戏"}},
            j_kranlaxs_zombiejoker = {name = "僵尸小丑", text = {"{C:attention}摧毁{}第一张不计芬的扑可牌", "并活得{C:red}+15{}被率", "但每打粗一次排", "失趣{C:red}-10{}被率", "如果姜到{C:red}0{}被率", "{C:attention}它就死咯 {}", "{C:inactive}(你现在有{C:red}+#1#{C:inactive}被率左右){}"}, unlock = {"使用{C:attention}太空卡组{}", "在{C:attention}紫色底注{}下赢得一次游戏"}},
            j_kranlaxs_thecousin = {name = "表亲", text = {"每有一张计分的{C:attention}质数{}牌", "获得{C:chips}+13{}筹码", "{C:inactive}(当前{C:chips}+#1#{C:inactive}筹码){}"}, unlock = {"使用{C:attention}太空卡组{}", "在{C:attention}绿松石底注{}下赢得一次游戏"}},
            j_kranlaxs_colasoda = {name = "可乐汽水", text = {"提供{X:dark_edition,C:white} ^#1# {}倍率", "几乎你执行的{C:attention}任何操作{}", "都会使其失去{X:dark_edition,C:white} ^#2# {}"}, unlock = {"使用{C:attention}每周挑战{}卡组", "在{C:attention}蓝色底注{}下赢得一次游戏"}},
            j_kranlaxs_icecreamsandwich = {name = "冰淇淋三明治", text = {"在回合结束时", "赚取{X:money,C:white} $#1# {}", "每个回合后", "奖励减少{X:money,C:white} $#2# {}"}, unlock = {"在单次回合中", "通过结算赚取", "{X:money,C:white} $50 {}或以上"}},
            j_kranlaxs_dispensermachine = {name = "自动售货机", text = {"离开商店时，如果此小丑被{C:attention}选中{}", "花费{X:money,C:white} $#1# {}", "并创建一个{C:attention}食物小丑{}"}, unlock = {"同时拥有{C:attention}4{}个", "食物小丑"}},
            j_kranlaxs_bottledwater = {name = "瓶装水", text = {"{X:chips,C:white} X#1# {}筹码", "每有一张计分的卡牌", "失去{X:chips,C:white} X#2# {}"}, unlock = {"使用{C:attention}每周挑战{}卡组", "在{C:attention}蓝色底注{}下赢得一次游戏"}},
            j_kranlaxs_burrow = {name = "兔子洞", text = {"每击败一个{C:attention}盲注{}", "获得{C:attention}+1{}只兔子", "被{C:gold}出售{}时，创建{C:attention}#1#{}只兔子"}},
            j_kranlaxs_bunny = {name = "兔子", text = {"你每拥有一个{C:attention}兔子{}小丑", "获得{X:mult,C:white} X#1# {}倍率", "{C:inactive}(当前{X:mult,C:white} X#2# {C:inactive}倍率){}"}},
            j_kranlaxs_sushi = {name = "寿司", text = {"将盲注要求", "降低{C:attention}#1#%{}", "击败{C:attention}盲注{}后", "降低幅度减少{C:attention}#2#%{}",}, unlock = {"使用{C:attention}每周挑战{}卡组", "在{C:attention}紫色底注{}下赢得一次游戏"}},
            j_kranlaxs_gigachad = {name = "GigaChad", text = {"几乎你执行的{C:attention}任何操作{}", "都会使其获得{C:chips}+#2#{}筹码", "{C:inactive}(当前{C:chips}+#1#{C:inactive}筹码){}"}, unlock = {"使用{C:attention}每周挑战{}卡组", "在{C:attention}白色底注{}下赢得一次游戏"}},
            j_kranlaxs_nft = {name = "加密骗局", text = {"牌型计分时，", "将你手中所有卡牌的", "{C:attention}点数{}降低{C:attention}1{}", "{C:inactive}(不能降低至2以下){}"}},
            j_kranlaxs_beanstalk = {name = "豆蔓", text = {"没用的豆子"}, unlock = {"使用{C:attention}每周挑战{}卡组", "在{C:attention}白色底注{}下赢得一次游戏"}},
            j_kranlaxs_suspiciousbeanstalk = {name = "可疑的豆蔓", text = {"没用的豆子？..."}},
            j_kranlaxs_epicbeanstalk = {name = "史诗豆蔓", text = {"也许它们并不是没用的豆子..."}},
            j_kranlaxs_zenithbeanstalk = {name = "天顶豆蔓", text = {"豆子"}},
            j_kranlaxs_commonseed = {name = "常见种子", text = {"{C:attention}创建{}一个随机的", "{C:common}常见{}小丑牌"}},
            j_kranlaxs_weirdlookingseed = {name = "怪异种子", text = {"{C:attention}创建{}一个随机的", "{C:uncommon}罕见{}小丑牌"}},
            j_kranlaxs_magnificentseed = {name = "华丽种子", text = {"{C:attention}创建{}一个随机的", "{C:rare}稀有{}小丑牌"}},
            j_kranlaxs_godseed = {name = "神圣种子", text = {"{C:attention}创建{}一个随机的", "{C:legendary}传奇{}小丑牌"}},
            j_kranlaxs_anonymousjoker = {name = "匿名小丑", text = {"计分时翻转，并提供", "{X:mult,C:white} X1.5 {}到{X:mult,C:white} X4.0 {}之间的倍率"}, unlock = {"击败{C:attention}琥珀橡果{}", "Boss盲注1次"}},
            j_kranlaxs_littlebro = {name = "小老弟", text = {"如果打出的牌型是{C:attention}高牌{}且", "计分的卡牌是{C:attention}#2#{}，", "此小丑获得{X:red,C:white} X#3# {}倍率", "卡牌点数每回合改变", "{C:inactive}(当前{X:red,C:white} X#1# {C:inactive}倍率){}"}, unlock = {"在单次游戏中", "打出{C:attention}高牌{}", "{C:attention}30{}次"}},
            j_kranlaxs_medusa = {name = "美杜莎", text = {"打出牌型后，", "{C:attention}所有打出的卡牌{}", "永久变为{C:attention}石头牌{}", "{C:inactive}(包括未计分的牌){}"}, unlock = {"使用{C:attention}太空卡组{}", "在{C:attention}棕色底注{}下赢得一次游戏"}},
            j_kranlaxs_depression = {name = "经济衰退", text = {"提供{X:dark_edition,C:white}^#2#{}倍率", "低于{X:money,C:white} $0 {}的每{X:money,C:white} $1 {}", "增加{X:dark_edition,C:white}^#1#{}",}, unlock = {"带着{X:money,C:white} -$25 {}或更少的钱", "进入商店"}},
            j_kranlaxs_grannyjoker = {name = "老奶奶", text = {"提供{X:dark_edition,C:white} ^3 {}筹码和{X:dark_edition,C:white} ^3 {}倍率", "游戏速度锁定在{C:attention}0.25x{}", "{C:inactive}(如果你打出{C:attention}顺子{}", "{C:inactive}或{C:attention}同花顺{C:inactive}则会被销毁){}"}, unlock = {"在游戏速度为{C:attention}0.5{}的情况下", "击败{C:attention}12{}个盲注"}},
            j_kranlaxs_lateshippment = {name = "迟来的发货", text = {"在{C:attention}上一回合{}中每打出一次出牌", "将{C:attention}所有打出的卡牌{}", "重新触发{C:attention}1次{}", "{C:inactive}(当前{C:attention}#1#{C:inactive}次重新触发){}"}, unlock = {"使用{C:attention}太空卡组{}", "在{C:attention}橙色底注{}下赢得一次游戏"}},
            j_kranlaxs_unkownfactor = {name = "变量 X", text = {"所有打出的卡牌", "都被视为{C:attention}#1#{}", "{C:inactive}(点数在回合结束时改变){}"}, unlock = {"使用{C:attention}每周挑战{}卡组", "在{C:attention}金色底注{}下赢得一次游戏"}},
            j_kranlaxs_thethreers = {name = "三个 R", text = {"创建每张打出的卡牌的{C:attention}副本{}", "并将其加入你的{C:attention}卡组{}", "{C:attention}销毁{}所有计分卡牌"}, unlock = {"使用{C:attention}每周挑战{}卡组", "在{C:attention}金色底注{}下赢得一次游戏"}},
            j_kranlaxs_the = {name = "Jok", text = {"仅在回合的{C:attention}第一次出牌{}时", "提供{X:chips,C:white} X2 {}筹码和{X:mult,C:white} X2 {}倍率"}, unlock = {"只使用{C:attention}1{}次出牌", "击败{C:attention}5{}个盲注"}},
            j_kranlaxs_chainreaction = {name = "连锁反应", text = {"如果打出的牌型是{C:attention}#2#{}，", "获得{X:chips,C:white} X0.5 {}筹码并且牌型改变", "如果牌型{C:attention}不匹配{}则重置", "{C:inactive}(当前{X:chips,C:white} X#1# {C:inactive}筹码){}"}, unlock = {"在一次游戏中", "打出过所有扑克牌型至少{C:attention}1{}次"}},
            j_kranlaxs_anubis = {name = "阿努比斯", text = {"在牌型计分时，", "平衡{C:blue}筹码{}和{C:red}倍率{}"}, unlock = {"在每个底注难度下", "使用{C:attention}等离子卡组{}赢得一次游戏"}},
            j_kranlaxs_erraticjoker = {name = "古怪小丑", text = {"如果计分卡牌是", "{C:attention}万能牌{}，交换", "{C:blue}筹码{}和{C:red}倍率{}"}, unlock = {"使用{C:attention}太空卡组{}", "在{C:attention}白色底注{}下赢得一次游戏"}},
            j_kranlaxs_luckyseven = {name = "幸运七", text = {"如果打出的牌型恰好是", "全为{C:attention}7{}的{C:attention}三条{}，此小丑", "获得{C:blue}+7{}筹码，{C:red}+7{}倍率并提供{X:money,C:white} $7 {}", "{C:inactive}(当前{C:blue}+#1#{}筹码，{C:red}+#2#{}倍率)"}, unlock = {"卡组中至少有{C:attention}10{}张", "点数为{C:attention}7{}的卡牌"}},
            j_kranlaxs_certificateddocument = {name = "认证文件", text = {"重新触发{C:attention}所有{}印章"}, unlock = {"使用{C:attention}每周挑战{}卡组", "在{C:attention}紫色底注{}下赢得一次游戏"}},
            j_kranlaxs_platanito = {name = "小香蕉", text = {"每当另一个小丑触发时，", "提供{X:mult,C:white} X#3# {}额外倍率", "在回合结束时有{C:green}#1#/#2#{}的几率", "被销毁"}, unlock = {"使用{C:attention}太空卡组{}", "在{C:attention}白金底注{}下赢得一次游戏"}},
            j_kranlaxs_cubicaljoker = {name = "立方小丑", text = {"提供{C:mult}+#1#{}倍率", "每击败一个{C:attention}Boss盲注{}", "数值将被提升为{C:attention}立方 (^3){}"}},
            j_kranlaxs_grapesoda = {name = "葡萄汽水", text = {"被{C:gold}出售{}时，创建一个", "带有{C:dark_edition}负片{}版本的", "随机{C:spectral}幻灵{}牌"}, unlock = {"使用{C:attention}太空卡组{}", "在{C:attention}洋红底注{}下赢得一次游戏"}},
            j_kranlaxs_telescope = {name = "望远镜", text = {"如果{C:attention}#1#{}升级，", "使该牌型额外升级{C:attention}1{}次", "{C:inactive}(牌型在回合结束时改变){}"}, unlock = {"使用{C:attention}每周挑战{}卡组", "在{C:attention}红色底注{}下赢得一次游戏"}},
            j_kranlaxs_pandorabox = {name = "潘多拉魔盒", text = {"击败{C:attention}Boss盲注{}时，", "根据你当前的卡组", "创建一个{C:attention}有用{}的小丑", "{C:inactive}(必须有空位){}"}},
            j_kranlaxs_doppelganger = {name = "二重身", text = {"复制全游戏中一个随机", "{C:attention}小丑牌{}的能力。", "击败{C:attention}盲注{}后，", "复制的小丑会改变。", "{C:inactive}(当前：{C:attention}#1#{C:inactive})"}, unlock = {"使用{C:attention}每周挑战{}卡组", "在{C:attention}金色底注{}下赢得一次游戏"}},
            j_kranlaxs_thechampion = {name = "冠军", text = {"盲注要求 {C:attention}X#1#{}", "在回合结束时赚取{X:money,C:white} $#2# {}"}, unlock = {"达到{C:attention}底注 16{}"}},
            j_kranlaxs_clerigo = {name = "牧师", text = {"完整卡组中每有一张牌", "提供{C:mult}+#1#{}倍率", "每有一张带有增强或印章的牌", "失去{C:mult}-#2#{}倍率", "{C:inactive}(当前{C:mult}+#3#{C:inactive}倍率){}"}, unlock = {"完成挑战：", "{C:attention}祖传秘方{}"}},
            j_kranlaxs_entrenador = {name = "教练", text = {"如果你在底注{C:attention}#3#{}以下，", "提供{X:mult,C:white} X#1# {}倍率", "否则，提供{X:mult,C:white} X#2# {}倍率", "{C:inactive}(当前{X:mult,C:white} X#4# {C:inactive}倍率){}"}, unlock = {"完成挑战：", "{C:attention}经济危机{}"}},
            j_kranlaxs_medium = {name = "灵媒", text = {"你个人资料中每一次{C:red}失败{}的游戏", "提供{C:mult}+#1#{}倍率", "{C:inactive}(当前{C:mult}+#2#{C:inactive}倍率){}"}, unlock = {"失败{C:attention}1{}次", "{C:inactive}(进度：{C:attention}#1#{C:inactive} / 1){}"}},
            j_kranlaxs_monk = {name = "僧侣", text = {"如果你在不花费{X:money,C:white}金钱{}的情况下", "离开商店，获得{X:chips,C:white} X#1# {}筹码", "如果你买了东西则{C:red}重置{}", "{C:inactive}(当前{X:chips,C:white} X#2# {C:inactive}筹码){}"}, unlock = {"完成挑战：", "{C:attention}贫穷誓言{}"}},
            j_kranlaxs_knight = {name = "骑士", text = {"在有{C:attention}#1#{}张{C:attention}钢铁{}牌计分后，", "{C:attention}禁用{}下一个{C:attention}Boss盲注{}", "{C:inactive}(已计分卡牌：#2#/#1#){}"}, unlock = {"完成挑战：", "{C:attention}Boss辛迪加{}"}},
            j_kranlaxs_overpopulation = {name = "人口过剩", text = {"卡组中每有一张超过", "限制{C:attention}#2#{}张的{C:attention}人头牌{}", "提供{C:mult}+#1#{}倍率", "{C:inactive}(当前{C:mult}+#3#{C:inactive}倍率){}"}, unlock = {"使用{C:attention}太空卡组{}", "在{C:attention}绿色底注{}下赢得一次游戏"}},
            j_kranlaxs_antisocial = {name = "反社会", text = {"如果你恰好打出{C:attention}1{}张牌，", "此小丑获得{C:mult}+#1#{}倍率", "如果你打出多于1张牌则{C:red}重置{}", "{C:inactive}(当前{C:mult}+#2#{C:inactive}倍率){}"}, unlock = {"完成挑战：", "{C:attention}完全痴迷{}"}},
            j_kranlaxs_famous = {name = "名人", text = {"如果打出的牌型是{C:attention}五条{}、", "{C:attention}同花五条{}或{C:attention}同花葫芦{}", "提供{C:chips}+#1#{}筹码"}},
            j_kranlaxs_influencer = {name = "影响者", text = {"如果打出的牌型是{C:attention}五条{}、", "{C:attention}同花五条{}或{C:attention}同花葫芦{}", "提供{C:mult}+#1#{}倍率"}},
            j_kranlaxs_potatobag = {name = "马铃薯袋", text = {"累积计分的筹码", "当达到{C:attention}#1#{}时，将", "{X:mult,C:white} X#2# {}倍率应用到", "下一次出牌并清空", "{C:inactive}(已累积：#3#/#1#){}"}},
            j_kranlaxs_simonsays = {name = "西蒙说", text = {"完成其要求时，", "此小丑获得{X:mult,C:white} X#2# {}倍率", "西蒙说... {C:attention}#3#{}", "{C:inactive}(当前{X:mult,C:white} X#1# {C:inactive}倍率){}"}, unlock = {"完成挑战：", "{C:attention}巨大的豆蔓{}"}},
            j_kranlaxs_cheater = {name = "作弊者", text = {"商店中的小丑牌", "有{C:green}35%{}的几率", "被替换为", "{C:attention}优惠券{}或{C:attention}补充包{}"}, unlock = {"完成挑战：", "{C:attention}扭蛋机{}"}},
            j_kranlaxs_philosopher = {name = "哲学家", text = {"揭示你卡组中的", "下{C:attention}5张牌{}", "{C:inactive}(每张牌有20%的几率{}", "{C:inactive}保持隐藏状态){}", "{C:attention}#1#{}"}, unlock = {"完成挑战：", "{C:attention}预感{}"}},
            j_kranlaxs_mandalajoker = {name = "曼荼罗小丑", text = {"每使用一张{C:spectral}幻灵{}牌，", "此小丑获得{X:mult,C:white} X0.5 {}倍率", "{C:inactive}(当前{X:mult,C:white} X#1# {C:inactive}倍率){}"}, unlock = {"使用{C:attention}20{}张{C:spectral}幻灵{}牌", "{C:inactive}(进度：{C:attention}#1#{C:inactive} / 20){}"}},
            j_kranlaxs_regift = {name = "转赠小丑", text = {"被{C:gold}出售{}时，创建一个", "随机的{C:attention}小丑牌{}", "稀有度取决于当前的{C:attention}盲注{}"}, unlock = {"总共出售{C:attention}50{}张小丑牌", "{C:inactive}(进度：{C:attention}#1#{C:inactive} / 50){}"}},
            j_kranlaxs_pyromaniac = {name = "纵火狂", text = {"牌型计分后，{C:red}销毁{}", "你手中所有的{C:attention}数字{}牌", "{C:inactive}(黄金、玻璃和钢铁牌是安全的){}"}, unlock = {"销毁{C:attention}100{}张", "非人头牌", "{C:inactive}(进度：{C:attention}#1#{C:inactive} / 100){}"}},
            j_kranlaxs_neverendinggambling = {name = "无尽赌博", text = {"你采取的每一次行动失去{X:money,C:white} $1 {}", "{C:inactive}(仅当你有{X:money,C:white} $5 {}或以上时){}", "转动3个数字。如果匹配，赢得奖品！", "如果2个匹配，收回{X:money,C:white} $1 {}作为安慰", "{C:inactive}(当前旋转：#1# - #2# - #3#){}"}, unlock = {"在小丑或消耗品概率上", "失败{C:attention}30{}次", "{C:inactive}(进度：{C:attention}#1#{C:inactive} / 30){}"}},
            j_kranlaxs_solarsystem = {name = "太阳系", text = {"在{C:attention}回合结束时{}，按照固定顺序", "创建一张{C:planet}星球{}牌", "{C:inactive}(下一颗星球：{C:planet}#1#{C:inactive}){}"}, unlock = {"在单次游戏中", "至少使用过全部{C:attention}12{}张标准{C:planet}星球{}牌", "{C:inactive}(进度：{C:attention}#1#{C:inactive} / 12){}"}},
            j_kranlaxs_deranged = {name = "疯狂", text = {"提供{C:mult}+#1#{}倍率或{C:chips}+#2#{}筹码", "每次你出牌时", "效果会交换"}, unlock = {"完成挑战：", "{C:attention}身份危机{}"}},
            j_kranlaxs_deranged_mult = {name = "疯狂", text = {"提供{C:mult}+#1#{}倍率", "每次你出牌时", "效果会交换"}},
            j_kranlaxs_deranged_chips = {name = "疯狂", text = {"提供{C:chips}+#2#{}筹码", "每次你出牌时", "效果会交换"}},
            j_kranlaxs_tmtrainer = {name="TMTRAINER",text={"{C:dark_edition}#1#{}","{C:attention}#2#{}","{C:red}#3#{}","{C:chips}#4#{}"},unlock={"完成挑战：","{C:attention}身份危机{}"}},
            j_kranlaxs_bingocard = {name = "宾果卡", text = {"每完成一条线", "获得{X:mult,C:white} X0.25 {}倍率", "{C:inactive}(总计：{X:mult,C:white} X#2# {C:inactive}倍率){}", "{C:attention}#3#{}", "{C:attention}#4#{}", "{C:attention}#5#{}", "{C:attention}#6#{}", "{C:attention}#7#{}"}, unlock = {"完成挑战：", "{C:attention}完全匿名{}"}}
        },

        Back = {
            b_kranlaxs_week_challenge = {name = "每周挑战", text = {"开局拥有一张{C:attention}每周挑战{}小丑牌", "每个{C:attention}周末{}{C:red}可被击败{}"}, unlock = {"在{C:attention}星期六{}或{C:attention}星期日{}", "打开游戏"}},
            b_kranlaxs_chaos_deck = {name = "混沌卡组", text = {"享受混沌吧"}, unlock = {"解锁你收藏中的", "{C:legendary,E:1}所有物品{}"}},
            b_kranlaxs_dungeon_deck = {name = "地牢卡组", text = {"击败{C:attention}Boss盲注{}后，", "在3个带有{C:green}优点{}和{C:red}缺点{}", "的{C:attention}选项{}中进行选择"}, unlock = {"使用{C:attention}每周挑战{}卡组", "在{C:attention}绿色底注{}或以上赢得一次游戏"}},
            b_kranlaxs_space_deck = {name = "太空卡组", text = {"{C:attention}0{}个小丑槽位，{C:attention}5{}个消耗品槽位", "商店只出售{C:attention}石英{}", "商店规模{C:attention}+1{}，盲注要求降低{C:attention}7.5%{}", "胜利底注：{C:attention}10{}"}, unlock = {"使用{C:attention}魔法卡组{}、{C:attention}星云卡组{}", "和{C:attention}黄道卡组{}，", "在{C:attention}绿色底注{}下赢得游戏"}},
            b_kranlaxs_bugged_deck = {name = "漏洞卡组", text = {"!?"}, unlock = {"首次获得", "{C:attention}TMTRAINER{}"}}
        },

        Stake = {
            stake_kranlaxs_magenta = {name = "洋红底注", text = {"商店里的卡牌可能", "带有{C:attention}固定{}贴纸"}},
            stake_kranlaxs_brown = {name = "棕色底注", colour = "棕色", text = {"商店中{C:attention}补充包{}槽位{C:attention}-1{}"}},
            stake_kranlaxs_turquoise = {name = "绿松石底注", colour = "绿松石色", text = {"盲注有{C:attention}50%{}的几率", "{C:red}无法被跳过{}"}},
            stake_kranlaxs_deviled = {name = "恶魔底注", colour = "恶魔", text = {"{C:attention}-1{}个{C:attention}小丑牌{}槽位"}},
            stake_kranlaxs_glass = {name = "玻璃底注", colour = "玻璃", text = {"每个{C:attention}底注{}的分数", "要求增长得更快"}},
            stake_kranlaxs_platinum = {name = "白金底注", colour = "白金", text = {"必须击败{C:attention}底注10{}", "才能赢得游戏"}}
        },

        UNOCards = {
            c_kranlaxs_skip = {name = "跳过", text = {"{C:attention}立刻{}获得盲注要求分数", "对{C:attention}Boss盲注{}无效"}},
            c_kranlaxs_stacking = {name = "叠加", text = {"为你手中选择的{C:attention}1{}张牌", "添加{C:attention}粉色印章{}"}},
            c_kranlaxs_draw2 = {name = "抽2张", text = {"使用时，额外{C:attention}抽取2张牌{}", "到你的手中，失去{C:blue}1{}次出牌"}},
            c_kranlaxs_draw4 = {name = "抽4张", text = {"使用时，额外{C:attention}抽取4张牌{}", "到你的手中，失去{C:blue}1{}次出牌"}},
            c_kranlaxs_reverse = {name = "反转", text = {"将你手中的{C:attention}所有牌{}", "返回卡组并{C:attention}重新洗牌{}"}},
            c_kranlaxs_wildcard = {name = "万能色", text = {"{C:attention}独立地{}将你手中的", "每张牌{C:attention}转化{}为", "{C:attention}随机花色{}"}},
            c_kranlaxs_replay = {name = "重放", text = {"将最后一次打出的", "手牌返回你的手中", "{C:inactive}(使用后或回合结束", "{C:inactive}时重置)"}},
            c_kranlaxs_discardall = {name = "弃掉全部", text = {"需要{C:attention}1{}张选中的卡牌。", "弃掉你{C:attention}手中{}和{C:attention}卡组{}里", "具有相同花色的{C:red}所有{}牌"}},
            c_kranlaxs_shield = {name = "护盾", text = {"被动保护你免于死亡，或者", "可以被出售以禁用{C:attention}Boss盲注{}"}},
            c_kranlaxs_misery = {name = "苦难", text = {"选择一种{C:attention}花色{}。", "不停地从你的卡组中抽牌，", "直到你抽到", "该花色的牌为止"}},
            c_kranlaxs_gift = {name = "礼物", text = {"给予以下{C:attention}1{}种", "随机奖品：", "• 一张带版本的{C:attention}小丑牌{}", "• 一张负片{C:attention}消耗品{}", "• 一张带有增强、印章和版本的{C:attention}扑克牌{}"}},
            c_kranlaxs_customdraw = {name = "自定义抽牌", text = {"抽取与你已弃牌次数", "相同数量的卡牌", "{C:inactive}(当前：{C:attention}#1#{C:inactive}张卡牌){}"}}
        },

        InverseTarot = {
            c_kranlaxs_thefool = {name = "愚者？", text = {"创建一张随机的{C:spectral}幻灵{}牌", "{C:attention}降级{}一个随机的扑克牌型"}},
            c_kranlaxs_themagician = {name = "魔术师？", text = {"创建{C:attention}2{}张随机的{C:attention}幸运{}牌"}},
            c_kranlaxs_thehighpriestess = {name = "女祭司？", text = {"创建一个{C:spectral}黑洞{}", "你的{X:money,C:white} 金钱 {}{C:attention}减少{}20%"}},
            c_kranlaxs_theempress = {name = "皇后？", text = {"为最多{C:attention}2{}张选中的卡牌", "添加永久的{C:red}+8{}倍率"}},
            c_kranlaxs_theemperor = {name = "皇帝？", text = {"创建{C:attention}2{}个随机的{C:attention}标签{}"}},
            c_kranlaxs_thehierophant = {name = "教皇？", text = {"为最多{C:attention}2{}张选中的卡牌", "添加永久的{C:blue}+40{}筹码"}},
            c_kranlaxs_thelovers = {name = "恋人？", text = {"如果你的卡组中有一张{C:attention}万能牌{}", "获得{C:attention}+1{}手牌上限"}},
            c_kranlaxs_thechariot = {name = "战车？", text = {"创建{C:attention}1{}张带有{C:attention}红色{}印章的", "随机{C:attention}钢铁{}牌"}},
            c_kranlaxs_justice = {name = "正义？", text = {"为{C:attention}1{}张选中的卡牌", "添加永久的{X:red,C:white} X2 {}倍率", "有{C:green}#1#/#2#{}的几率{C:attention}销毁{}该牌"}},
            c_kranlaxs_thehermit = {name = "隐者？", text = {"如果你{C:attention}少于{}{X:money,C:white} $25 {}", "将你的{X:money,C:white} 金钱 {}{C:attention}设置{}为{X:money,C:white} $25 {}"}},
            c_kranlaxs_thewheeloffortune = {name = "命运之轮？", text = {"有{C:green}#1#/#2#{}的几率创建一张", "带有{C:dark_edition}负片{}版本的随机小丑{C:attention}副本{}"}},
            c_kranlaxs_strenght = {name = "力量？", text = {"将最多{C:attention}2{}张选中的卡牌的", "{C:attention}点数{}{C:attention}降低{} {C:attention}1{}"}},
            c_kranlaxs_thehangedman = {name = "倒吊人？", text = {"完全{C:attention}随机化{}手中", "最多{C:attention}2{}张选中的卡牌"}},
            c_kranlaxs_death = {name = "死神？", text = {"创建一个随机小丑的{C:attention}负片副本{}", "一个随机小丑获得{C:attention}易腐{}贴纸"}},
            c_kranlaxs_temperance = {name = "节制？", text = {"以售价的{C:money}三倍{}", "出售{C:attention}所有{}小丑（包括永恒的）", "{C:inactive}(不会出售固定的小丑){}"}},
            c_kranlaxs_thedevil = {name = "恶魔？", text = {"为最多{C:attention}2{}张选中的卡牌", "添加永久的{X:money,C:white} $2 {}"}},
            c_kranlaxs_thetower = {name = "高塔？", text = {"{C:attention}移除{}手中卡牌的所有增强、", "印章、版本和额外奖励", "每移除一个修改项获得{X:money,C:white} $1 {}"}},
            c_kranlaxs_thestars = {name = "星星？", text = {"为最多{C:attention}2{}张选中的卡牌", "添加{C:attention}白色印章{}"}},
            c_kranlaxs_themoon = {name = "月亮？", text = {"为最多{C:attention}2{}张选中的卡牌", "添加{C:attention}灰色印章{}"}},
            c_kranlaxs_thesun = {name = "太阳？", text = {"为最多{C:attention}2{}张选中的卡牌", "添加{C:attention}橙色印章{}"}},
            c_kranlaxs_judgement = {name = "审判？", text = {"{C:attention}兑换{}一张随机{C:attention}优惠券{}", "{C:red}-1{}手牌上限"}},
            c_kranlaxs_theworld = {name = "世界？", text = {"为最多{C:attention}2{}张选中的卡牌", "添加{C:attention}棕色印章{}"}}
        },

        Voucher = {
            v_kranlaxs_more_stock = {name = "进货", text = {"商店有{C:attention}1{}个额外的", "{C:attention}补充包{}槽位"}},
            v_kranlaxs_even_more_stock = {name = "大量进货", text = {"商店有{C:attention}1{}个额外的", "{C:attention}优惠券{}槽位"}},
            v_kranlaxs_shiny_appearance = {name = "闪亮登场", text = {"传奇牌和稀有消耗品", "现在可以出现在商店中"}},
            v_kranlaxs_stickerfever = {name = "贴纸狂热", text = {"每当你获得一个", "{C:attention}标签{}时，获得", "{C:attention}1{}个额外副本"}},
            v_kranlaxs_stickeralbum = {name = "贴纸相册", text = {"每当你获得一个", "{C:attention}标签{}时，再获得", "{C:attention}1{}个额外副本"}},
            v_kranlaxs_hotfix = {name = "热修复", text = {"{C:attention}重掷{}商店时", "也会刷新{C:attention}优惠券{}", "和{C:attention}补充包{}"}},
            v_kranlaxs_version2 = {name = "版本 2.0", text = {"跳过盲注时，直接授予你", "该盲注的{X:money,C:white} 金钱 {}奖励。", "盲注要求{C:attention}-15%{}"}},
            v_kranlaxs_common_shinys = {name = "传奇目击", text = {"传奇牌和稀有消耗品", "将更频繁地出现"}},
            v_kranlaxs_blessing = {name = "祝福", text = {"在每个盲注中，你开始时", "就已经完成了筹码要求的{C:attention}10%{}"}},
            v_kranlaxs_protection = {name = "神圣庇护", text = {"保护你免于{C:attention}游戏结束{}。", "使用后，此优惠券将被销毁", "并可能在商店中重新出现，", "但价格是原价的{X:money,C:white} 两倍 {}"}}
        },

        Quartz = {
            c_kranlaxs_blackquartz = {name = "黑曜石", text = {"根据你的选择", "修改一些规则"}, unlock = {"使用{C:attention}魔法卡组{}", "在{C:attention}棕色底注{}下赢得一次游戏"}},
            c_kranlaxs_whitequartz = {name = "珍珠", text = {"创建最后一次", "使用的消耗品", "{C:inactive}(最后一张牌：{C:attention}#1#{C:inactive}){}"}, unlock = {"使用{C:attention}幽灵卡组{}", "在{C:attention}棕色底注{}下赢得一次游戏"}},
            c_kranlaxs_pinkquartz = {name = "玫瑰石英", text = {"为选择的{C:attention}小丑牌{}", "或{C:attention}扑克牌{}添加{C:dark_edition}镭射{}"}, unlock = {"使用{C:attention}地牢卡组{}", "在{C:attention}洋红底注{}或以上赢得游戏"}},
            c_kranlaxs_bluequartz = {name = "蓝宝石", text = {"为选择的{C:attention}小丑牌{}或{C:attention}扑克牌{}", "添加{C:chips}闪箔{}"}, unlock = {"使用{C:attention}等离子卡组{}", "在{C:attention}白金底注{}下赢得游戏"}},
            c_kranlaxs_lilacquartz = {name = "紫锂辉石", text = {"为选择的{C:attention}小丑牌{}或{C:attention}扑克牌{}", "添加{C:mult}幻彩{}"}, unlock = {"使用{C:attention}星云卡组{}", "在{C:attention}棕色底注{}下赢得游戏"}},
            c_kranlaxs_grayquartz = {name = "赤铁矿", text = {"为选择的{C:attention}小丑牌{}", "或{C:attention}消耗品{}添加{C:dark_edition}负片{}"}, unlock = {"使用{C:attention}彩绘卡组{}", "在{C:attention}绿松石底注{}下赢得游戏"}},
            c_kranlaxs_transparentquartz = {name = "钻石", text = {"{C:attention}移除{}一个小丑牌上的所有贴纸或版本，", "或移除选择的{C:attention}卡牌{}上的", "印章或版本"}, unlock = {"使用{C:attention}地牢卡组{}", "在{C:attention}白金底注{}下赢得游戏"}},
            c_kranlaxs_redquartz = {name = "红宝石", text = {"当{C:attention}持有{}时，", "提供{X:mult,C:white} X2 {}倍率", "{C:inactive}(被动){}"}, unlock = {"使用{C:attention}红色卡组{}", "在{C:attention}洋红底注{}或以上赢得游戏"}},
            c_kranlaxs_celestequartz = {name = "拉利玛", text = {"当{C:attention}持有{}时，", "提供{X:chips,C:white} X1.5 {}筹码", "{C:inactive}(被动){}"}, unlock = {"使用{C:attention}棋盘卡组{}", "在{C:attention}绿松石底注{}下赢得游戏"}},
            c_kranlaxs_yellowquartz = {name = "黄玉", text = {"创建指定的{C:attention}小丑牌{}。", "每个{C:attention}回合{}后，", "小丑牌会随机改变", "{C:inactive}(目标：{C:attention}#1#{C:inactive}){}"}, unlock = {"使用{C:attention}地牢卡组{}", "在{C:attention}蓝色底注{}下赢得游戏"}},
            c_kranlaxs_greenquartz = {name = "祖母绿", text = {"当{C:attention}持有{}时，击败{C:attention}盲注{}后", "创建一个{C:attention}标签{}", "创建{C:attention}#2#{}个标签后销毁", "{C:inactive}(当前：{C:attention}#1#{C:inactive}){}", "{C:inactive}(被动){}"}, unlock = {"使用{C:attention}绿色卡组{}", "在{C:attention}洋红底注{}或以上赢得游戏"}},
            c_kranlaxs_brownquartz = {name = "虎眼石", text = {"创建指定的{C:attention}扑克牌{}。", "商店{C:green}重掷{}后", "卡牌会随机改变", "{C:inactive}(目标：{C:attention}#1#{C:inactive}){}"}, unlock = {"使用{C:attention}红蓝3D卡组{}", "在{C:attention}绿松石底注{}下赢得游戏"}},
            c_kranlaxs_turquoisequartz = {name = "绿松石", text = {"当{C:attention}持有{}时，{C:attention}禁用{}", "除第一个以外的所有小丑", "将该小丑重新触发{C:attention}2{}次", "{C:inactive}(被动){}"}, unlock = {"使用{C:attention}黄道卡组{}", "在{C:attention}绿松石底注{}下赢得游戏"}},
            c_kranlaxs_orangequartz = {name = "黄水晶", text = {"为一张{C:attention}卡牌{}添加{C:green}薄荷印章{}", "或为选中的{C:attention}小丑牌{}", "添加{C:green}三叶草贴纸{}"}, unlock = {"使用{C:attention}黄色卡组{}", "在{C:attention}洋红底注{}或以上赢得游戏"}},
            c_kranlaxs_lapislazuli = {name = "青金石", text = {"当{C:attention}持有{}时，为第一张", "计分的卡牌添加{C:chips}+#1#{}筹码", "每次使用效果减少{C:chips}-#2#{}。", "{C:inactive}(降至0时失效){}", "{C:inactive}(被动){}"}, unlock = {"使用{C:attention}蓝色卡组{}", "在{C:attention}洋红底注{}或以上赢得游戏"}},
            c_kranlaxs_cinnabar = {name = "朱砂", text = {"当{C:attention}持有{}时，为第一张", "计分的卡牌添加{C:mult}+#1#{}倍率", "每次使用效果减少{C:mult}-#2#{}。", "{C:inactive}(降至0时失效){}", "{C:inactive}(被动){}"}, unlock = {"使用{C:attention}废弃卡组{}", "在{C:attention}棕色底注{}下赢得游戏"}},
            c_kranlaxs_graphite = {name = "石墨", text = {"当{C:attention}持有{}时，有{C:green}#1#/#2#{}的几率", "在你的手中创建", "所有打出卡牌的副本。", "触发时几率下降。", "{C:inactive}(降至0时失效){}", "{C:inactive}(被动){}"}, unlock = {"使用{C:attention}黑色卡组{}", "在{C:attention}洋红底注{}或以上赢得游戏"}},
            c_kranlaxs_uranium = {name = "铀", text = {"当{C:attention}持有{}时，每回合应用1个", "随机效果。它可能", "非常棒，也可能非常具有破坏性。", "{C:dark_edition}当前状态：{}", "{C:red,E:2}#1#{}", "{C:inactive}(敢带着它吗？){}", "{C:inactive}(被动){}"}, unlock = {"使用{C:attention}无常卡组{}", "在{C:attention}白金底注{}下赢得游戏"}}
        },

        Tag = {
            tag_kranlaxs_mega_invtarot = {name = "巨型逆位标签", text = {"立即获得一个免费的", "{C:attention}巨型逆位塔罗包{}"}},
            tag_kranlaxs_mega_uno = {name = "超大 UNO 标签", text = {"立即获得一个免费的", "{C:attention}超大 UNO 包{}"}},
            tag_kranlaxs_mega_invtarot_store = {name = "储存的巨型逆位标签", text = {"立即获得一个免费的", "{C:attention}储存的巨型逆位塔罗{}"}},
            tag_kranlaxs_quartz_tag = {name = "石英标签", text = {"生成一个随机{C:attention}石英{}", "{C:inactive}(必须有空位){}"}},
            tag_kranlaxs_sticker_remover = {name = "净化标签", text = {"从一个随机{C:attention}小丑牌{}身上", "移除{C:attention}永恒{}、{C:attention}易腐{}或{C:attention}租赁{}贴纸", "{C:inactive}(如果没有贴纸，则给{X:money,C:white} $5 {C:inactive}){}"}},
            tag_kranlaxs_legendary = {name = "传奇标签", text = {"商店里有一个免费的", "{C:legendary}传奇小丑牌{}"}},
            tag_kranlaxs_cosmic_tag = {name = "宇宙标签", text = {"为你{C:attention}牌组{}中的一张随机牌", "添加{C:dark_edition}宇宙{}版本"}},
            tag_kranlaxs_yellowish_tag = {name = "泛黄标签", text = {"为你{C:attention}牌组{}中的一张随机牌", "添加{C:attention}深乌{}版本"}},
            tag_kranlaxs_boring_tag = {name = "无聊标签", text = {"商店里的下一张小丑牌", "必定为{C:dark_edition}单色{}"}},
            tag_kranlaxs_demonic_tag = {name = "恶魔标签", text = {"商店里的下一张小丑牌", "必定带有{C:red}诅咒{}"}},
            tag_kranlaxs_wet_tag = {name = "潮湿标签", text = {"为你{C:attention}牌组{}中的一张随机牌", "添加{C:blue}水下{}版本"}},
            tag_kranlaxs_zen_tag = {name = "禅意标签", text = {"将当前{C:attention}基础底注{}减少{C:blue}-1{}"}}
        },

        Edition = {
            e_kranlaxs_cosmic = {name = "宇宙", text = {"{C:red}弃牌{}时，", "升级{C:attention}选中的牌型{}"}},
            e_kranlaxs_sepia = {name = "深乌", text = {"计分时若在手牌中，", "有{C:green}#1#/#2#{}的几率生成一个{C:attention}标签{}"}},
            e_kranlaxs_cursed = {name = "诅咒", text = {"计分时{C:attention}平衡{}筹码和倍率。", "之后有{C:green}#1#/#2#{}的几率{C:red}摧毁{}自身。"}},
            e_kranlaxs_monochrome = {name = "单色", text = {"{X:dark_edition,C:white} ^#1# {} 倍率", "计分时{C:red}摧毁{}自身"}},
            e_kranlaxs_underwater = {name = "水下", text = {"{X:chips,C:white} X#1# {} 筹码"}}
        },

        Other = {
            kranlaxs_magenta_sticker = {name = "洋红贴纸", text = {"使用这个小丑牌", "在{C:attention}洋红底注{}下赢得了游戏"}},
            kranlaxs_brown_sticker = {name = "棕色贴纸", text = {"使用这个小丑牌", "在{C:attention}棕色底注{}下赢得了游戏"}},
            kranlaxs_turquoise_sticker = {name = "绿松石贴纸", text = {"使用这个小丑牌", "在{C:attention}绿松石底注{}下赢得了游戏"}},
            kranlaxs_platinum_sticker = {name = "白金贴纸", text = {"使用这个小丑牌", "在{C:attention}白金底注{}下赢得了游戏"}},
            kranlaxs_orangeseal_seal = {name = "橙色印章", text = {"如果在手中计分：{C:attention}#1#{}，", "创建一个{C:attention}#2#{}", "{C:inactive}使用后改变。{}", "{C:inactive}(必须有空位){}"}},
            kranlaxs_pinkseal_seal = {name = "粉色印章", text = {"在{C:attention}计分{}时，", "应用{X:dark_edition,C:white}^1.75{}倍率"}},
            kranlaxs_whiteseal_seal = {name = "白色印章", text = {"{C:attention}必定计分{}，免疫", "{C:red}无效化{}、{C:red}销毁{}", "或{C:attention}翻转{}"}},
            kranlaxs_brownseal_seal = {name = "棕色印章", text = {"拿在手中时，有{C:green}#1#/#2#{}的几率", "{C:attention}复制{}这张卡牌"}},
            kranlaxs_grayseal_seal = {name = "灰色印章", text = {"在{C:attention}计分{}时，{C:attention}随机{}改变", "这张卡牌的{C:enhanced}增强{}"}},
            kranlaxs_mintseal_seal = {name = "薄荷印章", text = {"将这张卡牌上", "{C:attention}所有列出的概率{}翻倍"}},
            p_kranlaxs_uno_store_3 = {name = "UNO 包", text = {"从最多{C:attention}3{}张{C:blue}UNO{}牌中", "选择{C:attention}1{}张"}},
            p_kranlaxs_uno_store_5 = {name = "超大 UNO 包", text = {"从最多{C:attention}5{}张{C:blue}UNO{}牌中", "选择{C:attention}1{}张"}},
            p_kranlaxs_invtarot_instant_3_1 = {name = "逆位塔罗包", text = {"从最多{C:attention}3{}张{C:purple}逆位塔罗{}牌中", "选择{C:attention}1{}张"}},
            p_kranlaxs_invtarot_instant_5_1 = {name = "超大逆位塔罗包", text = {"从最多{C:attention}5{}张{C:purple}逆位塔罗{}牌中", "选择{C:attention}1{}张"}},
            p_kranlaxs_invtarot_instant_5_2 = {name = "巨型逆位塔罗包", text = {"从最多{C:attention}5{}张{C:purple}逆位塔罗{}牌中", "选择{C:attention}2{}张"}},
            p_kranlaxs_invtarot_store_3_1 = {name = "储存的逆位塔罗", text = {"从最多{C:attention}3{}张{C:purple}逆位塔罗{}牌中", "选择{C:attention}1{}张"}},
            p_kranlaxs_invtarot_store_5_1 = {name = "储存的超大逆位塔罗", text = {"从最多{C:attention}5{}张{C:purple}逆位塔罗{}牌中", "选择{C:attention}1{}张"}},
            kranlaxs_deviled_sticker = {name = "恶魔贴纸", text = {"使用这个小丑牌", "在{C:attention}恶魔底注{}下赢得了游戏"}},
            kranlaxs_glass_sticker = {name = "玻璃贴纸", text = {"使用这个小丑牌", "在{C:attention}玻璃底注{}下赢得了游戏"}},
            p_kranlaxs_invtarot_store_5_2 = {name = "储存的巨型逆位塔罗", text = {"从最多{C:attention}5{}张{C:purple}逆位塔罗{}牌中", "选择{C:attention}2{}张"}}
        },

        Booster = {
            p_kranlaxs_uno_store_3 = {name = "UNO 包", text = {"从最多{C:attention}3{}张{C:blue}UNO{}牌中", "选择{C:attention}1{}张"}},
            p_kranlaxs_uno_store_5 = {name = "超大 UNO 包", text = {"从最多{C:attention}5{}张{C:blue}UNO{}牌中", "选择{C:attention}1{}张"}},
            p_kranlaxs_invtarot_instant_3_1 = {name = "逆位塔罗包", text = {"从最多{C:attention}3{}张{C:purple}逆位塔罗{}牌中", "选择{C:attention}1{}张"}},
            p_kranlaxs_invtarot_instant_5_1 = {name = "超大逆位塔罗包", text = {"从最多{C:attention}5{}张{C:purple}逆位塔罗{}牌中", "选择{C:attention}1{}张"}},
            p_kranlaxs_invtarot_instant_5_2 = {name = "巨型逆位塔罗包", text = {"从最多{C:attention}5{}张{C:purple}逆位塔罗{}牌中", "选择{C:attention}2{}张"}},
            p_kranlaxs_invtarot_store_3_1 = {name = "储存的逆位塔罗", text = {"从最多{C:attention}3{}张{C:purple}逆位塔罗{}牌中", "选择{C:attention}1{}张"}},
            p_kranlaxs_invtarot_store_5_1 = {name = "储存的超大逆位塔罗", text = {"从最多{C:attention}5{}张{C:purple}逆位塔罗{}牌中", "选择{C:attention}1{}张"}},
            p_kranlaxs_invtarot_store_5_2 = {name = "储存的巨型逆位塔罗", text = {"从最多{C:attention}5{}张{C:purple}逆位塔罗{}牌中", "选择{C:attention}2{}张"}}
        }
    },
    
    misc = {
        labels = {
            kranlaxs_magenta_sticker = "洋红贴纸",
            kranlaxs_brown_sticker = "棕色贴纸",
            kranlaxs_turquoise_sticker = "绿松石贴纸",
            kranlaxs_platinum_sticker = "白金贴纸",
            kranlaxs_orangeseal_seal = "橙色印章", 
            kranlaxs_pinkseal_seal = "粉色印章", 
            kranlaxs_whiteseal_seal = "白色印章", 
            kranlaxs_brownseal_seal = "棕色印章", 
            kranlaxs_grayseal_seal = "灰色印章", 
            kranlaxs_mintseal_seal = "薄荷印章", 
            clover = "三叶草贴纸",
            kranlaxs_deviled_sticker = "恶魔贴纸",
            kranlaxs_glass_sticker = "玻璃贴纸",
            p_kranlaxs_uno_store_3 = "UNO 包",
            p_kranlaxs_uno_store_5 = "超大 UNO 包",
            p_kranlaxs_invtarot_instant_3_1 = "逆位塔罗包",
            p_kranlaxs_invtarot_instant_5_1 = "超大逆位塔罗包",
            p_kranlaxs_invtarot_instant_5_2 = "巨型逆位塔罗包",
            p_kranlaxs_invtarot_store_3_1 = "储存的逆位塔罗",
            p_kranlaxs_invtarot_store_5_1 = "储存的超大逆位塔罗",
            p_kranlaxs_invtarot_store_5_2 = "储存的巨型逆位塔罗",
            kranlaxs_wave = "水生",
            e_kranlaxs_cosmic = "宇宙",
            e_kranlaxs_sepia = "深乌",
            e_kranlaxs_cursed = "诅咒",
            e_kranlaxs_monochrome = "单色",
            e_kranlaxs_underwater = "水下"
        },

        v_text = {
            ch_c_kran_fijado_1 = {"所有小丑牌都有{C:attention}固定{}贴纸"},
            ch_c_kran_abuela_1 = {"{C:attention}计分{}小丑牌被{C:red}禁用{}"},
            ch_c_kran_crisis_1 = {"商店价格{C:attention}贵20%{}"},
            ch_c_kran_crisis_2 = {"盲注基础奖励{C:red}降低{}{X:money,C:white} $2 {}"},
            ch_c_kran_crisis_3 = {"卡组仅由{C:attention}52张A{}组成"},
            ch_c_kran_doppel_1 = {"所有小丑牌在商店被{C:red}禁用{}"},
            ch_c_kran_anonimo_1 = {"手中卡牌和小丑牌处于{C:attention}背面朝上{}状态"},
            ch_c_kran_jefes_1 = {"小盲注和大盲注变为{C:attention}Boss盲注{}"},
            ch_c_kran_premon_1 = {"你手中所有的牌都处于{C:attention}背面朝上{}状态"},
            ch_c_kran_tallo_1 = {"其他{C:attention}小丑牌{}和{C:attention}补充包{}被{C:red}禁用{}"},
            ch_c_gacha_rule_1 = {"商店中不会出现{C:attention}单张卡牌{}"},
            ch_c_kran_pobreza_1 = {"{C:common}常见{}小丑牌有{C:attention}50%{}的几率变为{C:legendary}传奇{}"},
            ch_c_kran_pobreza_2 = {"如果你的{C:attention}僧侣{}小丑感到失望，{C:red}你输掉游戏{}"}
        }
    }
}